longhorn/longhorn-manager

- csi/controller_server.go
Fix CSI sanity test failure.
```
unexpected error: invalid csi snapshot type: . Must be snap or bak
Expected
<codes.Code>: 3
to equal
<codes.Code>: 5
```
https://github.com/longhorn/longhorn/issues/2271
> [CSI Sanity] Should fail when the volume source snapshot is not found

- controller/replica_controller.go
> Fix: if a node or disk changes its EvictionRequested, enqueue all replicas on that node/disk

- webhook/resources/volume/mutator.go
> admission webhook: remove duplicate in volume mutation

- manager/engine.go
https://github.com/longhorn/longhorn/issues/3748
> Disable reverting to a removed snapshot

- webhook/admission/README.md
> admission webhook: add README.md

- manager/engine.go
https://github.com/longhorn/longhorn/issues/3764
> [BACKPORT][v1.1.4] Disable reverting to a removed snapshot

- manager/engine.go
> [BACKPORT][v1.2.5]Disable reverting to a removed snapshot

- examples/data_migration.yaml
https://github.com/longhorn/longhorn/issues/3787
> Fix data migration YAML command args

- controller/backup_controller.go
- engineapi/backup_monitor.go
- k8s/pkg/apis/longhorn/v1beta1/backup.go
https://github.com/longhorn/longhorn/issues/3792
> [BACKPORT-v1.2.5] Mark backup to Pending state if encounter the engine RPC error code DeadlineExceeded

- controller/uninstall_controller.go
https://github.com/longhorn/longhorn/issues/2034
> Fix hardcoded namespace in uninstall controller

- controller/kubernetes_configmap_controller.go
> controller: StorageClass change should trigger the controller sync-up

- controller/kubernetes_configmap_controller.go
> controller: wait for the storage class informer cache sync

- deploy/install/02-components/03-ui.yaml
https://github.com/longhorn/longhorn/issues/3829
Signed-off-by: Siye Wang <siye@rancher.com>
> [master] Make Longhorn UI Listen Binding configurable

- manager/volume.go
- webhook/resources/volume/validator.go
[Longhorn 3860](https://github.com/longhorn/longhorn/issues/3860)
> Fix volumeMounts missing in admission webhook

- .drone.yml
- Dockerfile.dapper
This PR adds support to build on s390x architecture.
> Add s390x support

- types/setting.go
https://github.com/longhorn/longhorn/pull/3879#discussion_r855735086
https://github.com/longhorn/longhorn/issues/2203
> Reword kubernetes-cluster-autoscaler-enabled setting description

- upgrade/util/util.go
- upgrade/util/util_test.go
- upgrade/v122to123/upgrade.go
> [Backport v1.2.5] Add progress status to the upgrade path v1.2.2 to v1.2.3

- deploy/scripts/environment_check.sh
Detect the worker OS rather than host OS.
[Longhorn 3550](https://github.com/longhorn/longhorn/issues/3550)
> environment_check: fix OS detection

- webhook/resources/node/validator.go
The disk spec and status should be one-to-one matching.
Longhorn 685
> validator: reject update request before syncing disk spec and status

- deploy/scripts/environment_check.sh
- add missing double quotes to a error message
- avoid waiting really long time on sles/zypper for checking packages
- remove unneeded single quotes
context: https://github.com/longhorn/longhorn/issues/3550#issuecomment-1117525837
> environment_check.sh: fix quoting and add timeout

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- go.mod
- go.sum
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/3922
> Update im to v1_20220505 to fix optional tls

- controller/volume_controller.go
[Longhorn 3529](https://github.com/longhorn/longhorn/issues/3529)
> Avoid unnecessary warning message if PV does not exist

- deploy/scripts/environment_check.sh
https://github.com/longhorn/longhorn/issues/3550
https://github.com/longhorn/longhorn/issues/3937
> Improve the environment check script to check for dependences

- datastore/longhorn.go
- manager/engine.go
- util/util.go
https://github.com/longhorn/longhorn/issues/2777
> Check storage space before snapshot purge 

- datastore/uncached.go
[longhorn/longhorn#3958](https://github.com/longhorn/longhorn/issues/3958)
> Fix event log disappeared on UI.

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/util/grpcutil.go
- vendor/modules.txt
wait for newly released im image before merge
depends on https://github.com/longhorn/longhorn-instance-manager/pull/115
longhorn/longhorn#3966
> updated im dep + image

- app/daemon.go
- datastore/longhorn.go
- deploy/install/01-prerequisite/03-crd.yaml
- deploy/install/02-components/01-manager.yaml
- k8s/pkg/apis/longhorn/v1beta2/setting.go
- types/setting.go
We will move the logic to configmap controller.
https://github.com/longhorn/longhorn/issues/2570
> Revert ConfigMap to Setting Design

- controller/snapshot_controller.go
> Keep the owner check inside the isResponsibleFor in the worker goroutine only

- upgrade/v122to123/upgrade.go
> Cache the engines and volumes object to speed up the upgrade path from v1.2.2 to v1.2.3

- upgrade/v122to123/upgrade.go
> Fix bug copying the pointer of the same for-loop variable

- controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/4004
> grpc-proxy: fix engine live upgrade

- upgrade/v122to123/upgrade.go
https://github.com/longhorn/longhorn/issues/3996
> [Backport] [v1.2.5] Fix bug copying the pointer of the same for-loop variable

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
> Update longhorn share manager image to v1_20220523

- api/model.go
- datastore/longhorn.go
- types/setting.go
> Protect SettingDefinitions by RWMutex

- controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/3546
> grpc-proxy: fix ctx cancelled during replica list

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
https://github.com/longhorn/longhorn/issues/3546
> version-bump: instance-manager

- datastore/longhorn.go
- types/setting.go
default setting config -> this should impact default builtin setting definitions
updating setting CR -> this should not impact the default setting definitions
longhorn/longhorn#2570
> Fix unexpected overwrite of default settings

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
> Update longhorn-shared-manager image

- types/setting.go
https://github.com/longhorn/longhorn/issues/2285
> storage-network: fix description

- controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/3546
> grpc-proxy: add missing proxy client close

- deploy/longhorn-images.txt
> Update backing image manager to v3_20220531

- controller/snapshot_controller.go
> Fix nil pointer dereference when enqueuing the snapshot CR

- engineapi/proxy_backup.go
https://github.com/longhorn/longhorn/issues/4061
> grpc-proxy: fix NPE from SnapshotBackup

- controller/engine_controller.go
- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy_backup.go
- vendor/modules.txt
[Longhorn 4049](https://github.com/longhorn/longhorn/issues/4049)
Depends on https://github.com/longhorn/longhorn-instance-manager/pull/121
> Fix taskErr assertion failure

- api/model.go
> api: Expose backing image UUID

- controller/backing_image_controller.go
https://github.com/longhorn/longhorn/issues/4073
> controller: Try to recover the backing image when all records become failed

- engineapi/proxy.go
> grpc-proxy: adjust log level

- controller/backing_image_manager_controller.go
https://github.com/longhorn/longhorn/issues/4090
> controller: automatically delete and resync failed backing images if possible

- controller/setting_controller.go
https://github.com/longhorn/longhorn/issues/4065
> cluster-autoscaler: fix NPE when UI not found

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy.go
- vendor/modules.txt
https://github.com/longhorn/longhorn-instance-manager/pull/125
> vendor: update longhorn-instance-manager

- controller/instance_manager_controller.go
> cluster-autoscaler: fix misleading variable

- controller/backing_image_data_source_controller.go
https://github.com/longhorn/longhorn/issues/4106
> controller: avoid using the old backing image data source pod after upgrade

- engineapi/backup_monitor.go
https://github.com/longhorn/longhorn/issues/4110
> grpc-proxy: connection leak when failed to backup

- controller/backing_image_controller.go
> controller: backing image manager shutdown should wait for the file cleanup complete

- app/daemon.go
- controller/backing_image_data_source_controller.go
- controller/backup_controller.go
- controller/backup_target_controller.go
- controller/backup_volume_controller.go
- controller/controller_manager.go
- controller/engine_controller.go
- controller/snapshot_controller.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- engineapi/proxy.go
- manager/engine.go
- manager/volume.go
- metrics_collector/instance_manager_collector.go
- metrics_collector/metrics_collector.go
- util/counter.go
https://github.com/longhorn/longhorn/issues/4038
> monitoring: add proxy-grpc-connection

- controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/4120
> Remove scale-down replica warning

- controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/4120
> [BACKPORT][v1.2.x] Remove scale-down replica warning

- controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/4120
> [BACKPORT][v1.3.x] Remove scale-down replica warning

- controller/volume_controller.go
> controller: Fix the misleading log for the replicas that have no StorageIP

- controller/monitor/node_monitor.go
[Longhron 4143](https://github.com/longhorn/longhorn/issues/4143)
> Fix wrong nodeOrDiskEvicted collected in node monitor

- controller/backup_controller.go
https://github.com/longhorn/longhorn/issues/4113
> backup-monitor: fix goroutine leak

- datastore/longhorn.go
https://github.com/longhorn/longhorn/issues/4160
https://github.com/longhorn/longhorn/issues/4162
> Avoid validation failure while syncing configmap to setting CRs

- controller/backup_controller.go
https://github.com/longhorn/longhorn/issues/4113
> [BACKPORT][v1.3.x] backup-monitor: fix goroutine leak

- datastore/kubernetes.go
https://github.com/longhorn/longhorn-manager/pull/1398
cc @DaleWYZ
> [BACKPORT][master] fix a crush bug

- scheduler/replica_scheduler.go
- scheduler/replica_scheduler_test.go
https://github.com/longhorn/longhorn/issues/4185
> Consider disk space when schedule replica

- scheduler/replica_scheduler.go
- scheduler/replica_scheduler_test.go
https://github.com/longhorn/longhorn/issues/4185
https://github.com/longhorn/longhorn-manager/pull/1397
> [BACKPORT][v1.3.x] consider disk space when schedule replica

- scheduler/replica_scheduler.go
- scheduler/replica_scheduler_test.go
https://github.com/longhorn/longhorn/issues/4185
https://github.com/longhorn/longhorn-manager/pull/1397
> [BACKPORT][v1.2.x] consider disk space when schedule replica

- controller/engine_controller.go
- controller/events.go
- types/setting.go
> Purge snapshots before rebuilding

- scheduler/replica_scheduler.go
> We want to reuse replica on the disk that is unschedulable due to allocated space being bigger than max allocable space but the disk is not full yet

- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy_snapshot.go
- vendor/modules.txt
> [BACKPORT][v1.3.x] vendor: update longhorn-instance-manager

- controller/engine_controller.go
- controller/events.go
- types/setting.go
Longhorn/longhorn#4183
Longhorn/longhorn#4251
> [BACKPORT][v1.3.x] Purge snapshots before rebuilding

- controller/engine_controller.go
- controller/events.go
- datastore/longhorn.go
- types/setting.go
Longhorn/longhorn#4183
Longhorn/longhorn#4252
> [BACKPORT][v1.2.x] Purge snapshots before rebuilding

- controller/volume_controller.go
This allow Longhorn to detach the volume and retry attaching the volume thus fix the deadlock situation in the issue description
longhorn/longhorn#4197
> Set replics.spec.failedAt when a replica failed at attaching stage before engine become running

- controller/volume_controller.go
> [BACKPORT][v1.3.x] Set replics.spec.failedAt when a replica failed at attaching stage before engine become running

- controller/backing_image_controller.go
- controller/backing_image_manager_controller.go
> Clean up backing image files and backing image managers correctly

- controller/backing_image_controller.go
- controller/backing_image_manager_controller.go
https://github.com/longhorn/longhorn/issues/4256
https://github.com/longhorn/longhorn/issues/4297
> [Backport][v1.3.x] Clean up backing image files and backing image managers correctly

- controller/volume_controller.go
- datastore/longhorn.go
- manager/volume.go
https://github.com/longhorn/longhorn/issues/4238
> Avoid evicting or removing the last healthy replica

- controller/volume_controller.go
- datastore/longhorn.go
- manager/volume.go
https://github.com/longhorn/longhorn/issues/4238
https://github.com/longhorn/longhorn/issues/4313
> [Backport][v1.3.x] Avoid evicting or removing the last healthy replica

- controller/volume_controller.go
- datastore/longhorn.go
- manager/volume.go
https://github.com/longhorn/longhorn/issues/4238
https://github.com/longhorn/longhorn/issues/4314
> [Backport][v1.2.x] Avoid evicting or removing the last healthy replica

- controller/snapshot_controller.go
- controller/volume_controller.go
> Fix bug snapshot CR block the deletion of volume CR

- controller/uninstall_controller.go
- datastore/longhorn.go
- manager/misc.go
> Collect the snapshot yamls in support bundle

- controller/uninstall_controller.go
- datastore/longhorn.go
- manager/misc.go
> [IMPROVEMENT][BACKPORT][v1.3.x] Collect the snapshot yamls in support bundle

- controller/engine_image_controller.go
- controller/engine_image_controller_test.go
- deploy/install/01-prerequisite/03-crd.yaml
- k8s/pkg/apis/longhorn/v1beta1/engineimage.go
- k8s/pkg/apis/longhorn/v1beta2/engineimage.go
https://github.com/longhorn/longhorn/issues/4332
https://github.com/longhorn/longhorn/issues/4338
> [BACKPORT][v1.3.1] Include volumes, engines, and replicas in the engineImage refcount calculation

- controller/engine_image_controller.go
- controller/engine_image_controller_test.go
- deploy/install/01-prerequisite/03-crd.yaml
https://github.com/longhorn/longhorn/issues/4332
https://github.com/longhorn/longhorn/issues/4339
> [BACKPORT][v1.2.5][IMPROVEMENT] Avoid accidentally deleting engine images that are still in use

- controller/kubernetes_pod_controller.go
Issue:
https://github.com/longhorn/longhorn/issues/4302
check `pod.DeletionTimestamp` first.
> fix 4302: avoid repeat deletion of pod

- datastore/longhorn.go
Longhorn/longhorn#4308
Longhorn/longhorn#4343
> [Backport][v1.3.x] datasource: Stop using cascading deletion for backing image manager

- go.mod
- go.sum
- vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go
- vendor/github.com/longhorn/go-iscsi-helper/util/util.go
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/4364
> [BACKPORT][v1.2.x] vendor: update go-iscsi-helper

- go.mod
- go.sum
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/4363
> [BACKPORT][v1.3.x] vendor: update go-iscsi-helper

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
To refresh installed packages in the image.
> Update share and backing images

- controller/engine_controller.go
- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/4294
> Fix evicting error and improve the related logs

- controller/engine_controller.go
- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/4294
https://github.com/longhorn/longhorn/issues/4365
> [Backport][v1.3.x] Fix evicting error and improve the related logs

- controller/engine_controller.go
- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/4294
https://github.com/longhorn/longhorn/issues/4373
> [Backport][v1.2.x] Fix evicting error and improve the related logs

- controller/kubernetes_pod_controller.go
> Only delete the VolumeAttachment on the downed node

- controller/volume_controller.go
In this case, there are still other replicas that can be started
so we don't set the volume to faulted here
longhorn/longhorn#4390
> [BACKPORT][1.2.x][BUG] Fix don't set volume to faulted if it is attaching the first time and one of the replica failed during attaching proccess

- controller/kubernetes_pod_controller.go
> [BACKPORT][v1.2.x] Only delete the VolumeAttachment on the downed node

- controller/kubernetes_pod_controller.go
> [BACKPORT][v1.3.x] Only delete the VolumeAttachment on the downed node

- deploy/uninstall/uninstall.yaml
> Add volumeattachment to uninstaller's service account

- deploy/uninstall/uninstall.yaml
> [BACKPORT][v1.2.x] Add volumeattachment to uninstaller's service account

- deploy/uninstall/uninstall.yaml
> [BACKPORT][v1.3.x] Add volumeattachment to uninstaller's service account

- k8s/pkg/apis/longhorn/v1beta1/volume.go
https://github.com/longhorn/longhorn/issues/4412
> Convert volume.spec.dataLocality from empty string to disabled

- k8s/pkg/apis/longhorn/v1beta1/volume.go
https://github.com/longhorn/longhorn/issues/4412
https://github.com/longhorn/longhorn/issues/4419
> [BACKPORT][v1.3.2] Convert volume.spec.dataLocality from empty string to disabled

- controller/engine_controller.go
Just give a couple times to retry restoreBackup only when getting lock failed.
longhorn/longhorn#3055
> Retry restoring Backup if getting lock failed.

- controller/engine_controller.go
Just give couple time to retry restoreBackup only when getting
lock failed.
longhorn/longhorn#4429
> [BACKPORT][v1.3.x] Retry restoring Backup if getting lock failed.

- .drone.yml
- Dockerfile.dapper
- scripts/ci
Codecov integration
For https://github.com/longhorn/longhorn/issues/4425
Signed-off-by: Yang Chiu <yang.chiu@suse.com>
> Codecov integration

- codecov.yml
Config codecov.yml to prevent codecov status check blocking pull request.
For https://github.com/longhorn/longhorn/issues/4425
Signed-off-by: Yang Chiu <yang.chiu@suse.com>
> Config codecov.yml to prevent codecov status check blocking pull request.

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
> Update managed components images

- deploy/install/01-prerequisite/03-crd.yaml
Sync with longhorn/longhorn templates
https://github.com/longhorn/longhorn/issues/4505
> Add "preserveUnknownFields: false" to crds

- deploy/install/01-prerequisite/03-crd.yaml
Sync with longhorn/longhorn templates
https://github.com/longhorn/longhorn/issues/4506
> [BACKPORT][v1.3.2] Add "preserveUnknownFields: false" to crds

- types/types.go
- webhook/resources/backup/mutator.go
- webhook/resources/volume/mutator.go
[Issue #4528](https://github.com/longhorn/longhorn/issues/4528)
> [BACKPORT][v1.3.x] update backup label with admission webhook

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
[Longhorn 2380](https://github.com/longhorn/longhorn/issues/2380)
> Update longhorn-share-manager to v1_20220914

- go.mod
- go.sum
- vendor/github.com/longhorn/backupstore/util/util.go
- vendor/modules.txt
[Longhorn 4552
](https://github.com/longhorn/longhorn/issues/4552)
> vendor: update backupstore

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
[Longhorn 3601
](https://github.com/longhorn/longhorn/issues/3601)
> manifest: update longhorn-instance-manager version

- go.mod
- go.sum
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/3601
https://github.com/longhorn/longhorn/issues/4609
> [BACKPORT][v1.3.2] vendor: update longhorn-engine

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/4502
> fix(replica-auto-balance): unschedulable node rebuilding loop

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/4630
https://github.com/longhorn/longhorn/issues/4502
> [BACKPORT][v1.3.2] fix(replica-auto-balance): rebuilding loop on unschedulable node

- controller/backup_volume_controller.go
- webhook/resources/backup/mutator.go
Getting the access mode of a volume that does not exists would block creating a backup created by another Longhorn system.
longhorn/longhorn#4637
> fix: Can not pull a backup created by another Longhorn system from the remote backup target

- controller/backup_volume_controller.go
- webhook/resources/backup/mutator.go
Getting the access mode of a volume that does not exists would block creating a backup created by another Longhorn system.
[Longhorn#4638
](https://github.com/longhorn/longhorn/issues/4638)
> fix(backup): block creating a backup (backport to 1.3.2)

- controller/share_manager_controller.go
- datastore/kubernetes.go
- recovery_backend/backend/configmap.go
- types/types.go
https://github.com/longhorn/longhorn/issues/4648
> Fix the share-manager deletion failure if the confimap is not existing

- controller/volume_controller.go
- datastore/kubernetes.go
- manager/volume.go
- scheduler/replica_scheduler.go
https://github.com/longhorn/longhorn/issues/4654
> Update volume-scheduling-error failure

- controller/volume_controller.go
- datastore/kubernetes.go
- manager/volume.go
- scheduler/replica_scheduler.go
https://github.com/longhorn/longhorn/issues/4654
https://github.com/longhorn/longhorn/issues/4657
> [BACKPORT][v1.2.6] Update volume-scheduling-error failure

- controller/volume_controller.go
- datastore/kubernetes.go
- manager/volume.go
- scheduler/replica_scheduler.go
https://github.com/longhorn/longhorn/issues/4654
https://github.com/longhorn/longhorn/issues/4656
> [BACKPORT][v1.3.2] Update volume-scheduling-error failure

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
> Update system managed componente images for v1.3

- controller/uninstall_controller.go
- types/setting.go
> Add deleting confirmation step to Longhorn uninstallation

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
> Update system managed component images for v1.2.6

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/4767
https://github.com/longhorn/longhorn/issues/4761
> [BACKPORT][v1.2.6] fix replica auto balance single replica rebuild loop

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/4762
https://github.com/longhorn/longhorn/issues/4761
> [BACKPORT][v1.3.3] fix replica auto balance single replica rebuild loop

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
> [v1.2.x]update backing image manager tag to longhornio/backing-image-manager:v2_20221027

- controller/volume_controller_test.go
- datastore/longhorn.go
- webhook/common/common.go
- webhook/resources/engine/mutator.go
- webhook/resources/replica/mutator.go
- webhook/resources/volume/mutator.go
- webhook/server/mutation.go
[Issue #4870](https://github.com/longhorn/longhorn/issues/4870)
backport https://github.com/longhorn/longhorn/issues/3917
> [BACKPORT][v1.3.3] improve: move labeling and finalizer for workload to mutating webhook

- controller/kubernetes_configmap_controller.go
- datastore/longhorn.go
[Issue #4769](https://github.com/longhorn/longhorn/issues/4769)
backport https://github.com/longhorn/longhorn/issues/4554
> [BACKPORT][v1.3.3] fix: Custom default settings and values ​​will not be updated if they exist

- controller/engine_controller.go
- datastore/longhorn.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- engineapi/instance_manager.go
- go.mod
- go.sum
- types/setting.go
- vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go
- vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go
- vendor/github.com/longhorn/go-iscsi-helper/util/process.go
- vendor/github.com/longhorn/go-iscsi-helper/util/util.go
- vendor/github.com/longhorn/longhorn-engine/pkg/meta/version.go
- vendor/github.com/longhorn/longhorn-engine/pkg/replica/client/client.go
- vendor/github.com/longhorn/longhorn-engine/pkg/types/types.go
- vendor/github.com/longhorn/longhorn-engine/pkg/util/util.go
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/4491
Depends on https://github.com/longhorn/longhorn-engine/pull/762
Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)
> Introduce the setting "engine-replica-timeout" for changing iSCSI timeout value

- go.mod
- go.sum
- vendor/github.com/longhorn/backupstore/config.go
- vendor/github.com/longhorn/backupstore/driver.go
- vendor/github.com/longhorn/backupstore/lock.go
- vendor/github.com/longhorn/backupstore/logging/logging.go
- vendor/github.com/longhorn/backupstore/util/util.go
- vendor/modules.txt
[Longhorn 4491
](https://github.com/longhorn/longhorn/issues/4491)
> vendor: update dependencies

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
[Longhorn 4491](https://github.com/longhorn/longhorn/issues/4491)
> Update longhorn-instance-manager to v2_20221115

- controller/share_manager_controller.go
> Allow kubernetes scheduler control over the share-manager pod

- controller/share_manager_controller.go
longhorn/longhorn#4789
https://github.com/longhorn/longhorn/issues/4876
> Backport sm pod scheduling

- controller/volume_controller.go
Replicas are waiting for that IMs starts and the volume controller consider IMs are failed and then set replicas failed.
Not to check replicas launchable when IM-r is not running during volume is upgrading.
longhorn/longhorn#4726
longhorn/longhorn#4873
> [BACKPORT][v1.2.7] old IM-r Pods are not deleted

- controller/node_controller.go
This reverts commit 867b51ad662bbd81a7d276aba833845eb8a08fc1.
> Revert "duplicated event log when node restarted"

- controller/node_controller.go
This reverts commit 0c4ca74e160bc1d6b498f2bb044776ec84581f2a.
> Revert "[BACKPORT][v1.3.3] duplicated event log when node restarted"

- controller/node_controller.go
This reverts commit c9a16ed14bf73617a4d2b7329d5ba78c276cd2e9.
> Revert "[BACKPORT][v1.2.7] duplicated event log when node restarted"

- csi/node_server.go
[Longhorn 4642](https://github.com/longhorn/longhorn/issues/4642)
> feat: make FS format options configurable in storage class

- controller/engine_controller.go
Check that backup exists before restoring the volume.
[Regression test result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2523/), and three failed cases: Passed in my local environment.
longhorn/longhorn#1867
> fix(restore): Restoring volume got stuck if the backup was deleted

- controller/engine_controller.go
Check that backup exists before restoring the volume.
And set restoring volume failed.
And unify the log messages for controller/engine_controller.go
longhorn/longhorn#1867
https://github.com/longhorn/longhorn/issues/4926
> [BACKPORT][v1.2.7] Restoring volume stuck if backup deleted 

- controller/support_bundle_controller.go
> fix(support-bundle): typo

- controller/engine_controller.go
- controller/instance_manager_controller.go
- controller/replica_controller.go
- controller/volume_controller.go
- datastore/longhorn.go
- engineapi/instance_manager.go
- k8s/pkg/apis/longhorn/v1beta2/volume.go
- manager/volume.go
- scheduler/replica_scheduler.go
- types/setting.go
- types/types.go
- webhook/resources/volume/validator.go
[Longhorn 3957](https://github.com/longhorn/longhorn/issues/3957)
> feat: support local volume

- app/driver.go
- csi/deployment.go
https://github.com/longhorn/longhorn/issues/3907
> feat(csi-liveness-probe): longhorn-csi-plugin

- controller/backing_image_controller.go
- datastore/longhorn.go
https://github.com/longhorn/longhorn/issues/4887
https://github.com/longhorn/longhorn/issues/4888
> [Backport][v1.3.x]controller: Avoid wrongly updating the node and disk ID for BIDS

- csi/server.go
https://github.com/longhorn/longhorn-manager/pull/1570#discussion_r1034264740
https://github.com/longhorn/longhorn/issues/3907
> feat(csi-liveness-probe): trace level logging

- app/driver.go
- csi/deployment.go
- csi/server.go
https://github.com/longhorn/longhorn/issues/4875
https://github.com/longhorn/longhorn/issues/3907
> [Backport][v1.3.3] feat(csi-liveness-probe): longhorn-csi-plugin

- controller/replica_controller.go
- engineapi/instance_manager.go
[Longhorn 4962](https://github.com/longhorn/longhorn/issues/4962)
> Check engine image version before creating a replica process

- controller/backing_image_data_source_controller.go
- controller/backing_image_manager_controller.go
- controller/engine_image_controller.go
https://github.com/longhorn/longhorn/issues/4380
https://github.com/longhorn/longhorn/issues/4874
> [BACKPORT][v1.3.3] fix(engine binary): recovery

- controller/backing_image_data_source_controller.go
- controller/backing_image_manager_controller.go
- controller/engine_image_controller.go
https://github.com/longhorn/longhorn/issues/4380
https://github.com/longhorn/longhorn/issues/4960
> [BACKPORT][v1.2.7] fix(engine binary): recovery

- api/backup.go
[Longhorn 4975](https://github.com/longhorn/longhorn/issues/4975)
> [BACKPORT][v1.2.7] fix: Check if backup exists before performing backup deletion

- api/backup.go
[Longhorn 4974](https://github.com/longhorn/longhorn/issues/4974)
> [BACKPORT][v1.3.3] fix: Check if backup exists before performing backup deletion

- controller/engine_controller.go
> style(log): engine controller

- controller/backing_image_data_source_controller.go
[Longhorn 4866](https://github.com/longhorn/longhorn/issues/4866)
(cherry picked from commit b26d6e6cb5b159407dcf18d0f4b0f3e796c1d096)
> [BACKPORT][v1.3.3] fix: Notify by sending a signal to stop instead of using close channel

- api/model.go
> Fix the missing api codes for volume.spec.snapshotDataIntegrity

- controller/engine_controller.go
- types/setting.go
https://github.com/longhorn/longhorn/issues/4558
> feat(concurrent-backup-restore): implement

- webhook/resources/volume/validator.go
> Reject the request moving a strict-local volume to another node

- webhook/resources/volume/validator.go
> Don't allow users to change the volume.Spec.NodeID of a strict-local volume

- .drone.yml
ref: https://github.com/longhorn/longhorn/issues/5040
> ci: exclude s390x PR check

- api/model.go
- controller/engine_controller.go
- controller/volume_controller.go
- csi/controller_server.go
- csi/crypto/crypto.go
- csi/crypto/luks.go
- csi/identity_server.go
- csi/node_server.go
- manager/volume.go
> Online expansion support

- controller/system_backup_controller.go
- controller/system_backup_controller_test.go
- controller/system_restore_controller_test.go
- webhook/resources/systembackup/validator.go
- webhook/server/validation.go
https://github.com/longhorn/longhorn/issues/5055
> fix(system-backup): should handle empty backup target

- controller/system_restore_controller.go
- controller/system_restore_controller_test.go
- controller/system_rollout_controller.go
https://github.com/longhorn/longhorn/issues/5057
> style(system-restore): job/pod name prefix

- controller/system_restore_controller.go
- controller/system_restore_controller_test.go
- controller/system_rollout_controller.go
https://github.com/longhorn/longhorn/issues/5057
> [BACKPORT][v1.4.0] style(system-restore): job/pod name prefix

- controller/engine_controller.go
Decrease restore when:
- Restore complete (LastRestoredBackup updated)
- Failed to restore
- Engine monitor shut down
Added lock around limit check and acquiring counter to avoid counter increase above the limit when volumes backup restores concurrently.
Ref: https://github.com/longhorn/longhorn/issues/4558#issuecomment-1345721240
> fix(concurrent-backup-restore): decreased counter before restored

- controller/engine_controller.go
Decrease restore when:
- No replica is restoring
- Backup restore failed
- Engine monitor shut down
Added lock around limit check and acquiring
counter to avoid counter increase above the limit
when volumes backup restores concurrently.
Ref: https://github.com/longhorn/longhorn/issues/4558#issuecomment-1345721240
(cherry picked from commit fe05edbb43151d0540a870c8f5d2f4625c4fac6a)
> [BACKPORT][v1.4.0] fix(concurrent-backup-restore): decreased counter before restored

- types/setting.go
> types: Update description for the trim setting

- controller/controller_test.go
- controller/system_restore_controller_test.go
- controller/system_rollout_controller.go
- controller/system_rollout_controller_test.go
- datastore/kubernetes.go
- types/types.go
https://github.com/longhorn/longhorn/issues/5074
> fix(system-restore): missing services

- controller/controller_test.go
- controller/system_restore_controller_test.go
- controller/system_rollout_controller.go
- controller/system_rollout_controller_test.go
- datastore/kubernetes.go
- types/types.go
https://github.com/longhorn/longhorn/issues/5074
> [BACKPORT][v1.4.0] fix(system-restore): missing services 

- types/setting.go
> [Backport][v1.4.x]types: Update description for the trim setting

- controller/system_restore_controller_test.go
- controller/system_rollout_controller.go
- controller/system_rollout_controller_test.go
- types/types.go
https://github.com/longhorn/longhorn/issues/5064
> fix(system-restore): do not overwrite existing volume, PV, PVC

- controller/kubernetes_pod_controller.go
https://github.com/longhorn/longhorn/issues/5061#issuecomment-1357085967
> fix(pod-controller): log when associated resource not found

- controller/system_restore_controller_test.go
- controller/system_rollout_controller.go
- controller/system_rollout_controller_test.go
- types/types.go
https://github.com/longhorn/longhorn/issues/5064
https://github.com/longhorn/longhorn-manager/pull/1621
> [BACKPORT][v1.4.0] fix(system-restore): do not overwrite existing volume, PV, PVC

- controller/kubernetes_pod_controller.go
https://github.com/longhorn/longhorn/issues/5061#issuecomment-1357085967
https://github.com/longhorn/longhorn-manager/pull/1633
> [BACKPORT][v1.3.3] fix(pod-controller): log when associated resource not found

- controller/kubernetes_pod_controller.go
https://github.com/longhorn/longhorn/issues/5061#issuecomment-1357085967
https://github.com/longhorn/longhorn-manager/pull/1633
> [BACKPORT][v1.4.0] fix(pod-controller): log when associated resource not found

- controller/system_backup_controller.go
- datastore/kubernetes.go
- datastore/uncached.go
https://github.com/longhorn/longhorn/issues/5091
> fix(system-backup): backup PV, PVC with Longhorn provisioner

- constant/events.go
- controller/support_bundle_controller.go
- controller/system_rollout_controller.go
https://github.com/longhorn/longhorn/issues/5086
> fix(system-restore): add log when volume failed to create

- controller/system_restore_controller.go
- controller/system_restore_controller_test.go
https://github.com/longhorn/longhorn/issues/5072
> fix(system-restore): handle non-exist system backup config file

- controller/system_restore_controller.go
- types/types.go
https://drone-publish.longhorn.io/longhorn/longhorn-manager/1079/1/3
> fix(system-restore): undefined reason

- controller/system_backup_controller.go
- datastore/kubernetes.go
- datastore/uncached.go
https://github.com/longhorn/longhorn/issues/5091
https://github.com/longhorn/longhorn-manager/pull/1631
> [BACKPORT][v1.4.0] fix(system-backup): backup PV, PVC with Longhorn provisioner

- constant/events.go
- controller/support_bundle_controller.go
- controller/system_rollout_controller.go
https://github.com/longhorn/longhorn/issues/5086
https://github.com/longhorn/longhorn-manager/pull/1627
> [BACKPORT][v1.4.0] fix(system-restore): add log when volume failed to create

- controller/system_restore_controller.go
- controller/system_restore_controller_test.go
- types/types.go
https://github.com/longhorn/longhorn/issues/5072
https://github.com/longhorn/longhorn-manager/pull/1625
https://github.com/longhorn/longhorn-manager/pull/1638
> [BACKPORT][v1.4.0] fix(system-restore): handle non-exist system backup config file

- .github/mergify.yml
> ci: fix mergify conditon for github action

- .github/mergify.yml
> ci: remove linear history from mergify check

- constant/events.go
- controller/system_rollout_controller.go
- util/util.go
https://github.com/longhorn/longhorn/issues/5086#issuecomment-1358725844
> fix(system-restore): ignore PV, PVC due to missing Volume

- constant/events.go
- controller/system_rollout_controller.go
- util/util.go
https://github.com/longhorn/longhorn/issues/5086#issuecomment-1358725844
https://github.com/longhorn/longhorn-manager/pull/1642
> [BACKPORT][v1.4.0] fix(system-restore): ignore PV, PVC due to missing Volume

- util/util.go
> Support trim operation on a volume with multiple mountpoints

- util/util.go
> Check mountpoint is healthy before trimming the volume

- controller/engine_controller.go
> controller: Set expansion error when the info is not empty

- controller/system_rollout_controller.go
https://github.com/longhorn/longhorn/issues/5134#issuecomment-1365604838
> fix(system-restore): replica crash during EngineImage update

- controller/system_rollout_controller.go
- controller/system_rollout_controller_test.go
https://github.com/longhorn/longhorn/issues/5157
> fix(system-restore): volume name different to PV

- controller/engine_controller.go
- datastore/longhorn.go
> Fix the expansion error issue

- api/router.go
- datastore/uncached.go
- recovery_backend/backend/configmap.go
- recovery_backend/server/model.go
> recovery backend: get configmap from kubernetes rather than cache

- controller/controller_test.go
- controller/kubernetes_pv_controller_test.go
- controller/system_backup_controller_test.go
- controller/system_restore_controller_test.go
- controller/system_rollout_controller_test.go
- datastore/kubernetes.go
- datastore/uncached.go
- manager/kubernetes.go
https://github.com/longhorn/longhorn/issues/5286
> fix(system-backup): NPE when PV source not from CSI

- types/setting.go
https://github.com/longhorn/longhorn/issues/5338
Result:
> fix(setting): UI missing asterisk in formulas

- csi/util.go
UnmountWithForce will do graceful umount. If failed, do the force unmount.
[Longhorn 5296](https://github.com/longhorn/longhorn/issues/5296)
> Force unmount the mount point of the Longhorn volume

- controller/volume_controller.go
- controller/volume_controller_test.go
> Don't fail a running replica when node is no ready

- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta1/instancemanager.go
- k8s/pkg/apis/longhorn/v1beta1/volume.go
- k8s/pkg/apis/longhorn/v1beta2/instancemanager.go
- k8s/pkg/apis/longhorn/v1beta2/volume.go
> fix(crd): description

- controller/controller_manager.go
> refactor(controller-manager): duplicated logic

- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/volume.go
https://github.com/longhorn/longhorn/pull/5409#discussion_r1109183655
> docs(crd): reword

- types/types.go
- upgrade/upgrade.go
- upgrade/util/util.go
- upgrade/v070to080/upgrade.go
- upgrade/v100to101/upgrade.go
- upgrade/v102to110/upgrade.go
- upgrade/v110to111/upgrade.go
- upgrade/v110to120/upgrade.go
- upgrade/v111to120/upgrade.go
- upgrade/v120to121/upgrade.go
- upgrade/v122to123/upgrade.go
- upgrade/v12xto130/upgrade.go
- upgrade/v13xto140/upgrade.go
- upgrade/v14xto150/upgrade.go
https://github.com/longhorn/longhorn/issues/5368
> Fix upgrade failures caused by CRD differences between longhorn versions

- upgrade/v14xto150/upgrade.go
- webhook/resources/volume/mutator.go
> Force disable revision counter for a strict local volume

- app/recurring_job.go
- controller/backup_target_controller.go
- controller/engine_image_controller.go
- datastore/longhorn.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/recurringjob.go
- scheduler/replica_scheduler.go
- webhook/resources/recurringjob/mutator.go
- webhook/resources/recurringjob/validator.go
https://github.com/longhorn/longhorn/issues/3836
> feat(recurring-job): periodically cleanup snapshots

- controller/controller_manager.go
https://github.com/longhorn/longhorn/issues/5419
> fix: instance manager cpu reservation

- app/recurring_job.go
- controller/backup_target_controller.go
- controller/engine_image_controller.go
- datastore/longhorn.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/recurringjob.go
- scheduler/replica_scheduler.go
- webhook/resources/recurringjob/mutator.go
- webhook/resources/recurringjob/validator.go
https://github.com/longhorn/longhorn/issues/5109
https://github.com/longhorn/longhorn/issues/3836
> [BACKPORT][v1.4.1] feat(recurring-job): periodically cleanup snapshots

- app/recurring_job.go
- controller/engine_image_controller.go
- datastore/longhorn.go
- deploy/install/01-prerequisite/03-crd.yaml
- k8s/pkg/apis/longhorn/v1beta2/recurringjob.go
- scheduler/replica_scheduler.go
- webhook/resources/recurringjob/mutator.go
- webhook/resources/recurringjob/validator.go
https://github.com/longhorn/longhorn/issues/4893
https://github.com/longhorn/longhorn/issues/3836
> [BACKPORT][v1.3.3] feat(recurring-job): periodically cleanup snapshots

- webhook/resources/recurringjob/validator.go
https://github.com/longhorn/longhorn/issues/5434
> doc(validator): recurring-job invalid retain value

- controller/support_bundle_controller.go
https://github.com/longhorn/longhorn/issues/5467
> fix(support-bundle): agent missing registry secret

- controller/system_rollout_controller.go
https://github.com/longhorn/longhorn/issues/5442
> fix(system-restore): backup target overwritten

- controller/backup_controller.go
- controller/engine_controller.go
- datastore/longhorn.go
> Disallow backup deletion when it is used for restoring a volume

- controller/backup_controller.go
> Retry backup deletion based on the resync mechnism

- controller/backup_controller.go
- controller/engine_controller.go
- datastore/longhorn.go
https://github.com/longhorn/longhorn/issues/5458
> [BACKPORT][v1.4.1] Disallow backup deletion when it is used for restoring a volume 

- controller/backup_controller.go
The volume.Status.RestoreRequired of a DR volume is always true. To make sure a backup is deletable, need to check the associated replicas are not restoring.
Before the fix:
[tests.test_basic.test_dr_volume_with_backup_block_deletion[s3]](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3089/testReport/junit/tests/test_basic/test_dr_volume_with_backup_block_deletion_s3_/)
[tests.test_basic.test_dr_volume_with_backup_block_deletion[nfs]](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3089/testReport/junit/tests/test_basic/test_dr_volume_with_backup_block_deletion_nfs_/)
[tests.test_basic.test_dr_volume_with_backup_block_deletion_abort_during_backup_in_progress[s3]](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3089/testReport/junit/tests/ …
> Check replica is not restoring before deleting a backup

- controller/support_bundle_controller.go
[Longhorn 5073](https://github.com/longhorn/longhorn/issues/5073)
A New parameter: `SUPPORT_BUNDLE_COLLECTOR` is passed to support-bundle-kit to execute the specified collector script.  And the [support-bundle-kit PR](https://github.com/rancher/support-bundle-kit/pull/63) will also accept this new parameter and execute `collector-longhorn.sh` to collect system information and logs.
> feat(support-bundle): Add new parameter: `SUPPORT_BUNDLE_COLLECTOR` to execute specified support-bundle-kit collector

- controller/engine_controller.go
- controller/system_backup_controller.go
- datastore/kubernetes.go
> Try the best to delete RWX volume's engine instance

- app/daemon.go
- csi/crypto/luks.go
- util/util.go
> style: inconsistent naming convention

- controller/controller_manager.go
- controller/kubernetes-pdb-controller.go
- controller/share_manager_controller.go
> Use PDB to protect Longhorn components from drains

- controller/engine_controller.go
When the IM was not running and disconnected, the RWX volume gets stuck at detaching, because the engine instance can't be deleted. Avoid getting stuck by ignoring the failure. There is only one attempt at deletion, and the best effort is made.
Longhorn/longhorn#5558
> Ignore the failure of RWX volume's engine instance deletion if the IM is not running

- controller/instance_manager_controller.go
- types/setting.go
> Create a new setting so that Longhorn will allow the drain when the node contains the last healthy replica of a volume but the replica is stopped

- deploy/longhorn-images.txt
ref: https://github.com/longhorn/longhorn/issues/3907
cc @c3y1huang
> chore(build): add livenessprobe image for 1.3

- controller/backing_image_controller.go
- controller/backing_image_data_source_controller.go
Ref: [longhorn/longhorn5626](https://github.com/longhorn/longhorn/issues/5626)
When deleting the backing image, and there is no backing image data source (missing)
The Controller crashes cause it doesn't catch not found error and use nil pointer.
We should consider the case of bids not found.
> fix (backing image): fix bids not found crash during clean up

- controller/volume_controller.go
> Fix: Only active replica if it doesn't have deletion timestamp

- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/sharemanager.go
Incorrect change
This reverts commit 77b4bcc9db2a4ecc792c550054cd387bfa2ae990.
> chore(crd): revert "crd: add IP address of share manager pod to status in share manager's CRD"

- controller/engine_controller.go
> [BACKPORT] [v1.3.3] chore(log): fix misleading log (backport #1816)

- controller/engine_controller.go
> [BACKPORT] [v1.4.2] chore(log): fix misleading log (backport #1816)

- app/recurring_job.go
- datastore/longhorn.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/recurringjob.go
- webhook/resources/recurringjob/mutator.go
https://github.com/longhorn/longhorn/issues/5186
> feat(recurring-job): filesystem trim

- csi/node_server.go
- types/setting.go
https://github.com/longhorn/longhorn/issues/4914
Remove deprecated mkfs-ext4-parameters setting.
> Remove deprecated mkfs-ext4-parameters setting

- controller/backup_volume_controller.go
Users have two operations
1. delete backup -> delete backup CR
2. delete all backup -> delete backup volume CR -> delete all backup
when deleting backup we check if it is used for restoration and wait until it finished [code](https://github.com/longhorn/longhorn-manager/blob/master/controller/backup_controller.go#L305)
but when `deleting all backup -> delete backup volume` we didn't check if there is any backup of the backup volume is used for restoration 
- so the volume in restoration will  stuck in progress because remote backupstore is deleted already
- and volume wii be in attached state and Ready for workload = Not Ready
we should wait until there is no any backup of the backup volume is used for restoration 
ref: [longhorn/longhorn#5506](https://github.com/longhorn/longhorn/issues/5 …
> fix(backup): wait until restoration finished before deleting the backup volume

- types/setting.go
- upgrade/upgrade.go
- upgrade/util/util.go
longhorn/longhorn#4997
This would look cleaner if we followed my suggestion in https://github.com/longhorn/longhorn/issues/5131#issuecomment-1544541401, but there may good reason not to do so. For now, I left a local copy of the setting in `upgrade/v120to121/upgrade.go` so the project will build.
> Remove disable-replica-rebuild setting

- controller/setting_controller.go
- types/setting.go
- types/types.go
ref: [longhorn/longhorn#5888](https://github.com/longhorn/longhorn/issues/5888)
add global setting for log level used in longhorn manager, default is warning
> feat(log): add global setting for log level

- api/model.go
- api/node.go
- client/generated_instance_manager.go
- client/generated_node.go
- controller/controller_manager.go
- controller/setting_controller.go
- datastore/longhorn.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/node.go
- types/setting.go
- types/types.go
- webhook/resources/node/validator.go
https://github.com/longhorn/longhorn/issues/5917
> chore: remove Guaranteed Engine/Replica CPU settings

- controller/volume_controller.go
- scheduler/replica_scheduler.go
- types/types.go
- types/types_test.go
- util/util.go
https://github.com/longhorn/longhorn/issues/5971
> fix(replica-auto-balance): filter node-selector

- controller/recurring_job_controller.go
- controller/volume_controller.go
- datastore/longhorn.go
- manager/volume.go
- types/types.go
https://github.com/longhorn/longhorn/discussions/5791
> feat(recurring-job): set recurring job to pvc

- types/setting.go
ref: [longhorn/longhorn5888](https://github.com/longhorn/longhorn/issues/5888)
> fix: change log level to Debug

- controller/replica_controller.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/backingimage.go
- k8s/pkg/apis/longhorn/v1beta2/backingimagemanager.go
- k8s/pkg/apis/longhorn/v1beta2/instancemanager.go
- k8s/pkg/apis/longhorn/v1beta2/replica.go
- k8s/pkg/apis/longhorn/v1beta2/volume.go
- k8s/pkg/apis/longhorn/v1beta2/zz_generated.deepcopy.go
https://github.com/longhorn/longhorn/issues/3289
> chore: remove deprecated fields

- controller/volume_controller.go
- util/k8s.go
https://github.com/longhorn/longhorn/issues/5448
> fix(data-locality): strict-local adds node affinity to PV

- controller/share_manager_controller.go
Add support for crypto parameters for RWX volumes
Ref: longhorn/longhorn#3353, longhorn/longhorn#4829
> fix(encrypt) crypto parameters for RWX volumes

- controller/system_backup_controller.go
https://github.com/longhorn/longhorn/issues/5011#issuecomment-1569823220
> fix(system-backup): volume backup duplicated backup name

- datastore/longhorn.go
Remove the default image from the selector.
> fix(storage-network): volume detach check

- controller/instance_manager_controller.go
- types/setting.go
> Remove deprecated allow-node-drain-with-last-healthy-replica setting

- csi/controller_server.go
- csi/deployment_util.go
- csi/node_server.go
ref: [longhorn/longhorn#5888](https://github.com/longhorn/longhorn/issues/5888)
> fix(logging): review and adjust log message and level in csi plugin

- engineapi/instance_manager.go
> Reduce the number of replica ports of a legacy volume to 10

- controller/uninstall_controller.go
ref: [longhorn/longhorn#5868](https://github.com/longhorn/longhorn/issues/5868)
> fix(backup uninstall): delete backup having no backup volume manually when uninstall

- controller/engine_controller.go
> Fix invalid memory address or nil pointer dereference

- engineapi/engine_binary.go
> SPDK volume does not support engine binary client

- types/setting.go
> Reduce BackupConcurrentLimit and RestoreConcurrentLimit to 2

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
from v1_20230407 to v1_20230616
Ref: longhorn/longhorn#4927
> update: update instance-manager image version

- engineapi/instance_manager.go
The default value of sync-agent-port-count is 10 ([code](https://github.com/longhorn/longhorn-engine/blob/master/app/cmd/replica.go#L58)), and it is fine when DefaultReplicaPortCount is 15. Currently, DefaultReplicaPortCount is set to 10, 3 ports are used by replica server, data server and syncagent server. Hence, sync-agent-port-count should be `DefaultReplicaPortCount - 3`.
Longhorn/longhorn#6145
> Set correct sync-agent-port-count when creating a replica process

- controller/backup_controller.go
Backing up a small size of a snapshot will cause the backup volume tries to synchronize the `backup.Spec.SyncRequestedAt` and it will make a conflict when this new creating backup tries to update its status and then re-queue it to make a second time snapshot backup at engine side.
Regression test:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4235
Re-run Regression test:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4245
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4248
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4250
Ref: longhorn/longhorn#6130
> fix(backup): backup a snapshot twice

- types/setting.go
> Highlight CPU usage in v2-data-engine setting

- controller/setting_controller.go
- types/setting.go
- util/struct.go
- util/util.go
https://github.com/longhorn/longhorn-manager/pull/1891#issuecomment-1588645215
https://github.com/longhorn/longhorn/issues/5235
> feat(upgrade-checker):  implement extra info (tag, field)

- controller/volume_attachment_controller.go
If a degraded volume is in maintenance mode, the replica rebuilding can directly be executed and no need to detach it again.
Longhorn/longhorn#6166
> Fix attaching/detaching loop when a degraded SPDK volume is in maintenance mode

- controller/uninstall_controller.go
https://github.com/longhorn/longhorn/issues/6185
> fix(uninstall): system backup CRs not deleted

- controller/volume_attachment_controller.go
https://github.com/longhorn/longhorn-manager/pull/2035
> [BACKPORT][v1.5.x] Fix migration stuck due to snapshot chains in old engine and new engine mismatch

- controller/backup_controller.go
ref: [longhorn/longhorn#6264](https://github.com/longhorn/longhorn/issues/6264)
> fix(backup): pvc storage class could be in annotation

- engineapi/instance_manager.go
> Fix socket fd leakage

- csi/deployment_util.go
- upgrade/v14xto150/upgrade.go
- util/util.go
- webhook/resources/volume/mutator.go
The patch is only for improving resilience.
Longhorn/longhorn#6259
> Mutate the resources that need update during upgrade

- api/router.go
> api: generalize writeErr function

- controller/volume_controller.go
Just found one change was missing in the last commit
> Move some debug level messages to info level

- controller/setting_controller.go
https://github.com/longhorn/longhorn/issues/6410
> fix(telemetric): collect SettingNameSnapshotDataIntegrityCronJob setting as boolean

- webhook/resources/backingimagemanager/mutator.go
> [BACKPORT][v1.5.2] Fix backing image manager webhook is never called

- upgrade/util/util.go
Removing duplicated package imported.
> refactor: duplicated package imported

- metrics_collector/types.go
- metrics_collector/volume_collector.go
https://github.com/longhorn/longhorn/issues/5297
> feat: add pvc name to volume metrics

- util/util.go
https://github.com/longhorn/longhorn/issues/3786
> feat: remove non-existing source directory log

- app/daemon.go
- app/driver.go
- app/get_proc_arg.go
- app/migrate.go
- app/post_upgrade.go
- app/pre_upgrade.go
- app/recovery_backend.go
- app/recurring_job.go
- app/uninstall.go
- app/upgrader.go
- app/webhook.go
Tidying up imports so they are consistent throughout the project.
> refactor: cleanup imports

- controller/support_bundle_controller.go
Fixed missing informer in cacheSyncs.
> fix(support-bundle): missing informer in cacheSyncs

- types/setting.go
> backup store: support SMB/CIFS hidden share

- controller/volume_controller.go
ref: [longhorn/longhorn#6019](https://github.com/longhorn/longhorn/issues/6019)
To prevent log flooding issue here https://github.com/longhorn/longhorn/issues/4069
We could move most of scheduling log messages to debug level and only keep those important decision message
And only do `getIsSchedulableToDiskNodes` check when there is `adjustCount` so we can reduce the log from checking function
> refactor(logging): change scheduling related message to debug

- api/model.go
- client/generated_controller.go
- client/generated_pvcreate_input.go
- client/generated_replica.go
- client/generated_volume.go
- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/instance_handler.go
- controller/instance_handler_test.go
- controller/replica_controller.go
- controller/utils.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- engineapi/instance_manager.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/instancemanager.go
- k8s/pkg/apis/longhorn/v1beta2/volume.go
- manager/volume.go
- scheduler/replica_scheduler.go
- scheduler/replica_scheduler_test.go
- upgrade/v15xto160/upgrade.go
- webhook/resources/volume/mutator.go
- webhook/resources/volume/validator.go
> Replace spec.engineImage with spec.image in volume, replica and engine resources

- csi/controller_server.go
- csi/crypto/luks.go
- csi/deployment.go
- csi/node_server.go
- csi/util.go
> Support encrypted volumes in block mode

- csi/node_server.go
- biggger timeo and retrans
- softerr: return ETIMEDOUT rather than EIO. Fall back to soft if the option is not supported
Longhorn/longhorn#6655
> RWX volume: use bigger timeo, retrans and softerr for nfs client

- app/daemon.go
- datastore/kubernetes.go
- types/types.go
- upgrade/upgrade.go
- upgrade/util/util.go
Backport of https://github.com/longhorn/longhorn-manager/pull/2166
> [Backport-v1.4.4] Waiting for old Longhorn manager to be fully removed before starting upgrade path

- controller/backing_image_controller.go
- controller/backing_image_data_source_controller.go
- controller/backing_image_manager_controller.go
- controller/backup_controller.go
- controller/backup_target_controller.go
- controller/backup_volume_controller.go
- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/kubernetes_configmap_controller.go
- controller/kubernetes_node_controller.go
- controller/kubernetes_pdb_controller.go
- controller/kubernetes_pod_controller.go
- controller/kubernetes_pv_controller.go
- controller/kubernetes_secret_controller.go
- controller/node_controller.go
- controller/orphan_controller.go
- controller/recurring_job_controller.go
- controller/replica_controller.go
- controller/setting_controller.go
- controller/share_manager_controller.go
- controller/snapshot_controller.go
- controller/support_bundle_controller.go
- controller/system_backup_controller.go
- controller/system_restore_controller.go
- controller/system_rollout_controller.go
- controller/utils.go
- controller/volume_controller.go
This is a backport of https://github.com/longhorn/longhorn-manager/pull/2211
> [Backport-v1.4.4] Improve log level for reconciliation error

- metrics_collector/disk_collector.go
New metric is created called longhorn_disk_status. Works similary as longhorn_node_status, it exposes information about disk by adding conditions as metric labels.
With this metric one can setup alerts in prometheus in case disk is not schedulable
resolves https://github.com/longhorn/longhorn/issues/6858
> Add metrics about disk conditions

- controller/instance_manager_controller.go
- controller/node_controller.go
Backport of pull request https://github.com/longhorn/longhorn-manager/pull/2102
> Update unknown instance manager handling logic (backport #2102)

- controller/share_manager_controller.go
- controller/volume_attachment_controller.go
Add messages for helping debug.
> misc: add logs for volume attachment and detachment

- metrics_collector/disk_collector.go
- upgrade/upgrade.go
- upgrade/util/util.go
- upgrade/util/util_test.go
- upgrade/v15xto160/upgrade.go
- upgrade/v1beta1/upgrade.go
- util/client/client.go
- util/cmd.go
- util/daemon/daemon.go
- util/server/server.go
> style: imports

- util/client/client.go
https://github.com/longhorn/longhorn-manager/pull/2237/files#r1368404186
> fix(import): typo

- app/daemon.go
- app/recovery_backend.go
- app/webhook.go
- controller/controller_manager.go
- util/client/client.go
- webhook/server/mutation.go
- webhook/server/server.go
- webhook/server/validation.go
Longhorn/longhorn#6866
Longhorn/longhorn#6936
> Eliminate multiple client creations

- upgrade/v14xto150/upgrade.go
longhorn/longhorn#6653
Problem:
The v1.4.x -> v1.5.0 upgrade logic caches entirely new Longhorn volume attachments. [The v1.5.2 logic that ultimately updates the volume attachments on the cluster](https://github.com/longhorn/longhorn-manager/blob/55a90cf72b98a0399672eb6d1de3fd5e69b98f95/upgrade/util/util.go#L958-L987) assumes that it should do an update to any existing Longhorn volume attachments with the contents of the cached resources. If, for some reason, a previous upgrade v1.4.x -> v1.5.2 failed BUT successfully created Longhorn volume attachments, that logic attempts to do an update with an entirely new Longhorn volume attachment. This is illegal, as `metadata.resourceVersion` is not set.
Solution:
Populate the cache with existing Longhorn volume attachments in the v1.4.x -> v1.5.0 …
> Don't crash when upgrading volume attachments after a previous failure

- metrics_collector/types.go
- metrics_collector/volume_collector.go
https://github.com/longhorn/longhorn/issues/7077
> feat(metrics): add pvc namespace to volume metrics

- package/Dockerfile
ref: https://github.com/longhorn/longhorn/issues/5911
> build: reduce iamge size by removing unused packages

- csi/crypto/crypto.go
- csi/crypto/luks.go
> csi: log the stderr output of cryptsetup

- controller/backing_image_data_source_controller.go
- controller/backing_image_manager_controller.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/share_manager_controller.go
- csi/deployment.go
- types/deploy.go
https://github.com/longhorn/longhorn/issues/5681
> feat: add GOCOVERDIR for deployment

- controller/share_manager_controller.go
> share manager: update status to error if unable to re-mount volume

- package/Dockerfile
ref: https://github.com/longhorn/longhorn/issues/7143
> build: add zip/unzip package for backup and restore

- types/types.go
- webhook/resources/node/validator.go
> Global setting default-data-path supports block device

- k8s/generate_code.sh
Fix "unbound variable" error if GOPATH is not set correctly.
> k8s: fix generate_code.sh

- datastore/longhorn.go
> Return a clear error when attaching with no scheduled replicas

- controller/share_manager_controller.go
Issues:  https://github.com/longhorn/longhorn/issues/6776 and https://github.com/longhorn/longhorn/issues/7112
> 6776 - Simplify share-manager volume attachment path.

- datastore/longhorn.go
https://github.com/longhorn/longhorn/issues/6508
> fix(replica-auto-balance): loop when node has no schedulable disk

- controller/volume_controller.go
- scheduler/replica_scheduler.go
https://github.com/longhorn/longhorn/issues/6671
> fix(replica-auto-balance): loop when node has no storage available

- metrics_collector/backup_collector.go
> refactor: correcting variable names

- controller/setting_controller.go
- k8s/pkg/apis/longhorn/v1beta2/node.go
- types/device.go
https://github.com/longhorn/longhorn/issues/6033
> feat(telemetry): collect SPDK related info

- controller/node_controller.go
longhorn/longhorn#7302
When kubelet goes down, we generally aren't able to update the node.longhorn.io for 40 seconds.
- https://github.com/kubernetes/kubernetes/blob/0c645922edcc06adff43c70c02fb56751364bbb5/pkg/controller/nodelifecycle/config/v1alpha1/defaults.go#L41
- https://github.com/kubernetes/kubernetes/blob/0c645922edcc06adff43c70c02fb56751364bbb5/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L926
However, when kubelet is restarted, it is able to report an interim unhealthy status immediately. In my testing, this interim unhealthy status may only last for less than a second, but it leads directly to the killing of migration engines.
This PR allows us to wait 10 seconds before reacting to an unhealthy kubelet.
> Allow kubelet to be down for 10 seconds before responding

- metrics_collector/metrics_collector.go
> refactor(metrics_collector): replace abbreviations

- datastore/longhorn.go
- types/setting.go
- webhook/resources/recurringjob/validator.go
Add a global setting to allow users to customize the maximum retain number of the snapshot or backup for a recurring job.
This number should not exceed the maximum number of snapshots (250).
Ref: longhorn/longhorn#5713
> feat: customize MaxRecurringJobRetain

- controller/volume_controller.go
longhorn/longhorn#6961
This addresses a slightly modified version of the original race described in https://github.com/longhorn/longhorn/issues/6961#issuecomment-1854811140.
> Don't start migrating when a replica will start to rebuild

- metrics_collector/metrics_collector.go
- metrics_collector/snapshot_collector.go
- metrics_collector/types.go
https://github.com/longhorn/longhorn/issues/5869
> feat(metrics): collect snapshot size

- controller/setting_controller.go
https://github.com/longhorn/longhorn/issues/7380
> fix(telemetry): wrong average volume sizes due to V2 volume counts

- metrics_collector/snapshot_collector.go
- metrics_collector/types.go
https://github.com/longhorn/longhorn/issues/5869#issuecomment-1865823767
> fix(metrics): snapshot size was collected before with the same name and label values

- webhook/resources/replica/validator.go
To prevent accidentally from deleting the last replica regardless of that it is healthy or faulty, reject the last replica deletion if spec.deletionTimestamp of its volume is not set in the validating webhook.
Longhorn/longhorn#7372
> Reject the last healthy replica deletion

- webhook/resources/volume/validator.go
> Reject the creation of encrypted v2 volume in validating webhook

- controller/node_controller.go
longhorn/longhorn#7302
https://github.com/longhorn/longhorn-tests/pull/1629#issuecomment-1866933096
> Increase ignoreKubeletNotReadyTime to 15 seconds

- Dockerfile.dapper
- scripts/validate
https://github.com/longhorn/longhorn/issues/7366
> ci: add condition for merge to master

- types/types.go
> disk: only reject automatic creation of default block-type disk

- webhook/resources/volume/mutator.go
- webhook/resources/volume/validator.go
> Explicitly reject encrypted and backing image for v2 volumes

- controller/engine_controller.go
- datastore/longhorn.go
- engineapi/types.go
- go.mod
- go.sum
- upgrade/util/util.go
- upgrade/util/util_test.go
- vendor/github.com/longhorn/longhorn-engine/pkg/meta/version.go
- vendor/modules.txt
- webhook/resources/engine/validator.go
- webhook/resources/replica/validator.go
- webhook/resources/volume/validator.go
https://github.com/longhorn/longhorn/issues/5842
> feat: engine version enforcement

- csi/deployment.go
https://github.com/longhorn/longhorn/issues/7377
https://github.com/longhorn/longhorn/issues/7384
https://github.com/longhorn/longhorn/issues/6916
> chore(csi): update default images version

- controller/setting_controller.go
`...Infof call needs 2 args but has 3 args`
> fix(log): mismatched args

- controller/backup_target_controller.go
- controller/monitor/disk_monitor.go
- datastore/longhorn.go
> controller: use available data engine for getting backup target client

- controller/instance_manager_controller.go
Issue longhorn/longhorn#7551
- instancce manager pod for v1 data engine
- 8500: process manager grpc service
- 8501: proxy grpc service
- 8502: disk grpc service
- 8503: instance grpc service
- instancce manager pod for v2 data engine
- 8500-8503
- 8504: spdk grpc service
- spdk_tgt daemon process
https://github.com/longhorn/longhorn-spdk-engine/pull/87
> instance manager: update liveness probe

- webhook/common/common.go
Add break for early exit from the loop once the finalizer is found.
> refactor(webhook): break for early exit in finalizer check

- controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/7555
1. Install Longhorn `v1.5.3`
```
git clone https://github.com/longhorn/longhorn
cd longhorn/chart
git checkout v1.5.3
helm install longhorn . --namespace longhorn-system --create-namespace
```
2. Create a volume from UI and attach it to a node
3. Upgrade Longhorn to `master-head`
```
git checkout master
helm upgrade longhorn . --namespace longhorn-system \
--set image.longhorn.engine.repository=frankyang/longhorn-engine \
--set image.longhorn.engine.tag="arm64-latest" \
--set image.longhorn.manager.repository=frankyang/longhorn-manager \
--set image.longhorn.manager.tag="arm64-latest" \
--set image.longhorn.instanceManager.repository=frankyang/longhorn-instance-manager \
--set image.longhorn.instanceManager.tag="arm64-latest" \
--set …
```
> fix: add condition for updating snapshot attritube to engine

- controller/backup_controller.go
> backup controller: fix log message

- engineapi/proxy_volume.go
https://github.com/longhorn/longhorn/issues/6563
In https://github.com/longhorn/longhorn-manager/pull/2386/files, we replaced backend store driver with data engine. We should also apply it on snapshot related APIs.
> fix: replace backend store driver with data engine

- controller/backup_controller.go
Issue https://github.com/longhorn/longhorn/issues/6654
Ensures that the temporary volume attachment used to create a backup is detached when the backup creation is complete.
> 6654 - Move deletion of backup volume attachment ticket.

- types/setting.go
Issue https://github.com/longhorn/longhorn/issues/7606
> Incease default hugepage size for v2 data engine to 2GiB

- api/model.go
- api/volume.go
- client/generated_volume.go
https://github.com/longhorn/longhorn/issues/7522
Support `snapshotMaxCount` and `snapshotMaxSize` in LH Volume API.
> feat: add snapshotMaxCount and snapshotMaxSize to Volume API

- webhook/resources/volume/validator.go
Issue Longhorn/longhorn#7627
Reject DR volume creation for v2 volume.
The rejection will be removed after supporting DR volume feature.
> Reject DR volume creation for v2 volume

- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/engine_image_controller_test.go
- datastore/longhorn.go
- engineapi/types.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/engineimage.go
- upgrade/util/util.go
- upgrade/util/util_test.go
- upgrade/v15xto160/upgrade.go
- webhook/resources/engine/validator.go
- webhook/resources/replica/validator.go
- webhook/resources/volume/validator.go
Issue longhorn/longhorn#7539
Skip to check the engine upgrade path if the upgrade version check flag is disabled.
> fix(upgrade): skip to check engine upgrade path

- api/model.go
- api/volume.go
- client/generated_client.go
- client/generated_update_snapshot_max_count_input.go
- client/generated_update_snapshot_max_size_input.go
- manager/volume.go
https://github.com/longhorn/longhorn/issues/7522
add updateSnapshotMaxCount and updateSnapshotMaxSize to Volume actions
> feat: add updateSnapshotMaxCount and updateSnapshotMaxSize actions

- api/model.go
- client/generated_update_snapshot_max_count_input.go
https://github.com/longhorn/longhorn/issues/7522
Addressed comment in https://github.com/longhorn/longhorn-manager/pull/2447#issuecomment-1887221111.
> feat: add updateSnapshotMaxCount and updateSnapshotMaxSize to schema

- client/generated_instance_manager.go
https://github.com/longhorn/longhorn/issues/7095
> feat: add DataEngine to generated_instance_manager.go

- controller/uninstall_controller.go
- datastore/kubernetes.go
- types/types.go
- types/webhook.go
- webhook/server/server.go
> Fix uninstallation job forgot to cleanup some resources

- csi/node_server.go
> Crypto device mapper of RWX volume with migratable=true is not cleaned up

- webhook/resources/engine/validator.go
- webhook/resources/replica/validator.go
Issue longhorn/longhorn#7631
Allow to modify a volume, create/update an engine, or create/update a replica with its engine image incompatible when the volume is attached.
Not affect to the engine image `master-head`:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5985
> fix(engineimage): engine image incompatible

- controller/setting_controller.go
Issue longhorn/longhorn#7676
Check if volumes are attached for v1 and v2 dataEngine separately when updating the setting `GuaranteedInstanceManagerCPU` or `V2DataEngineGuaranteedInstanceManagerCPU`.
> fix(dataengine): separately update the setting for IMs CPU.

- types/setting.go
Issue longhorn/longhorn#7173, longhorn/longhorn#7675
Remove the descriptions such as `WARNING: volumes can not be attached` for updating danger zone settings.
> doc(setting): modify for lazy updating

- controller/volume_controller.go
ref: https://github.com/longhorn/longhorn/issues/7728
StorageClass can specify the mountOption.
User may intend to mount the volume as read-only by giving "ro" in the mountOptions in StorageClass
We should only restart the Pod when it is read-only and there is no "ro" in mountOption
> fix(volume): only restart pod when it is ro and the option is not ro

- csi/node_server.go
- csi/util.go
Issue longhorn/longhorn#7694
See the *So, What Happened?* section in https://github.com/longhorn/longhorn/issues/7694#issuecomment-1893094315.
`None`
`None`
> fix(csi): volume manager failed to find vol_data.json after kubelet restart

- engineapi/instance_manager.go
ref: https://github.com/longhorn/longhorn/issues/7501
> fix(instance): add conditions when parsing instance

- controller/volume_controller.go
Fix a TODO: add the AD state machine graph to the code for better readability
> Add the AD state machine graph

- controller/volume_controller.go
- manager/volume.go
Longhorn 7997
https://github.com/longhorn/longhorn/issues/7997
> controller: Allow DR volume activation if the latest backup is not found

- controller/volume_controller.go
- manager/volume.go
https://github.com/longhorn/longhorn/issues/7997
> Allow DR volume activation if backup or backup volume is deleted

- controller/backup_target_controller.go
Issue longhorn/longhorn#8045
Do not update the LastSyncedAt when the controller marks the BackupTarget unavailable.
> fix(backuptarget): backuptarget update skipped when enqueued by engineimage update

- api/backupbackingimage.go
- api/model.go
- api/router.go
- client/generated_backup_backing_image.go
- client/generated_client.go
- datastore/longhorn.go
- manager/backupbackingimage.go
- manager/volume.go
ref: 
https://github.com/longhorn/longhorn/issues/8068
https://github.com/longhorn/longhorn/issues/7541
1. Get `BackupBackingImages (list)`
2. Get `BackupBackingImage`
3. Delete `BackupBackingImage`
4. For each BackupBackingImage, we have action `backupBackingImageRestore`
5. For each BackingImage, we have new action `backupBackingImageCreate`
> feat(backupbackingimage): add backend api

- controller/setting_controller.go
- util/util.go
Issue longhorn/longhorn#7797
Check if the settings are synchronized first instead of checking
if volumes are attached first to eliminate unnecessary error logs.
> fix(setting): check if the settings are synchronized first.

- scripts/test
https://github.com/longhorn/longhorn/issues/8400
> Add coverage.out file after running the test

- .github/workflows/build.yml
https://github.com/longhorn/longhorn/issues/8039
> ci: fix images tag

- controller/volume_controller.go
- scheduler/replica_scheduler.go
- upgrade/v16xto170/upgrade.go
- webhook/resources/volume/mutator.go
- webhook/resources/volume/validator.go
>  Remove v2 volume offline rebuilding

- .github/workflows/build.yml
https://github.com/longhorn/longhorn/issues/8039
> fix: remove parameters for checkout action

- controller/instance_manager_controller.go
> Close instance manager client after synchronizing log settings

- go.mod
longhorn/longhorn#8481
I will wait on https://github.com/longhorn/longhorn-manager/pull/2592 to transition this to ready for review, since it might make merging that one more difficult (and that one will likely make this one unmergeable without modification).
> Add replace directive clarifying comment

- controller/uninstall_controller.go
ref: https://github.com/longhorn/longhorn/issues/8408
* In `deleteCRDs` we delete the `BackupTarget` if it is found
* We return and wait for the next reconcile to see if the resource is truly deleted by checking `len(BackupTarget) == 0`
* We only start to delete manager when we make sure all the CRs are deleted.
* But there is a large chance that the BackupTarget just got recreated between two reconciliation
Just like the comment mentions
> // A race condition exists where manager may attempt to recreate certain
> // CRDs after their deletion. We must delete manager and do a final check
> // for CRDs, just in case.
But actually, the logic won't work because if the BackupTarget gets recreated fast enough then there is no chance for the `uninstall()` function to execute `deleteManager()`. …
> fix(uninstall): delete recreated CR after managers are deleted

- controller/engine_image_controller.go
- datastore/kubernetes.go
> controller: Avoid unnecessary DeepCopy in EngineImageController list functions

- datastore/longhorn.go
Issue # longhorn/longhorn#7159
> fix(backup): appropriate warning messages for credential data

- controller/replica_controller.go
Issue Longhorn/longhorn#8551
Expose all logical volume and attach it to attached node.
> v2 volume: expose all replica instances

- api/model.go
- controller/node_controller_test.go
Issue # longhorn/longhorn#8070
> fix(setting): add `applied` field in RESTFul APIs

- csi/util.go
- types/setting.go
> Disable revision counter by default

- csi/controller_server.go
Found a small error in a log message while debugging with a customer. Won't create an issue for it.
cc @PhanLe1010
> Fix ControllerUnpublishVolume failure message

- controller/controller_test.go
- controller/monitor/disk_monitor.go
- controller/monitor/fake_disk_monitor.go
- controller/node_controller.go
- controller/orphan_controller.go
- types/types.go
- webhook/resources/orphan/validator.go
https://github.com/longhorn/longhorn/issues/8642
> Minor improvement for orphan creation

- .gitignore
> .gitignore: exclude Dockerfile.dapper[0-9]*

- controller/engine_controller.go
- engineapi/engine.go
- engineapi/enginesim.go
- engineapi/enginesim_test.go
- engineapi/proxy_replica.go
- engineapi/proxy_snapshot.go
- engineapi/snapshot.go
- engineapi/types.go
- go.mod
- go.sum
- types/setting.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy_replica.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy_snapshot.go
- vendor/modules.txt
longhorn/longhorn#2765
Note: we need to update go.mod to have this changes: before merging:
1. https://github.com/longhorn/types/pull/14
2. https://github.com/longhorn/longhorn-instance-manager/pull/512
> Make long gRPC timeout configurable

- controller/setting_controller.go
Issue # longhorn/longhorn#6446
> fix(setting): create a real SC for the setting "default-longhorn-static-storage-class"

- upgrade/v16xto170/upgrade.go
See explanation at https://github.com/longhorn/longhorn/issues/8844#issuecomment-2197769331
longhorn/longhorn#8844
> Remove headless services for instance manager pods

- controller/setting_controller.go
- types/setting.go
- types/types.go
Issue Longhorn/longhorn#7939
1. Remove Disabled which is not supported by spdk_tgt yet.
2. Rename level Warn to Warning. spdk_tgt only accepts Warning.
> fix(log): fix the log levels of v2 data engine

- controller/volume_controller.go
Issue longhorn/longhorn#8869
Bypass the precheck when hardNodeAffinity is provided, as users would expect a new Replica CR to be created in this scenario.
`None`
https://github.com/longhorn/longhorn-manager/pull/2918
> fix(volume-controller): replica CR not created when data-locality set best-effort

- csi/controller_server.go
ref: https://github.com/longhorn/longhorn/issues/6526
- allow user to set node and disk selector to the backing image through csi volumesnapshot
> feat(csi backingimage): allow csi snapshot backing image can set node and disk selector

- manager/recurringjob.go
ref: https://github.com/longhorn/longhorn/issues/8291
fix update recurring job parameters doesn't work issue
> fix(recurring): fix update recurring job parameters does not work issue

- controller/volume_controller.go
- controller/volume_controller_test.go
Issue None
Enhance precheck error.
`None`
`None`
> feat(volume-controller): enhance precheck error

- k8s/crds.yaml
- k8s/generate_code.sh
- k8s/patches/crd/webhook/backingimage.yaml
- k8s/patches/crd/webhook/backuptarget.yaml
- k8s/patches/crd/webhook/node.yaml
- k8s/patches/crd/webhook/volume.yaml
Issue longhorn/longhorn#8901
- update controller-gen to `v0.15.0`
- update kustomize to `kustomize/v5.4.2`
> chore(k8s): update controller-gen and kustomize

- api/router.go
> fix: fix backupbackingimage websocket typo

- webhook/resources/backingimage/mutator.go
in the backing iamge webhook mutator
use ignore as default value when encryption is not set
> fix(backing image clone): use ignore as default value when encryption is not set

- controller/websocket_controller.go
Need to add the informer to websocket controller so the websocket can work
- Have tested it in local env
- Have tested it with UI
cc @a110605
> fix(websocket): add backup backing image websocket to websocket controller

- controller/volume_controller.go
longhorn/longhorn#3692
Don't block cloning if `e.Status.CloneStatus` has empty entries
> Fix cloning stuck due to having empty entries in e.Status.CloneStatus

- datastore/longhorn.go
Issue Longhorn/longhorn#8967
There is one running instance manager for v2 data engine on each node, so the function find one running instance manager instead.
> fix(datastore): CheckInstanceManagersReadiness should find running instance managers for v2 data engine

- controller/node_controller.go
Issue # longhorn/longhorn#7571
Fix commands and options to get the correct environment package information.
> fix(node): broken commands to get packages information

- controller/setting_controller.go
- datastore/longhorn.go
Issue longhorn/longhorn#9014, longhorn/longhorn#9022
Fix AreAllRWXVolumesDetached to check if there are no more Longhorn VolumeAttachment for the RWX volumes.
`None`
- https://github.com/longhorn/longhorn/issues/9022#issuecomment-2234423678
> fix(rwx): workload pod hangs after node reboot

- controller/engine_controller.go
- controller/replica_controller.go
- controller/volume_controller.go
Without the fix, volume/engine/replica continue to wait for the share manager pod to be scheduled (i.e., pod.Spec.NodeName is non empty) to set ownerID to the same pod's node. However, because we don't want to use pod's imformers, when the share manager pod is scheduled, volume/engine/controller might not catch that event and continue to wait. This introduce up to 30s delay and behavioral inconsistency
Also, the > 30s delay in share manager pod recreation is destroying the RWX fast failover's original goal
longhorn/longhorn#6205
Some testing results:
* Before the fix, it was taking from 15s to 70s for the new share manager pod to become running after shutting down the node of the old share manager pod
* After the fix, it is taking from 15s to 17s for the new share manager pod to become …
> If volume is delinquent, switch owner of volume/engine/replica to share manager CR's owner

- controller/share_manager_controller.go
1. Switch the share manager controller sync loop to sync volume first then sync share manager pod after
2. Skip calling gprc to mount the share manager volume if the share manager is currently delinquent. This helps to avoid the 20s delay when attemping to make the grpc call to dead share-manager pod
This PR helps:
1. Fulfill the requirement to the investigation at https://github.com/longhorn/longhorn-manager/pull/2811#issuecomment-2244142848
2. Resolve the fail test https://github.com/longhorn/longhorn/issues/9081
longhorn/longhorn#6205
> Maintain the previous state machine of share manager CR

- controller/share_manager_controller.go
- csi/deployment.go
- csi/node_server.go
- package/Dockerfile
- package/nsmounter
- types/deploy.go
See the explanation at:
1. RCA https://github.com/longhorn/longhorn/issues/9223#issuecomment-2285019408
2. Proposal https://github.com/longhorn/longhorn/issues/9223#issuecomment-2285033777
longhorn/longhorn#9223
> fix(networking): networking between longhorn-csi-plugin and longhorn-manager is broken after upgrading Longhorn to 1.7.0-rc3

- controller/instance_manager_controller.go
Issue # https://github.com/longhorn/longhorn/issues/9183
btw: https://github.com/longhorn/longhorn/issues/5910
Log more detailed message to help troubleshooting
Test log of manual attached volume when drain node
>time="2024-08-05T18:48:14Z" level=info msg="Node instance-manager-68cd2514dd3f6d59b95cbd865d5b08f7 is marked unschedulable but removing harv2 PDB is blocked: some volumes are still attached " func="controller.(*InstanceManagerController).syncInstanceManagerPDB" file="instance_manager_controller.go:730" controller=longhorn-instance-manager node=harv2
> fix(manager): add detailed message when deleting pdb is not allowed

- controller/instance_manager_controller.go
> fix(lint): avoid some lint errors about deprecated fields

- controller/engine_controller.go
- controller/instance_handler.go
- controller/replica_controller.go
- datastore/longhorn.go
> refactor: remove isCLIAPIVersionOne related codes

- controller/backup_controller.go
Issue # longhorn/longhorn#9252
Delete the snapshot directly by `backup.Spec.SnapshotName` when doing the automatic cleanup by deleting the backup.
> fix(backup): delete the snapshot directly by backup.Spec.SnapshotName.

- upgrade/v14xto150/upgrade.go
- webhook/resources/volume/mutator.go
Issue # https://github.com/longhorn/longhorn/issues/9279
Refer to https://github.com/longhorn/longhorn/issues/9279#issuecomment-2307833776
> fix: do not change the revisionCounterDisabled as it is an immutable field after creation

- controller/uninstall_controller.go
ref: https://github.com/longhorn/longhorn/issues/9303
We should ignore not found error when deleting resources
> fix(uninstall): ignore not found error when deleting CR

- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-engine/pkg/types/types.go
- vendor/github.com/longhorn/longhorn-engine/pkg/util/shared_timeouts.go
- vendor/modules.txt
Issue # longhorn/longhorn#9282
> chore(vendor): update dependencies

- controller/uninstall_controller.go
ref: https://github.com/longhorn/longhorn/issues/9303
should not return error when it is not found
> fix(uninstall): don't return error when error is not found

- upgrade/upgrade.go
- upgrade/v170to171/upgrade.go
- upgrade/v17xto180/upgrade.go
ref: https://github.com/longhorn/longhorn/issues/9352
add upgrade path
1.7.0 -> 1.7.1
1.7.x -> 1.8.0
> fix(backingimage): add upgrade path from 1.7.0 to 1.7.1 to add default min number of copies

- controller/volume_controller.go
Issue longhorn/longhorn#9011
Reduce logging noise. See https://github.com/longhorn/longhorn/issues/9011#issuecomment-2233714842.
`None`
Side-effect from https://github.com/longhorn/longhorn-manager/pull/1946.
> fix(logging): update log level to trace to reduce noise

- k8s/crds.yaml
- k8s/patches/crd/webhook/backingimage.yaml
- k8s/patches/crd/webhook/backuptarget.yaml
- k8s/patches/crd/webhook/engineimage.yaml
- k8s/patches/crd/webhook/node.yaml
- k8s/patches/crd/webhook/volume.yaml
> fix(crd): update conversion webhook port to 9501

- controller/system_restore_controller.go
Issue longhorn/longhorn#8656
The system restore rollout pod should respect taint toleration.
`None`
`None`
> fix(system-restore): should respect taint toleration

- webhook/resources/volume/validator.go
Issue # https://github.com/longhorn/longhorn/discussions/9804 https://github.com/longhorn/longhorn/issues/9805
allow changing the replica count for a v2 volume
> fix: allow changing the replica count for a v2 volume

- controller/volume_eviction_controller.go
Issue longhorn/longhorn#9781
https://github.com/longhorn/longhorn/issues/9781#issuecomment-2475637671
`None`
`None`
> fix: detached volume reattached after node eviction

- webhook/resources/node/validator.go
Issue # https://github.com/longhorn/longhorn/issues/9842
- This PR will enable modifying Storage Reserved for the block type as well
> feat(webhook): enable storage reserved updates via webhook

- api/model.go
- client/generated_disk_info.go
ref: https://github.com/longhorn/longhorn/issues/8757
Add scheduledBackingImage in node api resource
> feat: add scheduled backing image to node api resource

- controller/node_controller.go
Issue # https://github.com/longhorn/longhorn/issues/9915
Currently, the kernel module check only verifies dm_crypt. It would be beneficial to also check the kernel modules used by Longhorn Engine v2 (vfio_pci, uio_pci_generic, nvme_tcp) to ensure accurate node status reporting.
> feat: add kernel module check for data engine v2

- types/types.go
> fix(backup): modify backup volume and backup backing image name

- api/volume.go
> fix(backup): create volumes with backup target name

- go.mod
- go.sum
- vendor/modules.txt
Issue Longhorn/longhorn#9898
CVE-2024-45337 CRITICAL
usr/local/sbin/longhorn-manager (gobinary)
==========================================
Total: 2 (HIGH: 2, CRITICAL: 0)
> chore(vendor): update golang.org/x/crypto to v0.31.0

- controller/volume_controller.go
When replica is restarted unexpectedly, it will get new port number according to our new port allocation logic https://github.com/longhorn/longhorn/issues/8598
Longhorn autosalvage logic is blocked due to replica's port number has changed. Volume controller cannot find matching ip:port in engine's status to mark the replica as failed
This commit will mark all replicas' of the engine as failed if engine.Status.ReplicaModeMap contains all unknown and errored replicas. This trigger the autosalvage flow and unblock the deadlock
See more explaination at https://github.com/longhorn/longhorn/issues/9939#issuecomment-2549996366
longhorn/longhorn#9939
> fix: volume stuck in no backend available leading to IO errors

- upgrade/util/util.go
- upgrade/v17xto180/upgrade.go
> fix(upgrade): patch backup and backingImage status while upgrade

- app/recurring_job.go
- csi/controller_server.go
- manager/engine.go
> fix(backup): modify logic to list backup volume for recurring job and CSI snapshotter

- app/daemon.go
Issue longhorn/longhorn#10054
https://github.com/longhorn/longhorn-manager/pull/3405#issuecomment-2561576037
`None`
`None`
> refactor: move logic to startWebhooksByLeaderElection

- api/forwarder.go
- api/router.go
- controller/setting_controller.go
- datastore/longhorn.go
- types/setting.go
- webhook/resources/backuptarget/validator.go
- webhook/resources/systembackup/validator.go
> feat: remove default backup target settings

- upgrade/v17xto180/upgrade.go
Issue # longhorn/longhorn#10181
> fix(upgrade): directly add backup target label `default` to old backups

- controller/backup_controller.go
Issue https://github.com/longhorn/longhorn/issues/9978
> fix: close engine client in error path to avoid a leak

- README.md
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/backupbackingimage.go
- k8s/pkg/apis/longhorn/v1beta2/snapshot.go
> fix: remove redundant description

- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/backupvolume.go
Issue # longhorn/longhorn#10191
> fix(backup): add backup target column for backup volume

- api/model.go
Issue # longhorn/longhorn#10182
Ensure backups have backup target name and volume name in the
returning information of API `BackupList` and `BackupGet`.
Backups in state `pending`, `in-progress`, and `error`
will not have the backup target name and volume name in `b.Status`.
> fix(backup): modify backup APIs for backup target and volume name

- csi/controller_server.go
Issue # longhorn/longhorn#5411, longhorn/longhorn#9987, longhorn/longhorn#10024
> fix(backup): return null if backup volume is not found

- .github/workflows/create-crd-update-pr-in-longhorn-repo.yml
> fix(workflow): add commit message in create-crd-update-pr-in-longhorn-repo.yml

- k8s/crds.yaml
- k8s/patches/crd/webhook/engineimage.yaml
> fix: update k8s patch yamls

- .github/workflows/build.yml
- .gitignore
- Dockerfile.dapper
- Makefile
- package/Dockerfile
- scripts/build
- scripts/ci
- scripts/package
Backport the following secure PRs to v1.8.x:
- #3544 
- #3587
> feat(ci): Backport secure build to v1.8.x

- types/setting.go
> docs: update description for upgradeResponderURL

- controller/setting_controller.go
- go.mod
- go.sum
- vendor/github.com/longhorn/go-common-libs/ns/sys.go
- vendor/github.com/longhorn/go-common-libs/sys/sys.go
- vendor/golang.org/x/exp/constraints/constraints.go
- vendor/golang.org/x/exp/slices/slices.go
- vendor/golang.org/x/exp/slices/sort.go
- vendor/modules.txt
Issue longhorn/longhorn#7047
Gather host architecture and the count of encrypted volumes to the upgrade responder.
`None`
`None`
> feat(metric): collect system host arch and volume encrypted count

- controller/monitor/snapshot_monitor.go
Issue Longhorn/longhorn#10518
Snapshot checksum is used for fast replica rebuilding and identify corrupted replicas. If the healthy replica count is less than 2, the checksum is useless.
> feat(snapshot): skip snapshot calculation if volume's healthy replica count is less than 2

- controller/setting_controller.go
Issue longhorn/longhorn#7599
Gather:
- Number of replicas
- Number of snapshots
- Backing image count
- Orphan count
`None`
`None`
> feat(metric): extend upgrade responder collections

- k8s/generate_code.sh
Issue #10556
Currently, the code generator works only when the longhorn-manager's source is placed under conventional Go source, i.e. `$HOME/go/src/github.com/longhorn/longhorn-manager`. This change make it possible to execute even when the source part of Go workspace.
> chore(k8s): generalize K8s code generator

- csi/controller_server.go
ref: https://github.com/longhorn/longhorn/issues/9785
pass backup mode through csi volume snapshot
> feat: pass backup mode through csi volume snapshot

- engineapi/proxy_metrics.go
- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/disk.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/instance.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/process_manager.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy_backup.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy_metrics.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/proxy_replica.go
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/10472
> feat: add dataEngine field in MetricsGet

- upgrade/util/util.go
ref: https://github.com/longhorn/longhorn/issues/10646
> [Manually Backport] feat: add strict field validation to the upgrade operaiton in upgrade path

- types/setting.go
- types/types.go
> feat(setting): remove ValueIntRangeMaximum of v2-data-engine-guaranteed-instance-manager-cpu

- engineapi/proxy_snapshot.go
> fix: wrapping a nil error is misleading

- controller/kubernetes_pod_controller.go
Issue longhorn/longhorn#10689
Proactively clean up the Kubernetes VA of force-deleted pods. Without this, Kubernetes will eventually clean up the stale VA, but users may experience a significant delay before the pod becomes running again.
`None`
https://github.com/longhorn/longhorn/issues/10689#issuecomment-2788357346
> fix: cleanup K8s VA associated with force-deleted pods

- controller/monitor/snapshot_monitor.go
- go.mod
- go.sum
- types/setting.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/util/log.go
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/util/util.go
- vendor/modules.txt
- webhook/resources/volume/mutator.go
- webhook/resources/volume/validator.go
> feat: implement v2 volume data integrity feature 

- controller/backup_controller.go
Issue # longhorn/longhorn#9213
Delete the backup snapshot after the backup is completed and the backup status is updated correctly.
> fix(backup): delete snapshot after backup completed

- metrics_collector/engine_colletor.go
- metrics_collector/metrics_collector.go
- metrics_collector/types.go
https://github.com/longhorn/longhorn/issues/10550
> feat: add rebuildStatus metric for engine rebuild progress

- .coderabbit.yaml
Issue #
Add .coderabbit.yaml but disable auto_review.
> chore: add .coderabbit.yaml

- controller/uninstall_controller.go
Issue longhorn/longhorn#10731
Cleanup support bundle at uninstall.
`None`
`None`
> fix(uninstall): cleanup SupportBundle CRs

- metrics_collector/engine_colletor.go
- metrics_collector/metrics_collector.go
- metrics_collector/replica_collector.go
- metrics_collector/types.go
https://github.com/longhorn/longhorn/issues/10722
> feat: add prometheus metrics for replica and engine crs

- csi/controller_server.go
- csi/node_server.go
- csi/util.go
Support create ublk frontend volume from CSI flow
longhorn/longhorn#9456
> feat: implement ublk frontend for v2 data engine - part 3

- webhook/resources/persistentvolumeclaim/validator.go
Issue https://github.com/longhorn/longhorn/issues/10741
Fix the oversized PVC deletion issue
Testing plan: https://github.com/longhorn/longhorn/issues/10741#issue-3003794869
Please refer to https://github.com/harvester/harvester/issues/8096#issuecomment-2814328640 for more details
> fix: improve the volume expansion check in PVC validator

- api/model.go
- api/router.go
- api/volume.go
- client/generated_volume.go
- controller/volume_attachment_controller.go
- controller/volume_rebuilding_controller.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/volume.go
- k8s/pkg/client/applyconfiguration/longhorn/v1beta2/volumespec.go
- manager/volume.go
- types/setting.go
- types/types.go
- upgrade/v18xto190/upgrade.go
- util/util.go
- webhook/resources/volume/mutator.go
- webhook/resources/volume/validator.go
Issue # longhorn/longhorn#8443
- Introduce a global setting `offline-replica-rebuilding`
- Introduce the field `Volume.Spec.OfflineRebuild`
- Add APIs for the offline replica rebuilding
- Modify the setting and volume rebuild controllers to support volume offline rebuilding.
> feat(volume): offline replica rebuilding

- controller/engine_controller.go
- controller/monitor/snapshot_monitor.go
- controller/node_controller.go
- controller/snapshot_controller.go
- datastore/longhorn.go
- go.mod
- go.sum
- vendor/github.com/longhorn/backupstore/backupbackingimage/backupbackingimage.go
- vendor/modules.txt
Issue https://github.com/longhorn/longhorn/issues/10563
> feat: stop checksum hash

- vendor/modules.txt
PR longhorn/longhorn-manager#3715
Fix vendor to resolve build break in CI pipe: https://github.com/longhorn/longhorn-manager/actions/runs/14621878387/job/41023739095?pr=3694#step:4:586
> fix: update vendor for k8s.io/externaljwt

- api/model.go
- controller/instance_manager_controller.go
- controller/node_controller.go
- controller/node_controller_test.go
- controller/orphan_controller.go
- controller/setting_controller.go
- datastore/datastore.go
- datastore/longhorn.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/instancemanager.go
- k8s/pkg/apis/longhorn/v1beta2/orphan.go
- k8s/pkg/client/applyconfiguration/longhorn/v1beta2/orphanspec.go
- types/setting.go
- types/types.go
- upgrade/v18xto190/upgrade.go
- webhook/resources/orphan/mutator.go
- webhook/resources/orphan/validator.go
Issue longhorn/longhorn#6764
Implement orphaned runtime instance cleanup.
LEP: longhorn/longhorn#10675
> feat: orphaned runtime instance cleanup

- controller/snapshot_controller.go
- controller/utils.go
Issue longhorn/longhorn#10808
https://github.com/longhorn/longhorn/issues/10808#issuecomment-2837145679
`None`
`None`
> fix(snapshot): skip new snapshot handling if engine is purging

- controller/volume_controller.go
Issue longhorn/longhorn#10824
https://github.com/longhorn/longhorn/issues/10824#issuecomment-2849960020
`None`
`None`
> fix(dr-volume): backup volume not found during up-to-date check

- controller/snapshot_controller.go
- controller/utils.go
Issue longhorn/longhorn#10808
https://github.com/longhorn/longhorn/issues/10808#issuecomment-2852725033
`None`
`None`
> fix(snapshot): skip new snapshot handling if it is found in engine

- controller/backup_backing_image_controller.go
- controller/node_controller.go
- go.mod
> fix(controller): remove unnecessary lasso dependency

- controller/volume_rebuilding_controller.go
Issue # longhorn/longhorn#10889
Reduce the false warning logs for offline rebuilding when deleting a volume.
> fix(rebuild): change the code flow for offline rebuilding

- types/setting.go
> fix(setting): orphan-resource-auto-deletion-grace-period should be in Orphan category

- .github/workflows/create-crd-update-pr-in-longhorn-repo.yml
> fix(workflow): update author and committer

- controller/setting_controller.go
- k8s/crds.yaml
- k8s/pkg/apis/longhorn/v1beta2/setting.go
- k8s/pkg/client/applyconfiguration/longhorn/v1beta2/settingstatus.go
> feat(setting): add the 'LastAppliedAt' field in Setting status

- .github/workflows/create-crd-update-pr-in-longhorn-repo.yml
> fix(workflow): fix invalid curl path

- app/recurringjob/job.go
- app/recurringjob/type.go
- app/recurringjob/volume.go
Issue longhorn/longhorn#11016
- https://github.com/longhorn/longhorn/issues/11016#issuecomment-2938499276
- https://github.com/longhorn/longhorn/issues/11016#issuecomment-2942250481
`None`
`None`
> fix(recurring-job): race condition

- webhook/resources/backuptarget/validator.go
Issue longhorn/longhorn#8537
aggregate errors when verifying credential secret
> fix: backup target secret validation error improvement

- api/engineimage.go
- manager/backingimage.go
- manager/backupbackingimage.go
- manager/engineimage.go
- manager/node.go
- manager/volume.go
- webhook/resources/backingimage/validator.go
- webhook/resources/backupbackingimage/mutator.go
- webhook/resources/engineimage/validator.go
- webhook/resources/node/validator.go
- webhook/resources/replica/validator.go
- webhook/server/validation.go
> feat: move validation and mutation logics to the admission webhook

- webhook/resources/volumeattachment/validator.go
Issue longhorn/longhorn#11150
Record the attachment ticket content to track the attacher.
> feat(webhook): record the content while rejecting migration attachment tickets

- api/forwarder.go
- controller/backing_image_data_source_controller.go
- controller/backing_image_manager_controller.go
- controller/instance_manager_controller.go
- datastore/longhorn.go
- engineapi/backing_image_data_source.go
- engineapi/backing_image_manager.go
- engineapi/instance_manager.go
- engineapi/share_manager.go
- engineapi/types.go
Issue longhorn/longhorn#2259
Support for IPv6.
`None`
`None`
> feat(ipv6): address family support

- controller/snapshot_controller.go
Issue # longhorn/longhorn#10874
> fix(snapshot): set OwnerID and get notification when volume is updated

- controller/system_backup_controller.go
- controller/system_backup_controller_test.go
Issue longhorn/longhorn#11232
https://github.com/longhorn/longhorn/issues/11232#issuecomment-3043315952
`None`
`None`
> fix(system-backup): failed when volume backup policy is if-not-present

- types/setting.go
Issue # longhorn/longhorn#11204
Enable offline replica rebuilding by default.
> fix(replica): enable offline replica rebuilding by default

- .github/workflows/create-crd-update-pr-in-longhorn-repo.yml
> chore(workflow): use longhorn bot to submit PR

- types/setting.go
Issue # longhorn/longhorn#11204, longhorn/longhorn#11270, longhorn/longhorn#11273
We will enable the setting after all tasks are done.
> revert: disable the `offline-replica-rebuilding` setting

- controller/backing_image_manager_controller.go
- controller/instance_manager_controller.go
- controller/share_manager_controller.go
- controller/utils.go
Issue https://github.com/longhorn/longhorn/issues/10263
> feat: implement exponential backoff retry for re-creating pods on failure

- controller/backing_image_manager_controller.go
- controller/instance_manager_controller.go
- controller/share_manager_controller.go
- controller/utils.go
Issue https://github.com/longhorn/longhorn/issues/10263
> feat: modify newBackoff func to accept context.Context

- webhook/resources/backup/mutator.go
- webhook/resources/backup/validator.go
Issue longhorn/longhorn#11216
1. validate snapshotName
2. auto fill backup-volume if missing
3. check volume consistency
4. check backup target consistency
> fix: check invalid input for backup YAML file

- controller/instance_manager_controller.go
- controller/monitor/environment_check_monitor.go
- datastore/longhorn.go
- types/setting.go
> feat: add data-engine prefix to cpu-mask and hugepage-limit settings

- controller/backup_target_controller.go
- go.mod
- go.sum
- vendor/github.com/longhorn/go-common-libs/multierr/multierr.go
- vendor/modules.txt
> feat: getBackupTarget() should iterate all available data engines

- types/types.go
- webhook/resources/volume/validator.go
> feat: reject volume.spec.replicaRebuildingBandwidthLimit update for v1 data engine

- controller/node_controller.go
> fix: avoid flooding and misleading log message "Deleting orphans on ..."

- Dockerfile.dapper
- controller/instance_manager_controller.go
- types/setting.go
- types/types.go
> feat: persist instance manager and spdk_tgt log messages

- controller/setting_controller.go
Issue Longhorn/longhorn#5948
Fix the missing collecting settings.
> fix: collect settings ReplicaRebuildingBandwidthLimit and DefaultBackupBlockSize

- datastore/longhorn.go
- k8s/pkg/apis/longhorn/v1beta2/node.go
> fix: validate hugepage while enabling v2 data engine

- webhook/resources/volume/validator.go
> feat: update volume validation logics for v2 data engine

- upgrade/v19xto1100/upgrade.go
> fix(env-check): remove outdated unsupported os conditions

- controller/instance_manager_controller.go
longhorn-11605
Issue longhorn/longhorn#11605
When an instance is not scheduled to any node, e.g. an engine of a detached volume, the `instance.spec.NodeID == ""` but `instance.status.OwnerID != ""`. Orphan controller should not consider the instance is in ownership transaction.
> fix(orphan): detect running unscheduled instances

- controller/instance_manager_controller.go
- controller/monitor/environment_check_monitor.go
- datastore/longhorn.go
- types/setting.go
> feat: support v2 data engine without hugepage

- webhook/resources/volume/mutator.go
> feat: remove mutations for v2 volume scheduling settings

- controller/volume_rebuilding_controller.go
- scheduler/replica_scheduler.go
> fix(scheduler): exclude nodes where the data engine is disabled

- controller/monitor/snapshot_monitor.go
> fix(monitor): fix potential race condition

- controller/replica_controller.go
> fix(backingimage): schedule the volume replica after the 1st v2 backing image copy get ready

- api/model.go
- types/volumes.go
- webhook/resources/volume/validator.go
> fix: prevent volume expansion when it is not ready

- api/model.go
- types/volumes.go
- webhook/resources/volume/validator.go
longhorn/longhorn#11484
Last PR to fix DR volume. Ref https://github.com/longhorn/longhorn/issues/11774#issuecomment-3301721225
> fix: allow DR volume to expand

- types/setting.go
> feat(setting): skip customized settings with invalid values

- controller/volume_controller.go
> fix: fix stuck engine upgrade caused by additional replicas
