api/model.go
api/volume.go
controller/controller_test.go
controller/provisioner.go
controller/replica_controller.go
manager/volume.go
types/resource.go
util/util.go
util/util_test.go

The interpretation of different units can be vary. So keep it consistent by
passing bytes in int64 which won't be up to interpretation.
Also start to use Kubernetes' `Ki`(1024) vs `k`(1000) as standard units.

controller: Change Volume.Spec.Size from string to int64

---

deploy/02-components/01-manager.yaml

Previous engine image 9fd4ddd is broken.
Update engine to: rancher/longhorn-engine:0f24789
Based on: 0f24789f066a2979cda9a9a5ba277860790d2a1f

Update Longhorn engine image

---

api/model.go
api/setting.go
app/volume.go
controller/replica_controller.go
controller/volume_controller.go
datastore/longhorn.go
deploy/01-prerequisite/02-serviceaccount.yaml
engineapi/backups.go
engineapi/enginesim.go
engineapi/snapshot.go
engineapi/types.go
manager/engine.go
types/resource.go
types/types.go
util/util.go

To support S3 backup for longhorn-manager, some components need aws credential.
- User need to create credential secret manually, and set secret name to `Setting.secretConfig`
- If backupTarget for s3, longhorn-manager need to get credential and passing them as an environment variable to engine.

Enable S3 backup

---

driver/longhorn

issue: https://github.com/rancher/longhorn/issues/71
1. Catch result of `mkfs` execute
2. Embed the result in json of driver return 
rke deploy, use `docker logs kubelet 2>&1` to show the log, other use `journal -u kubelet`.
```
I0608 08:44:51.149196    6873 kubelet.go:1872] SyncLoop (DELETE, "api"): "voll-1-r-84920ccf_longhorn-system(13ef89a8-6af8-11e8-9c36-0644e7ac27f2)"
I0608 08:44:51.152964    6873 kubelet.go:1866] SyncLoop (REMOVE, "api"): "voll-1-r-84920ccf_longhorn-system(13ef89a8-6af8-11e8-9c36-0644e7ac27f2)"
I0608 08:44:51.153067    6873 kubelet.go:2060] Failed to delete pod "voll-1-r-84920ccf_longhorn-system(13ef89a8-6af8-11e8-9c36-0644e7ac27f2)", err: pod not found
E0608 08:44:56.913922    6873 driver-call.go:258] mount command failed, status: Failure, reason: Failed to create …
```

driver: Output the result of mkfs to the log

---

deploy/02-components/01-manager.yaml
deploy/02-components/03-ui.yaml
deploy/02-components/04-driver.yaml

Engine to rancher/longhorn-engine:31c42f0
Manager to rancher/longhorn-manager:58cbdda
UI to rancher/longhorn-ui:23e53f0
Also update the default Flexvolume location to the one used by RKE. See the
inline comments for the other options.

Update image, and default Flexvolume location

---

app/driver.go
controller/controller_manager.go
csi/deployment.go
csi/deployment_util.go
main.go
types/types.go

1. If it’s v1.8 or v1.9, Flexvolume Plugin would be deployed.
No configuration needed for 1.8 (because we can detect the location using an alpha API).
User will need to set the FLEXVOLUME_DIR manually in the yaml file for 1.9.
2. If it’s v1.10+, CSI would be deployed. No configuration needed.
3. The choice can be overridden in the command line.
4. If CSI driver has been chosen, the built-in Longhorn provisioner must be disabled.
5. If user choose to override the default choice, he will need to
provide additional command line parameter to longhorn manager in
addition to the longhorn driver deployer.

Automatically figure out which driver to use

---

controller/engine_controller.go

If we cannot get version with current API, we shouldn't do live upgrade with the
image.

controller: engine: live upgrade: Remove unsafe upgrade path

---

api/forwarder.go
api/model.go
api/node.go
api/router.go
app/daemon.go
controller/controller_manager.go
controller/controller_test.go
controller/node_controller.go
controller/node_controller_test.go
controller/volume_controller_test.go
datastore/longhorn.go
k8s/pkg/apis/longhorn/v1alpha1/zz_generated.deepcopy.go
scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go
types/deepcopy.go
types/resource.go
types/types.go
util/util.go

Phase 2(https://github.com/rancher/longhorn/issues/47):
integration test for Phase 2(https://github.com/rancher/longhorn-tests/pull/74)

Multiple disk with capacity based scheduling

---

deploy/02-components/04-driver.yaml

This can improve the driver's deployment success rate.
Not urgent.

Add init container to wait for the manager api

---

example/example_storageclass.yaml

Apparently missed this typo when I was writing the examples.
The `reclaimPolicy` was set as lowercase delete, causing issues since Kubernetes didn't recognize that as an acceptable policy.

Fix StorageClass example

---

controller/controller_manager.go
controller/node_controller.go
controller/node_controller_test.go
datastore/longhorn.go
scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go
types/resource.go
types/setting.go
types/types.go

Phase 3(https://github.com/rancher/longhorn/issues/47):
integration test for Phase3(https://github.com/rancher/longhorn-tests/pull/81)

Multiple disk with capacity based scheduling(Phase3)

---

controller/provisioner.go
types/types.go

If the storageclass definition doesn't contain default value for `numberOfReplicas` and `staleReplicaTimeout`, we will have error in provisioner. So we need to add default value for these two parameters.
Fix issue(https://github.com/rancher/longhorn/issues/123)

provisioner:Add default values for volume

---

controller/node_controller.go
controller/node_controller_test.go

Fixed issue: https://github.com/rancher/longhorn/issues/138

controller: clean disk status when disk removed from the node spec

---

api/model.go
client/generated_client.go
client/generated_disk_condition.go
client/generated_disk_info.go
client/generated_node.go
client/generated_node_condition.go
controller/node_controller.go
controller/node_controller_test.go
controller/volume_controller_test.go
csi/deployment_util.go
datastore/longhorn.go
manager/volume.go
scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go
types/deepcopy.go
types/resource.go
types/types.go

- Change node.Status.State to node.Status.Condition
- Change node.Status.MountPropagaion to node.Status.Condition
- Change diskStatus.State to diskStatus.Condition
- Update node api and generate longhorn client.
- driver deployer will wait for node MountPropagation condition before deploy flexvolume or csi.
Fixed issue: https://github.com/rancher/longhorn/issues/168 and https://github.com/rancher/longhorn/issues/149 and https://github.com/rancher/longhorn/issues/164

Change some of node status parameters to node.Status.Condition

---

controller/node_controller.go
controller/node_controller_test.go
controller/volume_controller.go
controller/volume_controller_test.go

It caused too many conflicts for now. We will dig more later. Temporarily stop
updating the ProbeTime

controller: Temporarily stop updating the ProbeTime for the conditions

---

controller/node_controller.go
controller/volume_controller_test.go

Pod `Phase` field remain `Running` even when it has crashed, So it's better to use pod condition to check manager status.

controller: Using pod conditions to check manager node status

---

controller/node_controller.go
controller/node_controller_test.go
scheduler/replica_scheduler.go
types/resource.go

Add `ready` state condition for disk status, when disk is not ready, e.g. umount the disk, `Schdulable` condition should be `Unschedulable` too.
Fixed issue: https://github.com/rancher/longhorn/issues/189

controller: Add Ready State for disk Status

---

api/node.go
api/router.go
controller/controller_manager.go
controller/node_controller.go
controller/node_controller_test.go
controller/volume_controller_test.go
datastore/kubernetes.go
datastore/longhorn.go
manager/node.go
types/resource.go

We need to support user remove physical node from cluster. Generally when user delete physical node: 
- Change node status to `Down`
- Export Node delete API for UI, user could delete the node without longhorn-manager running on it.
- If volume has attached to the node which has been deleted, Detach it(replica on the removed node is remained for now and user need to delete this replica manually before attach to other node).
- If EngineImage is controlled by the node which has been deleted, change it to another node.

Deal with physical node remove

---

deploy/02-components/01-manager.yaml

There is no function change from v0.3.0 to v0.3.1-rc1. Don't want to trigger
unnecessary upgrade process for the engine.

deploy: Keep the engine at v0.3.0

---

app/uninstall.go
controller/engine_image_controller.go
controller/uninstall_controller.go
datastore/kubernetes.go
datastore/longhorn.go
main.go

https://github.com/rancher/longhorn/issues/316
Longhorn makes use of CustomResourceDefinitions to store system state. Some of
these resources have finalizers attached to them, allowing for Longhorn manager
to intervene upon deletion request. If Longhorn manager is deleted before all
finalizers are released, manual intervention will be required to complete the
uninstallation. This procedure aims to gracefully cleanup all resources with
finalizers, which will be triggered by a Helm pre-delete hook.

Implement graceful uninstallation procedure

---

controller/setting_controller.go

It's non-critical error, and may caused by other managers update the entry at
the same time.

controller: setting: don't retry if failed to update latest version

---

controller/replica_controller.go
controller/volume_controller.go
util/util.go

Before this commit, we need following configuration in the secret to use AWS S3:
```
AWS_ENDPOINTS: <base64 encoded AWS endpoint> #s3.<region>.amazonaws.com
```
Noticed that we've made a typo here, it should be `AWS_ENDPOINT` instead of
`AWS_ENDPOINTS`. Though change it will break backward compatiability. We will do
it later.

controller: no longer require S3 endpoint if we're using AWS S3

---

controller/volume_controller_test.go
datastore/longhorn.go

The node down reason for manager pod down/missing can due to the restart of
manager, which shouldn't affect the running volumes at all.
Fixes https://github.com/rancher/longhorn/issues/390

controller: Fix regression caused by mark the replicas on down nodes as failed when attaching

---

deploy/install/02-components/03-ui.yaml

This reverts commit b04a3b27ba921569b0f95e7c4668690f8b27daf7.
User can manually adjust the UI replica numbers.
Nginx doesn't make it better if one UI lost.

Revert "deploy: Scale UI to 3 replicas for HA"

---

controller/controller_test.go
controller/volume_controller.go
controller/volume_controller_test.go
datastore/datastore.go
datastore/longhorn.go

Kubernetes listers have built-in cache mechanism, so it's much faster than query the API server directly. But they cannot guarantee the order of the sequence since we create/update the object in the API, and it will take some time for the lister's cache to reflect that change.
For example:
1. Create an object X
2. Get the object X using lister
The second step can still return NotFound since the lister's cache may not be updated yet.
This won't happen most of the time, but still caused many troubles for Longhorn who relies on the lister. This happened more frequently on K3S since K3S is using SQLite instead of ETCD in the backend for the API server, so the event trigger for updating the lister's cache may not be as fast as ETCD's watch mechanism.
We've tried to switch to use API directly …

Check for update after getting result from lister

---

api/misc.go
api/model.go
api/router.go
manager/misc.go
manager/volume.go

Earlier the support bundle download was a single GET request and it was a blocking call where the request was forwarded to the manager and when the download completes it returns the compressed zip file back to the caller. This was causing timeout if the content is huge.
The detailed design of this feature is described here: 
Support bundle could be obtained using 3 HTTP requests:
1. POST request to Initiate Support Bundle feature
2. GET request to Query the state of the previous request
3. POST request to Download the Support Bundle file
Commit ID: 918b224d68cb62dc94c81dba48c595533e2d2cc0
After Review: ab5404a26bf8748a9b599db2b53c33998120329a

New Support Bundle Design

---

api/misc.go
api/model.go
manager/misc.go

This commit entails the Support Bundle request to contain the GitHub issue URL and the issue description which is read by the Initiate API and eventually written into metadata.yaml
As a result when the user sends the compressed zip file, all the information he entered in UI will be part of metadata.yaml.

Enforcing Support Bundle Description

---

api/misc.go
manager/misc.go
manager/volume.go

Make it easier for UI to repeat the request if needed.
The downside is if multiple users request the bundle at the same time,
some of the requests will be denied and the user would need to retry.

manager: Initiate support bundle now clean existing request automatically

---

controller/engine_image_controller.go

The engine spec owner ID is not updated when the node that is referred by the current ownerID goes down. Controllers running in other nodes wouldn't pick up as the ownerID value is not empty.
Hence the following code changes explicitly check if the node is down and then set owner ID to the current controller ID.

Update EngineSpec OwnerID when the existing OwnerID goes down

---

controller/kubernetes_controller_test.go
controller/node_controller.go
controller/volume_controller_test.go
datastore/longhorn.go
manager/node.go
types/resource.go

When the role of the node changes from worker to non-worker, the manager pod will be stopped and as a result node removal was resulting in failure. The following code changes support removing node in such situations.
IssueURL: https://github.com/rancher/longhorn/issues/453

Allow node removal upon role change from worker to master

---

manager/misc.go

When the progress complete was 100%, even then the file was not available for download as it was set in a wrong place. The following code fixes that.

Progress complete was set at wrong place

---

manager/misc.go

When the object expires, the support bundle file was getting deleted but not the directory. The following code changes delete the directory as well

Support bundle not deleting the directory

---

.drone.yml

- Publish Longhorn manager image to dockerhub when push event happens to master branch
- image will be published with tag (master)

Configure drone to publish to dockerhub

---

.drone.yml

Reverts rancher/longhorn-manager#302
It broke the drone build.

Revert "Configure drone to publish to dockerhub"

---

controller/volume_controller_test.go
datastore/longhorn.go
types/setting.go
types/types.go

This PR adds a new command line flag for the `longhorn-manager` `daemon` called `--default-data-path`, allowing the user to specify which path by default should be used to store the data and replicas created by `longhorn-manager`. This is an optional command line flag, and if not set, will default to the usual path of `/var/lib/rancher/longhorn/` automatically.
Because this would also affect nodes on initial setup of `longhorn-manager`, this setting can only be set via the command line. Additionally, the deployment scripts have been updated with comments indicating what fields in the `spec` a user has to change in order to change the default data path for their `Longhorn` installation.

Add "Default Data Path" setting

---

scheduler/replica_scheduler.go
types/setting.go

This PR adds a setting as per #586 called "Replica Hard Anti-Affinity". This is a simple `boolean` value, which, when enabled, skips the logic for attempting to schedule on a `Node` that already has `Healthy` replicas, returning an empty `slice` of `diskCandidates` instead of trying to schedule this replica anyways.

Add "Replica Hard Anti-Affinity" Setting

---

api/misc.go
api/model.go
api/node.go
api/router.go
api/volume.go
client/generated_disk_info.go
client/generated_disk_update.go
client/generated_node.go
client/generated_volume.go
controller/provisioner.go
controller/volume_controller.go
csi/util.go
driver/longhorn
manager/kubernetes.go
manager/node.go
manager/volume.go
scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go
types/resource.go
types/types.go
util/util.go

This PR adds a "storage pool" feature as requested in longhorn/longhorn#311 that allows users to divide up their `Nodes` and `Disks` and specify on their `Volumes` which `Nodes` and `Disks` a `Volume` should be scheduled to. There are multiple changes involved here:
1. `Disks` and `Nodes` have been modified to have a `Tags` attribute that allows a user to label them with as many `Tags` as they wish. `Tags` are stored as a `string slice`, can be modified by `PUT`-ing a `string array` in the `longhorn-manager` API, and must conform to the rules that validate `Kubernetes labels`. `Tags` that are applied to a `Node` are inherited by all `Disks` on that `Node`, but any `Tags` applied to a `Disk` apply to that one only.
2. `Volumes` now have a corresponding `TagSelector` attribute which is also …

Implement "storage pools" feature

---

api/model.go
controller/engine_controller.go
engineapi/enginesim.go
engineapi/snapshot.go
engineapi/types.go
types/resource.go

This PR has two parts:
1. Fetching the list of backups when controller is monitoring the engine.
2. Providing a REST api for Manager so that UI can request the backup status maintained by any engine any time.
Issue: https://github.com/longhorn/longhorn/issues/45

Backup Progress List in Longhorn Manager

---

controller/volume_controller.go
datastore/longhorn.go

This PR mades some changes to how the `NodeID` fields is handled on unscheduled `Replicas`.
The first change fixes a bug in how the `IsNodeDownOrDeleted` function works so that if an empty `string` is provided, it returns an `error`. Previously, it would return `true`, which would imply a `Node` was down or deleted even though none was specified, which was problematic for certain checks.
The second change adds a check in `ReconcileVolumeState` to skip over `Replica` handling on a live `Volume` if that `Replica` is unscheduled. This prevents a `Replica` from having a `Pod` launched since it's unscheduled, and will also prevent the `Replica` from needlessly being marked as failed and constantly having to be recreated. As a side effect, this change reduces the rate at which an attempt at …

Fix Node checks during Volume reconciliation

---

scheduler/replica_scheduler.go
types/setting.go

This PR changes the `Anti-Affinity Setting` to be `Soft Anti-Affinity` instead. The language of the setting has been modified to avoid using negative keywords, and the default for this `Setting` has been flipped to true, as suggested in longhorn/longhorn#607.
The tests relating to this `Setting` have been modified in longhorn/longhorn-tests#163.

Flip Anti-Affinity setting

---

datastore/longhorn.go
types/setting.go

This PR makes some additional changes to the implementation of the `Default Data Path Setting` that were discussed in longhorn/longhorn#582:
- The default value of the `Setting` is now `/var/lib/longhorn`.
- There is a new `boolean Setting` titled `create-default-disk` that allows users to specify whether or not they'd like to have the default `Disk` automatically created.
- The description of the `Default Data Path Setting` has been fixed to use the verb `storing` instead of `mounting`.
- On `Node` creation, the `longhorn-manager` will attempt to enter the host `namespace` to create the directory specified by `Default Data Path`. This will create the directory if it doesn't already exist, and do nothing if it does already exist. Of course, if this fails, the `longhorn-manager` will still …

Additional "Default Data Path" changes

---

k8s/pkg/apis/longhorn/v1alpha1/zz_generated.deepcopy.go
types/deepcopy.go

This PR fixes an error in the `Kubernetes` generated `API` for the new `InstanceManager CRD`. The `API` is now properly regenerated to account for the new `Instances map` that exists on the `InstanceManagerStatus`, and implements the required `DeepCopyInto` function needed for the `DeepCopy` to work properly.

Fix Instance Manager deepcopy

---

deploy/uninstall/uninstall.yaml

This PR sets the `Namespace` for the `ServiceAccount` and `Job` used for uninstalling `Longhorn` to `default` to match the `Namespace` that is defined in the `ServiceAccount` subject of the `ClusterRoleBinding`. This prevents the possibility of the client creating the uninstall `Resources` but placing them in the incorrect `Namespace` inadvertently, possibly allowing for the uninstall `Job` to fail.

Set uninstaller ServiceAccount and Job namespace

---

controller/instance_manager_controller.go
types/setting.go

This PR allows for us to guarantee CPU resources for the new `Engine Manager Pods` and `Replica Manager Pods` that we are creating as part of the `InstanceManager` refactor. On creation of an `Instance Manager Pod`, the `InstanceManagerController` will check to see if a `Resource Requirement` has been set, and if set, will apply this requirement to the `Pod` specification as it is created. This means that all `Engine` and `Replica` processes running on the `Pod` will share this requirement.
Note that since `QoS` cannot be modified after `Pod` creation, the user will have to manually delete an `Instance Manager Pod` during maintenance time in order for a new `Pod` to be created after a new `QoS` value has been set.

Apply QoS to Instance Manager Pods

---

controller/node_controller.go
datastore/longhorn.go
types/setting.go
types/types.go

This PR implements the ability to specify which `Nodes` should be used for storage by default as described in longhorn/longhorn#583. To implement this, the recently introduced `Setting: create-default-disk` has been changed to `create-default-disk-labeled-nodes`, which, when enabled, will only create the default `Disk` on `Nodes` with `Label: longhorn=storage-node` on it. Other `Nodes` will not have this `Disk` created if the `Setting` is enabled, and will thus be disabled for scheduling as a result.
The default value for this switch is `false`, meaning that by default, the default `Disks` will still be created on all `Nodes`. Regardless of whether or not this `Setting` has been enabled, the path of the default `Disk` can still be set in the `Setting: default-data-path`.

Add Node labeling support

---

types/deepcopy.go

This PR updates the `DeepCopyInto` methods defined for the `VolumeSpec` and `NodeSpec` so that they properly `deepcopy` the `slices` used to store information about `Tags`. These fields were never updated, meaning that on `DeepCopy`, the `VolumeSpec`, `DiskSpec`, and `NodeSpec` would retain the same reference to the old `Tag slice` instead of gaining a new `slice`, which could've caused potential problems.

Deepcopy Tags for Volume, Node, and Disk

---

types/setting.go

This PR modifies the description for `Setting: Create Default Disk on Labeled Nodes` such that it now refers to the `Label` that we're looking for to determine initial `Disk` creation, which is `node.longhorn.io/create-default-disk=true`. This value was previously still referring to the old value from when the feature was still being developed, which was `node.longhorn.io/role=storage`.

Fix Label description for Create Default Disk on Labeled Nodes

---

controller/engine_controller.go
engineapi/engine.go
engineapi/enginesim.go
engineapi/types.go
types/resource.go

Earlier engine controller was executing controller info command to fetch
the isRestoring and lastRestored values from engine. Now that it's moved
to sync-agent-server, it's querying backup restore-status to fetch the
same.
Essentially, The following code changes implements the following: 
1. Add an interface for engine client to execute backup restore-status
2. Use the above interface to determine if incremental restore is required or not.

Manager fetching restore status attributes

---

api/snapshot.go
app/volume.go
controller/volume_controller.go
manager/volume.go
types/deepcopy.go
types/resource.go
types/types.go
util/util.go

https://github.com/longhorn/longhorn/issues/563
This PR extends the `longhorn-manager API` to allow users to be able to label `Backups` of `Snapshots`.
Calls to the `snapshotBackup` action on a `Volume` will now properly parse the `Labels` field of a `SnapshotInput` in order to validate them, making sure that every `Label` key conforms to a `Kubernetes Qualified Name` and that every `Label` value is non-empty. Additionally, the validation will ensure that none of the provided `Label` keys are reserved keywords (currently `KubernetesStatus`, `RecurringJobLabel`, and `ranchervm-base-image`). These will be passed to the `Engine API`, which will then make the appropriate calls with the `map` of `Labels` on the `longhorn-engine` to create the `Backup` with those `Labels`.
Additionally, the …

Allow for Backup labeling

---

manager/volume.go

This PR modifies the restoration logic on the `longhorn-manager` such that it sets the `KubernetesStatus` fields `PVName` and `PVStatus` to `empty string`, preventing `longhorn-manager` from having a `Volume` that is stuck with a reference to a nonexistent `PersistentVolume` as described in longhorn/longhorn#638.
The other mitigation described in that issue has been dropped due to the possible fixes requiring either conflicting with the existing logic in the `KubernetesController` or requiring that the `VolumeController` also modify the `KubernetesStatus` and potentially cause conflicts.

Don't restore Persistent Volume status from Backup

---

api/model.go
manager/engine.go
types/resource.go

The following code changes modify the name `backupError` to `error`

Renaming BackupError to Error in Manager

---

api/model.go
client/generated_backup_status.go
client/generated_client.go
client/generated_kubernetes_status.go
client/generated_workload_status.go

Right now Kubernetes cannot attach Longhorn volume via csi handler. Because the generated Longhorn go client code is incorrect, the volume object cannot be parsed into go struct hence `ControllerPublishVolume()` always errors out.

Update go client

---

api/model.go
controller/engine_controller.go
types/resource.go

The following code changes adds Progress, RestoreError and the filename that's being restored into the RestoreStatus structure. This information is fetched every 5 seconds from engine.
Further, the code changes also includes exporting the restore status into the volume API so that when UI requests for the volume details, restore status is included in it for every replica.
Issue: https://github.com/longhorn/longhorn/issues/49

Restore Progress in Longhorn Manager

---

controller/engine_controller.go
controller/instance_handler.go
controller/replica_controller.go

This PR makes various changes to the implementations of the `InstanceHandler` (the `EngineController` and `ReplicaController`) to fix several bugs that currently exist in their logic:
- A call to `getProcessManagerClient` in the `ReplicaController` now has the proper `error` check in order to avoid a `panic` from a `nil pointer dereference`.
- When handling deletion, the `EngineController` and `ReplicaController` will only attempt deletion of the associated `Instance` if `InstanceManagerName` is set to indicate that an associated `Instance` does exist. This avoids issues with being unable to delete `Volumes`, `Engines`, and `Replicas` due to the `InstanceHandler` not being able to find a nonexistent `Instance`.
- `enqueueInstanceManagerChange` has been modified to avoid filtering …

Fixes to Instance Handler implementation

---

api/model.go
types/resource.go

The following changes adds the state field to BackupStatus and RestoreStatus so that when UI queries for the volume, these fields are available with the right state values.

Adding backup and restore state

---

vendor.conf
vendor/github.com/longhorn/longhorn-instance-manager/api/types.go
vendor/github.com/longhorn/longhorn-instance-manager/client/engine_manager.go
vendor/github.com/longhorn/longhorn-instance-manager/client/process_manager.go

This PR updates the `longhorn-instance-manager` dependency in `vendor.conf` to the latest version (currently `3e573d294759af29c18daae037ba8a2bd0cb85fb`) instead of the branch `master`.

Update longhorn-instance-manager vendor

---

api/volume.go

This PR modifies the `longhorn-manager REST API` input to reject any `Volume` creation requests that have the `BaseImage` specified, effectively disabling the `Base Image` feature since it is currently unimplemented as part of the `Instance Manager` refactor. This implements the `longhorn-manager` portion of longhorn/longhorn#650.
Note that `Volume` listings still contain the `Base Image` field and that this field still appears in the `Kubernetes API` definition.

Disable BaseImage in longhorn-manager API for now

---

api/model.go
datastore/longhorn.go

As it's hard for UI to identify the replica based on it's IP, we are
translating the replica address to it's name instead

Translating Replica address to Replica Name

---

controller/instance_manager_controller.go

This PR fixes some random issues with the implementation of the `Watch` functionality used to monitor `Instances` in the `Instance Manager Controller`:
- Ensured that the `watcherLock` of the `InstanceManagerController` is always released after running through the logic to attempt to create a `ManagerWatch`. Previously, any errors creating the `Watch` had the potential to eventually lead to `deadlock`.
- Moved the `Watch` creation logic to be in the same place as the `polling` logic. Previously, this was only run during startup of the `InstanceManager Pod` and in some circumstances could be skipped and result in the `InstanceManagerController` falling back to the slow `resync` period for `Instance` updates.

Manager Watch fixes

---

datastore/longhorn.go
manager/node.go
util/util.go

This PR modifies the logic used to handle new `Disks` created on a `Node` to additionally create the `replicas/` subdirectory, which is needed to actually store the `Replicas`.
This subdirectory of a `Disk` was previously created by the `Instance Pod` of a `Replica`, since the `HostPath` would create this directory if it didn't exist. However, the new `Instance Manager` refactor did not handle creation of this directory automatically, and on all new installations of `Longhorn`, all new `Replicas` would fail with the error `No such file or directory`.

Create Replica directory for new Disks

---

engineapi/engine.go

Due to the port and IP check.
```
Error syncing Longhorn engine image longhorn-system/ei-605a0f3e: fail to
sync engine image for longhorn-system/ei-605a0f3e: cannot get engine
client to check engine version: Invalid empty IP or port from request
```

Fix failed to wait for engine image start

---

api/misc.go
api/model.go
api/router.go
controller/controller_manager.go
controller/controller_test.go
controller/instance_handler_test.go
controller/instance_manager_controller_test.go
controller/node_controller.go
controller/node_controller_test.go
manager/node.go
types/resource.go

This PR adds a new field to the `NodeStatus` titled `Readiness`, meant to indicate the state of the `Node` in relation to the `Engine Images` and `Instance Managers` to indicate whether or not the `Node` is ready for deploying `Volumes`.
As part of the reconciliation process, the `Node Controller` will obtain a listing of the `Engine Images`, and as it attempts to create and delete the appropriate `Instance Managers`, it will set the `Readiness` as either `Deploying` or `Ready`. For the `Node` to be `Ready`, the `Node Controller` will ensure that these conditions are met for the `Engine Images` and the related `Instance Managers`:
- If the `Engine Image` is `Incompatible` or `Deploying`, there must not be any `Instance Managers` that exist for that `Engine Image`.
- All `Engine Images` …

Indicate Node readiness based on Instance Manager status

---

engineapi/types.go

This reverts commit f06134ec2efa80cbc541f2a65999666c77add6bd.
Cannot pass engine integration test

Revert "Add a flag Deleting to backup object"

---

controller/instance_handler.go

1. Wrongly update instance state to `error` when its current state is `running` and `desire state is `stopped`.
2. Cannot print log for error instance

Fix bugs in instance handler

---

controller/node_controller.go
manager/node.go

The following code changes does two things:
1. Reverts the changes where the node controller was looking up the nodeRoleLabel to decide if a node is worker or non-worker. This is introduced by RKE and other clusters wouldn't have it.
2. When the manager pod goes missing in a node, make that node as unschedulable.
Issue: https://github.com/longhorn/longhorn/issues/453

Allowing node deletion when role changes from worker to non-worker

---

deploy/install/02-components/01-manager.yaml
deploy/install/02-components/03-ui.yaml
deploy/install/02-components/04-driver.yaml
deploy/uninstall/uninstall.yaml

`master` tag has been used for all up to date developing version
Longhorn components.
The tag will be updated during the official releases, includes release
candidate.
Issue: #664

Update default deployment in manager to use master version

---

controller/kubernetes_controller.go

If the volume name and the `volumeHandle` of the PV are same, then
longhorn was blindly attaching the volume with the PV. Now, it checks
the driver for the value `io.rancher.longhorn` before doing so.
Issue: https://github.com/longhorn/longhorn/issues/639

Checking CSI driver before binding with k8s PV

---

api/model.go
app/volume.go
controller/engine_controller.go
engineapi/enginesim.go
engineapi/snapshot.go
engineapi/types.go
manager/engine.go
types/deepcopy.go
types/resource.go

This PR makes changes to the `SnapshotPurge` logic to account for the `SnapshotPurge` operation being moved to the `SyncAgentServer` in `longhorn-engine` as part of longhorn/longhorn-engine#402:
- Various comments and logs have been modified to indicate the `asynchronous` nature of the `SnapshotPurge` operation.
- The `EngineStatus` now stores the `SnapshotPurgeStatus` of the `Volume` during the `refresh` operation.
- The `SnapshotPurge` call during the `RecurringJob` now waits for the `SnapshotPurge` operation to complete before finishing.
This PR implements the `longhorn-manager` portion of longhorn/longhorn#665.

Modify SnapshotPurge logic in longhorn-manager

---

app/driver.go
app/get_proc_arg.go
controller/controller_manager.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/instance_manager_controller_test.go
deploy/install/02-components/03-ui.yaml

https://github.com/longhorn/longhorn/issues/603
Now longhorn service account will be applied to all Longhorn components. Then as long as the Longhorn service account is using correct pod security policy, Longhorn will work fine in the cluster enabling pod security policy.

Set service account for all pods creation in Longhorn 

---

controller/engine_controller.go

To prevent the following corner case:
1. Engine monitor updates field `Endpoint` with empty string
2. Engine's frontend is started and the endpint is suddenly set
3. Engine's all replicas are state `running` with mode `RW`
4. Engine monitor updates field `ReplicaModeMap`
5. Volume controller checks `ReplicaModeMap` then updates the volume
to state`Healthy`
In this case, field `Endpoint` is out of date. Then the volume is `Healthy`
but with empty `Endpoint`.

Engine monitor will update endpoint after checking replica mode

---

api/model.go
datastore/longhorn.go

Otherwise, the manager's log will be flooded by the warning messages `"replica address[%v] received from engine restoreStatus for volume[%v] is not found"`.

Clean up engine purge status after detaching the volume

---

deploy/scripts/longhorn-engine-exec

https://github.com/longhorn/longhorn/issues/655
If the field `instanceManagerName` of the engine object is empty, this field will be `instanceManagerName: ""` rather than `instanceManagerName: `.

The script longhorn-engine-exec will handle the case that instance manager is empty or not found

---

api/model.go
controller/engine_controller.go

Otherwise intermediate errors can block the engine status update
Also, remove the unnecessary warning of `cannot find the replica with
address` since it's likely due to the replica has been removed.
https://github.com/longhorn/longhorn/issues/715

controller: engine: monitor shouldn't treat progress error as blocker

---

controller/instance_manager_controller.go

During toleration setting update, the instance manager pod will be
deleted temporarily. And the receive function of instance manager
monitor will error out. If there is no wait interval for retrying
the receive function, the longhorn manager's log will be flooded
by the following message:
```
[longhorn-manager-thcvm] time="2019-09-17T21:49:43Z" level=error msg="error receiving next item in engine watch: rpc error: code = Unavailable desc = transport is closing"
```

controller: Add poll interval if the instance manager monitor fails to receive the info

---

controller/engine_image_controller.go

The engine state should show so.

controller: engine image: Remove flooded debug message on incompatible engine

---

controller/instance_manager_controller.go

The wrong configuration results in skyrocketed CPU usage on instance
manager pods. The liveness and readiness probe set to 1 second interval,
which is too short. Being an `exec` type of probe doesn't help too.
Also remove readiness probe since instance maangers are not behind a
Kubernetes Service.
Set liveness probe interval to 5 seconds, with initial delay of 3
seconds.
https://github.com/longhorn/longhorn/issues/767

controller: instance manager: Fix high cpu utilization caused by health probe

---

controller/instance_handler.go

If the instance process somehow gets crashed and the instance
handler directly unset the field `instanceManagerName`, then
longhorn manager won't send request to the related instance manager
to  clean up the process since it doesn't know which the instance
manager should be used.
Later if we detached and re-attach the volume, the instance manager
will find the related process already exists with `error` state
hence it will do nothing for the re-attach. This volume cannot become
attached anymore.
https://github.com/longhorn/longhorn/issues/789

controller: Unset the instance manager name if we cannot find the related instance or instance manager

---

controller/instance_manager_controller.go

We need `tini` to handle reaping the children properly.
This approach can avoid breaking the images without `tini` packaged.
https://github.com/longhorn/longhorn/issues/795

controller: Use `Args` instead of `Command` to respect image's entrypoint

---

controller/events.go
controller/instance_handler.go
controller/instance_manager_controller.go
controller/volume_controller.go
types/resource.go

https://github.com/longhorn/longhorn/issues/851
This is one half of the solution. The other half is automatically remounting when reattach happened. Would derive from https://github.com/longhorn/longhorn-manager/pull/453

Automatically reattaching the volume if was detached unexpectedly

---

controller/volume_controller.go

controller: Fix a bug on reseting CurrentNodeID unintentially

---

controller/instance_manager_controller.go
controller/volume_controller.go
hack/cleancrds.sh
upgrade/v1alpha1/upgrade.go

Now upgrade following the YAML path in  https://github.com/longhorn/longhorn/blob/v0.7.0/docs/upgrade-from-v0.6.2-to-v0.7.0.md works. Previously due to the owner reference, the instance manager will be deleted when v0.6.2 CRD object removed.

Upgrade fixes

---

controller/node_controller.go

controller: node: Remove unnecessary `BUG` prefix

---

controller/instance_handler.go

If instance handler directly cleans up the field for the error process with spec.DesireStatus running, then there is no way to find the correct instance manager and clean up the
corresponding error process for the subsequent detachment.

Clean up status.InstanceManagerName for detaching error instance only

---

controller/controller_manager.go
controller/engine_controller.go
controller/instance_manager_controller.go
controller/kubernetes_controller.go
controller/replica_controller.go
controller/volume_controller.go

https://github.com/longhorn/longhorn/issues/1058
Also, change the polling interval of instance manager to 1 second from
500ms.

controller: Change rate limiter for engine/replica's workqueue

---

controller/engine_image_controller.go

The pods will use command `diff` to check if there is an existing
binary in the destination and if it's the same as the new one.
Besides, engine image pods won't copy the binary
`longhorn-instance-manager` now since it's no longer needed.
longhorn/longhorn#1116

controller: Engine image pods won't blindly overwriting the engine binary

---

types/setting.go

https://github.com/longhorn/longhorn/issues/1068
Overprovision factor to 200.
Minimal available disk to 25%.

settings: Change default setting for storage related options

---

controller/engine_controller.go
types/resource.go

For SnapshotList() error.
If a node went down, before we remove the replica from the engine,
snapshot list error might happen.
Notice it won't affect the actual size calcuation in the volume
controller since snapshot list will be cleaned up and actual size
calcuation will be skipped for empty snapshot list.

types: engine status: Add snapshotsError to stop the error become critical

---

app/get_proc_arg.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
csi/deployment.go
csi/deployment_util.go

longhorn/longhorn#1288
Always deploying Longhorn components with ImagePullSecrets spec, kubelet logs will report
`Unable retrieve pull secret longhorn-system/ for longhorn-system`

skip adding ImagePullSecrets if not specified

---

go.mod
go.sum
vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go
vendor/github.com/longhorn/go-iscsi-helper/util/util.go
vendor/modules.txt

This way the manager and engine versions are consistent.
longhorn/longhorn#1223

Update go-iscsi-helper to v0.0.0-20200424013728-e7c199ecb487

---

app/volume.go
controller/volume_controller.go
types/types.go

We no longer compare all the labels, instead we only check against our
retention marker label. This applies to backups as well as snapshots.
longhorn/longhorn#1267

Compare recurring job label for backup/snapshot retention calculation

---

controller/node_controller.go
controller/node_controller_test.go
controller/volume_controller_test.go
scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go
types/resource.go
types/setting.go

This change introduced "disable-scheduling-on-cordoned-node" setting and
node condition Schedulable.
If the setting is enabled, we will disable the node scheduling when
the Kubernetes Node is cordoned. And it will be reflected in the
Longhorn Node's Schedulable condition.
https://github.com/longhorn/longhorn/issues/1287

scheduler: Introduce node condition Schedulable

---

scheduler/replica_scheduler.go
types/setting.go

This commit is to add zone hard anti-affinity in scheduler with current node hard anti-affinity
zone hard anti-affinity means the scheduler should not schedule replica on the same zone
zone soft anti-affinity means the scheduler can schedule replica on the same zone
https://github.com/longhorn/longhorn/issues/1052

scheduler: Add replica zone hard anti-affinity support

---

controller/engine_controller.go
controller/volume_controller.go
types/setting.go

This PR allows the user to set a limit for how many replicas can be rebuilt at any given time across the cluster. The limit can be set to 0, to disable the replica rebuild across the cluster.
The limit will have no impact on the replicas that already in the process of rebuilding.
The limit was implemented by checking all the existing running engines when a replica is due for scheduling for the rebuild purpose. The data is read from the cache (implemented by Kubernetes informer), so there should be a minimal performance impact.
Moreover, we no longer schedule all the replicas first then start rebuilding. In the past, if there are two or more replicas missing from the volume, we will pre-schedule the space for all the replicas, then start rebuilding one by one. Now we only schedule one …

Add Setting Replica Rebuild Concurrent Limit

---

types/setting.go

This will help with the stability of the engine.
0.25 was chosen because as long as the user has one 1 vcpu, the upgrade
of the instance manager can be performed, since both engine and replica
instance manager of the old and new version needs 1/4 of one vcpu.
https://github.com/longhorn/longhorn/issues/1345

setting: Set GuaranteedEngineCPU to 0.25 by default

---

controller/volume_controller_test.go
scheduler/replica_scheduler_test.go
types/setting.go

This change enables replica node level hard anti-affinity by default.
Also adjust some test cases setting with enabling replica node level soft
anti-affinity.
https://github.com/longhorn/longhorn/issues/1282

types: Enable Replica Node Level Hard Anti-Affinity By Default

---

controller/controller_manager.go
controller/setting_controller.go
types/setting.go

Make sure user don't change GuaranteedEngineCPU when there are active
workload running.
Also, add catalog `Danger Zone` for settings that may have big impact on
running workload.
https://github.com/longhorn/longhorn/issues/1318

setting: recreate instance manager pod when GuaranteedEngineCPU changed

---

controller/volume_controller.go
types/setting.go

Now we count scheduled replicas for rebuilt instead of engine
replicaModeMap which might be delayed.
But it might still result in race condition that cause rebuilding more
than specified number of replica sometimes.
https://github.com/longhorn/longhorn/issues/307

controller: volume: Improve the replica rebuilt concurrent count

---

controller/kubernetes_pv_controller.go
controller/kubernetes_pv_controller_test.go
csi/controller_server.go
types/setting.go
types/types.go

When a pod resides on an offline node kubernetes will by default wait
forever to delete the pod resource from the api server. The kubernetes
volume attach/detach controller will not remove the volume attachment
till the pod is deleted. This leads to the replacement pod not being
able to start since it will forever wait for the volume attachment.
longhorn/longhorn#820

Cleanup volume attachment on terminating pods

---

datastore/uncached.go
manager/misc.go

If volumeattachment object is available in kubernetes, we add it to the
support bundle yamls/kubernetes directory.
https://github.com/longhorn/longhorn/issues/1369

Add volumeattachments to the support bundle

---

csi/node_server.go
csi/util.go
types/setting.go

This allows to support older host kernels, that don't support the optional metadata_csum feature.
longhorn/longhorn#1208

Add ability to use user provided fs params for ext4 fs creation

---

controller/controller_manager.go
controller/controller_test.go
controller/setting_controller.go

Nil pointer was treated differently from the empty value.
longhorn/longhorn#1384

controller: Fix unnecessarily restarting instance managers due to GuranteedEngineCPU

---

controller/engine_image_controller.go
controller/kubernetes_node_controller.go
controller/node_controller.go
controller/setting_controller.go

To improve the throughput of the controller.

controller: Use EnhancedDefaultControllerRateLimiter() on all controllers

---

controller/node_controller.go

This is for getting `Disable Scheduling On Cordoned Node` setting error,
we return error.

Fix missing return err

---

app/driver.go
controller/uninstall_controller.go
csi/deployment.go
csi/deployment_util.go
types/deploy.go

This commit revertes commit f88d71c1fae0a21057724e2290d07f0a3103c66b.
It's to remove compatible CSI deployment 'io.rancher.longhorn'.
https://github.com/longhorn/longhorn/issues/1365

csi driver: Remove compatible CSI deployment

---

controller/engine_image_controller.go

This PR modifies the `Daemon Set` spec used for deploying `Engine Images` in order to run them with as `Privileged`. This allows the `Pods` that run as part of this `Daemon Set` to be able to succeed even when running with `SELinux` (which normally blocks containers from being able to write to `/var/lib`).
longhorn/longhorn#1273

Run Engine Image Pods as Privileged

---

app/volume.go

This PR modifies the logic of the cleanup steps when running a `Job` for creating `Snapshots` or `Backups` such that any errors encountered during cleanup (purging `Snapshots` or deleting old `Backups`) will result in a warning being logged rather than an error on exit.
This allows the `Job` to treat the `Job` invocation as a success so that multiple `Backups` aren't created as the result of a failed cleanup. This means that the next invocation of the `Job` will try the cleanup and keep passing off cleanup until it eventually succeeds.
longhorn/longhorn#1424

Warn instead of error on job cleanup failure

---

controller/volume_controller.go
controller/volume_controller_test.go

longhorn/longhorn#1355
longhorn/longhorn#1366
The modifications of this commit:
1. Automatically unset volume.Status.CurrentNodeID for the
restoring/DR volumes on the down node.
It means the restore/DR volumes will be detached once the node is
down. Then Longhorn can reattach it and restart restoring later.
2. Set volume.Status.CurrentNodeID only if the volume is
detached/newly created.
This modification guarantees that the auto detachment mentioned
above won't be intervened by this auto attachment logic, and the
restore/DR volumes can be reattached after the node down and the
auto detachment complete.
3. Fix a bug in the unit test: When restore already starts and the
field `RestoreInitiated` is true, the volume current state should
not be Detached.

controller: Automatically recover the restoring/DR volumes on the down node

---

controller/volume_controller.go

controller: Reattach the DR volume if the node is down during the inc restore

---

types/types.go

Use checksum instead of full image name for the instance manager labels. Similar to how we make the engine image labels.
Issue: [1323](https://github.com/longhorn/longhorn/issues/1323)

types: Use checksum instead of full image name for the instance manager labels

---

types/types.go

This reverts commit cd425ffb82058f1241a0f8f0aaacdf5d1bd3d79f.
Since it broke updates.
longhorn/longhorn#1323

Revert "types: Use checksum instead of full image name for the instance manager labels"

---

api/backup.go
api/model.go
api/snapshot.go
app/volume.go
client/generated_backup_list_output.go
client/generated_backup_volume.go
client/generated_client.go
client/generated_instance_manager.go
client/generated_setting_definition.go
client/generated_snapshot.go
client/generated_snapshot_list_output.go
client/generated_volume.go
controller/volume_controller.go
types/types.go
util/util.go

This PR refactors the logic responsible for running `Recurring Jobs` as per longhorn/longhorn#1406 such that instead of using the `Engine API` directly in order to make `Snapshot` and `Backup` calls, the `Recurring Job` calls the `longhorn-manager` in order to make requests instead. 
This means that the actual `Backup` or `Snapshot` calls will go through the same code that a user-created `Backup` or `Snapshot` would go through, and the `Backup` and `Snapshot` operations will be visible from the `longhorn-manager` log.

Run Recurring Jobs via longhorn-manager API

---

controller/engine_image_controller.go
controller/instance_manager_controller.go
csi/deployment.go
csi/deployment_util.go
deploy/install/02-components/01-manager.yaml
deploy/install/02-components/03-ui.yaml
deploy/install/02-components/04-driver.yaml

We change the imagePullPolicy from Always to IfNotPresent so that users who do air-gap installation don't have to set up a registry to install Longhorn.
Also, provided a script for developers to quickly change it back to Always located inside `longhorn/dev/scripts` repo.
longhorn/longhorn#1491

controller, deploy: change imagePullPolicy to IfNotPresent for Engine Image daemonset, Manager daemonset, UI deployment, Driver Deployer deployment

---

controller/volume_controller.go

This PR adds logic to the `Volume Controller` that reads the `Kubernetes Status` as part of the `Volume` deletion process to check for `Kubernetes` resources to clean up. If the `Kubernetes Status` indicates the existence a `Persistent Volume` and possibly a `Persistent Volume Claim` associated with the `Volume`, those resources will be cleaned up as part of the deletion process as requested in longhorn/longhorn#520.

Clean up Kubernetes resources on Volume deletion

---

types/types.go
upgrade/upgrade.go
upgrade/v100to101/upgrade.go

Use checksum instead of full image name for the instance manager labels. Similar to how we make the engine image labels.
Also, when doing longhorn upgrade, update all the instance manager labels to use checksum of image names.
Issue longhorn/longhorn#1323

types, upgrade: Use checksum instead of full image name for the instance manager labels

---

controller/instance_manager_controller.go
controller/instance_manager_controller_test.go

Fix the 1st scenario in longhorn/longhorn#1545

controller: Clean up the instance manager when the node is disconnected

---

csi/deployment.go

This help to remove the extra dependency on different container image registry. Docker Hub now holds all Longhorn components' images.
**Note:** We need to push all Longhorn CSI images to Docker Hub first before this code can work.
longhorn/longhorn#1419

csi: change the default image registry to Docker Hub for CSI components

---

patch/vendor-add-duration-seconds-to-election-record.patch
patch/vendor-fix-nil-pointer-for-Leader-Election-Record.patch
vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go

This PR patches the `client-go` dependency in order to fix a bug in which the `LeaderDurationSeconds` is not properly set on the `LeaderElectionRecord` created in the `release()` function. This fixes the bug in longhorn/longhorn#1379 in which the `LeaderDurationSeconds` field is set to 0, leading to a failure to release the upgrade lock and delaying the upgrade process while the other Longhorn Managers wait for the lock to expire.
This PR contains an additional fix to the `LeaseSpecToLeaderElectionRecord()` function, which prevents a panic resulting from a nil pointer occurring when `LeaderDurationSeconds` is set, which is necessary for the above patch to work properly in the current version of the Kubernetes API we are using.
If the `vendor/` is overwritten, these patches can be applied …

Set LeaderDurationSeconds on LeaderElectionRecord

---

deploy/install/01-prerequisite/05-podsecuritypolicy.yaml

This PR adds an additional file to `deploy/` that creates the necessary resources for Longhorn to be deployed with Pod Security Policy. This file creates a Pod Security Policy with the necessary privileges for Longhorn to operate correctly, along with the necessary Role and Role Binding for Longhorn's Service Accounts to use this policy.
This PR is based off of the Pod Security Policy that is proposed in longhorn/longhorn#1634.

Add Pod Security Policy to deploy

---

controller/engine_image_controller.go
controller/engine_image_controller_test.go

1. The sync function should error out if the version check command
execution fails.
2. Check the binary executability in the daemonset readiness probe.
3. Make sure the engine image state can be updated/corrected later
even if it is wrongly marked as incompatible.
longhorn/longhorn#1663

Fix the issue that engine image may be wrongly marked as incompatible

---

manager/engine.go

Seems to make more sense to check for snapshot existence before revert.

Move snapshot check before snapshot revert

---

controller/volume_controller.go

Seems reasonable to consolidate the two for loops.

Consolidate for loops in switchActiveReplicas

---

controller/controller_manager.go
controller/kubernetes_pod_controller.go
deploy/install/01-prerequisite/04-default-setting.yaml
types/setting.go
types/types.go

Because k8s never force delete pods on a downed node, we provide an option for users to help them automatically force delete terminating pods of StatefulSet/Deployment on the downed node. By force deleting, k8s will detach Longhorn volume and spin up replacement pods on a new node.
We created a new controller, `Kubernetes-pod-controller`, to watch pods and nodes status and handle the force deletion.
Force delete a pod when all of the below conditions are met:
1. NodeDownPodDeletionPolicy is different than DoNothing
2. pod belongs to a StatefulSet/Deployment depend on NodeDownPodDeletionPolicy
3. node containing the pod is down
4. the pod is terminating and the DeletionTimestamp has passed.
5. pod has a PV with provisioner driver.longhorn.io
longhorn/longhorn#1105

controller, types: improve node failure handling by automatically force delete terminating pods of StatefulSet on downed node

---

types/types.go

Actually the longhorn manager doesn't support well IPv6 adresses. For
example, in an IPv6-only k8s cluster we can see the following logs:
>  level=info msg="Listening on 2001:db8:caca:8273:187:4:ffff:4f5a:9500
which is missing brackets. The pod fails its readiness probe and never
becomes available.
PS: please excuse me for any fuckups. It's actually my first time writing a line in Go.
Cheers

Make daemon support IPv6 adresses

---

app/uninstall.go
controller/base_controller.go
controller/controller_manager.go
controller/engine_controller.go
controller/engine_image_controller.go
controller/engine_image_controller_test.go
controller/instance_handler_test.go
controller/instance_manager_controller.go
controller/instance_manager_controller_test.go
controller/kubernetes_node_controller.go
controller/kubernetes_pod_controller.go
controller/kubernetes_pv_controller.go
controller/kubernetes_pv_controller_test.go
controller/node_controller.go
controller/node_controller_test.go
controller/replica_controller.go
controller/setting_controller.go
controller/uninstall_controller.go
controller/volume_controller.go
controller/volume_controller_test.go
controller/websocket_controller.go

This adds a base controller that takes care of setting up the initial instance based logger so that we always have the controller name and node fields.
longhorn/longhorn#1724
longhorn/longhorn#1736

Refactor to add support for instance based logging

---

api/node.go

Eviction is only allowed on scheduling disabled disk or node. Return
error message to user if trying to evict on a scheduled disk or node, or
enabled scheduling on an eviction requested disk or node.
https://github.com/longhorn/longhorn/issues/298

api: Fix return error message to UI

---

controller/volume_controller.go
scheduler/replica_scheduler.go
types/resource.go

Added a new field HardNodeAffinity in replica's spec to keep track of which node this replica must be scheduled to.
Refactor the replica scheduler so that it considers the HardNodeAffinity.
Modify the fail-to-scheduled replica cleanup logic so that it avoids the local replica.
longhorn/longhorn#1045

controller, scheduler: Refactor data locality code

---

csi/deployment.go

By default the csi snapshotter uses snapshot as a prefix, the prefix
cannot be removed only changed, so it's better to just stick with the
default prefix of `snapshot`
Longhorn #304

Use default snapshot csi prefix

---

datastore/longhorn.go
deploy/install/01-prerequisite/02-serviceaccount.yaml
monitoring/instance_manager_collector.go
monitoring/monitoring.go
monitoring/node_collector.go
monitoring/volume_collector.go

Added the following metrics:
1. longhorn_node_cpu_capacity_millicpu
2. longhorn_node_cpu_usage_millicpu
3. longhorn_node_memory_capacity_bytes
4. longhorn_node_memory_usage_bytes
We use the above metrics to detect when there is cpu/memory high pressure on worker nodes. This will help when debugging cases such as engines die unexpectedly due to cpu pressure. 
Also, change the metric name `longhorn_volume_usage_bytes` to `longhorn_volume_actual_size_bytes` to avoid the confusion between the size of the filesystem (usage_bytes) vs used space by Longhorn block device (actual size)
longhorn/longhorn#1180

Prometheus Support, Part 4

---

deploy/install/01-prerequisite/03-crd.yaml

This allows `kubectl` to display summary information about Longhorn CRs upon listing.
The good news is this does not impact upgrade. Kubernetes allows editing CRDs' spec on the flight.
We can discuss what fields should be exposed in this PR
longhorn/longhorn#1480

deploy: Add `additionalPrinterColumn` to CRDs

---

app/volume.go
controller/volume_controller.go
deploy/install/01-prerequisite/04-default-setting.yaml
types/setting.go

In the current Longhorn implementation, users cannot do recurring backup when volumes are detached. 
This PR gives the users an option to do recurring backup even when volumes are detached.
The design overview is documented at the PR https://github.com/longhorn/longhorn/pull/1851
longhorn/longhorn#1509

app, controller: allow recurring backup for detached volumes

---

app/get_proc_arg.go

The new script will detect both:
k3s versions before v1.19 (the cmdline is separated by `\000`)
and k3s versions after v1.19 (the cmdline is separated by `\040`)
longhorn/longhorn#1861

app: change GetK3SCmdlineScript to adapt to the command line separator r in k3s v1.19.2+k3s1

---

datastore/longhorn.go

The issue here is that in the case where we do creation verification,
we return a reference to the `readOnly` object from the lister directly.

Fix datastore object creation returning pointers to the cached objects

---

app/uninstall.go
controller/controller_manager.go
controller/engine_image_controller_test.go
controller/instance_handler_test.go
controller/instance_manager_controller_test.go
controller/kubernetes_pv_controller_test.go
controller/node_controller_test.go
controller/uninstall_controller.go
controller/volume_controller_test.go
datastore/datastore.go
scheduler/replica_scheduler_test.go

Sometimes the CSIDriver object or deployments are not cleaned up immediately after the deletion timestamps are set, there is no way to trigger the uninstaller. Then the uninstallation will get stuck.
The root cause of this case is different from the 1st case mentioned in https://github.com/longhorn/longhorn/issues/1820

Add missed informers for the uninstaller

---

types/setting.go

Modify the setting 'Allow Recurring Job While Volume Is Detached' note from ```Note that during the time the volume was attached automatically, the volume is not ready for workload.``` to ```Note that the volume is not ready for workload during the period when the volume was automatically attached.```
longhorn/longhorn #1881

Modify the description of the setting 'Allow Recurring Job While Volume Is Detached'

---

datastore/longhorn.go
upgrade/upgrade.go
upgrade/v102to110/upgrade.go

`kubectl drain` by default is blocked when there is orphan pod on draining the node.
By adding the field `controller: true` to the `ownerReferences` of instance manager pods, we allow the user to run `kubectl drain` without the --force flag
Now users can run something like:
```
kubectl drain phan-cluster-v25-worker-1 --delete-local-data=true --force=false --grace-period=-1 --ignore-daemonsets=true --timeout=120s
```
longhorn/longhorn#1286

allow `kubectl drain` without the --force flag

---

controller/volume_controller.go
types/setting.go

If disabled replica rebuild, the eviction and data locality feature
won't work, but restore disaster recovery volume feature and currently
rebuilding replica would still work as expected.
https://github.com/longhorn/longhorn/issues/307

Add disable replica rebuild setting to pause cross cluster rebuild

---

controller/instance_manager_controller.go
deploy/install/01-prerequisite/04-default-setting.yaml
types/setting.go

By default, Longhorn will block `kubectl drain` action on a node if the node contains the last healthy replica of a volume.
If the setting is enable and the node contains the last healthy replica of a volume, Longhorn will not use PodDisruptionBudget to protect instance manager pod from being deleted
https://github.com/longhorn/longhorn/issues/1631

add a global setting for user to choose whether Longhorn should block`kubectl drain` if the node contains the last replica of a volume

---

controller/instance_manager_controller.go
datastore/longhorn.go

Fix the bug: Longhorn always deletes PDB of replica instance manager pod when the current node is draining eventhough the node contains the last replica of a volume and user set `Allow Node Drain with the Last Healthy Replica` to false.
The reason was that after the the volume is detached, the `im.Status.Instance` map  is empty and the loop https://github.com/longhorn/longhorn-manager/blob/12ab9ef33ef043b230c11e28ef2e4505fb650e82/controller/instance_manager_controller.go#L532
is never executed
longhorn/longhorn #1631

fixed the bug: Longhorn always delelte PDB of replica instance manager pod

---

api/model.go
controller/volume_controller.go
controller/volume_controller_test.go
deploy/install/01-prerequisite/04-default-setting.yaml
manager/volume.go
types/setting.go

The setting allows user to create a volume with less than specified
number of replicas, so user can use the default Longhorn configuration
without issues in one or two nodes cluster.
It is recommended to disable the feature when using Longhorn in
production environment.
Notice this PR also adds the ability to restore volume/DR volume with degraded availability.
https://github.com/longhorn/longhorn/issues/1701

feature: Add AllowVolumeCreationWithDegradedAvailability

---

controller/engine_controller.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/kubernetes_node_controller.go
controller/kubernetes_pod_controller.go
controller/kubernetes_pv_controller.go
controller/node_controller.go
controller/replica_controller.go
controller/setting_controller.go
controller/uninstall_controller.go
controller/volume_controller.go

If an informer misses a deletion event, the final state of the object
will be unknown and instead the event will be a marker object of type
cache.DeletedFinalStateUnknown with a sub Obj that contains the last
cached state.
Previously we didn't handle the cache.DeletedFinalStateUnkown object and instead always used a type assertion for the corresponding longhorn object.
longhorn/longhorn#1900
related: #1877

Fix missed deletion events crash the longhorn-manager

---

csi/deployment.go
deploy/longhorn-images.txt
deploy/release-images.txt

```
longhornio/csi-attacher:v2.2.1-lh1
longhornio/csi-provisioner:v1.6.0-lh1
longhornio/csi-resizer:v0.5.1-lh1
longhornio/csi-snapshotter:v2.1.1-lh1
longhornio/csi-node-driver-registrar:v1.2.0-lh1
```
https://github.com/longhorn/longhorn/issues/1886

Update CSI component images

---

csi/controller_server.go
util/util.go

Fix csi minimal volume size to 10MiB.
Add round up to multiple of 2MiB to align with UI behavior.
https://github.com/longhorn/longhorn/issues/357

Fix csi minimal volume size to 10MiB

---

controller/instance_manager_controller.go

longhorn/longhorn#1880
If somehow the ETCD doesn't work correctly (may due to master reboot) and the instance manager pods are restarted with different IPs during the period, the InstanceManager Controller may miss the instance manager IP sync.

controller: Keep syncing IP when IM is running

---

controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/volume_controller.go
datastore/longhorn.go

This PR does:
1. Remove the hardcoded NodeName in pod's spec of recurring job
2. Set the tolerations for the cronjob pods that are set by the user via the longhorn-settings
3. Reduce SuccessfulJobsHistoryLimit to 1 to reduce total number of pods in the cluster
Previously, we used the engine client binary on the current node to do backup. Therefore, we need to add NodeName: v.Status.CurrentNodeID. Now that we changed to use Longhorn API to do backup, the NodeName field is no longer needed.
Issues:
longhorn/longhorn#1903
longhorn/longhorn#1796
longhorn/longhorn#1793

Fix recurring job scheduling problems

---

manager/volume.go

This is to make the shcedule failure more clear for csi attacher.
https://github.com/longhorn/longhorn/issues/1700

Update volume schedule failure error message

---

controller/node_controller.go
types/resource.go

This new field will prevent multiple node controllers to update the same
node object.
https://github.com/longhorn/longhorn/issues/1449

Add 'node.Status.OwnerID' field to bind the node object to a node controller

---

controller/node_controller.go
types/resource.go

Reverts longhorn/longhorn-manager#749
It broke the Longhorn node down detection.
Ref: https://github.com/longhorn/longhorn/issues/1449

Revert "Add 'node.Status.OwnerID' field to bind the node object to a node controller"

---

deploy/install/01-prerequisite/03-crd.yaml

We need to upgrade because `apiextensions.k8s.io/v1beta1` is being deprecated. It will be unavailable in Kubernetes v1.22+.
In this PR, we disable pruning for Longhorn CRDs for the ease of implementation by setting `x-kubernetes-preserve-unknown-fields: true`. In the future, we can turn it on by having a full description of `schema. openAPIV3Schema`; removing the field `x-kubernetes-preserve-unknown-fields: true `; and set `preserveUnknownFields : false`. By doing that, it allows us to turn on the schema validation feature of Kubernetes on both the API server-side and client-side (kubectl, client-go, etc,..). 
This also servers as a preparation for the upgrade from `longhorn.io/v1beta1` to `longhorn.io/v1`. The idea is that we can deploy both `v1` and `v1beta1` versions at the same time …

Upgrade longhorn.io CRDs from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1

---

csi/controller_server.go

DisableFrontend gets set to false during volume attach hence no need to check before.

Remove DisableFrontend check in ControllerPublishVolume

---

datastore/longhorn.go
monitoring/disk_collector.go
monitoring/monitoring.go
monitoring/node_collector.go
monitoring/types.go

Added metrics:
1. longhorn_node_storage_capacity_bytes
2. longhorn_node_storage_usage_bytes
3. longhorn_node_storage_reservation_bytes
4. longhorn_disk_capacity_bytes
5. longhorn_disk_usage_bytes
6. longhorn_disk_reservation_bytes
longhorn/longhorn#1832

Add disk and node storage metrics

---

examples/rwx/01-security.yaml

Updating ClusterRoleBinding to reference correct name of PodSecurityPolicy. Original yaml referenced a PSP named "nfs-provisioner" but the yaml creates a PSP named "longhorn-nfs-provisioner". Updated to reference correct name.
Signed-off-by: Zachary Bialik <zachbialik1207@gmail.com>

Reference correct PodSecurityPolicy name

---

types/deepcopy.go

longhorn/longhorn#1950
Use function `DeepCopy` when copying `DiskStatus`.
Need to copy `ScheduledReplica` in `DiskStatus.DeepCopy`

Fix DeepCopy() for NodeStatus and DiskStatus

---

api/model.go
api/volume.go
app/volume.go
client/generated_attach_input.go
client/generated_volume.go
manager/volume.go
types/resource.go

We have discussed the option of removing the auto-reattachment feature entirely. However, I think that we shouldn't do it because:
1. We need the auto-reattachment feature in some cases. For example, when the volume is in the restoring process, if it is detached unexpectedly, Longhorn should auto-reattach the volume and continue doing the restoration. 
1. Removing the auto-reattachment feature doesn't solve the problem in this issue. The root cause of this problem is that when the volume is detached unexpectedly during a recurring backup job, the `volume.Spec.NodeID` field is not cleared (therefore, workload pod cannot uses the volume). The auto-reattachment feature lives inside VolumeController and VolumeController never changes volume's spec.
This PR proposes another approach:
1. We add …

Fix: volume remains attaching to the wrong node during a recurring backup

---

controller/uninstall_controller.go
datastore/kubernetes.go
deploy/uninstall/uninstall.yaml
upgrade/upgrade.go

Clearn up the lease object longhorn-manager-upgrade-lock in the longhorn-system namespace as a part of uninstallation, so the NPE can be avoided
longhorn/longhorn#1779

Clearn up the lease object longhorn-manager-upgrade-lock when uninstall Longhorn

---

controller/uninstall_controller.go

Previously, we delete node resources before deleting instance manager resources. This leads to a chaotic situation in which the ownership of instance manager resources gets transferred constantly between Longhorn managers ([see the log](https://github.com/longhorn/longhorn/issues/1653#issuecomment-670109463)). There are always conflicts when updating the instance manager resources in `etcd` and the Longhorn managers cannot remove the `finalizer` for the instance manager resources.
Now, we delete instance manager resources, then delete node resources. The problem is gone.
longhorn/longhorn#1653

Fix: uninstallation takes long time to finish

---

app/daemon.go
deploy/install/01-prerequisite/04-default-setting.yaml
manager/kubernetes.go

There are 2 reasons for doing this:
1. To avoid confusing users. In v1.0.2, users have to specify `Private Registry Secret` in the default setting section which is hidden by default. See more at [link](https://github.com/longhorn/longhorn/issues/1670#issuecomment-670723484). With this fix, all the private registry settings are on the same `Private Registry Setting` section. See more at [link](https://github.com/longhorn/longhorn/blob/e020e22913fd3f92c7bfc9d513a5bc86ecd7e0b8/chart/values.yaml#L98)
1. In v1.0.2, when users updating Longhorn deployment and specify a new setting for `registry secret `, it won't be applied because the old `registry secret ` already existed. With this fix, the new value of  `registry secret ` will be applied.
The approach is similar to how we handle the default …

Move registry secret setting to outside of  default setting

---

app/driver.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/setting_controller.go
controller/volume_controller.go
csi/deployment.go
csi/deployment_util.go
types/setting.go
types/types.go
upgrade/upgrade.go
upgrade/v102to110/upgrade.go
util/util.go

We allow the user to set all kinds of taint tolerations including the ones that contain `kubernetes.io` substring. This allows users to run Longhorn on control/etcd nodes.
We remember which tolerations applied by us in the annotation `longhorn.io/last-applied-tolerations`
Also, allow empty effect to enable 2 special cases for tolerations:
>An empty key with operator Exists matches all keys, values and effects which means this will tolerate everything.
An empty effect matches all effects with key key.
Also, fix the bug to allow multiple tolerations with the same key
longhorn/longhorn#1874 
longhorn/longhorn#1977

Allow user to set all kind of taint tolerations

---

controller/volume_controller.go

Why do we need this fix?
When users disable the revision counter, Longhorn will use `e.Spec.SalvageRequested` as an indicator to decide whether it needs to choose the best replica to salvage the volume when the engine process starts. If all replicas of volumes fail, and users disable the revision counter, and `autoSalvage=true`, and we fail to set `e.Spec.SalvageRequested=true`, Longhorn will pick all replicas when the volume's engine restarts. It is problematic because replicas might not be in sync. 
How does this PR fix this issue?
When all volume's replicas fail and `autoSalvage==true`, we set `e.Spec.SalvageRequested=true` and make sure that it persists in etcd before auto-salvage the replicas. This makes sure that when the engine process restarts, it picks the correct replica for …

Always set e.Spec.SalvageRequested=true when all volume's replicas fail

---

controller/instance_manager_controller.go
controller/volume_controller.go
util/util.go

When users enter duplicated tolerations (same key, operation, value, and effect) in Longhorn UI setting, make sure Longhorn doesn't set duplicated tolerations for IM pods and cronjob.
Related to this comment https://github.com/longhorn/longhorn/issues/1977#issuecomment-733396340
longhorn/longhorn#1977

Avoid setting duplicated tolerations for IM pods and cronjob

---

controller/volume_controller.go

The live upgrade will be suspended when:
1. there are additional (error) replicas even if the volume is healthy
2. the volume is degraded
longhorn/longhorn#1975

Fix bugs for live upgrade

---

controller/setting_controller.go
controller/share_manager_controller.go
datastore/kubernetes.go

There is an interesting behavior, that we can only change the toleration settings while all volumes are detached, so the user needs to scale down all rwx volumes, for the sharemanager to detach the volume.
https://github.com/longhorn/longhorn/issues/2049

Restart share manager pods, when tolerations/priority class changes

---

controller/kubernetes_pod_controller.go

When volume's `remountRequestedAt` is set, Longhorn manager delete workload pod if the pod is on the same node as the manager
longhorn/longhorn#2057

Make sure only  one manager handle pod deletion when volume's remount RequestedAt is set

---

csi/nfs/nsenter.go
csi/nfs/nsenter_mount.go
csi/node_server.go

there is 2 calls remainnig, where we need to replace the os.stat invocation
with a namespaced stat invocation and parse the results of the command
manually.
longhorn/longhorn#2063

Remove most of the hostMount requirement for the nsenter mounter

---

csi/deployment.go

We only require the pid, mnt, net and uts namespaces
longhorn/longhorn#2074

Remove host ipc from the csi plugin deployment

---

controller/share_manager_controller.go

While a volume is in standby mode there is no need for the volume to be
controlled by a share manager, since the user needs to activate a volume
before it can be used by workloads.
https://github.com/longhorn/longhorn/issues/2048

Add support for DR volumes in RWX mode

---

csi/controller_server.go
csi/nfs/nsenter_mount.go
csi/node_server.go

Also includes the full error message on a mount failure for shared volumes
We can then add information to the knowledge base to help the user diagnose failures

No need to call attach for shared volumes from the csi driver

---

controller/volume_controller.go

This cleans up orphaned share managers for no longer existing volumes, for whatever reason a volume might no longer be present, while the share manager crd is still present.

Cleanup orphaned share managers for no longer existing volumes

---

deploy/install/02-components/01-manager.yaml

It caused issue for https://github.com/longhorn/longhorn/issues/2088
Also, frankly speaking, I cannot recall why it's needed. Cannot find
any meaningful references in the code.

deploy: remove `/var/run` bind-mount

---

api/model.go
csi/controller_server.go
csi/node_server.go

Instead the user of a shared volume needs to check for shareEndpoint
availability directly via shareState == running and shareEndpoint != ""

Don't use the Ready flag for share availability signal

---

examples/data_migration.yaml

This can be used to migrate data from other storage systems or the old nfs
provisioner. The job will restart up to 3 times in the case of failure of
the copy operation.
After successful completion the list of files, can be viewed in the logs
of the job pod. The job can be deleted once the operation succeeded.

Add volume data migration example job

---

datastore/longhorn.go

Inside `InitSettings()`, don't return error when creating a setting and the setting already exists.
longhorn/longhorn#2077

Setting creation conflicts

---

controller/events.go
controller/volume_controller.go

For the error during the SnapshotPurge progress, it will be recorded by
the engine/replica process automatically. Then once there is an error
in the engine's purgeStatus, the volume controller will mark the replica
as failed.
longhorn/longhorn#1895

controller: mark replica failed when we detect a bad replica while doing SnapshotPurge

---

deploy/install/02-components/01-manager.yaml
deploy/longhorn-images.txt
deploy/release-images.txt

We switched from fedora to an ubuntu base image, to support the security
scanner.
longhorn/longhorn#2111

Update default share-manager image to v1_20210106

---

deploy/iscsi/longhorn-iscsi-installation.yaml

fix debian and add suse support to resolve ticket 'Improve documentation for installing open-iscsi' (#1741)
1. Add code logic to install open-iscsi in SUSE (zypper) platform.
2. Use `bash` instead of `sh` to enable platform check using `[[ ]]`.
3. Update Alpine from 3.7 to 3.12.
Improvement.
1. Deploy RKE/K3S on Centos/Ubuntu/SLES15SP2 and verify if containers run successfully on each node have package installed.
Refs: #1741
None
Signed-off-by: cclhsu <clark.hsu@suse.com>

fix debian and add suse support (#1741)

---

controller/engine_image_controller.go
controller/volume_controller.go
deploy/install/01-prerequisite/04-default-setting.yaml
manager/volume.go
types/setting.go

Reduce the amount of manual work users have to do when upgrading Longhorn by automatically upgrade engine images for volumes when they are ok to upgrade. E.g. when we can do engine live upgrade or when volume is in detaching state.
Engine image controller will continuously watch and upgrade volumes' engine image to default engine image
More detail about the implementation at https://github.com/longhorn/longhorn/pull/2172
longhorn/longhorn#2152

controller: upgrade engine automatically to default version

---

controller/engine_controller.go
engineapi/backups.go
engineapi/engine.go
engineapi/snapshot.go
manager/backup.go
types/types.go
util/util.go

Pass S3 specific environment variables to sub-process only.
This could prevent the sub-process environment variables affect the parent process.
For example: if the backup target S3 need to go through proxy server, then pass the additional envs to sub-process by
```go
cmd := exec.Command("backup", "ls", args...)
cmd.Env = append(os.Environ(), "HTTP_PROXY=<http-proxy>", "HTTPS_PROXY=<https-proxy>", "NO_PROXY=<no-proxy>", ...)
```
https://github.com/longhorn/longhorn/issues/2198

Setup environment variables to sub-process only

---

controller/replica_controller.go

fix nil pointer cause longhorn-manager pods crushloopbackoff to resolve ticket '[BUG] All longhorn-manager pods crushloopbackoff' (#2208)
Fixed Bug.
It seems that during creating, diskStatus is nil. Need to check if diskstatus existed.
time="2021-02-18T08:41:05Z" level=info msg=disk-1
time="2021-02-18T08:41:06Z" level=info msg=disk-1
time="2021-02-18T08:41:06Z" level=info msg="Diskname disk-1 has status %!b(bool=true)"
NOTE: this was sample print during implementation/verification.
Refs: https://github.com/longhorn/longhorn/issues/2208
None
Signed-off-by: cclhsu <clark.hsu@suse.com>

fix nil pointer cause longhorn-manager pods crushloopbackoff (#2208)

---

csi/controller_server.go
csi/node_server.go

Fix failures from [csi-sanity](https://github.com/kubernetes-csi/csi-test/tree/master/cmd/csi-sanity) tests.
* Add volume name autocorrection.
* Remove the unimplemented capability to bypass related tests.
* Correct misuse of the error codes.
* Validate resources to fix unexpected returns.
* Address to idempotency of volume life cycle.
Relate to https://github.com/longhorn/longhorn/issues/2076

Fix CSI sanity check

---

engineapi/backups.go
engineapi/backups_test.go
engineapi/types.go
go.mod
go.sum
vendor/github.com/longhorn/backupstore/backupstore.go
vendor/github.com/longhorn/backupstore/deltablock.go
vendor/github.com/longhorn/backupstore/list.go
vendor/modules.txt

- Pass labels to backup volume structure
- Add unit-test to test parseBackupVolumesList
- Consolidate two backupVolume/BackupVolume structure into one
- Bump longhorn/backupstore version to add KubernetesStatus metadata to volume.cfg
https://github.com/longhorn/longhorn/issues/1539

Bump longhorn/backupstore version to add KubernetesStatus metadata to volume.cfg

---

deploy/install/02-components/01-manager.yaml
deploy/longhorn-images.txt
deploy/release-images.txt

Include
- patched nfs-ganesha v3.3 to fallback to ipv4 when ipv6 is not available
https://github.com/longhorn/longhorn/issues/2197
- Fix for pod hanging at ganasha server error due to missing /etc/mtab file.
https://github.com/longhorn/longhorn/issues/2111
Test: https://github.com/longhorn/longhorn/issues/2197#issuecomment-788595045

Update default share-manager image to v1_20210302

---

api/forwarder.go
api/router.go
app/daemon.go
app/volume.go
client/generated_engine_image.go
controller/controller_manager.go
controller/controller_test.go
controller/engine_controller.go
controller/engine_image_controller.go
controller/engine_image_controller_test.go
controller/instance_handler_test.go
controller/instance_manager_controller_test.go
controller/volume_controller.go
controller/volume_controller_test.go
datastore/kubernetes.go
datastore/longhorn.go
manager/engine.go
manager/engineimage.go
manager/node.go
manager/volume.go
scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go
types/resource.go
types/setting.go

If the engine image is failed to be deployed on some nodes, it shouldn't prevent Longhorn from operating volumes that don't have engine or replicas on those nodes. This PR changes from checking engine image's availability on all nodes to checking the engine image's availability on required nodes.
More details about the detail proposal is at https://github.com/longhorn/longhorn/issues/2081#issuecomment-780964823

Change from checking engine image's availability on all nodes to checking the engine image's availability on required nodes

---

datastore/longhorn.go

This prevents repeatedly printing out the logs when checking
CheckEngineImageReadiness for the spec.NodeID of detached
volumes
longhorn/longhorn#2081

datastore: don't log when checking CheckEngineImageReadiness for the empty string node

---

api/model.go
api/router.go
api/volume.go
app/volume.go
client/README.md
client/generated_client.go
client/generated_detach_input.go
client/generated_volume.go
controller/share_manager_controller.go
controller/volume_controller.go
csi/controller_server.go
csi/node_server.go
csi/util.go
examples/rwx/storageclass-migratable.yaml
manager/engine.go
manager/volume.go
types/resource.go

The live migration function works like this:
- n1 | vm1 has the volume attached (v.spec.nodeID = n1)
- n2 | vm2 requests attachment (v.spec.migrationNodeID = n2) [migrationStart]
- volume-controller brings up new engine on n2, with inactive matching replicas (same as live engine upgrade)
- csi driver polls for existence of second engine on n2 before acknowledging attach
The following detach decides whether a migration is successful or a migration rollback on the longhorn side.
- n1 | vm1 requests detach of n1 (v.spec.nodeID = n2, v.spec.migrationNodeID = "") [migrationComplete]
- n2 | vm2 requests detach of n2 (v.spec.NodeID = n1, v.spec.migrationNodeID = "") [migrationRollback]
The volume controller then cleans up the second engine and switches the active replicas to be the current …

live migration feature

---

types/types.go

If the user sets a wrong CPU value on a specific node, the error log will convert the concrete value to a percentage value without symbol `%`, which is confusing. e.g.
If I set the requested engine manager CPU to 20000m but the total CPU of this node is 2000m, the error message is:
```
the sum of the engine manager CPU value 1000 and the replica manager CPU value 13 should not be greater than 40% or smaller than 0%
```
Longhorn #2207

types: Improve the CPU reservation error log

---

util/util.go

Volume name not converted to lower-case.
https://github.com/longhorn/longhorn/issues/2270

Fix volume name not auto-correct to lowercase

---

deploy/prerequisite/longhorn-iscsi-installation.yaml
deploy/prerequisite/longhorn-nfs-installation.yaml

fix iscsi install manifest to create config file initiatorname iscsi to resolve ticket '[BUG] Configuration file  does not exist iscsi using ' (#2319)
- generate `/etc/iscsi/initiatorname.iscsi`
- fix `yum makecache fast` invalid in Centos 8.x
check if `/etc/iscsi/initiatorname.iscsi` created 
Refs: # https://github.com/longhorn/longhorn/issues/2319
Verified in Centos 7.8 and Centos 8.2

fix iscsi install manifest to create config file initiatorname iscsi

---

controller/controller_manager.go
controller/setting_controller.go
datastore/longhorn.go

Currently the backupstore monitor poll is processed by every node in the 
cluster, this is undesired since it leads to excessive S3 calls and cost.
This also has the side effect that each nodes backupstore monitor will 
race against each other to try to update each volumes lastBackup field. 
This leads to unnecessary conflicts and processing of the volumes.
Since the backup monitor is run on each node, but we only need a single 
update we pick a consistent random ready node for each poll run. This is
accomplished by the following steps:
- sort the candidate list, this normalizes the list across nodes.
- use a time index to derive an index into the candidate list, this 
normalizes time differences across nodes.
- arbitrarily choose the pollInterval as your time normalization factor, 
since …

Fix backup monitor polling from each node at the same time

---

csi/controller_server.go
csi/deployment.go
manager/volume.go

Also added a fix in a separate commit for an issue on the CSI drivers, volume expansion idempotency. Since I was testing the RWX expansion at the same time.
https://github.com/longhorn/longhorn/issues/2316
https://github.com/longhorn/longhorn/issues/2181
@shuo-wu closed the other pr in favor of this one, kept the old error behavior except in the case where the requested size == the actual size, since that makes the call idempotent. We still error out in the longhorn api where size < actual size.
For the csi part it's expected behavior to return success in case where size < actual size and include the actual size.

Fixes the RWX attach call

---

deploy/uninstall/uninstall.yaml

```shell
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/deploy/longhorn.yaml
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/uninstall/uninstall.yaml
kubectl get job/longhorn-uninstall -n default -w
```
The job pod in the stuck state.
According to PSP Policy Order:
> 1. PodSecurityPolicies which allow the pod as-is, without changing defaults or mutating the pod, are preferred. The order of these non-mutating PodSecurityPolicies doesn't matter.
> 2. If the pod must be defaulted or mutated, the first PodSecurityPolicy (ordered by name) to allow the pod is selected.
since the uninstall Job did not set any `securityContext`, it causes it would fall into `global-restricted-psp` first since the pod must be defaulted or mutated, the first …

Enable uninstall job security context privileged

---

controller/setting_controller.go
controller/share_manager_controller.go
csi/deployment.go
csi/deployment_util.go
datastore/kubernetes.go
deploy/install/02-components/01-manager.yaml
deploy/install/02-components/03-ui.yaml
deploy/install/02-components/04-driver.yaml
manager/engineimage.go
types/setting.go
types/types.go
upgrade/upgrade.go
upgrade/util/util.go
upgrade/v070to080/upgrade.go
upgrade/v100to101/upgrade.go
upgrade/v102to110/upgrade.go
upgrade/v110to111/upgrade.go

Longhorn shouldn't modify user deployed components (e.g., manager, driver,
UI) because doing so would have problems for users who deploy Longhorn using
GitOps tools.
* This PR adds a new labels `longhornio/managed-by: longhorn manager` to all
managed components. Then Longhorn only watchs and updates toleration/priority class for those
managed components
* This PR also makes sure that the labels is added after upgrade Longhorn from
an older version.
Now that we only watch/update managed components, we should allow user to specify Helm values for user deployed components (manager, driver, UI). This is tracked at https://github.com/longhorn/longhorn/pull/2348
longhorn/longhorn#2120

Only watch and update toleration/priority class for managed components

---

deploy/uninstall/uninstall.yaml

According to https://github.com/longhorn/longhorn-manager/pull/849#issuecomment-804234586
> When the user deletes the longhorn-system namespace by mistake and gets stuck, the Pod cannot be created in that namespace. That's why we're running the uninstaller job in the default namespace.
- Rvert the change of removing ServiceAccount, ClusterRole, and ClusterRoleBinding
- Keep the job running in `default` namespace
- Add PSP `longhorn-uninstall-psp` for ServiceAccount `longhorn-uninstall-service-account`
https://github.com/longhorn/longhorn/issues/2292

Keep uninstall job in default namespace

---

controller/engine_image_controller.go
util/util.go

`limitAutomaticEngineUpgradePerNode()` may be called multiple times with the same inputs. Therefore, we need to sort the `upgradingCandidates` slice so that the function has deterministic finalCandidates output. This prevents selecting more than `concurrentAutomaticEngineUpgradePerNodeLimitcandidates` to upgrade at the same time.
I am not sure why the `limitAutomaticEngineUpgradePerNode()` sometime is called multiple times with the same inputs. @joshimoo , @yasker Do you have any idea? I actually don't like the current fix (sorting the list of volumes) because it may hurt Longhorn in the long run when Longhorn is used to manage million of volumes. So, if we can prevent the `limitAutomaticEngineUpgradePerNode()` from being called multiple times with the same inputs, it would be a better …

Fix bug Longhorn upgrades more than concurrentAutomaticEngineUpgradePerNodeLimit engines per nodes

---

controller/controller_test.go
controller/engine_image_controller.go
controller/engine_image_controller_test.go
datastore/kubernetes.go
types/types.go

We recently changed the labels for engine image CR in the PR https://github.com/longhorn/longhorn-manager/pull/842. We added the label `longhorn.io/managed-by: longhorn-manager` to `engine image`, `engine image daemonset`, and `engine image daemonset pod` by updating the fucntion [GetEngineImageLabels()](https://github.com/longhorn/longhorn-manager/blob/f6ff18666ea238c4eec4bfdce9612796da1a0701/types/types.go#L234)
On the other hand, during Longhorn upgrading, we only update the label for `engine image`, `engine image daemonset` but not the `engine image daemonset pod`  of the existing engine image.
This creates a problem when we [syncNodeDeploymentMap()](https://github.com/longhorn/longhorn-manager/blob/f6ff18666ea238c4eec4bfdce9612796da1a0701/controller/engine_image_controller.go#L363), …

Fixed engine image never becomes deployed after upgrading

---

app/uninstall.go
controller/controller_manager.go
controller/engine_image_controller_test.go
controller/instance_handler_test.go
controller/instance_manager_controller_test.go
controller/kubernetes_pv_controller_test.go
controller/kubernetes_secret_controller.go
controller/node_controller_test.go
controller/volume_controller_test.go
datastore/datastore.go
datastore/kubernetes.go
datastore/longhorn.go
engineapi/backups.go
engineapi/backups_test.go
go.mod
go.sum
scheduler/replica_scheduler_test.go
types/types.go
vendor/modules.txt

- Create a new secret controller, the purpose is to update the annotation of the `iam.amazonaws.com/role` to longhorn manager and replica instance manager Pod.
- If the user performs S3 list/backup/restore/delete, the longhorn-manager checks:
- AWS_IAM_ROLE_ARN :heavy_check_mark: & AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY :heavy_check_mark: -> :ok:
- AWS_IAM_ROLE_ARN :heavy_check_mark: & AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY :x: -> :ok:
- AWS_IAM_ROLE_ARN :x: & AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY :heavy_check_mark: -> :ok:
- AWS_IAM_ROLE_ARN :x: & AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY :x: -> :x:
- Bump longhorn/backupstore version
https://github.com/longhorn/longhorn/issues/1526

Support AWS IAM Role

---

api/model.go
api/stream.go

Currently, websocket stream will return all resource data at 1-sec interval even when there is no update in the resource data. This is caused by the timestamp in all resource objects.
Remove the timestamp and instead returns an empty data list to the frontend reduces the duplicated data transfer and also keeps the websocket connection alive.
https://github.com/longhorn/longhorn/issues/2372

Fix websocket traffic flood

---

app/uninstall.go
controller/uninstall_controller.go

update unsinstall controller to cleanup share manager crds to resolve ticket '[BUG] uninstall-controller does not cleanup share-manager crds' (#2384)
- add clean up for share-manager and settings
Bug
- deploy longhorn
- deploy a rxw volume/pod
- uninstall using uninstaller from "https://raw.githubusercontent.com/longhorn/longhorn-manager/master/deploy/uninstall/uninstall.yaml"
- check log for uninstaller
```
ttime="2021-04-01T06:49:07Z" level=info msg="Found 1 share managers remaining" controller=longhorn-uninstall
time="2021-04-01T06:49:07Z" level=info msg="Marked for deletion" controller=longhorn-uninstall owner=centos-worker-0 shareManager=pvc-d6e490b0-0437-481c-ba0f-c6d8944757f4 state=running volume=pvc-d6e490b0-0437-481c-ba0f-c6d8944757f4
time="2021-04-01T06:49:07Z" level=info …
```

update unsintall controller to cleanup share manager crds (#2384)

---

controller/uninstall_controller.go

update execution order for share manager crd in uninstall controller to resolve ticket '[BUG] uninstall-controller does not cleanup share-manager' (#2384)
Bug
Refs: # https://github.com/longhorn/longhorn/issues/2384
None

update execution order for share manager crd in uninstall controller

---

api/model.go
controller/volume_controller.go
csi/controller_server.go
csi/server.go

There is two things that are required one is the csi changes to always call attach/detach.
This insures that kubernetes + longhorn volumes are in sync.
I plan on working on structured error returns for the longhorn api, so that we can use them to do appropriate error handling.
https://github.com/longhorn/longhorn/issues/1875
The other issue is the auto salvage hotfix.
Honestly I have a hard time to reason about the current volume controllers
attach/detach behavior and therefore I cannot confidently say whether this
change has any undesired side effects.
I recommend we prioritize the volume controller refactor, 
so that attach/detach decisions and state are solely based on the set v.Spec.NodeID
https://github.com/longhorn/longhorn-manager/pull/857
Issues:
- …

Always call attach/detach from the csi driver + auto salvage hotfix

---

controller/backing_image_controller.go
controller/controller_manager.go
controller/engine_controller.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/kubernetes_configmap_controller.go
controller/kubernetes_node_controller.go
controller/kubernetes_pv_controller.go
controller/replica_controller.go
controller/share_manager_controller.go
controller/volume_controller.go
datastore/longhorn.go
manager/engine.go
manager/engineimage.go
manager/volume.go

1. When the manager pod on the owner node of the CR is missing, we switch
the ownerID of the CR to a different node
2. Don’t cleaning up CRs base on the current ownerID. The convention is 
that ownerID only indicates which node should watch the CR. We shouldn’t 
make any other logic depend on the ownerID. This way we can freely transfer
ownership
3. Make sure that when the engine/instance manager CR is transfered to 
new ownerID, the old owner must stop monitoring them. Also, remove 
engine/instance manager monitoring from the monitoring map of engine/instance 
manager controller when stop monitoring the engine. This allow the old
owner to restart the monitoring when the CRs’ owner is transfered back to it
4. Don’t clear the engine status when switching ownership. The new owner 
will take …

Ownership transferring refactoring

---

csi/controller_server.go

Fix error code when node does not exist.
```
Expected
<codes.Code>: 13
to equal
<codes.Code>: 5
```
https://github.com/longhorn/longhorn/issues/2076
https://github.com/longhorn/longhorn/issues/2270

CSI-sanity check - should fail when the node does not exist

---

deploy/install/02-components/01-manager.yaml
deploy/longhorn-images.txt
deploy/release-images.txt

Include:
* Fix rwx mount ownership reset to nobody (https://github.com/longhorn/longhorn/issues/2357)

Update default share-manager image to v1_20210406

---

controller/instance_manager_controller.go

**Problem:**
When we [clean up the instance manager CR](https://github.com/longhorn/longhorn-manager/blob/51c3b60138b0ca85c8bbfdffa4cc6998844246a8/controller/instance_manager_controller.go#L420), we update the IM CR at the middle of the syncInstanceManager loop [here](https://github.com/longhorn/longhorn-manager/blob/51c3b60138b0ca85c8bbfdffa4cc6998844246a8/controller/instance_manager_controller.go#L759). This update alter the IM CR and create [the conflict](https://github.com/longhorn/longhorn-manager/blob/51c3b60138b0ca85c8bbfdffa4cc6998844246a8/controller/instance_manager_controller.go#L310) at the end of the loop. Because of the conflict, we successfully create the pod but fail to set [im.Status.CurrentState = types.InstanceManagerStateStarting](https://github.com/longhorn/longhorn-man …

Fixing IM pods get deleted during new Longhorn installation

---

app/driver.go
app/get_proc_arg.go
controller/backing_image_manager_controller.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/setting_controller.go
controller/share_manager_controller.go
controller/volume_controller.go
csi/deployment.go
csi/deployment_util.go
datastore/longhorn.go
deploy/install/01-prerequisite/04-default-setting.yaml
deploy/install/02-components/01-manager.yaml
deploy/install/02-components/03-ui.yaml
deploy/install/02-components/04-driver.yaml
deploy/uninstall/uninstall.yaml
types/setting.go

This feature allows user to limit Longhorn on a specific set of nodes in the cluster. 
User stories:
* Deploy Longhorn in a cluster with both Linux nodes and Windows nodes
* [Longhorn in GKE](https://forums.rancher.com/t/longhorn-in-gke-node-affinity/19814)
User experience:
1. Set the node selector for user-deployed components (Longhorn manager, UI, driver deployer) in Helm or YAML file
2. Then set the node selector for managed components (everything else) in `system-managed-components-node-selector` setting
Note: Workloads that use Longhorn volume can only run on the selected nodes in the cluster.
longhorn/longhorn#2199

Allow users to sepecify node selector for Longhorn components

---

controller/setting_controller.go

When node selector is empty,  the object return by client-go has a `nil` map for nodeSelector. This makes the deep equal comparison always fail since the nodeSelector is an empty map. As the result, Longhorn manage restarts the managed components
longhorn/longhorn#2199

Fix bug: Longhorn always restart the managed components when the node selector is empty

---

manager/volume.go

This condition is already covered by the readiness check in the detached
state. I identified some issues with the way the scheduling conditions are
handled in the volume controller, but they are outside of the scope for
v1.1.1 This is a surgical fix, to allow for rwx volumes to be used even if
one replica cannot be scheduled.
The share manager currently does not check for this condition, and will
always allow for volume usage even if not all replicas could be scheduled.
After creation, this is part of the problem, since the intent of the
scheduling failure is to keep the volume in the creation state, right now
the volume controller does not do this instead, it has some hacks for the
detached state.
I plan on looking into this, when working on the volume controller refactor. …

Remove the schedule condition check from the Volume attach call

---

csi/node_server.go

We use a 3s timeout, with 3 retransmission tries before failure.
After each timeout the timeout will be linearly increased (3s, 6s, 9s)
This means that an IO operation has a maximum runtime of 18s before failure.
For the HA solution we want to use hard mode, which will lead to an infinite
retry, since in that mode we want to be able to guarantee the survival of
the workload pods instead of having to terminate them.
longhorn/longhorn#2528

Increase the hardcoded NFS client timeout

---

app/volume.go

The default request timeout for recurring jobs is 10s, which is
definitely not enough. If multiple recurring jobs for a volume
start simultaneously (due to the mutex lock), or some steps take
several seconds, the timeout will fail the recurring jobs.
Increasing the timeout is not able to completely avoid duplicate 
snapshots/backups if there are intensive snapshot-related
operations. But this should reduce the probability.
longhorn/longhorn#2278
Signed-off-by: Shuo Wu <shuo.wu@suse.com>

app: Increase the timeout for the http client

---

app/volume.go

To avoid creating unnecessary extra snapshots which consume the disk space, we only keep up to 2 snapshots for recurring backup jobs (the snapshot of the last backup and the snapshot of the currently running backup)
If users want to create more snapshots, they can use recurring snapshot job
longhorn/longhorn#2231

Only keep upto 2 snapshots for recurring backup jobs

---

manager/backingimage.go

If the backing image name is longer than 63 char, Longhorn cannot put it in the replica label. And Longhorn cannot list the replicas using the backing image name with the name.
longhorn/longhorn#2522

manager: Auto correct backing image name during creation

---

types/deepcopy.go

Fixes missed deepcopy sub element cases for 
- EngineStatus->Snapshots->Snapshot 
- VolumeStatus.KubernetesStatus.WorkloadStatus
longhorn/longhorn#2631

2631 deep copy fix

---

controller/kubernetes_pv_controller.go

fixes unnecessary volume status updates caused by unnorded processing of pods for kubernetesStatus->WorkloadStatus
longhorn/longhorn#2632

normalize pod processing order for kubernetesStatus

---

api/model.go
api/stream.go
util/util.go

- [List order caused full data transfer when no resource updated.](https://github.com/longhorn/longhorn/issues/2646)
- [Full data over WS at per 30/seconds interval seems useless.](https://github.com/longhorn/longhorn/issues/2591)

Fix full data over web sockets when there is no update

---

api/model.go
api/stream.go
util/util.go

- [List order caused full data transfer when no resource updated.](https://github.com/longhorn/longhorn/issues/2646)
- [Full data over WS at per 30/seconds interval seems useless.](https://github.com/longhorn/longhorn/issues/2591)

[Backport][v1.1.2] Fix full data over web sockets when there is no update

---

controller/volume_controller.go
csi/controller_server.go
datastore/kubernetes.go
manager/kubernetes.go
manager/volume.go

use pvc to expand volume to resolve ticket 'Application couldn't mount the volume after expanded the volume' (#2422)
- Modify 'Expand' API to provide PVC/PV expand
Bug fix
```
GIVEN:
- Kubernetes cluster deployed
- Longhorn deployed
- a statefulset/deployment with mounted volume deployed
WHEN:
- scale down replicas for statefulset/deployment to zero
- POST `Expand` to `longhorn_backend` 
THEN:
- wait for pvc/pv successful expand
- statefulset/deployment scale replica to 1 and disk attached successfully
```
Curl API
```
ACTION=expand
curl -sSX POST -H 'Content-Type: application/json' "http://${BACKEND_URL}:${BACKEND_PORT}/v1/volumes/${PV_NAME}?action=${ACTION}" -d '{"size":"4Gi"}' 
```
if volume is not detached will receive error like this
```
{
"actions": {},
"code": "Server Error", …
```

use pvc to expand volume (#2422)

---

controller/volume_controller.go
csi/controller_server.go
datastore/kubernetes.go
manager/kubernetes.go
manager/volume.go

Backport to v1.1.2
use pvc to expand volume to resolve ticket 'Application couldn't mount the volume after expanded the volume' (#2422)
- Modify 'Expand' API to provide PVC/PV expand
Bug fix
```
GIVEN:
- Kubernetes cluster deployed
- Longhorn deployed
- a statefulset/deployment with mounted volume deployed
WHEN:
- scale down replicas for statefulset/deployment to zero
- POST `Expand` to `longhorn_backend` 
THEN:
- wait for pvc/pv successful expand
- statefulset/deployment scale replica to 1 and disk attached successfully
```
Curl API
```
ACTION=expand
curl -sSX POST -H 'Content-Type: application/json' "http://${BACKEND_URL}:${BACKEND_PORT}/v1/volumes/${PV_NAME}?action=${ACTION}" -d '{"size":"4Gi"}' 
```
if volume is not detached will receive error like this
```
{
"actions": {},
"code": …
```

Use pvc to expand volume

---

controller/controller_manager.go
controller/kubernetes_pv_controller.go
controller/kubernetes_pv_controller_test.go

This removes the VA cleanup feature, since the use case is covered by the pod deletion feature.
It's better to only have a single way of accomplishing this.
I didn't touch the settings as part of this PR, since it's not important and they are just ignored.
So I can easily backport to 1.1.2
longhorn/longhorn#2060

Remove VA cleanup feature

---

csi/node_server.go
csi/util.go

Ensure that corrupt mount points are cleaned up during NodePublishVolume calls, this currently returns an error afterwards to make sure that kubelet can cleanup on it's side. In the future we might want to consider utilizing the NodeStateVolume calls to actually deal with the block device then only do bind mounts during NodePublishVolume calls.
We should also update the node plugin (lock per volume) to keek track of currently running operations for a single volume. To prevent multiple operations from running concurrently, the correct error to return then is aborted. Since that will signal that a previous operation is in progress.
longhorn/longhorn#2629
supersedes longhorn/longhorn-manager#908

Ensure cleanup of corrupted mount points

---

api/backingimage.go
api/model.go
api/stream.go
manager/backingimage.go

- Fix backing image data send over WS when no update. 
https://github.com/longhorn/longhorn/issues/2672
- Do not send WS an empty data list when no update.
https://github.com/longhorn/longhorn/issues/2372

WS data cleanup

---

controller/engine_image_controller.go
controller/node_controller.go
controller/replica_controller.go
datastore/longhorn.go
manager/node.go

There is probably a couple more places where we can use the ReadOnly elements from the cache directly, instead of having to go through the deepCopy if we are only using the items for evaluation.
There is also a fix for ListReplicasByDiskUUID returning the raw cached object which is then potentially modified by NodeController::syncDiskStatus

Use Readonly returns for listers where we only read

---

controller/volume_controller.go
manager/volume.go

Currently if the FromBackup specified backup cannot be found in the backup store, the volume create call will succeed which signals that the volume can be created. This will then lead to a npe in the controller.
https://github.com/longhorn/longhorn/issues/2686

Volume creation with an invalid FromBackup should fail

---

controller/backing_image_manager_controller.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/share_manager_controller.go
datastore/kubernetes.go

- Increase the Pods' ReadinessProbe.TimeoutSeconds from 1 sec to `PodProbePeriodSeconds-1` secs (4 secs).
- Backing image manager Pods
- Engine image Pods
- Share manager Pods
- Change instance manager Pod LivenessProbe to TCP probe to decrease the overhead than gRPC probe.
https://github.com/longhorn/longhorn/issues/2590#issuecomment-856389880

Increase ReadinessProbe TimeoutSeconds to 5 secs

---

csi/controller_server.go
csi/deployment.go
csi/deployment_util.go
csi/nfs/nsenter_mount.go
csi/node_server.go
csi/server.go
csi/util.go

This is for v1.1.2 
- does not contain csi locking.
- contains the plugin path fixes, this might leave the obsolete plugin around, not sure in regard to updates.
I try unmounting a mount point when volume is not attached is encountered.
Since it means that any prior mount point would be useless at the moment.
Since we use soft mount, the nfs calls will return withhin 15s
I decreased the timeout of the external sidecars to 1m50s
and the final volume state polling of the csi driver to 90s, this gives the rest of the function 20s

kubelet csi corrupt mnt mitigations

---

controller/backing_image_manager_controller.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/share_manager_controller.go
datastore/kubernetes.go

- Increase the Pods' ReadinessProbe.TimeoutSeconds from 1 sec to `PodProbePeriodSeconds-1` secs (4 secs).
- Backing image manager Pods
- Engine image Pods
- Share manager Pods
- Change instance manager Pod LivenessProbe to TCP probe to decrease the overhead than gRPC probe.
https://github.com/longhorn/longhorn/issues/2590#issuecomment-856389880

[Backport-v1.1.2] Increase ReadinessProbe TimeoutSeconds to 4 secs 

---

datastore/kubernetes.go

Add functions to get pv pvc from kubernetes client for volume expansion to resolve issue '[BUG] Application couldn't mount the volume after expanded the volume'
- Once the pvc's status become bound, tried the expansions. Only the alternate operation of expansion works on the detached volume. The sequence is 1st - fail, 2nd- pass, 3rd - fail, 4th- pass etc.
Bug Fix
Use `longhorn-static` should always return error message 
```
unable to expand volume test: persistentvolumeclaims "test" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```
Refs: https://github.com/longhorn/longhorn/issues/2422
None

Add functions to get pv pvc from kubernetes client for volume expansion

---

README.md

Fix flexvolume url for readme to resolve issue '[BUG] README.md flexvolume url is 404'
Longhorn: #

Fix flexvolume url for readme

---

api/model.go
api/router.go
app/daemon.go
deploy/install/02-components/01-manager.yaml

Add pprof and enabled by default for Longhorn manager. Users can set cmd option flag `--disable-profiler` at deployment.
https://github.com/longhorn/longhorn/issues/2696

Add pprof and disable-profiler cmd flag

---

controller/volume_controller.go
datastore/kubernetes.go
types/types.go

Labels added to cronjob: job type, managed by longhorn manager, longhorn volume name
Labels added to crobjob pods: job type, longhorn volume name
Note that Kubernetes automatically add job-name label to cronjob pod
Example use case:
* User can select all pods that are doing snapshot
* User can select all pods that are doing backup
* User can select all pods that are doing recurring job (snapshot or backup)
* User can select all recurring pods for particular volume
longhorn/longhorn#2701

Add more labels to cronjob and cronjob pod

---

controller/volume_controller.go
datastore/kubernetes.go
types/types.go

Labels added to cronjob: job type, managed by longhorn manager, longhorn volume name
Labels added to crobjob pods: job type, longhorn volume name
Note that Kubernetes automatically add job-name label to cronjob pod
longhorn/longhorn#2701

Cherry-pick: Add more labels to cronjob and cronjob pod

---

types/setting.go

Some newline symbols are missed.

fix the description of setting 'Replica Auto Balance'

---

manager/volume.go

Fix regression v1.1.2 expand with static storage class to resolve issue 'Application couldn't mount the volume after expanded the volume'
Get static class name from setting `default-longhorn-static-storage-class`.  If class name exist, continue with PVC expansion.  If not exist, continue with LHV expansion.
enhancement
* Case 1: From UI, PVC expand Volume with `default-longhorn-static-storage-class` set as `longhorn-<CUSTOMIZED-NON-EXISTED-CLASS-NAME>`
Expand will success.
Refs: Longhorn: #2692
- Issue discussion: https://rancher.slack.com/archives/C01G91NUHFY/p1624409225268200?thread_ts=1624316294.238500&cid=C01G91NUHFY
(cherry picked from commit ba88af4015a17163c89a981830cf388182265d94)

Fix regression v1.1.2 expand with static storage class

---

client/common.go

My cluster `longhorn-csi-plugin` hits Longhorn client timeout easily.
```log
level=fatal msg="Error starting CSI manager: Failed to initialize Longhorn API client: Get \"http://longhorn-backend:9500/v1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
Follow #887, increase the Longhorn client timeout to 1 min.

Increase rancher HTTP client default timeout to 1 min

---

controller/instance_handler.go
controller/volume_controller.go

When the volume has no healthy replica, there could be 2 cases:
* All replicas have never ever become healthy (both failedAt and healthyAt are empty),
e.g. newly created volume
* There are some replicas which were once healthy but now failed
We should do auto salvage in the second case
Close the stream when done
longhorn/longhorn#2778

Fix auto salvage logic and log stream socket connection leaking

---

controller/volume_controller.go

This issue was raised by @kaxing at manual regressions for https://github.com/longhorn/longhorn/issues/587.
- [When there are two equal zones(with the same node numbers), replica-auto-balance will rebuild replica in between zones.](https://github.com/longhorn/longhorn/issues/587#issuecomment-881419481)
- And [one of the replica will rebuilding in between zones.](https://github.com/longhorn/longhorn/issues/587#issuecomment-882194830)
I can reproduce it manually on a cluster with 7 nodes, 3 zones, and 5 replicas. This is caused by the unnecessary hardNodeAffinity by the multiple candidates. This skips the node candidate when the replica adjust count is zero.

Fix replica auto-balance rebuild loop in zones

---

datastore/longhorn.go

The returned engine object is then modified during the sync as well as the monitor
refresh cycles. This in itself is really bad but even worse since the sync
and monitoring routine run concurrently.
longhorn/longhorn#2827

Fix Datastore::GetEngine returning raw cached object

---

controller/engine_controller.go
engineapi/engine.go
engineapi/enginesim.go
engineapi/types.go

Remove duplicate engine::info call to extract volume endpoint
Since we already require the volume info any way this is an unnecessary
process/engine client socket creation in the monitoring loop. 
In summary one engine monitor loop after these fixes will open 
`f() = 8e + 6*r`  connections the expected connection count for
a volume with 3 replicas is around 312 time-wait connection in a 
minute window.
additional explanation on why this cannot be further improved at
https://github.com/longhorn/longhorn-engine/pull/646
longhorn/longhorn#2818

Remove duplicate engine::info call to extract volume endpoint

---

vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go

Revert the change from master temporarily to make the longhorn-manager master branch able to use it.
related to https://github.com/longhorn/longhorn/issues/2828

Revert leader election vendor update

---

api/model.go
api/volume.go
client/generated_volume.go
csi/crypto/crypto.go
csi/crypto/luks.go
csi/node_server.go
csi/util.go
examples/secure/secret-secure-global.yaml
examples/secure/storageclass-secure-global.yaml
examples/secure/storageclass-secure-per-volume-dedicated-namespace.yaml
examples/secure/storageclass-secure-per-volume.yaml
types/resource.go

Add support for volume encryption,  the general  flow works like this:
Host Requirements:
- dm_crypt module loaded
- cryptsetup installed
NodeStageVolume -> NodePublishVolume  changes:
before we used NodePublish for all calls, this implements NodeStageVolume support.
So NodePublishVolume just becomes a bind mount of the per node mounted device (RWO Device, CryptoDevice)
Kubernetes is responsible for the reference counting
Volume Creation:
- encryption parameters are specified via the storageclass
- requires a secret according to the storage class parameters, templates are resolved
- the secret refs are added to the kubernetes PV via the side cars
- if secret is not present, PVC will be remain in pending state
Volume usage:
NodeStageVolume:
- formats the device via cryptsetup as luks
- …

Add volume encryption support

---

api/model.go
api/volume.go
client/generated_pvcreate_input.go
client/generated_volume.go
csi/node_server.go
csi/util.go
datastore/kubernetes.go
examples/crypto/secret-crypto-global.yaml
examples/crypto/storageclass-crypto-global.yaml
examples/crypto/storageclass-crypto-per-volume-dedicated-namespace.yaml
examples/crypto/storageclass-crypto-per-volume.yaml
manager/kubernetes.go
manager/volume.go
types/resource.go

By passing `secretNamespace, secretName` as part of the PVCreate input.
We can add the necessary secret reference to the PV that longhorn creates for restore/manual created volumes.
These fields are only evaluated if the volume has been marked as `Encrypted` (i.e. v.Spec.Encrypted == true)
NOTE: we renamed the Secure field to Encrypted
longhorn/longhorn#1859

Add restore support (PV creation) support for encrypted volumes

---

controller/engine_controller.go

We use `engine.Status.CurrentReplicaAddressMap` to know which replica needed to rebuild. Need to persist the `engine.Status.CurrentReplicaAddressMap` to `etcd` before start rebuilding. Otherwise we might start rebuild and
later on `engine.Status.CurrentReplicaAddressMap` might be failed to persisted in `etcd`. As a result, we mark the rebuilding replica as UNKNOWN and remove it while it is in rebuilding process
longhorn/longhorn#2849

Fix the rebuilding race condition

---

controller/engine_controller.go

we use engine.Status.CurrentReplicaAddressMap to know which replica
needed to rebuild. Need to persist the engine.Status.CurrentReplicaAddressMap
to etcd before start rebuilding. Otherwise we might start rebuild and
later on engine.Status.CurrentReplicaAddressMap might be failed to persist
in etcd. In this case, we make the rebuilding replica as UNKNOWN and remove it
while it is in rebuilding
longhorn/longhorn#2849

Backport v1.1.3: Fix the rebuilding race condition

---

api/forwarder.go
api/model.go
api/router.go
manager/backingimage.go

longhorn/longhorn#2404
Workflow:
1. Users create a backing image by uploading a local file via UI.
2. UI calls the backing image creation API then waits for backing image field `uploadAddress` to become non-empty.
3. Longhorn manager pods will ask the backing image manager pods to launch an HTTP upload server for the backing image after receiving the backing image creation call. When the upload server is launched, backing image field `uploadAddress` will be set.
4. UI starts to call the upload-related APIs for the backing image. Longhorn manager pod will forward the requests to the upload server in the backing image manager pods:
1. Action `uploadServerStart` will ask the upload server to create a tmp file and set the total size for the backing image. This means upload start.
2. Action …

Backing Image Upload

---

api/forwarder.go

The forwarder simply modifying the schema of a HTTPS request to
HTTP makes the URL become invalid. Since it contradicts the
entries "X-Forwarded-Proto" and "X-Forwarded-Host" in the Header.
By removing or modifying these 2 entries, the issue gets resolved.
longhorn/longhorn#2869

api: Fix forwarder for https requests

---

controller/backup_controller.go
controller/backup_target_controller.go
controller/backup_volume_controller.go
types/deepcopy.go
upgrade/v111to120/upgrade.go

1. The controllers need to guarantee there is no nil pointer before reconciling a resource.
2. The deep copy functions look weird. I have no time to verify if it's actually correct. I directly use the simplest way to rewrite them.

Correct pointer init and copy for backup related CRs

---

controller/setting_controller.go

To prevent uninstall job stuck in clean up BackupTarget CR.

Remove auto salvage default BackupTarget CR

---

go.mod
go.sum
vendor/github.com/longhorn/backupstore/go.mod
vendor/github.com/longhorn/backupstore/go.sum
vendor/modules.txt

Downupgrade spf13/afero to v1.5.1 to prevent using
testing/fstest which is only available at Go 1.16+

Bump longhorn/backupstore version

---

api/snapshot.go
controller/backup_controller.go
engineapi/backups.go
engineapi/enginesim.go
engineapi/types.go
manager/engine.go
types/resource.go

- Remove backing image name and checksum from Backup CR
- Do backing image checksum validation in backup_controller:
1. Get volume CR, if any error, return to enqueue (not found error or other error)
2. Get BackingImage CR according to the `volume.Spec.BackingImage`
3. Get BackupVolume CR (backup volume name is the same as volume name).
1. If found, check the BackupVolume.status.BackingImageChecksum and BackingImage.status.BackingImageChecksum matched
2. If not found, it's the first backup of this volume, no BackingImageChecksum need to be verified
3. If other error, return to enqueue
4. Call engine API `snapshotBackup`
https://github.com/longhorn/longhorn/issues/2871
https://github.com/longhorn/longhorn/issues/2876

Fix backing image backup creation failed

---

controller/share_manager_controller.go
csi/crypto/crypto.go
csi/crypto/luks.go
csi/node_server.go
csi/server.go
deploy/install/02-components/01-manager.yaml
deploy/longhorn-images.txt
deploy/release-images.txt

Add support for encrypted volumes, this works by retrieving the secret for the PV as part of the share-manager controller, the passphrase is then passed to the share-manager pod as an environment variable. From a security standpoint this isn't great but we currently have no way of securly transmitting that phasphrase, this would require a secure communication channel (grpc) to transmit the information at runtime.
REF: longhorn/longhorn#2867 longhorn/longhorn#1859
This also added new optional params "fs", "mount" to allow specifying a custom filesystem for the share-manager RWO volume. This has been requested in longhorn/longhorn#2814 These are optional and when not specified we use the same behavior as before. The fs/mount options are the ones specified as part of the storage class, since …

2867-rwx-encryption-support

---

controller/backup_controller.go
controller/backup_target_controller.go
controller/backup_volume_controller.go
controller/engine_controller.go
controller/setting_controller.go
controller/uninstall_controller.go
datastore/longhorn.go
engineapi/backups.go
manager/engine.go
types/deepcopy.go
types/resource.go
upgrade/v111to120/upgrade.go

https://github.com/longhorn/longhorn-manager/pull/952#discussion_r686744828: Updates backup creation state to ETCD
https://github.com/longhorn/longhorn-manager/pull/952#discussion_r686749679: Correct log message
https://github.com/longhorn/longhorn-manager/pull/952#discussion_r686754880: Skip the last modification check and directly inspect the backup volume if there is a backup CR creation/deletion.
https://github.com/longhorn/longhorn-manager/blob/master/upgrade/v111to120/upgrade.go#L34-L35: Address TODO, creates BackupTarget CR inside the setting_controller.
https://github.com/longhorn/longhorn/issues/2870: Remove `spec.FileCleanupRequired`, delete Backup CRs then delete BackupVolume CR
https://github.com/longhorn/longhorn/issues/2888: The volume event log is filtered by volume name at …

Backup refactoring enhancement

---

controller/backup_controller.go
controller/backup_volume_controller.go
deploy/install/01-prerequisite/03-crd.yaml
types/resource.go

To differentiate the backup that is ready to be used, add a new state `Ready`.
- `Completed` state means the backup creation is finished but hasn't be synced from the remote backup target.
- `Ready` state means the backup is sync from the remote backup target and ready to be used.
https://github.com/longhorn/longhorn/issues/2912

Add a new backup state ready

---

csi/deployment.go

Reduce the csi side car log level to V(2)
Which is recommended for most systems, since we don't heavily rely on the
logs from the csi sidecars, this should be fine. More information on the
available log levels below.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
longhorn/longhorn#1202

Lower csi sidecar log level

---

controller/backup_target_controller.go

When the backup target URL is unset, it cleans up all the backup volume CRs.
If the user unset the backup target URL, and if the other controller trigger backup_target_controller within the deleted BackupVolume CRs period, the backup_target_controller be trigger twice and there are two processes simultaneously
clean up all the backup volume CRs. It'd cause partially BackupVolume CRs to fail at clean up.
Therefore, we ignore the delete backup volume not found error.
https://github.com/longhorn/longhorn/issues/2913

Ignore delete backup volume error if not found

---

api/backup.go
api/model.go
api/router.go
manager/engine.go

Add WebSocket endpoint `/v1/ws/backupvolumes` and `/v1/ws/backups`.
Haven't found a way to allow passing the volume name as a parameter to filter per-backup volume's backups change. Either by:
- `/v1/ws/backups/{volName}`
- `/v1/ws/backups?volName=<volName>`
- `/v1/ws/backupvolumes/{backupName}`
So, the current behavior for the `backups` WebSocket endpoint is that sending all the Backup CRs to the frontend, and frontend will do filtering according to the field `backups.volumeName` when entering the page `Backup -> a Backup Volume`
This follows the same behavior as the `volume` WebSocket endpoint that also sending all the volume/engine/replica changes to the frontend. We need to improve the WebSocket data traffic sending in the future.
https://github.com/longhorn/longhorn/issues/2740

feat: add WebSocket for Backup page

---

controller/volume_controller.go

Don't attempt to find the IM on a down or deleted node before starting a replica.
Attempting to find the IM on a down or deleted node will always return error and block volume controller sync loop. 
longhorn/longhorn#2848

Fixed bug volume cannot attach after Kubernetes node is deleted

---

controller/kubernetes_pod_controller.go
controller/share_manager_controller.go

This detach/attach is so brittle, we really need to fix the volume controller
we need to wait till the volume is completely detached even though the state
might be detached it might still have a current node id set, which will then
block reattachment forever. Since the volume controller will error out,
when Status.CurrentNodeID != Spec.NodeID.
longhorn/longhorn#2933 longhorn/longhorn#2527

Fix RWX attachment getting stuck on old node (timing issue)

---

controller/backup_controller.go
controller/backup_volume_controller.go
types/resource.go

Previously we introduced the Backup CR `Ready` state, we want to distinguish the difference between the backup creation is completed and the backup is pulled from the remote backup target. And the GUI could check the state is `Ready` or not, and decide the button `Restore` and `Get URL` are clickable/unclickable.
But this introduces a corner case that the backup state might be transit from `Ready` back to `Completed` because we have two actors updating the same `status.state`, one is backup creation routine and the other one is synced from the remote backup target routine. The user might be confused what's the difference between the two states.
After that, we decided to let GUI decide the button `Restore` and `Get URL` are clickable/unclickable by `status.URL` is empty _or_ not. So, we …

Revert the Backup CR Ready state

---

csi/deployment.go
deploy/install/01-prerequisite/06-storageclass.yaml

This allow Kubernetes to properly changes the volume ownership and permissions when user specify `fsGroup` in workload pod
longhorn/longhorn#2964

Explicitly set default fsType to EXT4

---

csi/deployment.go
deploy/install/01-prerequisite/06-storageclass.yaml

This allow Kubernetes to properly changes the volume ownership
and permissions when user specify fsGroup in workload pod
longhorn/longhorn#2964

Backport to v1.2.1: Explicitly set default fsType to EXT4

---

csi/controller_server.go

Running csi-sanity `CreateVolume [It] should fail when the volume source volume is not found` fails at:
```
unexpected error: transport is closing
Expected
<codes.Code>: 14
to equal
<codes.Code>: 5
```
This also crashes all CSI workloads with stacktrace in log.
Result after fix:
```
Ran 1 of 78 Specs in 0.113 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 77 Skipped
```
https://github.com/longhorn/longhorn/issues/2271

Fix sanity test - source volume not found

---

types/resource.go
upgrade/v110to120/upgrade.go

@kaxing has managed to reproduce this on his local machine. The issue could be seen during manager re-try at failed run that is causing the volume spec to get removed before CR creation.
This PR refactors the recurringJob upgrade flow to ensure the recurringJob CRs are created before updating the storageClass and volume CRs.
This also fixed the environment-based inconsistent behavior when creating recurring job CR with null spec.groups.
https://github.com/longhorn/longhorn/issues/2961#issuecomment-909810861

Fix recurringJob CRs not created during upgrade

---

controller/kubernetes_pv_controller.go
controller/kubernetes_pv_controller_test.go
controller/share_manager_controller.go
types/resource.go

We changed the behavior so that we only set lastPodRefAt once there are
no more pods present, previously this was already set when the last pod
went into terminating state.
I added a unit test for both cases, to verify the behavior of tracking in
terminating state and lastPodRefAt setting once there are no more pods
present for that volume.
longhorn/longhorn#2874
Signed-off-by: Joshua Moody <joshua.moody@suse.com>

Track terminating pods

---

controller/kubernetes_pv_controller.go
controller/kubernetes_pv_controller_test.go
controller/share_manager_controller.go
types/resource.go

includes fixes for share-manager controller termination loop.
PR: https://github.com/longhorn/longhorn-manager/pull/1034
ISSUES: longhorn/longhorn#2874 https://github.com/longhorn/longhorn/issues/2960

Backport rwx share-manager termination loop to v1.2.1

---

deploy/install/02-components/01-manager.yaml
deploy/longhorn-images.txt

fixes previously created EXT4 RWX volumes that are now trying to be used as XFS
longhorn/longhorn#2991

Update share-manager images to v1_20210914

---

controller/backup_controller.go
controller/backup_target_controller.go
controller/backup_volume_controller.go
controller/kubernetes_secret_controller.go
controller/setting_controller.go
types/resource.go

Address PR comment https://github.com/longhorn/longhorn-manager/pull/1009#issuecomment-906903691
Change the BackupTarget/BackupVolume/Backup CR from second-level precision to millisecond-level precision.
It fixes if more than two controllers set the `spec.syncRequestedAt` within a short time (within 1 second), the second one would not be handled.

Change to millisecond-level precision

---

controller/backup_controller.go
controller/backup_target_controller.go
controller/backup_volume_controller.go
controller/controller_manager.go
datastore/longhorn.go

If the user configures a valid backup target and the poll interval to 0 during the default engine image is not ready, the backup target `status.available=false` even the default engine image is ready.
Check the backup target available or not shouldn't depend on the poll interval setting (i.e., the `spec.syncRequestedAt` and `status.lastSyncedAt`).
Therefore, change the check of `spec.syncRequestedAt > status.lastSyncedAt` before listing remote backup volumes. (To list remote backup volumes or not depends on the poll interval setting)
https://github.com/longhorn/longhorn/issues/2960

Fix backup target status.available always false

---

controller/backup_controller.go
controller/backup_target_controller.go
controller/backup_volume_controller.go
controller/kubernetes_secret_controller.go
controller/setting_controller.go
types/resource.go

Address PR comment https://github.com/longhorn/longhorn-manager/pull/1009#issuecomment-906903691
Change the BackupTarget/BackupVolume/Backup CR from second-level precision to millisecond-level precision.
It fixes if more than two controllers set the `spec.syncRequestedAt` within a short time (within 1 second), the second one would not be handled.

[Backport-v1.2.x] Change to millisecond-level precision

---

controller/backup_controller.go
controller/backup_target_controller.go
controller/backup_volume_controller.go
controller/controller_manager.go
datastore/longhorn.go

If the user configures a valid backup target and the poll interval to 0 during the default engine image is not ready, the backup target `status.available=false` even the default engine image is ready.
Check the backup target available or not shouldn't depend on the poll interval setting (i.e., the `spec.syncRequestedAt` and `status.lastSyncedAt`).
Therefore, change the check of `spec.syncRequestedAt > status.lastSyncedAt` before listing remote backup volumes. (To list remote backup volumes or not depends on the poll interval setting)
https://github.com/longhorn/longhorn/issues/2960

[Backport-v1.2.x] Fix backup target status.available always false

---

controller/volume_controller.go
controller/volume_controller_test.go
manager/volume.go

longhorn/longhorn#2805
This backport PR includes some commits related to [the PR](https://github.com/longhorn/longhorn-manager/pull/1039) of  longhorn/longhorn#2460. But the concurrent rebuilding limit feature won't be in. These commits are more about the enhancement of failed replica reusage & cleanup: If a newly created replica fails at the 1st rebuilding, which won't contain any data hence there is no need to reuse this kind of replicas.

[Backport][v1.1.3] Fix migration issue and enhance the failed replica reusage & cleanup

---

controller/volume_controller.go
csi/controller_server.go
manager/volume.go
scheduler/replica_scheduler.go

longhorn/longhorn#2962
longhorn/longhorn#2952

[Back-port v1.2.1] Enforce overprovisioning limit when expanding volume size and fix the rounding issue with Storage Over Provisioning Percentage

---

controller/volume_controller.go
csi/controller_server.go
manager/volume.go
scheduler/replica_scheduler.go

longhorn/longhorn#2962
longhorn/longhorn#2952

[Back-port v1.1.3] Enforce overprovisioning limit when expanding volume size and fix the rounding issue with Storage Over Provisioning Percentage

---

.drone.yml

adds fossa analyze and test, the job has a `failure: ignore` as `fossa test` will return a non-zero exit which means we will get data and have to approve/fix everything in the fossa backend and then we can remove that after we get passing fossa tests.

Adding fossa analyze/test

---

upgrade/v102to110/upgrade.go

This is a surgery fix for the original issue, which can not avoid
the old upgrade path intervening longhorn manager pod start.
To resolve this issue, Longhorn needs to somehow understand the
old version and the current version during system upgrade.
Longhorn/longhorn#2582

upgrade: Avoid CR update if there is nothing change

---

csi/node_server.go

After evaluating different options for addressing this issue.
I decided to do a check on the staging path and on failure to do a manual NodeUnstageVolume and NodeStageVolume call as part of the NodePublishVolume call.
The issue is only present for replicasets since they bypass the NodeStage phase depending on UpdateStrategy.
I tested this patch set for:
- RWO/RWX volumes with replica sets / stateful sets
- I tested IM crashes/deletions
- I tested kubelet restarts
This fix does not work for RWO encrypyted volumes, I worked on fixes for the encrypted RWO case.
But it introduces to much risk and issues around the case where a replicaset has multiple pods on the same node so I left them out of this patch set.
longhorn/longhorn#3070

HOTFIX replicaset issues when IM crashes

---

controller/volume_controller.go
controller/volume_controller_test.go

Set the `e.Spec.RequestedBackupRestore` to the correct backup in `v.Spec.FromBackup` for non-DR restoring volume
This fix should fix:
* First time restore from a correct backup
* Retry to restore from a correct backup
longhorn/longhorn#3111

Fixed bug: restoring backup always point to the latest backup

---

controller/replica_controller.go

Fixes `staticcheck S1002` caught by [Sonatype Lift](https://lift.sonatype.com/result/longhorn/longhorn-manager/01FHW2JKTWJ3Z4RA5MMT2A53WS?t=CustomTool%20%22Staticcheck%22%7CS1002).

Remove unnecessary comparisons

---

csi/deployment_util.go

To prevent the csi sidecar containers from running on one host,
apply podAntiAffinity rules to spread the workloads to different
workers.
Longhorn#2894

Apply podAntiAffinity rules to csi sidecar containers

---

types/setting.go

The volume attachment recovery policy is deprecated/removed from LH v1.1.2.
We'll release v1.3.0 in the next coming release, we could consider fully removing the code from the setting.

Remove volume attachment recovery policy from settings

---

api/setting.go
datastore/longhorn.go

If the secret is not found, do not proceed with it.
Also, remove duplicate retry on conflict since it's being handled at
- https://github.com/longhorn/longhorn-manager/blob/dbdea97/api/router.go#L61
- https://github.com/longhorn/longhorn-manager/blob/dbdea97/api/router.go#L47
- https://github.com/longhorn/longhorn-manager/blob/dbdea97/api/router.go#L25-L35
https://github.com/longhorn/longhorn/issues/3261

Fix UI can't set empty backup target credential secret

---

controller/kubernetes_pod_controller.go
controller/kubernetes_pv_controller.go
controller/kubernetes_pv_controller_test.go
controller/share_manager_controller.go
csi/node_server.go
types/resource.go

This contains a bunch of fixes, i kept the same commit naming/content except for the nfs sync mode change.
These are backports for the following issues:
https://github.com/longhorn/longhorn/issues/2874
https://github.com/longhorn/longhorn/issues/2946
https://github.com/longhorn/longhorn/issues/2549
There is also this PR included:
https://github.com/longhorn/longhorn-manager/pull/1010
which is part of this issue: https://github.com/longhorn/longhorn/issues/2933

Backport RWX fixes/improvements to v1.1.3

---

app/recurring_job.go
engineapi/backups.go
engineapi/backups_test.go
engineapi/types.go

- Update the recurring job to check the Backup CR state (`InProgress`/`Completed`/`Error`) instead of checking the engine's backup state (`in_progress`/`complete`/`error`)
- Change the engine CR state to private variable to avoid misuse.
https://github.com/longhorn/longhorn/issues/3309

Check the Backup CR state instead of engine's backup state

---

app/recurring_job.go
engineapi/backups.go
engineapi/backups_test.go
engineapi/types.go

- Update the recurring job to check the Backup CR state (`InProgress`/`Completed`/`Error`) instead of checking the engine's backup state (`in_progress`/`complete`/`error`)
- Change the engine CR state to private variable to avoid misuse.
https://github.com/longhorn/longhorn/issues/3312

[BACKPORT] Check the Backup CR state instead of engine's backup state

---

deploy/install/01-prerequisite/03-crd.yaml
k8s/pkg/apis/longhorn/v1beta1/node.go

There're 2 settings to control the engine/replica CPU request.
One is the global setting, the unit is the percentage(%).
The other one is per node setting, the unit is the milli CPU.
The max limit applies to the global setting only, which means a maximum of 40% of
total CPU per node.
The global setting will be ignored for a node if the node's
engine/replica on the node is set.
https://github.com/longhorn/longhorn/issues/791
This fixes https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/500/testReport/junit/tests/test_settings/test_instance_manager_cpu_reservation/

Remove maximum limitation for engine/replica CPU request

---

types/types.go
upgrade/v1beta1/upgrade.go

Add the label to the upgraded CRs.
The re-run upgrade process only needs to process the non-upgraded CRs.
Longhorn 3354

Handle the failure of the upgrade to v1beta2

---

api/model.go
csi/controller_server.go
csi/deployment.go

1. Specify a timeout for `csi-snapshotter` deployment to be 1:50s as other csi sidecar components
1. Probably we could change to set the [SnapshotName](https://github.com/longhorn/longhorn-manager/blob/da8ab84da751e90f858b69b6f3a77dca1f80fab2/api/model.go#L1292) to `b.Spec.SnapshotName` if `b.Spec.SnapshotName != ""`. Otherwise, set the `SnapshotName` to `b.Status.SnapshotName`. This reduces the waiting time. As long as there is a backup CR, we can safely set the `snapshotHandle` for the `VolumeSnapshotContent`
1. With the new backup design in 1.2.x, having a backup CR doesn't mean that the backup has finished. So we need to check the status of the backup. This code path needs to be updated to be compatible with the new design:
https://github.com/longhorn/longhorn-manager/blob/da8ab84da751 …

Fix potential bugs inside Longhorn CSI related to the CSI snapshot flow

---

controller/backup_controller.go

If we have 2 cluster points to the same backup store.
When cluster 1 makes snapshot backup to the remote backup store and
cluster 2 starts to inspect the backup config from the remote backup, it
will print the error message that the backup is still in progress.
We should skip printing the in-progress backup to the console.
https://github.com/longhorn/longhorn/issues/3405

[BACKPORT-v1.2.x] Do not print error log when backup in progress

---

controller/backup_controller.go

If we have 2 cluster points to the same backup store.
When cluster 1 makes snapshot backup to the remote backup store and
cluster 2 starts to inspect the backup config from the remote backup, it
will print the error message that the backup is still in progress.
We should skip printing the in-progress backup to the console.
https://github.com/longhorn/longhorn/issues/3402

Do not print error log when backup in progress

---

datastore/longhorn.go
deploy/install/01-prerequisite/03-crd.yaml
k8s/pkg/apis/longhorn/v1beta1/backingimage.go
k8s/pkg/apis/longhorn/v1beta1/backingimagedatasource.go
k8s/pkg/apis/longhorn/v1beta1/backingimagemanager.go
k8s/pkg/apis/longhorn/v1beta1/backup.go
k8s/pkg/apis/longhorn/v1beta1/backuptarget.go
k8s/pkg/apis/longhorn/v1beta1/backupvolume.go
k8s/pkg/apis/longhorn/v1beta1/engine.go
k8s/pkg/apis/longhorn/v1beta1/engineimage.go
k8s/pkg/apis/longhorn/v1beta1/instancemanager.go
k8s/pkg/apis/longhorn/v1beta1/node.go
k8s/pkg/apis/longhorn/v1beta1/volume.go
k8s/pkg/apis/longhorn/v1beta2/backingimage.go
k8s/pkg/apis/longhorn/v1beta2/backingimagedatasource.go
k8s/pkg/apis/longhorn/v1beta2/backingimagemanager.go
k8s/pkg/apis/longhorn/v1beta2/backup.go
k8s/pkg/apis/longhorn/v1beta2/backuptarget.go
k8s/pkg/apis/longhorn/v1beta2/backupvolume.go
k8s/pkg/apis/longhorn/v1beta2/engine.go
k8s/pkg/apis/longhorn/v1beta2/engineimage.go
k8s/pkg/apis/longhorn/v1beta2/instancemanager.go
k8s/pkg/apis/longhorn/v1beta2/node.go
k8s/pkg/apis/longhorn/v1beta2/volume.go
types/types.go
upgrade/v1beta1/upgrade.go

- The null fields of CRs Spec are initialized correctly during creation.
- The old null fields of the CRs Spec are fixed up.
- The slices and maps in the CRs Status are set `// +nullable` because some of them are not set while calling Update.
Longhorn 3352

Handle the CRD validation error

---

controller/backing_image_controller.go
controller/backing_image_data_source_controller.go
controller/backing_image_manager_controller.go
controller/engine_controller.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/kubernetes_node_controller.go
controller/kubernetes_pod_controller.go
controller/kubernetes_pv_controller.go
controller/node_controller.go
controller/replica_controller.go
controller/share_manager_controller.go
controller/volume_controller.go

When the object is gone from the cache, and the deletion event has been
missed, the unknown state struct gets pushed as a copy into the worker
instead of as a pointer.
https://github.com/longhorn/longhorn/issues/3417

Fix cache.DeletedFinalStateUnknown value type instead of pointer type

---

controller/uninstall_controller.go

No related issue, just read thru. the code and saw the potential risk to use old apiextension v1beta1 API to access the recurring job CRD in the uninstallation controller.

Use apiextension V1 API to access the recurring job CRD

---

controller/uninstall_controller.go

Delete the BackupTarget CRs once the BackupVolume/Backup CRs be uninstalled succeeded.

[BACKPORT] uninstall: delete the BackupTarget CRs

---

examples/network-policy/webhook-network-policy.yaml

The traffic from/to the longhorn webhook server is the kube-apiserver.
The only way we could add restriction is to add the network policy of
the ingress port because we can't know each Kubernetes distro default
kube-apiserver Pod's label. Therefore, we can't add the label selector
in the network policy rule to restrict the traffic that comes from the
kube-apiserver is able to access to the longhorn webhook server.
https://github.com/longhorn/longhorn/issues/3513

example: add longhorn webhook network policy yaml manifest

---

k8s/pkg/apis/longhorn/v1beta1/backingimage.go
upgrade/v1beta1/upgrade.go

1. CRD conversion failure of backingimages  because of the initialized variable
2. Upgrade failure from v1.1.x or below because of the empty string of volume.Spec.ReplicaAutoBalance
Longhorn 3265

Fix CRD upgrade and conversion failures

---

deploy/install/01-prerequisite/03-crd.yaml
k8s/pkg/apis/longhorn/v1beta2/engine.go
upgrade/v1beta1/upgrade.go
webhook/resources/backingimage/mutator.go
webhook/resources/backingimagedatasource/mutator.go
webhook/resources/backingimagemanager/mutator.go
webhook/resources/backup/mutator.go
webhook/resources/engine/mutator.go
webhook/resources/node/mutator.go
webhook/resources/recurringjob/mutator.go
webhook/resources/volume/mutator.go
webhook/server/mutation.go

- mutating webhook
Replace the invalid values on APIs and other interfaces with valid ones.
- upgrade path
The purpose of fix up functions are fixing the invalid fields in old CRs. The strategy is listing the CRs and then update the them. Before updating, the mutating webhook will check the invalid values and fix them.

Fix CRD validation failure due to the null field(s)

---

webhook/resources/backingimage/mutator.go
webhook/resources/backingimagedatasource/mutator.go

Fix upgrade failure from v1.1.x to master-head.
The sourceType of backingimage and backingimagedatasource in v1.1.x is "", so initialize it in the mutating webhook.

Initialize backingimage and backingimagedatasource sourceType

---

controller/controller_manager.go

Change the resync back to 30s for v1.1.4 and v1.2.4 since there are potentially conner cases that we cannot catch before releasing. Those are stable releases so we don't want to have mistakes. The scalability is still improved significantly even without changing the resync.
longhorn/longhorn#3609

Revert the resync back to 30s

---

deploy/prerequisite/longhorn-iscsi-installation.yaml
deploy/prerequisite/longhorn-nfs-installation.yaml
deploy/scripts/environment_check.sh

Remove unnecessary permission. The `nsenter` only needs permissions
- `hostPID: true`
- `securityContext.privileged: true`
https://github.com/longhorn/longhorn/issues/3549

Remove unnecessary permission

---

controller/backup_controller.go
controller/base_controller.go
controller/replica_controller.go

The resync period of the backingimage is one hour and the maxRetries is
3. Thus, the deletion of the backup in error state caused by the
shutdown of the replica during backing up will fail.
The workaround is to increase the maxRetries number and to retry the
deletion until the lock acquisition of the backup is timeout after 150
seconds.
maxRetriesOnAcquireLockError should guarantee the cumulative retry time
is larger than 150 seconds.
Longhorn 3620

backup: retry deletion after failing to acquire the lock

---

controller/setting_controller.go

This helps users quickly identify why the pods are deleted
longhorn/longhorn#2820

Add logs before deleting managed components' pods

---

controller/setting_controller.go

This helps users quickly identify why the pods are deleted
https://github.com/longhorn/longhorn/issues/3671
longhorn/longhorn#2820

[Backport][v1.2.4] Add logs before deleting managed components' pods

---

deploy/install/01-prerequisite/03-crd.yaml
k8s/generate_code.sh
k8s/patches/crd/webhook_in_backingimage.yaml
k8s/patches/crd/webhook_in_backuptarget.yaml
k8s/patches/crd/webhook_in_engineimage.yaml
k8s/patches/crd/webhook_in_node.yaml
k8s/patches/crd/webhook_in_volume.yaml

Fix upgrade failure because of the wrong conversion strategy in crd.yaml.
The conversion strategy and webhook settings are patched while generating the CRD manifest, and the `caBundle` will be dynamically generated in the conversion webhook.
Longrhorn 3631

Fix upgrade failure because of the wrong conversion strategy 

---

controller/backing_image_controller.go
controller/backing_image_manager_controller.go
controller/engine_controller.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
controller/kubernetes_node_controller.go
controller/kubernetes_pv_controller.go
controller/node_controller.go
controller/replica_controller.go
controller/setting_controller.go
controller/share_manager_controller.go
controller/volume_controller.go

For each controller, we only need to enable resync for the handler
that handles the events of its managed object. For example, the
volume controller only needs to enable resync for volumeInformer
event handler. By doing this, we reduce the workqueue depth of the
controller while still making sure that we resync every object
of the controller every resync period (30s)
longhorn/longhorn#3083

[Backport][v1.1.4] Reducing the workqueue depth while still keeping the resync period as 30s

---

controller/volume_controller.go
scheduler/replica_scheduler.go

We should requeue the volume when failed to schedule or fail
to add new replica. By doing this, the volume controller can
try those operations again. This is a quick fix. Long-term
fix may be separating the replica replenishment and scheduling
logic into a different controller
longhorn/longhorn#3626

Fix: Longhorn doesn't requeue the volume when failed to schedule or fail to add new replica

---

api/node.go
api/recurringjob.go
app/recurring_job.go
datastore/longhorn.go
deploy/install/01-prerequisite/03-crd.yaml
deploy/install/02-components/05-webhook.yaml
k8s/pkg/apis/longhorn/v1beta2/engineimage.go
manager/backingimage.go
manager/engineimage.go
manager/node.go
manager/recurringjob.go
manager/volume.go
webhook/resources/backingimage/mutator.go
webhook/resources/backingimage/validator.go
webhook/resources/engineimage/mutator.go
webhook/resources/engineimage/validator.go
webhook/resources/node/mutator.go
webhook/resources/node/validator.go
webhook/resources/recurringjob/mutator.go
webhook/resources/recurringjob/validator.go
webhook/resources/volume/mutator.go
webhook/resources/volume/validator.go
webhook/server/mutation.go
webhook/server/validation.go

The general mutation and validation logics in HTTP API functions are moved or re-implemented in the admission webhook.
[longhorn #3562](https://github.com/longhorn/longhorn/issues/3562)

Implement mutation and validation logics of resources in the admission webhook

---

controller/backup_controller.go
engineapi/backup_monitor.go
k8s/pkg/apis/longhorn/v1beta1/backup.go
k8s/pkg/apis/longhorn/v1beta2/backup.go
monitoring/backup_collector.go

Mark backup to **Pending** state if the engine SnapshotBackup API call returns RPC error code DeadlineExceeded.
The sync agent replica server _probably_ perform snapshot backup initialization succeeded in the end.
For this case, we create a backup monitor routine to periodically (2 seconds) fetch the backup status to see if the snapshot backup change initialization in the end (state change to InProgress/Completed) or keeps in an Error state. We have a maximum retry period of 10 minutes for the Pending state.
https://github.com/longhorn/longhorn/issues/3545

Mark backup to Pending state if encounter the engine RPC error code DeadlineExceeded

---

deploy/install/01-prerequisite/03-crd.yaml
k8s/pkg/apis/longhorn/v1beta2/node.go
k8s/pkg/apis/longhorn/v1beta2/recurringjob.go
k8s/pkg/apis/longhorn/v1beta2/volume.go
webhook/resources/node/validator.go
webhook/resources/recurringjob/validator.go

Fix the helm upgrade failure on kuberenetes v1.18.
Root cause: https://github.com/kubernetes/kubernetes/issues/87675
[Longhorn 3631](https://github.com/longhorn/longhorn/issues/3631)

Move minimum and maximum CRD schema validation to validating webhook

---

go.mod
go.sum
vendor/github.com/longhorn/backing-image-manager/pkg/client/manager_client.go
vendor/modules.txt

Depends on https://github.com/longhorn/backing-image-manager/pull/48
https://github.com/longhorn/longhorn/issues/3838

Fix BackingImageManager version request leaked grpc connection

---

controller/instance_manager_controller.go
controller/setting_controller.go
datastore/longhorn.go
deploy/install/01-prerequisite/04-default-setting.yaml
types/deploy.go
types/setting.go
types/types.go
util/util.go

https://github.com/longhorn/longhorn/issues/2203

Support Kubernetes cluster-autoscaler

---

.drone.yml

Drone pipelines for `s390x` are failing due to the publish steps are not able to reach **docker dameon** 
https://drone-publish.longhorn.io/longhorn/longhorn-manager/706/3/4
Adding the volume should do the trick.

Fix for not reaching docker daemon on s390x pipeline

---

controller/monitor/node_monitor.go
controller/node_controller.go

Move the new and missing orphaned replica directories checks to node
controller.
Address the discussion https://github.com/longhorn/longhorn-manager/pull/1310#discussion_r861713689
https://github.com/longhorn/longhorn/issues/685

Refactor new and missing orphaned replica directories check

---

controller/volume_controller.go
controller/volume_controller_test.go
k8s/pkg/apis/longhorn/v1beta2/node.go
scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go
types/types.go
util/multierror.go

Currently, the Condition["Schedule"].message is still empty even if there is a scheduling failure. We can update it with a verbose error message which is a combination of the errors, e.g. insufficient storage or insufficient storage, disk not found. Then, the verbose error message is updated to PV annotation.
https://github.com/longhorn/longhorn/issues/3529

Update PV annotation according to volume scheduled condition

---

datastore/longhorn.go

Use the resouce name returned by creation API as the verifyCreation
argument.
[Longhorn 3915](https://github.com/longhorn/longhorn/issues/3915)

Fix verifyCreation input resource name

---

datastore/longhorn.go
webhook/common/common.go
webhook/resources/backingimage/mutator.go
webhook/resources/backingimagemanager/mutator.go
webhook/resources/backup/mutator.go
webhook/resources/backupvolume/mutator.go
webhook/resources/engineimage/mutator.go
webhook/resources/node/mutator.go
webhook/resources/orphan/mutator.go
webhook/resources/sharemanager/mutator.go
webhook/server/mutation.go

CreateXXX, e.g. CreateBackup, adds Longhorn finalizer to new created resource.
To make the behavior consistent between API and Resource operation using CLI, we can move the longhorn finalizer creation logic to the mutating webhook.
[Longhorn 1315](https://github.com/longhorn/longhorn/issues/3918)

Create Longhorn finalizer in the mutating webhook

---

controller/node_controller.go

This bug is found by test_node.py.
Before syncing with the node monitor, don't update the storage data in diskStatus. The cleanup of the old storage data should happen when the updates of ready/scheduled conditions are available.
The incorrect update leads to the wrong StorageMaximum and StorageAvailable until next successful syncWithMonitor.
Longhorn 685

node controller: fix the incorrect update of disk status

---

controller/instance_manager_controller.go

The failure happened due to a missed deffer statement for the client closure of one of the one shot clients.
We plan on refactoring the one shot client mechanisms in the future after the im proxy PR's are merged.
longhorn/longhorn#3922

Fix IM restart failure related to non TLS im client closure

---

webhook/error/error.go
webhook/resources/node/validator.go

Replace werror.NewConflict with werror.NewInvalidError to avoid the API retries because
1. The Conflict error leads to the retry in HandleError (api/router.go). The retry does apiContext.Read again and then trigger EOF error.
2. The maximum node disk synchronization duration is 60 seconds (30 seconds in node controller and 30 seconds in node monitor), while the API's maximum retry number is ten, with each 1 second retry interval. As a result, retries are rarely successful. Furthermore, the retries cause the UI to hang for 10 seconds and does not provide a nice user experience. Therefore, if updating disk/node fails, giving a clear message to users is better.
[Longhorn 3956](https://github.com/longhorn/longhorn/issues/3956)

Do not retry if failed to update node or disk using API

---

app/daemon.go
datastore/longhorn.go
deploy/install/01-prerequisite/03-crd.yaml
deploy/install/01-prerequisite/04-default-setting.yaml
deploy/install/02-components/01-manager.yaml
k8s/pkg/apis/longhorn/v1beta2/setting.go
types/setting.go

Introduce ConfigMap resourceVersion into Setting
Record the resourceVersion of the ConfigMap, longhorn-default-setting,
in the Setting CR if the value is from ConfigMap.
During upgrade or longhorn-manager restart, if the resourceVersion of the
ConfigMap is different than the one in the Setting CR, update the Setting CR
using the latest value in the ConfigMap.
https://github.com/longhorn/longhorn/issues/2570

Fix customize default settings while upgrade/update

---

controller/controller_manager.go
monitoring/client_go_adapter/metrics.go
monitoring/monitoring.go
upgrade/upgrade.go

Items:
1. Fixed throttling issue with the client-go rest client inside Longhorn manager. This is the reason for the long upgrading time from v1.2.3 to v1.2.4 when the cluster have a lot of backups
2. Add metrics for the client-go rest client inside Longhorn manager
longhorn/longhorn#3980
ref: https://github.com/rancher/support-bundle-kit/pull/23

[Backport] [v1.2.5] Fixed throttling issue with the client-go rest client inside Longhorn manager

---

upgrade/v122to123/upgrade.go

longhorn/longhorn#3980
longhorn/longhorn#3996

[Backport] [v1.2.5] Cache the engines and volumes object to speed up the upgrade path from v1.2.2 to v1.2.3

---

deploy/install/01-prerequisite/03-crd.yaml
k8s/pkg/apis/longhorn/v1beta2/snapshot.go

Fix bug  `nullable` field is empty in  snapshots.spec.label

---

controller/volume_controller.go

In the test case https://github.com/longhorn/longhorn/issues/3220#issuecomment-1149558769,
a replica cannot be scheduled to a node, but it's spec.failedAt is set in
https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L1317.
The strict constraints of cleanupFailedToScheduledReplicas() results in that
the failed replica cannot be cleanup up.
[Longhorn 3320](https://github.com/longhorn/longhorn/issues/3220)

Relieve the constraints of cleanupFailedToScheduledReplicas()

---

controller/instance_manager_controller.go

'isUnusedReplicaOnCurrentNode' is always false at outer for loop.
longhorn/longhorn#2673

Wrong flag isUnusedReplicaOnCurrentNode scope.

---

controller/backup_target_controller.go

~Cannot do [this](https://github.com/longhorn/longhorn-manager/pull/1381#issuecomment-1154693709), getting NPE.~
Panic caused by variable binding.
https://github.com/longhorn/longhorn/issues/4110

grpc-proxy: fix NPE

---

datastore/longhorn.go

The validation failure while syncing configmap to setting CRs will lead to that the longhorn-manager cannot start successfully. However, the validation of setting creation and update cannot be skipped, because the logic is in the admission webhook.
We need to ignore the failure happened while syncing the configmap to setting CRs and let the longhorn-manager start. Thus, the PR is filtering the unavailable default settings and only syncing the available ones.
[Longhorn 4160
](https://github.com/longhorn/longhorn/issues/4160)

Avoid validation failure while syncing configmap to setting CRs

---

datastore/kubernetes.go

If Longhorn config the Storage Network, and the  cni is use ovs-cni, in the instance-manager pod there is no ip address for the cni net. in this situation net.IPs is nil, and return net.IPs[0] will make a panic, and the longhorn-manager pod will always in the CrashLoopBackOff state, so if we add a check of the net.IPs will solve the problem.

fix a crush bug

---

controller/setting_controller.go

Update Longhorn client to send appVersion and extra.kubernetesVersioninstead of the deprecated LonghornVersion and KubernetesVersion

---

app/uninstall.go
controller/controller_manager.go
controller/engine_image_controller_test.go
controller/instance_handler_test.go
controller/instance_manager_controller_test.go
controller/kubernetes_pod_controller.go
controller/kubernetes_pv_controller_test.go
controller/node_controller_test.go
controller/volume_controller_test.go
datastore/datastore.go
datastore/kubernetes.go
scheduler/replica_scheduler_test.go

This fix prevents the pod from hitting the backoff period with error
Multi-Attach error. Thus, speeding up the recovery time when a node
is turned off
longhorn/longhorn#4224

[BACKPORT][v1.2.5] Make sure the VolumeAttachment has gone first before force delete the statefulset/deployment  pod

---

controller/kubernetes_pod_controller.go
datastore/datastore.go
datastore/kubernetes.go

This fix prevents the pod from hitting the backoff period with error
Multi-Attach error. Thus, speeding up the recovery time when a node
is turned off
longhorn/longhorn#4225

[BACKPORT][v1.3.1] Make sure the VolumeAttachment has gone first before force delete the statefulset/deployment  pod

---

webhook/resources/node/validator.go

Previously, if the kubernetes node is gone, the node validating webhook did
not allow the modification of the node resource. It hindered the remove of the
finalizers and resulted in the deletion failure of the node resource.
[Longhorn 4213](https://github.com/longhorn/longhorn/issues/4213)

Allow update node resources if kubernetes node is already gone

---

upgrade/upgrade.go
upgrade/v12xto130/upgrade.go

When unexpectedly removed a node during an upgrade from v1.2.x to v1.3.0. There are chances of not reaching replica storage IP assignment. In this case, other controllers will get blocked by the `checkReplica` during the ownership change.
https://github.com/longhorn/longhorn/issues/4213#issuecomment-1184955056

upgrade: autofill replica storage IP

---

controller/volume_controller.go

[BACKPORT][v1.2.x] Set replics.spec.failedAt when a replica failed at attaching stage before engine become running

---

controller/backup_controller.go

Set the backup state `Error` if backup volume was deleted before
the backup finished.
longhorn/longhorn#3122

Backup stays in `InProgress` if volume deleted.

---

datastore/longhorn.go

The cascading deletion of the backing image manager would lead to
the pod being deleted before the file cleanup complete.
In other words, the pod should be deleted manually by the
controller after the file cleanup complete.
Longhorn/longhorn#4308

datasource: Stop using cascading deletion for backing image manager

---

datastore/longhorn.go

https://github.com/longhorn/longhorn/issues/4308
https://github.com/longhorn/longhorn/issues/4344

[Backport][v1.2.x] datasource: Stop using cascading deletion for backing image manager

---

go.mod
go.sum
vendor/modules.txt

Merely keeping package version consistent with other repositories.
https://github.com/longhorn/longhorn/issues/4362

vendor: update go-iscsi-helper

---

controller/volume_controller.go

In this case, there are still other replicas that can be started
so we don't set the volume to faulted here
longhorn/longhorn#4386

Fix don't set volume to faulted if it is attaching the first time and one of the replica failed during attaching process

---

controller/volume_controller.go

In this case, there are still other replicas that can be started
so we don't set the volume to faulted here
longhorn/longhorn#4391

[BACKPORT][1.3.x][BUG] Fix don't set volume to faulted if it is attaching the first time and one of the replica failed during attaching proccess

---

controller/engine_controller.go

Backport to v1.2.x. Just give couple time to retry restoreBackup
only when getting lock failed.
longhorn/longhorn#4428

[BACKPORT][v1.2.x] Retry restoring Backup if getting lock failed.

---

controller/backup_controller.go
controller/backup_volume_controller.go
deploy/install/01-prerequisite/04-default-setting.yaml
types/setting.go

Clean up failed backups when there is a backup in state `Error` or `Unknown`.
longhorn/longhorn#3898
longhorn/longhorn#4334

Failed backups cleanup

---

controller/backup_controller.go
controller/backup_volume_controller.go
deploy/install/01-prerequisite/04-default-setting.yaml
types/setting.go

Clean up failed backups when there is a backup in state `Error` or `Unknown`.
longhorn/longhorn#4456

[Backport][v1.2.x] Failed backups cleanup

---

types/types.go
webhook/resources/backup/mutator.go
webhook/resources/volume/mutator.go

[Issue #3444](https://github.com/longhorn/longhorn/issues/3444)
1. When create backup, save the access mode into backup label
2. When restore backup, if the access mode is empty then use the backup label to create new volume.
1. Create two volumes: ReadWriteOnce (RWO) * 1 + ReadWriteMany (RWX) * 1, and both are attached to one node.
3. Create backups for each volumes.
4. Wait all backups are complete, then delete all volumes.
5. Switch to `Backup' page, and click the backup name and the tags filed. 
6. **CHECK: The `LonghornVolumeAccessMode` of backup labels should be equal as the access mode.**
7. Select all backups and click `Restore Latest Backup` button
8. DON'T fill in any filed and click `OK` button.
9. Switch back to `Volume` page and …

Save the access mode when creating backup, for restoring from the backup

---

scheduler/replica_scheduler.go

Not to schedule unused replicas that marked as failed when the node with engine and instance-manager rebooted.
longhorn/longhorn#4546

Unused replica failed would not be scheduled.

---

scheduler/replica_scheduler.go

Not to schedule unused replicas that marked as failed when the node with engine and instance-manager rebooted.
longhorn/longhorn#4639

[BACKUPORT][v1.3.x] fix(replica-schedule): unused replica failed.

---

scheduler/replica_scheduler.go

Not to schedule unused replicas that marked as failed when the node with engine and instance-manager rebooted.
longhorn/longhorn#4696

[BACKPORT][v1.2.x] fix(replica-schedule): unused replica failed.

---

controller/volume_controller.go

The rebuild loop happens when the data locality is trying to rebuild a new replica, and it got cleaned up by the auto-balance because of the sorted order.
Exchanging the order will let the data locality clean up its own redundant replica first.
https://github.com/longhorn/longhorn/issues/4761

fix(replica-auto-balance): data locality rebuild loop

---

controller/volume_controller.go

In the test case https://github.com/longhorn/longhorn/issues/3220#issuecomment-1149558769, a replica cannot be scheduled to a node, but it's spec.failedAt is set in https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L1317. The strict constraints of cleanupFailedToScheduledReplicas() results in that the failed replica cannot be cleanup up.
https://github.com/longhorn/longhorn/issues/3220
https://github.com/longhorn/longhorn/issues/4732
(cherry picked from commit fedb7eb0303bbc509b995916b3f5460e519c4e2b)

[BACKPORT][v1.2.6] Relieve the constraints of cleanupFailedToScheduledReplicas()

---

controller/volume_controller.go

Set the replica RebuildRetryCount to FailedReplicaMaxRetryCount when the replica is considered as a rebuilding replica and marked as failed.
It would be deleted soon in func `cleanupCorruptedOrStaleReplicas'
longhorn/longhorn#4791
related: longhorn/longhorn#4724

Handle unscheduled failed replica

---

controller/volume_controller.go

Set the replica RebuildRetryCount to FailedReplicaMaxRetryCount when the replica is considered as a rebuilding replica and marked as failed.
It would be deleted in func `cleanupCorruptedOrStaleReplicas`
longhorn/longhorn#4791
longhorn/longhorn#4808

[BACKPORT][v1.3.x]Handle unscheduled failed replica

---

controller/volume_controller.go

Set the replica RebuildRetryCount to FailedReplicaMaxRetryCount when the replica is considered as a rebuilding replica and marked as failed.
It would be deleted in func `cleanupCorruptedOrStaleReplicas`
longhorn/longhorn#4791
longhorn/longhorn#4809

[BACKPORT][v1.2.x] Handle unscheduled failed replica

---

csi/crypto/crypto.go
csi/crypto/luks.go
csi/node_server.go
examples/crypto/secret-crypto-customized-rhel-FIPS-enabled.yaml
examples/crypto/secret-crypto-customized.yaml

Allow customization of the cipher used by cryptsetup in volume encryption.
Now the parameters allowing for customization are `cipher`, `hash`, and `key-size`.
longhorn/longhorn#3353

Allow customization of the cipher

---

controller/node_controller.go

Create the event log for node restart only when `UpdateNodeStatus` without then `conflict` error

fix(node): duplicated event log when node restarted

---

controller/kubernetes_configmap_controller.go
datastore/longhorn.go

[Longhorn 4554](https://github.com/longhorn/longhorn/issues/4554)
Singed-off-by: Ray Chang <ray.chang@suse.com>
1. Customized default settings won't be update if setting and value exist
2. Change the Customized default settings error message to warn instead, because it's not thrown out but just recognized 
3. Disable ConfigMap re-synchronize periodically
Step 1. Install Longhorn, e.g, via Helm
- 1.1 Clone Helm chart to local
- 1.2 Add tolerance value in `values.yaml` like below:
```yaml
defaultSettings:
taintToleration: "kubevirt.io/drain:NoSchedule"
longhornManager:
tolerations:
- key: "kubevirt.io/drain"
operator: "Equal"
value: ""
effect: "NoSchedule"
longhornDriver:
tolerations:
- key: "kubevirt.io/drain"
operator: "Equal"
value: ""
effect: "NoSchedule"
longhornUI:
tolerations:
- key: …
```

fix: Custom default settings and values ​​will not be updated if they exist

---

controller/volume_controller.go

Replicas are waiting for that IMs starts and the volume controller consider IMs are failed and then set replicas failed.
Not to set replicas failed when volume is upgrading.
longhorn/longhorn#4726

old IM-r Pods are not deleted

---

controller/node_controller.go

Create the event log for node restated only when `UpdateNodeStatus` without then `conflict` error
longhorn/longhorn#4867

[BACKPORT][v1.3.3] duplicated event log when node restarted

---

controller/node_controller.go

Create the event log for node restated only when `UpdateNodeStatus` without then `conflict` error
longhorn/longhorn#4869

[BACKPORT][v1.2.7] duplicated event log when node restarted

---

controller/volume_controller.go

Replicas are waiting for that IMs starts and the volume controller consider IMs are failed and then set replicas failed.
Not to check replicas launchable when IM-r is not running during volume is upgrading.
longhorn/longhorn#4726
longhorn/longhorn#4728

[BACKPORT][v1.3.3] old IM-r Pods are not deleted

---

controller/backing_image_manager_controller.go
controller/engine_image_controller.go
controller/instance_manager_controller.go
engineapi/backing_image_manager.go
engineapi/instance_manager.go
engineapi/types.go

CurrentInstanceManagerProxyAPIVersion and its check function are unused for now.
Remove it for avoiding the confusion.
https://github.com/longhorn/longhorn/issues/4210
https://github.com/longhorn/longhorn/issues/3198

Remove unused InstanceManagerProxyAPIVersion

---

controller/engine_controller.go

Check that backup exists before restoring the volume.
And set restoring volume failed.
And unify the log messages for controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/1867
https://github.com/longhorn/longhorn/issues/4927

[BACKPORT][v1.3.3] Restoring volume stuck if backup deleted 

---

api/backup.go

[Longhorn 4107](https://github.com/longhorn/longhorn/issues/4107)
If the backup not exists but performing backup deletion, then it will return error.  In the [Longhorn 4107](https://github.com/longhorn/longhorn/issues/4107) scenario, the `volumesnapshot` cannot be deleted normally.  
Test result
- the `volumesnapshot` can be delete normally even if the backup was removed first

fix: Check if backup exists before performing backup deletion

---

controller/backing_image_data_source_controller.go

[Longhorn 4865](https://github.com/longhorn/longhorn/issues/4865)
- When the `backingImageDataSource` POD fails to respond, the monitor thread in the LH manager will consider the `backingImageDataSource` pod as invalid. Then it tries to stop and close its own channel but it has already been closed. So check to see if the channel is closed before closing it to avoid panic.
- Self test results:
- After monitoring is stopped due to failure to connect to the data source POD, the next round of monitoring will continue.

fix: Check if the channel has been closed before closing

---

controller/kubernetes_pod_controller.go
types/setting.go

[Longhorn 5017](https://github.com/longhorn/longhorn/issues/5017)

Disable `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly` for RWX volumes

---

controller/system_restore_controller_test.go
controller/system_rollout_controller.go
controller/system_rollout_controller_test.go

Before https://github.com/longhorn/longhorn/issues/5030, to make things a bit flexible for users in `v1.4.0`, propose to ignore some settings at rollout:
- concurrent-volume-backup-restore-per-node-limit
- concurrent-replica-rebuild-per-node-limit
Longhorn will restore based on those limits. And the potential risk is, if the user originally disabled the above settings, then Longhorn will not rebuild/restore.
https://github.com/longhorn/longhorn/issues/1455

feat(system-backup/restore): ignore adjustable settings

---

controller/node_controller.go
types/types.go

Prevent creating multiple default instance managers by hashing (node name + image name) to create instance manager name
longhorn/longhorn#3000

Prevent creating multiple default instance managers on same node

---

controller/node_controller.go
types/types.go

Prevent creating multiple default instance managers by hashing (node name + image name) to create instance manager name
https://github.com/longhorn/longhorn/issues/5027

[BACKPORT][v1.3.3] Prevent creating multiple default instance managers

---

controller/node_controller.go
types/types.go

Prevent creating multiple default instance managers by hashing (node name + image name) to create instance manager name
https://github.com/longhorn/longhorn/issues/5039

[BACKPORT][v1.2.7] Prevent creating multiple default instance managers

---

manager/volume.go
util/util.go

Users need to enable flag `discards` for the encrypted devices manually first:
https://wiki.archlinux.org/title/Dm-crypt/Specialties#Discard/TRIM_support_for_solid_state_drives_(SSD)
Longhorn/longhorn#836

Allow trimming encrypted devices via UI

---

controller/volume_controller.go

https://github.com/longhorn/longhorn/issues/1674
Fix the [node deletion - volume attached to down node, so the expansion stuck](https://github.com/longhorn/longhorn/issues/1674#issuecomment-1367068900)

Fix expanding volume detachment failure when node is gone

---

controller/engine_controller.go
engineapi/types.go

https://github.com/longhorn/longhorn/issues/5218

Skip updating the trim related field for old engines or engines in old engine instance managers

---

api/router.go

Keep the http request body and copy to the request body again when the retry occurred.
Handling in HandleError function is not correct when the request body was already read before, and the next retry always hit the EOF error.
longhorn/longhorn#5259

fix: incorrect router retry mechanism

---

controller/volume_controller.go
manager/volume.go

[Longhorn 5292](https://github.com/longhorn/longhorn/issues/5292)
- the explanation for the fix 
- When activate the DR volume, it will trigger to synchronize the backup volume and backups. Then trigger the replicas of engine to restore from the latest backup.
- test steps
1. with 2 clusters w/ same backup target: cluster_a & cluster_b
2. deploy a volume w/ 5G data in cluster_a
3. create a backup for the volume in cluster_a
4. create a DR volume from the backup volume in cluster_b
5. extend `Backupstore Poll Interval` setting value, e.g., 1000 in cluster_b
6. write more data into the volume in cluster_a
7. activate the DR volume in cluster_b
8. show `restoring with latest backup in progress` if it is restoring w/ last backup
9. check the …

fix(restore): sync backup target when activate DR volume

---

controller/engine_controller.go
controller/volume_controller.go
datastore/longhorn.go
k8s/pkg/apis/longhorn/v1beta2/replica.go
scheduler/replica_scheduler.go

Do not count the RebuildRetryCount if rebuilding reused replicas failed caused by network disconnection or node down.
Need to collect more failed reasons of rebuilding replicas.
longhorn/longhorn#1923

feat(replica): RebuildRetryCount for disconnection

---

controller/instance_manager_controller_test.go

test(instance-manager-controller): missing error handling

---

controller/volume_controller.go
controller/volume_controller_test.go

Whenever the engine isn't attached, if the node goes down, the replica can be marked as failed. In the attached mode, we can determine whether the replica can fail by relying on the data plane's connectivity status.
Longhorn/longhorn#5464
Longhorn/longhorn#5477

Fail replica if volume is not attached and node is down

---

controller/volume_controller.go

Longhorn/longhorn#5464
Longhorn/longhorn#5477

Add log message for failing replica when the node is down and volume is at non-attached state

---

controller/backing_image_controller.go
controller/backing_image_data_source_controller.go
controller/backing_image_manager_controller.go
k8s/pkg/apis/longhorn/v1beta1/backingimage.go
k8s/pkg/apis/longhorn/v1beta2/backingimage.go

[longhorn/longhorn#3682](https://github.com/longhorn/longhorn/issues/3682)
Depends on: backing-image-manager [PR#101](https://github.com/longhorn/backing-image-manager/pull/101)
Implementation
- Add remove data source tmp file in `Delete api` in backing-image-manager
- Introduce a new state for BackingImageDataSource: `FailedAndCleanUp`
For Case: data source Pod is deleted in the progress
- invoke `Delete` when BackingImageManager Controller finds that
- BackingImageDataSource CurrentState is failed and Transferred is false ([ref](https://github.com/longhorn/longhorn-manager/blob/master/controller/backing_image_manager_controller.go#L678))
- then change the BackingImageDataSource state to `FailedAndCleanUp`
For Case: BackingImage CR is deleted in the progress
In BackingImageController
- …

feat: introduce failed-and-cleanup state to backingimage to handle data source tmp files

---

app/recurring_job.go
datastore/longhorn.go
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/recurringjob.go

Create an event to inform the users if it failed to clean up old snapshots.
~Add a new filed `DeleteSnapshotMode`, default is `create-first`, 
to force the recurring job to delete old snapshots before creating a new snapshot.~
Forcibly do deletion first when the snapshot count exceeds retain count.
Introduce a new recurring job type `snapshot-force-create` to take a new snapshot forcibly when cleaning up old snapshots failed and a new recurring job type `backup-force-create` to to take a new snapshot and do the backup forcibly when cleaning up old snapshots failed.
longhorn/longhorn#4898
Regression test: 
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3223/

fix(recurring job): add an eventRecorder and a new job type

---

controller/volume_controller.go

I am worrying about this case:
1. volume.Spec.EngineImage change to new one (EI-2) -> upgrading process start
1. [Longhorn create new migrating replicas and set them to inactive](https://github.com/longhorn/longhorn-manager/blob/0fad975f5ec4d4ccc98ecab7a9b8c5e176e520f4/controller/volume_controller.go#L2534)
1. Assume that all inactive replicas failed for some reason
[Volume controller set deletion timestamp for them](https://github.com/longhorn/longhorn-manager/blob/0fad975f5ec4d4ccc98ecab7a9b8c5e176e520f4/controller/volume_controller.go#L860-L867)
1. Then Volume controller [active these replicas](https://github.com/longhorn/longhorn-manager/blob/0fad975f5ec4d4ccc98ecab7a9b8c5e176e520f4/controller/volume_controller.go#L2581)
1. Replica controller delete all the replica folders [because …

Only active replica if it doesn't have deletion timestamp

---

client/common.go
controller/setting_controller.go
controller/support_bundle_controller_test.go
controller/system_rollout_controller.go
util/http.go
webhook/conversion/conversion.go

[The `io/ioutil` package is deprecated from Go 1.16](https://pkg.go.dev/io/ioutil#:~:text=Deprecated%3A%20As%20of%20Go%201.16%2C%20the%20same%20functionality%20is%20now%20provided%20by%20package%20io%20or%20package%20os).

chore: the io/ioutil package is deprecated from Go 1.16

---

controller/engine_controller.go
controller/volume_controller.go
engineapi/instance_manager.go
scheduler/replica_scheduler.go

1. During the live engine upgrade, if the volume becomes degraded before the engine.Spec.EngineImage is set to new engine image, Longhorn doesn't try to rebuild the volume. Volume never becomes healthy which block the engine live upgrade process
2. Due to ETCD update conflict, sometime the UpgradeEngineProcess() is called multiple times. However, if the first call already succeeded, the subsequent calls will always fail. We shouldn't call the function UpgradeEngineProcess() if the existing process already has the newer engine image
More details are at https://github.com/longhorn/longhorn/issues/5684#issuecomment-1496777410
longhorn/longhorn#5684

Fix bug: volume is stuck in live engine upgrading

---

webhook/resources/volume/mutator.go

The upgrade path can patch the values and directly update to the API server. However, vefore the volume lister is updated, volume.spec will be upated with outdated values. To mitigate the issue, we need to patch the empty values in the update as well.
Longhorn/longhorn#5485

volume mutator: update restoreVolumeRecurringJob and snapshotDataIntegrity

---

controller/support_bundle_controller.go
types/setting.go
types/types_test.go

https://github.com/longhorn/longhorn/issues/5614

fix(support-bundle): agent doesn't respect node-selector and taint-toleration

---

csi/deployment.go

[longhorn/longhorn#5672](https://github.com/longhorn/longhorn/issues/5672)
We can't move to these versions of external-provisioner and external-snapshotter in Longhorn < v1.5, as they no longer support the v1beta1 VolumeSnapshot API. We deprecated its use in Longhorn v1.4 (https://github.com/longhorn/longhorn/blob/master/CHANGELOG/CHANGELOG-1.4.0.md#deprecation--incompatibilities). I will create separate PRs to bump sidecar versions in the v1.4.x and v1.3.x branches without these components.
EDIT: This comment was previously (incorrectly) missing the "<" sign.

Bump CSI sidecars v1.5

---

types/setting.go

longhorn/longhorn#5585
longhorn/longhorn#5768

[v1.3.3] Mark the setting allow-node-drain-with-last-healthy-replica as deprecated

---

types/setting.go

[v1.4.2] Mark the setting allow-node-drain-with-last-healthy-replica as deprecated

---

controller/volume_controller.go
datastore/longhorn.go

Exclude empty node ID when checking engine image readiness

---

csi/deployment.go
csi/deployment_util.go

Update daemonset images as deployment images when deploying CSI drivers and plugins.
Ref: longhorn/longhorn#4519

fix(csi): update daemonset images

---

manager/volume.go
webhook/resources/volume/validator.go

Check if new volume size is smaller than old one and PVC size is expanded in the validator before expanding the volume.
Expansion is not allowed if storage class does not exist
Ref: longhorn/longhorn#5513

fix(expand): shrink volume is not allowed.

---

controller/volume_controller.go
datastore/longhorn.go

[Longhorn 5542](https://github.com/longhorn/longhorn/issues/5542)
In `ReconcileVolumeState()`, check if the node where the replica is located is deleted, and if so, directly mark the replica as failed.
Below are the test results:
- Having a volume with one replica, then delete the VM that volume attached
- Both the Volume and replica become `Faulted`
- Having a volume with two replicas
- delete the VM that volume attached
- The volume becomes `unknown` and the copy becomes `failed`. The volume is then reattached to another schedulable node and the failed replica is removed, and the volume returns to a `healthy` state.
- delete the VM that volume doesn't attached
- The volume becomes `Degraded` and the replica becomes `Failed`. After delete the …

feat: marked replica failed if the node is deleted

---

app/pre_uppgrade.go
upgrade/upgrade.go
upgrade/util/util.go
upgrade/util/util_test.go

Only allow upgrading from previous minor version. ex. v1.4.x to v1.5.0
Now it returns error only when new apps/pods are created by kubernetes for upgrading and old pods will be killed.
User could only apply the old manifest to roll back the longhorn system.
longhorn/longhorn#5131

feat: enforce the upgrade path

---

controller/controller_test.go
controller/engine_controller.go
controller/instance_manager_controller.go
controller/instance_manager_controller_test.go

https://github.com/longhorn/longhorn/issues/5867
This is the backport to https://github.com/longhorn/longhorn-manager/pull/1887. Those commits could not be directly backported because of changes to instance manager in Longhorn v1.5.x.
Integration tested against v1.4.2-rc1 (w/ modified longhorn-manager) using v1.4.x-head tests. All test cases passed.

Eliminate race between replica and instance manager controllers follow-up (backport #1887)

---

main.go

Add `pre-upgrade` command in main.go
Ref: longhorn/longhorn#5131, longhorn/longhorn#5862

fix(upgrade): missing command `pre-upgrade`

---

controller/backup_volume_controller.go
controller/volume_controller.go

ref: [longhorn/longhorn#5506](https://github.com/longhorn/longhorn/issues/5506)
There is a timing issue
- when user click Delete all Backups right before volume is attached and start restoration, the condition of volume restore is still false, and the BackupVolume can be deleted. In this case, we should block the situation by checking engine status instead, because its `isRestoring` will be **true** at the moment
- But if we only check engine status, then when engine restore progress 100%, it then turns into `isRestoring=False`. But the volume condition restore will still be true until it is **autodetached**. We should wait until condition `restore=False` then we can delete BackupVolume

fix(backupvolume): Ignore BackupVolume not found error in autodetachment

---

csi/controller_server.go

ref: [longhorn/longhorn#5005](https://github.com/longhorn/longhorn/issues/5005)
Volume will be auto-attached for exporting the BackingImage

fix(csi): no need to check if volume is attached when creating backing image type snapshot

---

controller/volume_controller.go

Counting the all healthy replicas and activated the DR volume if healthy replicas count is equal to or bigger than the number of default replica of the volume or all replicas scheduled are healthy
Ref: longhorn/longhorn#3069

fix(dr-volume): activating volume failed

---

app/daemon.go
controller/backing_image_controller.go
controller/backing_image_data_source_controller.go
controller/backing_image_manager_controller.go
controller/controller_manager.go
controller/controller_test.go
controller/volume_controller.go
controller/volume_controller_test.go
datastore/longhorn.go
manager/backingimage.go
types/setting.go

Remove the global default image settings during upgrade to v1.5.0 including `default-instance-manager-image`, `default-share-manager-image` and `default-backing-image-manager-image`.
Ref: longhorn/longhorn#5028
Regression Test:
- RWX: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3873
- Backing image: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3872
- Full run: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3875

fix: remove default image settings

---

controller/engine_controller.go
controller/volume_attachment_controller.go
controller/volume_controller.go

New created engine for migration will have empty snapshot list in `Status`, and running `syncSnapshotCRs` will delete all snapshot CRs of this volume before engine monitor synchronize the snapshots into `Status.Snapshots`.
Ref: longhorn/longhorn#5992

fix(snapshot): live migration deletes snapshots

---

api/model.go
api/volume.go
client/generated_detach_input.go
controller/backing_image_controller.go
controller/backing_image_data_source_controller.go
controller/backup_controller.go
controller/snapshot_controller.go
controller/utils.go
controller/volume_attachment_controller.go
controller/volume_clone_controller.go
controller/volume_controller.go
controller/volume_eviction_controller.go
controller/volume_expansion_controller.go
controller/volume_restore_controller.go
csi/controller_server.go
k8s/pkg/apis/longhorn/v1beta2/backingimagedatasource.go
manager/snapshot.go
manager/volume.go
types/types.go
upgrade/util/util.go
upgrade/v14xto150/upgrade.go
webhook/resources/backingimage/validator.go
webhook/resources/snapshot/validator.go

[PART-2] Attachment/Detachment Controller and Volume Controller Refactoring

---

controller/share_manager_controller.go
controller/volume_attachment_controller.go

- Do not detach attached RWX volumes while upgrading Longhorn system 
- RWX volume is not required if there is no active workload using it
longhorn/longhorn#6120

Fix unexpected attachment and detachment behaviors of RWX volumes

---

controller/share_manager_controller.go

The check is unnecessary, and upgrader ticker is enough. When detaching a volume, the upgrader ticker is deleted.
Longhorn/longhorn#6120

rwx: remove redundant `hasActiveWorkload` check

---

controller/backing_image_data_source_controller.go
controller/backing_image_manager_controller.go

longhorn/longhorn#6108
See https://github.com/longhorn/longhorn/issues/6108#issuecomment-1593527996 for analysis. Even though it doesn't need privileged for any other reason (currently), backing-image-manager still needs privileged for SELinux.
Need https://github.com/longhorn/longhorn-tests/pull/1426 to test on Jenkins.
This is currently not working as expected (tests are FAILED, instead of ERROR). I will have to return to it tomorrow.

Run backing-image-manager pod as privileged

---

controller/backup_controller.go

ref: [longhorn/longhorn#6124](https://github.com/longhorn/longhorn/issues/6124)
Detach the volume only when the status and the backup is synced

[WIP e2e test] fix(backup): detach the volume when the status is synced

---

constant/events.go
controller/volume_controller.go
manager/volume.go

Reattach volume if
- volume is detached unexpectedly and there are still healthy replicas
- engine dead unexpectedly and there are still healthy replicas when the volume is not attached
Longhorn/longhorn#6155

Try to reattach volume if volume is detached or engine is dead unexpectedly

---

controller/engine_controller.go
controller/volume_controller.go

longhorn/longhorn#6217
There are two fixes here. I will test each independently to confirm it fixes the issue, but would like to see both merged:
1. Don't delete rebuilding replicas until the engine is stopped when a volume detaches. This completely eliminates the recreate and avoids any awkward fail outs during engine reconciliation.
2. Check if an engine's `spec.desireState = stopped` before proceeding from snapshot purge to rebuild. This is kind of awkward, but it provides broader protection. There may be a way to trigger the issue different from the existing recreate, and this should help there.

6217 engine rebuilds deleted replica

---

csi/node_server.go
csi/util.go

Volume detached because only one replica failed and not remount the `globalmount`. We need to handle it at NodePublishVolume because os.ReadDir will be passed when it becomes a read-only file system after an unexpected volume detaching.
Ref: longhorn/longhorn#4814, longhorn/longhorn#5801
Test case test:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4403/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4425/

fix(csi): Invalid mount point with volume detached

---

webhook/resources/orphan/validator.go

Remove orphapn UPDATE validation

---

manager/volume.go

The symptom is similar to https://github.com/longhorn/longhorn/issues/6215#issuecomment-1612222566. But this one is at API level instead of inside the AD controller
longhorn/longhorn#6238

Fix migration stuck due to snapshot chains in old engine and new engine mismatch

---

controller/volume_controller.go
types/setting.go

https://github.com/longhorn/longhorn/issues/6257

fix(recurring-job): flooded source label log

---

controller/volume_controller.go
types/types.go

For a volume being restored, the spec.nodeID is empyty but the status.ownerID is set. Thus, set r.Spec.HardNodeAffinity to volume.status.ownerID instead.
Longhorn/longhorn#6239

Fix strict-local volume restore stuck in attaching state

---

api/router.go

ref: [longhorn/longhorn#6266](https://github.com/longhorn/longhorn/issues/6266)

fix(server): return 404 if get backing image and backup not found

---

controller/snapshot_controller.go

Fix bug: if the snapshot is no longer in engine CR, don't block the removal process

---

controller/volume_attachment_controller_test.go
controller/volume_controller_test.go

Implement/fix the unit tests of Volume Attachment and volume controller

---

datastore/longhorn.go
webhook/common/common.go
webhook/resources/backingimage/mutator.go
webhook/resources/backingimagedatasource/mutator.go
webhook/resources/backingimagemanager/mutator.go
webhook/resources/backup/mutator.go
webhook/resources/backupvolume/mutator.go
webhook/resources/engine/mutator.go
webhook/resources/engineimage/mutator.go
webhook/resources/node/mutator.go
webhook/resources/orphan/mutator.go
webhook/resources/recurringjob/mutator.go
webhook/resources/replica/mutator.go
webhook/resources/sharemanager/mutator.go
webhook/resources/snapshot/mutator.go
webhook/resources/supportbundle/mutator.go
webhook/resources/systembackup/mutator.go
webhook/resources/volume/mutator.go
webhook/resources/volumeattachment/mutator.go

longhorn/longhorn#4872
This work was started in https://github.com/longhorn/longhorn-manager/pull/1535. In that PR, we ensured that the webhook only added the finalizer during CREATE operations and not during UPDATE operations to avoid resources that cannot be deleted (e.g. we attempt to remove a resource's finalizer, but the finalizer is added back when we do so). After reading some discussion on the internet and thinking on it a bit, I decided a better approach would be for the webhook to always add the finalizer on both CREATE and UPDATE except when the deletion timestamp is set. After reviewing our code, every time longhorn-manager removes the finalizer, the deletion timestamp has already been set on an object. This approach has two benefits:
- The finalizer cannot be accidentally …

Add finalizer with webhook instead of controllers

---

controller/backup_controller.go

When starting a backup monitor, it will start to take a snapshot backup procedure and it will be failed if the s3 backup target is invalid (nfs backup target will be not be failed because of timeout and test the backup when it is in progress.)
Set the backup state as `Error` if starting the backup procedure returns an error.
Ref: longhorn/longhorn#1249

fix(backup): set backup error if backup target invalid

---

app/recurring_job.go

Recurring job pod status should be failed (error) if it creates and starts a backup or snapshot failed.
Recurring job will start a new pod to start a new backup because setting  RestartPolicy `onFailure`.
Ref: longhorn/longhorn#4255

fix(recurring-job): failed with backup failed

---

controller/engine_controller.go
engineapi/engine.go
engineapi/enginesim.go
engineapi/proxy_replica.go
engineapi/types.go

longhorn/longhorn#6522
I added the replicaName argument to instance-manager's ReplicaRebuildVerify client method (and the associated gRPC request) as a part of longhorn/longhorn#5845, but I did not create a way for longhorn-manager to provide it. This PR fixes the issue and allows the tests mentioned in longhorn/longhorn#6522 to pass.

Add replicaName argument to ReplicaRebuildVerify

---

datastore/datastore.go
datastore/kubernetes.go
datastore/longhorn.go

As Longhorn has expanded with additional Custom Resource Definitions (CRDs), the use of abbreviations may lose its clarity. Therefore, this PR proposes substituting the resource lister and informer abbreviations with their full names to improve readability.

refactor: replace resource lister and informer abbreviations

---

controller/volume_controller.go
datastore/longhorn.go

Only switch the new engine to active if we finish cleaning up the extra engines
longhorn/longhorn#6642

Fix bug two active engine when volume migrating

---

controller/volume_controller.go

This is inspired by https://github.com/longhorn/longhorn/issues/6688.
Currently, we haven't figured out the root cause of the issue yet, and the volume spec fields are correct. 
However, we can adopt a defensive way when checking the spec fields.
Longhorn/longhorn#6688

offline rebuilding: check spc.backendStoreDriver using a defensive way

---

datastore/uncached.go
webhook/resources/engine/validator.go

longhorn/longhorn#6682
I have tested this PR and it accomplishes its objective in the "normal" case. However, I think it may be just as susceptible to corner cases as the volume controller is without it. If the webhook's engine cache is out-of-date when it is listing engines (e.g. if one volume controller or two volume controllers decided to create duplicate engines nearly simultaneously), it will still allow the creation of duplicates. I'll discuss this further in the linked issue.

Refuse to create a duplicate engine

---

controller/volume_controller.go
types/types.go
types/types_test.go

* If there is no engine exists yet, the name of the new engine will be `<VolumeName>-e-0`
* if there is existing engine, increase the engine suffix by one for the new engine
By doing this, we don't create extra new engines even if the volume controller run multiple sync loops with stale cache data
longhorn/longhorn#6682

Make the new engine name deterministic based on the existing engine

---

controller/volume_controller.go
types/types.go
types/types_test.go

This is a backport of the pull request https://github.com/longhorn/longhorn-manager/pull/2180

[Backport-v1.4.4] Make the new engine name deterministic based on the existing engine (backport #2180)

---

controller/backup_controller.go

ref: [longhorn/longhorn#6699](https://github.com/longhorn/longhorn/issues/6699)
need to ensure engine status and desired statue are the same before taking backup

fix(backup): ensure volume attached before taking backup

---

controller/engine_controller.go

DR volume will fail to start an incremental restoration in target cluster, when the source cluster is deleting the eliminated backup by deleting lock in the backup store.
We handle the full restoration at the issue longhorn/longhorn#3055 and now add a regular expression pattern to handle similar failed message to have a backoff mechanism to retry the full/incremental restoration.
Ref: longhorn/longhorn#6750

fix(restore): dr volume failed by delete lock

---

controller/kubernetes_pod_controller.go
types/setting.go

Revert "Disable Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly for RWX volumes"

---

controller/snapshot_controller.go
datastore/uncached.go
upgrade/util/util.go
upgrade/v15xto160/upgrade.go

longhorn/longhorn#6652
Given the possibility of the scenario @PhanLe1010 suggested and the related comments from @innobead in a previous PR (https://github.com/longhorn/longhorn-manager/pull/2147#discussion_r1329341605), it seems a simpler approach is simply to do an uncached GET of a snapshot before creating an attachment ticket while the snapshot is deleting. If the snapshot no longer exists, the GET fails, and we don't proceed to create the attachment ticket. This eliminates the need for the extra annotations that PR introduced, is less susceptible to logical errors, and still prevents us from creating an attachment ticket on the last reconcile of a cached snapshot (after the garbage collector has already delete it).
In order to avoid unnecessarily hammering the API server, we only do …

Prevent orphan snapshot attachment tickets

---

app/daemon.go
datastore/kubernetes.go
types/types.go
upgrade/upgrade.go
upgrade/util/util.go

Fix the issue that both old and new Longhorn managers are running at the same time causing the problem for the upgrade logic
longhorn/longhorn#6294

Waiting for old Longhorn manager to be fully removed before starting upgrade path

---

controller/volume_controller.go

Clean up e.spec.upgradedReplicaAddressMap when live upgrade is no longer needed

---

controller/uninstall_controller.go
csi/deployment.go
csi/deployment_util.go
upgrade/v15xto160/upgrade.go

longhorn/longhorn#6581
We used to deploy the CSI components in StatefulSets, which require a service (even though in our case the service was nonfunctional). Since we are now using Deployments, do not deploy dummy services and clean up the dummy services that exist.
I thought about handling the cleanup of erroneous services in the driver deployer instead, but it's cleaner to remove all references from csi package in this PR and delete the services one time while walking the upgrade path.
There are some reports of these services not cleaning up nicely during driver upgrades in the issues linked to longhorn/longhorn#6581. Since the services are completely nonfunctional, I wrote the upgrade path to do a best effort background deletion. In the worst case, a dummy service will just stick …

6581 remove dummy services

---

app/system_rollout.go
app/uninstall.go
controller/engine_image_controller_test.go
controller/instance_handler_test.go
controller/instance_manager_controller_test.go
controller/kubernetes_pv_controller_test.go
controller/node_controller_test.go
controller/support_bundle_controller_test.go
controller/system_backup_controller_test.go
controller/system_restore_controller_test.go
controller/system_rollout_controller_test.go
controller/volume_attachment_controller_test.go
controller/volume_controller_test.go
datastore/datastore.go
scheduler/replica_scheduler_test.go
util/client/client.go

When a Kubernetes cluster contains numerous secrets, configmaps, and other Kubernetes resources, the synchronization of the cache can lead to longhorn-manager pod's high memory consumption. This ticket focuses on optimizing the resource cache to prevent high memory usage caused by the cache synchronization. For instance, secret is used for the backup target and share manager, so caching all secrets doesn't make sense. We need to avoid caching them.
Longhorn/longhorn#6954

Filter Kubernetes resources by longhorn-system namespace

---

go.mod
go.sum
vendor/github.com/longhorn/backupstore/backupstore.go
vendor/github.com/longhorn/backupstore/deltablock.go
vendor/github.com/longhorn/backupstore/util/util.go
vendor/modules.txt

https://github.com/longhorn/longhorn/issues/6608
Accept NFS mount options as a query appended to the backup target URL.
This PR is a placeholder for the vendor update to be done after backupstore is merged.

Update vendor files for backupstore.

---

datastore/kubernetes.go
types/setting.go

https://github.com/longhorn/longhorn/issues/6953

fix(storage-network): incompatible with Multus version above 4.0.0

---

controller/setting_controller.go
controller/utils.go
datastore/longhorn.go
types/types.go

https://github.com/longhorn/longhorn/issues/6812
Removes all the "level=error" logging from longhorn-manager, but leaves the one kubernetes-layer log.  The only thing logged every hour will be 
```
[longhorn-manager-rjzn8] E1017 21:53:38.219480       1 setting_controller.go:205] failed to sync setting for longhorn-system/v2-data-engine: Current state prevents this: cannot apply v2-data-engine setting to Longhorn workloads when there are attached volumes
[longhorn-manager-rjzn8] E1017 21:53:38.219766       1 setting_controller.go:205] failed to sync setting for longhorn-system/storage-network: Current state prevents this: failed to apply storage-network setting to Longhorn workloads when there are attached volumes
```

Suppress nagging error logging.

---

datastore/longhorn.go
types/setting.go
types/types.go
upgrade/util/util.go
webhook/resources/setting/validator.go

Add an annotation to mark that the updating is from Longhorn and it should be able to update successfully even if setting definition is set to be read-only.
Ref: longhorn/longhorn#5989

fix(setting): put settings' ReadOnly into effect

---

controller/kubernetes_secret_controller.go
controller/setting_controller.go
datastore/kubernetes.go

AWS IAM Role Annotation will not be added to longhorn-manager pods if the secret is created first and then set the `backup-target` and `backup-target-credential-secret`.
Ref: longhorn/longhorn#6947

fix(backup): AWS IAM Role Annotation

---

datastore/longhorn.go
upgrade/util/util.go

Checking the annotation of the `Settings` object is not nil before adding a new annotation for a Setting object.
Ref: longhorn/longhorn#6987, longhorn/longhorn#6947

fix(setting): checking setting annotation is nil or not

---

controller/backup_controller.go
k8s/pkg/apis/longhorn/v1beta2/backup.go

ref: https://github.com/longhorn/longhorn/issues/6491
If BackupTarget becomes unavailable during creating Backup
- Backup creation is an async call, so it will keep uploading in Engine/Replica
- Backup creation status will keep in the Engine memory which will sync with Replica
- Backup Controller will sync with the status in Engine memory
So even BackupTarget is unavailable, it will keep uploading the Backup and the updating the progress in CRD [here](https://github.com/longhorn/longhorn-manager/blob/master/controller/backup_controller.go#L386)
Now the problem is when Backup is `Completed`, we do `BackupInspect()` which will fail because Target is now unavailable.
So the `backup.Status.LastSyncedAt` is never set, we only set `backup.Status.State=Completed`.
In the next reconcile loop, …

fix(backup): fix backup status if target becomes invalid during creating backup

---

controller/support_bundle_controller.go

There is a issue https://github.com/harvester/harvester/issues/4630 in harvester. The description and issue url are empty from downloaded support bundle. And LH manager has the same issue here.
[Related downstream PR](https://github.com/rancher/support-bundle-kit/pull/81)

feat: pass support bundle issueURL and description

---

controller/setting_controller.go

Secret annotations might be nil (such kubectl `create` -f secret.yaml -n longhorn-system) when adding a backup-target annotation to a object. Initialize the annotaion if it is nil before we add a backup-target annotation.
regression testing: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5186
Ref: longhorn/longhorn#6947

fix(backup): secret annotations might be nil

---

controller/backup_volume_controller.go

The `backupInfo` would be nil when we try to pull the backups from the remote backup target.
Ref: longhorn/longhorn#6998

fix(backup): backupInfo might be nil

---

datastore/datastore.go
datastore/kubernetes.go

1. Get the secret/configmap directly from API server if it is not in longhorn-system namespace.
2. PriorityClass is non-namespaces, so moving it to KubeInformerFactory is much clear.
Longhorn/longhorn#7045

Fix resource not found error

---

datastore/longhorn.go

ref: [longhorn/longhorn#7062](https://github.com/longhorn/longhorn/issues/7062)
When selecting disk/node for backingimage
we should skip block type disk
In the future we will support backing image in spdk and we should distinguish them when selecting disk type
ref: https://github.com/longhorn/longhorn/issues/6341

fix(backing): disable block type disk for v1 type backing iamge

---

controller/replica_controller.go
controller/volume_controller.go

longhorn/longhorn#6961
Just https://github.com/longhorn/longhorn-manager/commit/be6aca60ae375d212256d9bc3363f70bce86a767 is sufficient to prevent the engine from crashing under the circumstances from https://github.com/longhorn/longhorn/issues/6961#issuecomment-1785634706. However, this commit alone leads to orphaned data once the migration is complete (as the replica we refuse to add to the engine becomes inactive without an active counterpart).
I experimented with a path to making use of this newly inactive replica after the migration (to avoid unnecessary rebuilding), but I ultimately decided that the migration logic refactor this required was outside the scope of the ticket.
The other commits are an attempt to ensure we don't orphan the newly inactive replica's directory by providing …

Fix engine migration crash

---

csi/node_server.go

Should be `softerr`.
Longhorn/longhorn#7104

rwx: fix mount option typo

---

package/Dockerfile

Add the `xfsprogs` back to longhorn-manger image so that longhorn-csi-plugin can run `mkfs.xfs` to mount the xfs PV
longhorn/longhorn#7140

Fix bug cannot mount xfs PV

---

csi/crypto/crypto.go
datastore/longhorn.go

The minimal encrypted volume size should be bigger than 16MiB because the default LUKS2 header size is 16MiB.
Ref: longhorn/longhorn#7033

fix(crypto): minimal encrypted volume size

---

controller/engine_controller.go
controller/snapshot_controller.go
datastore/longhorn.go
manager/engine.go
types/setting.go

longhorn/longhorn#7075
Key points:
- `disable-snapshot-purge` is meant to be enabled temporarily and for a very specific purpose.
- It would be confusing if `auto-cleanup-system-generated-snapshots` could be enabled at the same time as `disable-snapshot-purge`, since the behavior of one would outweigh the behavior of the other. This PR ensures only one can be enabled at a time.
- I originally took a simpler approach in the snapshot controller, but I realized it could lead to volumes being indefinitely attached for snapshot deletion while `disable-snapshot-purge` prevented that deletion from succeeding. The new approach is to log a warning, delete the detachment ticket, and do nothing as long as `disable-snapshot-purge` is enabled. Then, when it is disabled, ensure all snapshots with …

Add disable-snapshot-purge setting

---

datastore/longhorn.go

Already filtered in [ListReadyNodesRO](https://github.com/longhorn/longhorn-manager/blob/d4700d32d656a560712c27b3212b19224eda01e1/datastore/longhorn.go#L2523).

refactor: remove duplicated ready node filtering

---

upgrade/upgrade.go

No need to walk through the resource upgrade path for fresh Longhorn installation.
(lhVersionBeforeUpgrade is an empty value)
Ref: longhorn/longhorn#6988

fix: skip upgrade path for new installation

---

controller/volume_attachment_controller.go
datastore/longhorn.go
types/setting.go

ref: https://github.com/longhorn/longhorn/issues/6978
iterate the volumeattachment ticket
if there is `AttacherTypeLonghornAPI` ticket and the target node is being drained, then delete the ticket
in the next function `handleVolumeDetachment` will detach the volume if the volume is currently attached by this ticket.

feat(node drain): add DetachManuallyAttachedVolumesDuringDrain setting

---

csi/deployment.go
csi/deployment_util.go

Before this PR:
1. Deploy Longhorn master-head
1. Upgrade Kubernetes 
1. Crash longhorn-driver-deployer pod
1. Observer that the longhorn-driver-deployer clean up and redeploy csi-attacher/csi-provisioner/csi-resizer/csi-snapshotter/longhorn-csi-plugin/Longhorn csidrivers object. This is:
1. Unnecessary as these components are still up to date 
2. Even problematic as during this period Kubernetes cannot perform volume attach/detach/mount/unmount thus prevent kubernetes from draining the node
After this PR:
longhorn-driver-deployer does not clean up and redeploy csi-attacher/csi-provisioner/csi-resizer/csi-snapshotter/longhorn-csi-plugin/Longhorn csidrivers object after Kubernetes upgrade
Additional context:
The old behavior of longhorn-driver-deployer was necessary when upgrading …

improvement: driver deployer shouldn't cleanup previous deployment if Kubernetes version changes

---

Dockerfile.dapper
README.md
scripts/test

- By default run only tests on affected modules, if there are uncomitted changes in the git worktree. This speeds up local unit test runtime during development by only running tests on affected modules. In the CI pipeline or when changes have been committed, all unit tests are run for complete coverage.
- Make it possible to run particular tests using the TESTS environment variable. This is helpful when writing tests, as it helps both with turnaround times as well as reduce the output to only include the test under development.

ci: import test script

---

controller/node_controller.go

Longhorn exposed all unknown (to longhorn) node conditions as K8s events. This is a mechanism that only has informational value and is used as such in Longhorn as well, as it only serves to relay information to the UI.
In particular, the condition in question is `EtcdIsVoter` and is a K3s specific condition, indicating the membership details of an etcd node on that K3s node and is irrelevant to Longhorn, but other non-standard node conditions should be ignored too, if Longhorn doesn't derive any actionable value from them.
related-to: longhorn/longhorn#7290

fix: ignore unknown node condition

---

controller/replica_controller.go
controller/volume_controller.go

Quick summary of [the live engine upgrade logic](https://github.com/longhorn/longhorn-manager/blob/ae6b6aa99d0e2eb12fd0d868f5e67105bb6b685c/controller/volume_controller.go#L2631):
1. Volume controller check for the volume is attached and healthy
1. Check the old engine image and new engine image is ready
1. Create new inactive replicas set from old active replica set. Note that new inactive replicas will use new engine image and the old set is still using the old engine image
1. Start the new inactive replica set
1. Set the `e.Spec.UpgradedReplicaAddressMap` to the new inactive replica set and `e.Spec.Image` to the new engine image to start the upgrading inside engine process
1. Once the engine controller finish the image upgrade for engine, it will set `e.Status.CurrentImage` to new …

Fix bug volume stuck in live engine upgrading forever if it was degraded during live engine upgrade

---

app/post_upgrade.go
controller/node_controller.go
controller/volume_controller_test.go
types/deploy.go

Linkerd will inject a container `linkerd-proxy` in the longhorn-manger pod by adding the annotation `linkerd.io/inject: enabled`. It will fail when we check the `MountPropagation` for the first container that is `linkerd-proxy`. What we want to check is the `longhorn-manager` container.
Ref: longhorn/longhorn#3809

fix(node): the deploy driver failed with linkerd

---

controller/replica_controller.go
controller/volume_controller.go

Do not cleanup replica folder if there are more than 1 replicas CR for it even if all replica CRs are inactive.
More details at https://github.com/longhorn/longhorn/issues/7396#issuecomment-1865313517
longhorn/longhorn#7396

Fix: data lost during engine upgrade/migration

---

controller/controller_test.go
controller/node_controller_test.go

Refactor node controller unit tests:
- Break up single test function into multiple test functions
- Create a clear separation between test case input data and expected result data
- Implement existing tests with new structure as individual test functions
- Avoid checking things that aren't subject matter of the test case at hand
related-to: longhorn/longhorn#7332

ci: refactor node controller unit tests

---

csi/deployment.go

longhorn/longhorn#7116
If we can't get upstream changes in a reasonable amount of time, this works in the interim. It prevents a liveness probe from killing the `longhorn-csi-plugin` container for five minutes so we can get a successful liveness probe when the `livenessprobe` container comes back.

Add a startup probe to the longhorn-csi-plugin container

---

webhook/resources/volume/validator.go

Reject volume.spec.image update for v2 volumes before introducing live upgrade (https://github.com/longhorn/longhorn/issues/6001).
Longhorn/longhorn#7446

Reject volume.spec.image update for v2 volumes before introducing live upgrade

---

controller/controller_test.go
controller/node_controller.go
controller/node_controller_test.go
datastore/longhorn.go
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/node.go
scheduler/replica_scheduler.go
util/util.go
webhook/resources/volume/validator.go

Get the storage class of the PVC to check if the new volume size is bigger than the maximum size of the file system in the storage class for the volume expansion.
If the file system format of the disk is `ext4` and the volume size of this replica is bigger than 16TiB, it will not schedule replicas to this disk.
Ref: longhorn/longhorn#7423

Handling of 16TiB+ volumes with ext4 as the underlying file system

---

controller/instance_handler.go
controller/instance_handler_test.go

ref: https://github.com/longhorn/longhorn/issues/6386
When the pod is recreated and the engine is relaunched
There might be a time gap that the error condition is not sync from the instance-manager and remains `error=true`
And keep requesting remount.
Should reset error condition when the instance is not running

feat(instance status): reset instance error status when it is not running

---

controller/node_controller.go
datastore/longhorn.go
scheduler/replica_scheduler.go
types/types.go

When a kubernetes node is labeled with `node.longhorn.io/disable-v2-volume: "true"`, the v2 volume feature on the node is not supported.
The PR is based on https://github.com/longhorn/longhorn-manager/pull/2272
Longhorn/longhorn#7015

Support instance-manager pod for v2 volumes on selected nodes

---

controller/node_controller.go
webhook/common/common.go
webhook/common/common_test.go
webhook/resources/node/validator.go

longhorn/longhorn#7475
This PR fixes the two main issues from https://github.com/longhorn/longhorn/issues/7475#issuecomment-1876060097:
1. The nil pointer dereference is no longer possible. The manager pod on the removed node no longer panics and crashes immediately after the node is removed.
2. Even if the manager pod DOES restart and recreate the Longhorn node object in a broken (deleting) state, we can delete it right away instead of getting stuck.

Allow a Longhorn node to be deleted after its corresponding Kubernetes node

---

controller/controller_test.go
controller/instance_manager_controller_test.go
controller/node_controller_test.go
controller/volume_controller_test.go

Add test ensuring that an unknown node condition does not emit a K8s event.
related-to: longhorn/longhorn#7290

ci: add tests for unknown node conditions

---

datastore/longhorn.go
engineapi/backups.go
util/util.go

ref: https://github.com/longhorn/longhorn/issues/7543
> K8s resource name should follow the following constraints
> - contain at most 63 characters
> - contain only lowercase alphanumeric characters or '-'
> - start with an alphanumeric character
> - end with an alphanumeric character
But our regex allows uppper case which is invalid.
Also add the validation to the BackupVolume vame list, so it won't create BackupVolume with invalid name.
This util function is mostly used in webhook validation so it won't effect those functions
The only part effected is the group name of the recurring job. It is okay to have uppercase, so I create another util function `ValidateString()` for it.

fix(util): resource name should only contain lower case

---

datastore/longhorn.go
manager/volume.go

Issue Longhorn/longhorn#7570
`CheckDataEngineImageReadiness()` should handle v2 data engine as well.

`CheckDataEngineImageReadiness()` should handle v2 data engine as well.

---

controller/engine_image_controller.go
controller/replica_controller.go
controller/setting_controller.go
controller/volume_controller.go
manager/volume.go

Issue longhorn/longhorn#7568
spdk_tgt complains the improper sequence of deleting engines and replicas.
Replicas should be deleted before deleting its engine.

Prevent from complains in spdk_tgt when deleting a v2 volume

---

app/daemon.go
app/pre_upgrade.go
constant/events.go
upgrade/upgrade.go
upgrade/util/util.go
upgrade/util/util_test.go
upgrade/v14xto150/upgrade.go
upgrade/v151to152/upgrade.go

Issue longhorn/longhorn#7539
- Add v140-to-v15x path back
-  Add a new flag `FlagUpgradeVersionCheck: "upgrade-version-check"`
to accept the command to skip the upgrade path check.

fix(upgrade): skip upgrade path check

---

controller/volume_controller.go

Longhorn 7597
Issue https://github.com/longhorn/longhorn/issues/7597
v2 volume becomes faulted and detached after deleting one replica during full restoration.

v2 volume: fix the conflict of offline rebuilding and full restoration

---

controller/controller_manager.go
controller/instance_manager_controller.go
controller/instance_manager_controller_test.go
controller/node_controller.go
controller/setting_controller.go
datastore/longhorn.go
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/setting.go
types/setting.go
webhook/resources/systemrestore/validator.go

For settings `taint-toleration`, `guaranteed-instance-manager-cpu`, `system-managed-components-node-selector`, and `priority-class`, users can customize the settings, and the settings will only take effect when all volumes are detached.
Ref: longhorn/longhorn#7173

feat(setting): lazy update for volume-related settings

---

engineapi/instance_manager.go

https://github.com/longhorn/longhorn/issues/7642
Only append snapshot max count and size if `engineCLIAPIVersion` is larger than `10`.

fix: use engineCLIAPIVersion for snapshot max count & size

---

controller/instance_manager_controller.go
controller/setting_controller.go

Issue longhorn/longhorn#7640
https://github.com/longhorn/longhorn/issues/7640#issuecomment-1888491074
`None`
`None`

fix(storage-network): annotated pod in creation loop

---

types/setting.go

Issue Longhorn/longhorn#7655
v1 and v2 date engines are separate, so the warning `When applying the setting, Longhorn will restart all instance-manager pods.` is not required.

Update the description of v2-data-engine setting

---

controller/uninstall_controller.go

The old code assumes that validatingCfg is nil when ValidatingWebhookConfigurations().Get() return error NotFound. This is an incorrect assumption, the validatingCfg is actually an empty non-nil object in this case and the old logic attempted to delete a non-exist object https://github.com/longhorn/longhorn-manager/blob/41d50c237d2f91b9acfc57cedb6fa0c18970d7e6/controller/uninstall_controller.go#L946C1-L951
longhorn/longhorn#7657

Fix bug uninstallation stuck if the MutatingWebhookConfigurations or ValidatingWebhookConfigurations already deleted

---

controller/backup_target_controller.go

Issue longhorn/longhorn#7619
If a backup target is picked up by a node that is cordoned before the installation of Longhorn, the controller will render the backup target unusable.
`None`
https://github.com/longhorn/longhorn/issues/7619#issuecomment-1886222822

fix(backuptarget): cordoned node controller renders the backup target unusable

---

controller/setting_controller.go

Issue longhorn/longhorn#7654
https://github.com/longhorn/longhorn/issues/7649#issuecomment-1889282614
Move returning logs from `errors.Wrapf` to `types.ErrorInvalidState` when synchronizing the danger zone setting with volumes attached.
Move the log level from `Error` to `Trace`.

fix(setting): flooding error message

---

datastore/longhorn.go

Issue Longhorn/longhorn#7619
Prevent flooding warning messages "Found more than 1 xxx instance manager ...". It is a side effect of the solution to Longhorn 7619. To mitigate the issue, change the level to debug level.

Prevent flooding warning messages

---

k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/engineimage.go

Issue longhorn/longhorn#7683
Add a new k8s column `INCOMPATIBLE` for resource `EngineImage`.

chore(engineimage): add a new k8s column.

---

csi/node_server.go

Issue https://github.com/longhorn/longhorn/issues/7638
NFS v4.2 is a better default option, with more capabilities than the current v4.1.  The user can still force v4.1 if necessary.
Passes regression rwx tests.

feat: shift NFS default version to 4.2 for RWX mount.

---

csi/node_server.go

Issue https://github.com/longhorn/longhorn/issues/7741
This reverts the change in default RWX mount options to use NFS v4.2, and sets it back to v4.1.  The default can still be overridden using parameter nfsOptions in the volume's storage class, and that will remain the preferred way to use v4.2.
Passed `rwx` regression tests: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6055/
This will need to be backported to 1.4.5, 1.5.4, and 1.60, since the original change was.

fix(rwx): revert default NFS version to 4.1 for RWX volume mounts 

---

controller/kubernetes_pod_controller.go

ref: https://github.com/longhorn/longhorn/issues/7751
Pod controller reconcile pod every 30 secs.
We should not update request remount time too frequently or it might not delete the pod.
Because it checks if it is 5 secs after request remount time before deleting the pod.

fix(volume): request remount every 1 min when read only

---

engineapi/instance_manager.go

Issue Longhorn/longhorn#7783
The longhorn-manager communicates with the process manager gRPC service in an older instance-manager (apiVersion < 4). For a newer instance-manager, however, the longhorn-manager only needs to interact with the instance gRPC service. As a result, there is no requirement for the longhorn-manager to establish a connection to the process manager.

Remove unused process manager connection in longhorn-manager

---

csi/node_server.go
csi/util.go

csi: use ensureFolderPath rather than ensureMount for checking folder path

---

controller/engine_controller.go
controller/instance_manager_controller.go
controller/monitor/disk_monitor.go
controller/node_controller.go
controller/orphan_controller.go
controller/replica_controller.go
engineapi/disk_service.go
engineapi/instance_manager.go
engineapi/proxy.go

Issue longhorn/longhorn#7040
If TLS connection is broken, cancel() of ctx will be called. Then, it causes the fallback to non-TLS runs into the error `rpc error: code = Canceled desc = context canceled`.

Fix `rpc error: code = Canceled desc = context canceled` when falling back to non-TLS client

---

controller/engine_controller.go
controller/utils.go
controller/volume_controller.go
controller/volume_controller_test.go
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/replica.go
upgrade/upgrade.go
upgrade/v16xto170/upgrade.go
util/util.go
util/util_test.go

longhorn/longhorn#7425
- The `replica.Spec.HealthyAt` field tells us if a replica has ever been healthy.
- The `replica.Spec.FailedAt` field is set every time we detect a replica failure.
- Before we rebuild a replica, we set `replica.Spec.HealthyAt == ""` and `replica.Spec.FailedAt == ""`. The `replica.Spec.HealthyAt == ""` should be a solid indicator that we cannot trust the data on the replica and should never try to use it.
- If all replicas have `replica.Spec.FailedAt != ""`, we select replicas with `replica.Spec.HealthyAt != ""` to salvage (by removing clearing its `replica.Spec.FailedAt`.
- In some situations, we have seen a replica that was previously corrupted by a failed rebuild have a `replica.Spec.HealthyAt != ""` and be used by the engine.
- Longhorn tries to use this replica …

Be more careful while cleaning up stale replicas

---

util/util_test.go

Longhorn 7425
longhorn/longhorn#7425
Fixes a small (nonfunctional) typo in https://github.com/longhorn/longhorn-manager/pull/2432.
I am making this change in the backports of https://github.com/longhorn/longhorn-manager/pull/2432, so we do not need to backport this one.

Fix typo in TestTimestampAfterTimestamp case name

---

controller/engine_controller.go
controller/utils.go
controller/volume_controller.go
controller/volume_controller_test.go
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/replica.go
upgrade/upgrade.go
upgrade/v160to161/upgrade.go
util/util.go
util/util_test.go

longhorn/longhorn#7425
We previously backported this to `v1.6.x` before the release of `v1.6.0`, but reverted. Backporting again with the needed fixes from https://github.com/longhorn/longhorn-manager/pull/2541 and https://github.com/longhorn/longhorn-manager/pull/2540.

Be more careful while cleaning up stale replicas (backport #2432)

---

k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/instancemanager.go

longhorn/longhorn#7887
Make the InstanceProcessStatus.Conditions CRD field nullable (like the other status CRD fields that are maps). See the linked issue for context.

Make InstanceProcessStatus.Conditions nullable

---

csi/deployment.go

longhorn/longhorn#7428
This reverts commit fe405e668ca9619acb08e00f953881a3f8f21148. We no longer need these changes because livenessprobe was fixed upstream. 
https://github.com/kubernetes-csi/livenessprobe/issues/236

Revert "Add a startup probe to the longhorn-csi-plugin container"

---

k8s/generate_code.sh

N/A
We ensure GOPATH is set in `generate_code.sh`.
https://github.com/longhorn/longhorn-manager/blob/4b2a8db4c5a58c430455105e4e513ea273c4d046/k8s/generate_code.sh#L20-L27
However, we do not export it.
Later we execute the code generators in a child shell, which does not have access to the set GOPATH variable.
https://github.com/longhorn/longhorn-manager/blob/4b2a8db4c5a58c430455105e4e513ea273c4d046/k8s/generate_code.sh#L60-L65
The code generators (e.g. `deepcopy-gen`) look in the environment for GOPATH in order to find `boilerplate.go.txt`. Unless it was explicitly exported by the user, the code generators can't use it and default to `./`.
https://github.com/kubernetes/code-generator/blob/c3277d42784bc6492e21dee0e0ed900901ac0299/cmd/deepcopy-gen/main.go#L62-L64
Before this change:
``` …
```

Export GOPATH for code generators

---

k8s/crds.yaml
k8s/patches/crd/preserveUnknownFields/engine.yaml
k8s/patches/crd/preserveUnknownFields/engineimage.yaml
k8s/patches/crd/preserveUnknownFields/instancemanager.yaml
k8s/patches/crd/preserveUnknownFields/node.yaml
k8s/patches/crd/preserveUnknownFields/replica.yaml
k8s/patches/crd/preserveUnknownFields/setting.yaml

Longhorn 7887
longhorn/longhorn#7887
If Longhorn and Kubernetes are upgraded in a particular order from Longhorn `v1.0.2-` to the latest, `preserveUnknownFields` may remain `true`, even though the default (and intended value) is `false`. As a result, Kubernetes does not consider affected CRDs to have structural schemas, potentially resulting in unexpected behavior (including https://github.com/longhorn/longhorn/issues/7887).

Explicitly set preserveUnknownFields to false

---

engineapi/enginesim.go
engineapi/types.go

~Issue #~
Corrects misleading variable names.
None.
None.

refactor: misleading variable names

---

controller/volume_controller.go

Issue https://github.com/longhorn/longhorn/issues/7945

controller: DR volume should wait for the latest backup restored before activation

---

controller/volume_controller.go

https://github.com/longhorn/longhorn/issues/7945
This fixes the regression introduced by https://github.com/longhorn/longhorn-manager/pull/2611

controller: Fix issue that regular restore volume won't be detached

---

controller/support_bundle_controller.go

ref: https://github.com/longhorn/longhorn/issues/7998
Current image pull policy of support bundle is `Always` which is not necessary.
Change to `IfNotPresent`

fix(supportbundle): update support bundle image pull policy to if not present

---

controller/backup_controller.go
k8s/pkg/apis/longhorn/v1beta2/volumeattachment.go

When the volume.Spec.NodeID is different than the node ID of the backup VA ticket, we should not initiate a backup as the volume is going to detach soon
longhorn/longhorn#7937
This PR is going to replace the approach at the PR https://github.com/longhorn/longhorn-manager/pull/2627. After discussed with @ejweber and @james-munson , we think that this approach is better because:
1. The other approach only touches the logic for the VA ticket of RWO non-migratible volume. It still leaves the logic for the RWX and mitigrable volume the same as we cannot compare the volume.Spec.NodeID with the node ID of these VA tickets. They are most likely to be different
1. It is fundamentally still correct that when the volume start detaching (but not finish detaching yet) the VA ticket can set to …

Fix bug we initiate a backup when the volume has started detaching

---

controller/volume_controller.go

controller: Check backup volume sync time before activation

---

csi/node_server.go
csi/util.go

longhorn/longhorn#8009
If `NodePublishVolume` is called when a block volume is not staged (see context in longhorn/longhorn#8009), we automatically call `NodeUnstageVolume` and `NodeRestageVolume`). We already had this behavior for mount volumes.

Automatically restage block volumes if necessary

---

app/daemon.go
webhook/webhook.go

ref: https://github.com/longhorn/longhorn/issues/8005
The root cause is that we now have conversion-webhook(`:9501`), admission-webhook(`:9502`) in longhorn-manager
We set the readiness port to `9501`
The order of starting is as follow
1. conversion-webhook
2. admission-webhook
3. upgrade
4. ....
So there is a chance that the pod is not ready yet (readiness on `9501` hasn't succeeded) when the longhorn-manager starts to do the upgrade 
It then fails to call the webhook by endpoint because there is no longhorn-manager pod ready. 
```
Post \"https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/validaton?timeout=10s\"
````
This PR fix it by validating the endpoint works by testing the domain instead of local address before doing the upgrade.

fix(daemon): validate webhook by its domain

---

metrics_collector/volume_collector.go

Longhorn 8098
Issue longhorn/longhorn#8098

metrics: refactor volume collector

---

scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go

longhorn/longhorn#8043
~When `replicaNodeSoftAntiAffinity == false`, the scheduler should not schedule a second replica to a node that has a failed replica of the same volume. When `replicaNodeSoftAntiAffinity == true`, it should.~
When `replicaNodeSoftAntiAffinity == false` and there is already a failed replica for a volume scheduled to a node, the scheduler should ONLY consider that node for scheduling if:
- The failed replica is no longer usable (e.g. `spec.rebuildRetryCount >= 5`), or
- `replica-replenishment-wait-interval` is exceeded.

Consider a node with a failed reusable replica as still used

---

controller/volume_controller.go
webhook/resources/volume/validator.go

longhorn/longhorn#7833
@roger-ryao discovered that https://github.com/longhorn/longhorn-manager/pull/2564 was ineffective when upgrading from `v1.5.x` to `v1.6.x+`. In fact, the inclusion of https://github.com/longhorn/longhorn/issues/6563 in `v1.6.x` makes it impossible to upgrade Longhorn from `v1.5.x` to `v1.6.x+` while a volume is migrating at all. This is something I didn't notice in my original testing. Thanks @roger-ryao!
This PR:
1. Allows the `volume.spec.snapshotMaxCount` to be changed on a migrating volume ONLY if is from 0 (coming from `v1.5.x`) to `250` (as the upgrade logic does).
2. Waits to propagate that change to engines and replicas until migration is complete.
I updated the test steps at https://github.com/longhorn/longhorn-manager/pull/2558#issuecomment-1932296348 to …

Allow maxSnapshotSize to change from 0 to 250 while upgrading

---

controller/engine_controller.go
controller/volume_controller.go
datastore/longhorn.go
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/engine.go
k8s/pkg/apis/longhorn/v1beta2/replica.go
k8s/pkg/apis/longhorn/v1beta2/zz_generated.deepcopy.go
upgrade/v16xto170/upgrade.go

longhorn/longhorn#8114
When I added the below line of code in longhorn-manager, it was my intention for it to only update `lastHealthyAt` when a replica transitioned from some other mode to RW. However, it actually updates `lastHealthyAt` every time a replica reconciles as long as that replica is RW (whether it is transitioning or not).
https://github.com/ejweber/longhorn-manager/blob/e8f7d17d58b8897012ca9acbdbba97314beceedc/controller/volume_controller.go#L725
This bad behavior did not disrupt the purpose of the `lastHealthyAt` field in that PR (to allow Longhorn to verify that a replica had been healthy at some point since its last failure). However:
- It does not match the intended purpose of the field: to record the last time the replica became RW (not any arbitrary time we have …

Track replica mode transition times with replicaTransitionTimeMap

---

metrics_collector/volume_collector.go

Issue longhorn/longhorn#8139
Do not return early for non-engine-related metric collections.

fix(metrics): longhorn_volume_robustness not collected for detached volume

---

controller/engine_controller.go
upgrade/upgrade.go
upgrade/util/util.go
upgrade/v16xto170/upgrade.go

longhorn/longhorn#8114
Further testing of https://github.com/longhorn/longhorn-manager/pull/2685 shows two issues:
- ReplicaTransitionTimeMap was only created if ReplicaModeMap previously existed. This didn't really impact functionality (as we quickly created it on a followup reconciliation) but it led to erroneous log messages like `"BUG: Replica %v is in mode %v but transition time was not recorded"`.
- Update logic was added, but never triggered. Again, this didn't really affect functionality (as the volume and engine controllers quickly filled in the missing fields after upgrade), but it was confusing.

Fix minor issues with ReplicaTransitionTimeMap

---

controller/kubernetes_pv_controller.go

Fixes the root cause of longhorn/longhorn#8198.
https://github.com/longhorn/longhorn-manager/pull/2494 only allowed NodePublishVolume calls to proceed if a Longhorn volume's `status.kubernetesStatus.workloadsStatus` contained a pending workload. However, Longhorn's Kubernetes PV controller does not recognize workloads that use generic ephemeral volumes. As a result, NodePublishVolume calls fail for generic ephemeral volumes. https://github.com/longhorn/longhorn-manager/pull/2659 happened to mitigate this behavior, but the root cause remains.
This PR modifies Longhorn's Kubernetes PV controller so that it can detect workloads that use generic ephemeral volumes.

Recognize pods that use Longhorn generic ephemeral volumes

---

types/setting.go
types/types.go

ref: https://github.com/longhorn/longhorn/issues/7441
Some ideas:
1. **use map to present max and min value** instead of use int directly.
- Because we still want to `omitempty` and `distinguish 0 or nil`. We then need to use `*int` in the structure so it can show 0 correctly and omitempy when nil.
- We then need to declare a value first and assign it to structure as pointer for every definition which might make code not clean.
```
val := 0
difinition := SettingDefinition {
Minimum: &val
}
``` 
- Use map, we can avoid the above problem.
2. For some multi-choice settings, we used another util function to validate it which is not correct
- `SettingNameOfflineReplicaRebuilding`, `SettingNameSnapshotDataIntegrity`, `SettingNameBackupCompressionMethod`, `SettingNameReplicaAutoBalance` cc …

refactor(setting): add value range in setting definition and use it in validation

---

csi/deployment.go
csi/node_server.go

Issue # https://github.com/longhorn/longhorn/issues/7931
Log with kernel release and OS info when an NFS mount fails, to aid in troubleshooting.

fix(csi): add node info to failed mount logging.

---

csi/node_server.go

Applies to issue https://github.com/longhorn/longhorn/7931
Corrects issue found in testing on backport to 1.5.5 (backport issue https://github.com/longhorn/longhorn/issues/8286)
Still testing change, but want to get eyes on this simple fix.

fix(csi): correct error found in test.

---

controller/share_manager_controller.go

Issue Longhorn/longhorn#7872
- Share manager pod respects the newly introduced `storageClass.Parameters["shareManagerNodeSelector"]`
- Share manager pod respects the `storageClass.allowedTopologies` which are internally converted to the affinity of a share manager pod
- Share manager pod respects the newly introduced `storageClass.Parameters["shareManagerTolerations"]`

feat(rwx): share manager locality

---

manager/volume.go

Issue #
https://github.com/longhorn/longhorn/issues/7841
Check if volume size can be scheduled by the replica scheduler before expading the pv/pvc size.

fix(expand): check volume size first

---

controller/instance_manager_controller.go

Issue Longhorn/longhorn#8420
reflect.DeepEqual treats the two maps `var m1 map[string]process` and `m2 := map[string]process` as different maps. Therefore, to prevent unnecessary updates, we must check both that the length of the maps is zero and that the maps are identical.

Prevent unnecessary updates of instanceManager status

---

controller/instance_manager_controller.go

Issue longhorn/longhorn#8466
No need to sync log settings to non-running instance manager pod for avoiding flooding warning messages.

Only sync log settings to running instance manager pod

---

webhook/server/server.go

ref: https://github.com/longhorn/longhorn/issues/8387
Follow the same implementation in [Harvester](https://github.com/harvester/harvester/blob/68c52fa87b44906b7915e81fb674fb73c1d41951/pkg/server/types.go#L165-L175) to disable tls 1.0 and 1.1 on webhook service

fix(webhook): disable tsl 1.0 and 1.1 on webhook service

---

webhook/server/server.go

Reverts longhorn/longhorn-manager#2770
Change the fix to upgrading the golang version in v1.6.x

Revert "fix(webhook): disable tsl 1.0 and 1.1 on webhook service"

---

controller/controller_test.go
controller/system_backup_controller.go
controller/system_backup_controller_test.go
controller/system_restore_controller_test.go
controller/system_rollout_controller.go
controller/system_rollout_controller_test.go
datastore/datastore.go
datastore/longhorn.go
datastore/uncached.go
k8s/pkg/apis/longhorn/v1beta2/systembackup.go
types/types.go

ref: https://github.com/longhorn/longhorn/issues/5085
1. Backup all BackingImages after backing up Volumes and their yaml when taking system-backup
- **`After backing up Volumes`: Because now we already backup BackingImage when backing up Volumes**, In this stage, we only backup those BackingImages not being used.
3. Restore BackingImages before restoring Volumes, so the Volumes with BackingImages can restore successfully.
- **`Before restoring Volumes`: Because Volume with BackingImage creation will fail if there is no BackingImage in the cluster**
- If the BackingImage already exists, update the tag `last-skipped-system-restored` and `last-skipped-system-restored-at`
- If the BackingImage does not exist, restore it by creating `restore` type BackingImage
- use `Checksum: …

feat(system-backup): support backup backing image

---

api/backup.go
api/model.go
api/router.go
engineapi/types.go
manager/engine.go

Issue # longhorn/longhorn#7982
When users make a requst to get backup volumes information by Backup Volume Get/List APIs, it will also trigger the synchronization for these backup volumes once.

fix(backup): manually synchronizing backup volumes.

---

controller/monitor/disk_monitor.go
controller/node_controller.go
controller/node_controller_test.go
engineapi/disk_service.go
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/node.go

Issue longhorn/longhorn#8458
A block-type disk can only be managed by a specific spdk_tgt within an instance manager. The commit is intended to record the name of the instance manager associated with that disk.
On the other hand, for a filesystem-type disk, any instance manager can access it. Therefore, the recorded instance manager for a filesystem-type disk is always the default instance manager.

Record instance-manager name for a block disksin `node.spec.diskStatus`

---

csi/controller_server.go
manager/kubernetes.go
util/util.go

longhorn/longhorn#8488
Prevent the creation of Longhorn PersistentVolumes with `fstype: xfs` smaller than `300 MiB`.

Refuse to create an XFS volume smaller than 300 MiB

---

controller/volume_controller.go

longhorn/longhorn#8522
Delete a failed to schedule replica with HardNodeAffinity if DataLocality is disabled.
Previously, we would only do this if there were enough healthy replicas, but it led to the "deadlock" in longhorn/longhorn#8522 where we would not schedule more replicas until we deleted the failed to schedule one, but we would not delete the failed to schedule one until there were enough healthy ones.
I experimented with changing the behavior of this function even more, but there were some weird side effects. I think it is better to keep it working almost exactly as it did before. I did, however, rearrange a bit.

Always clean up FailedToScheduleReplica with wrong HardNodeAffinity

---

app/daemon.go
controller/uninstall_controller.go
util/client/client.go

longhorn/longhorn#8578
More details are at https://github.com/longhorn/longhorn/issues/8578#issuecomment-2121405795

Fix bug: we should start conversion webhook before initiating Longhorn datastore

---

controller/system_rollout_controller.go
webhook/admission/admission.go

https://github.com/longhorn/longhorn/issues/8601
During the system restore
Volume depends on BackingImage, our webhook rejects the Volume creation if the BackingImage is not in the cluster
=> move the volume restoration out of the parallel restoration
And since PV depends on Volume
=> So we also need to move PV,PVC restoration after Volume restoration
cc @c3y1huang

fix: fix system restore PV and PVC stuck beause of backing image and volume

---

controller/setting_controller.go
controller/support_bundle_controller.go
types/setting.go

Issue longhorn/longhorn#8623
Propose adding a setting that allows users to configure the node bundle collection timeout during support bundle generation.
`None`
https://github.com/rancher/support-bundle-kit/pull/109

feat(support-bundle): add support-bundle-node-collection-timeout setting

---

manager/kubernetes.go

longhorn/longhorn#8488
There is a typo in a log message that is confusing.

Fix a typo in message about small XFS filesystem

---

controller/engine_controller.go
controller/engine_controller_test.go

longhorn/longhorn#8076
This is meant to be an improvement over the rejected https://github.com/longhorn/longhorn-manager/pull/2817. It adds a rate limiter to provide the following behavior:
- The rate limiter generally only allows "size-only updates" (updates to `engine.status.snapshots[volume-head].size` once every thirty seconds.
- For responsiveness to bursty writing, the rate limiter allows up to three "size-only updates" in quick succession. (The underlying implementation is a "token bucket", so this burstability can be rebuilt over time if no writes happen.)
- Size changes that exceed a heuristic threshold ignore rate limiting (otherwise, it might feel weird).
- Any status changes that aren't "size-only" ignore rate limiting.
- Size fields have "eventual" byte accuracy (they are not …

Update engine and volume size less frequently

---

metrics_collector/backing_image_collector.go

ref: https://github.com/longhorn/longhorn/issues/7563
Fix a bug in backing image metrics support
should get the diskUUID instead of diskName
Test results
```
longhorn-manager-8hs5s:/ # curl -sSL http://10.96.75.66:9500/metrics | grep "parrot"
longhorn_backing_image_actual_size_bytes{backing_image="parrot",disk="ca203ce8-2cad-4cd1-92a7-542851f50518",node="kworker1"} 3.3554432e+07
longhorn_backing_image_state{backing_image="parrot",disk="ca203ce8-2cad-4cd1-92a7-542851f50518",node="kworker1"} 4
longhorn_backup_backing_image_actual_size_bytes{backup_backing_image="parrot"} 3.3554432e+07
longhorn_backup_backing_image_state{backup_backing_image="parrot"} 3
```

fix: fix backing image metrics support

---

metrics_collector/volume_collector.go

Issue Longhorn/longhorn#8266
Metric collector emits warning messages if the engine is not found during the transition state. Update these messages to debug level to prevent flooding in longhorn-manager.

metrics: update warning messages to debug level

---

controller/backup_controller.go
engineapi/backup_monitor.go

ref: https://github.com/longhorn/longhorn/issues/8650
Backup might failed because  the snapshot is not created yet.
We should prevent the Backup from triggering before the snapshot is found.
~~Introduce new state to the Backup CR: preparing~~
Reuse the status: `Pending`
and add some information to the Messages when the Backup is still waiting for the snapshot or engine.
When the backup starts
the message and the state will be override by the monitor
~~Note:~~
~~`Pending` state has been used for another purpose~~

Lh8650 make backup wait for snapshot

---

controller/uninstall_controller.go

Issue # longhorn/longhorn#8784

fix(uninstall): ignore the error 'the object has been modified' when touching backup targets

---

csi/node_server.go

longhorn/longhorn#2907
XFS does not allow to mount two volumes that have the same UUID on the same machine. This is problematic when using a cloned volume or a restored snapshot - the original volume and the new volume cannot be mounted on the same compute node.
This PR disables uuid checks on XFS same as other CSI providers:
1. https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1204/files
1. https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver/pull/570/files
1. https://github.com/topolvm/topolvm/pull/522/files

Disable uuid checks on XFS

---

csi/node_server.go

Like @shuo-wu mentioned in the US sync meeting, we don't need to do this NodePublishVolume because bind mount will preserve the mount options from NodeStageVolume
longhorn/longhorn#8796

Only need to force ignore xfs uuid in NodeStageVolume

---

controller/backup_controller.go
types/setting.go

https://github.com/longhorn/longhorn/issues/8365
When users create a Bakcup, LH automatically creates a related Snapshot. However, when users delete the Bakcup, LH doesn't cleanup the Snapshot. This occupies snapshot quota. We have snapshot space management now, so it's better to clean up related resources.
Case 1: set `auto-cleanup-when-delete-backup` as `false`
1. Create a volume and setup backup target.
2. Mount the volume.
3. Create multiple backups.
4. Delete a backup and check related snapshot is not removed.
Case 2: set `auto-cleanup-when-delete-backup` as `true`
1. Create a volume and setup backup target.
2. Mount the volume.
3. Create multiple backups.
4. Delete a backup and check related snapshot is removed too.

feat: remove related snapshot when removing backup

---

constant/events.go
controller/snapshot_controller.go

longhorn/longhorn#4126
Before this PR, we would emit events with type Warning when scaling up a volume by two replicas, even though nothing was actually wrong. Check https://github.com/longhorn/longhorn/issues/4126#issuecomment-1158156580 for context. We emitted warnings in response to two occurrences:
1. The snapshot controller saw that a snapshot which was previously NOT marked as removed in the engine became marked as removed. There's really no reason for there to be a warning here. It is just normal behavior when we try to purge the snapshot behind `volume-head`.
2. The engine monitor removed a snapshot from the engine CR and then deleted the corresponding snapshot CR. If the snapshot controller reconciled between the two events, it noticed the snapshot was no longer in the engine CR …

Don't emit a warning for normal snapshot delete operations

---

controller/volume_controller.go
controller/volume_controller_test.go
datastore/longhorn.go
scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go

Issue longhorn/longhorn#1992
- Before creating a new Replica CR, verify the availability of suitable nodes with sufficient disk to accommodate the replica. This prevents creating Replicas that cannot be scheduled.
- During node disk candidate selection, exclude nodes where the InstanceManager is not in a running state. This prevents creating redundant Replica CRs on nodes that haven't fully recovered after a power down.
`None`
`None`

fix(replica-scheduling): power off replica node should not rebuild new replica on same node

---

controller/setting_controller.go

Issue Longhorn/longhorn#8865
updateLogLevel() is for logrus log level.
v2-data-engine-log-level will be applied in instance-manager controller.

fix(log): fix v2-data-engine-log-level is not applied

---

app/post_upgrade.go

It is expected that Longhorn manager pod has multiple contains (some of them are image pre-pull containers)
longhorn/longhorn#8866

Fix bug: don't fail post upgrade check if longhorn-manager pod has multiple containers

---

controller/volume_controller.go
controller/volume_controller_test.go
k8s/pkg/apis/longhorn/v1beta2/node.go

Issue longhorn/longhorn#8867
- Set volume condition scheduled to false when failed at replica creation precheck.
- Add a condition to check if the Replica count equals or is greater then volume.Spec.NumberOfReplicas before set volume condition scheduled to true.
`None`
- https://github.com/longhorn/longhorn-manager/pull/2918

fix(volume): wrong scheduled condition

---

controller/instance_manager_controller.go

Longhorn/longhorn#8456
An extra instance manager pod for v2 data engine requires an additional CPU core and 2 GiB of memory. If the resources are insufficient, the instance manager pod will be recreated and retried. To minimize unnecessary retries, do not create any new instance manager pods if one is already running.

Do not create any instance manager pods for v2 volumes if one is already existing

---

api/backupbackingimage.go
api/router.go
manager/backupbackingimage.go

ref: https://github.com/longhorn/longhorn/issues/8849
- reject backup backing image restoration if backing image already exists
- reject backing image backup if backup already exists
- add websocket for backup backing image

feat(backup backing image): add websocket for backup backing image

---

controller/volume_controller.go

Issue longhorn/longhorn#8872
Before marking the volume as scheduled, we need to check the replica replenish count. Otherwise, the controller might accidentally mark it as scheduled when the replica count is correct, but new replicas are actually expected and are being blocked by the pre-check.
`None`
`None`

fix(volume-controller): mark volume as scheduled when no more replicas to replenish

---

controller/backing_image_controller.go
datastore/longhorn.go

spec.disks has been deprecated
fix to use spec.diskSpecMap

fix: backing image ha and encryption conflicts

---

controller/engine_controller.go

longhorn/longhorn#8952
The monitor update engine.Status.CloneStatus to a non-nil value and the PR https://github.com/longhorn/longhorn-manager/pull/2895 set it back to nil. They are fighting each other leading to unnecessarily repeatedly engine CR updates

Fix bug engine.status.clonestatus is unnecessarily repeatedly updated

---

constant/events.go
controller/utils.go
controller/volume_attachment_controller.go
controller/volume_controller.go
csi/controller_server.go
datastore/longhorn.go
util/volume.go
webhook/resources/volumeattachment/validator.go

longhorn/longhorn#8735
See context at https://github.com/longhorn/longhorn/issues/8735#issue-2347139063 and implementation plan at https://github.com/longhorn/longhorn/issues/8735#issuecomment-2177309258.
~This is a draft for now as I work on testing it in all situations.~

Improve interaction between volume attachment controller and migrations

---

controller/volume_controller.go

Issue longhorn/longhorn#4105
The `rNames` variable is declared inside the if statement, which shadows the outer `rNames` variable. Hence it has no effect on the outer variable.
`None`
- https://github.com/longhorn/longhorn/issues/4105#issuecomment-2216989458
- https://github.com/longhorn/longhorn-manager/pull/2547/commits/3518ab56cda494cd45da43077e20c31d79f20c9a

fix(volume-controller): rNames shadowed in cleanupAutoBalancedReplicas

---

controller/engine_controller.go
controller/instance_handler.go
controller/replica_controller.go
engineapi/instance_manager.go
go.mod
go.sum
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/instancemanager.go
vendor/github.com/longhorn/longhorn-instance-manager/pkg/api/instance.go
vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/instance.go
vendor/modules.txt

feat(upgrade): support V2 volume upgrade

---

app/daemon.go
app/pre_upgrade.go
controller/node_controller.go
controller/node_controller_test.go
k8s/pkg/apis/longhorn/v1beta2/node.go
package/Dockerfile

Issue # longhorn/longhorn#7571
Check if the environment settings are achieved, ref: [environment_check.sh](https://github.com/longhorn/longhorn/blob/master/scripts/environment_check.sh)

fix: check if environment settings are achieved

---

controller/volume_controller.go

ref: https://github.com/longhorn/longhorn/issues/8874
fix recurring job recreating even the job already exists issue
`reflect.DeepEqual` considers `nil` and `map[]` are different, need to init the map struct before comparing

fix: fix recurring job recreate issue

---

csi/crypto/crypto.go
csi/deployment.go

longhorn/longhorn#9000
https://github.com/longhorn/longhorn/issues/9000#issuecomment-2228720946
- `examples/block/crypto` works with this PR (from https://github.com/longhorn/longhorn/issues/9000#issuecomment-2227888212).
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7224 - PASSED
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7225 - PASSED
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7226 - PASSED
- https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7228/ - PASSED
- I also set up a storage network and tried some basic attach/detach operations and everything worked.
@c3y1huang, can you foresee any issues with Talos / container optimized distros?

fix(crypto): execute cryptsetup in the host namespace again

---

controller/setting_controller.go
controller/share_manager_controller.go
csi/node_server.go
csi/util.go
datastore/kubernetes.go

Issue longhorn/longhorn#8999
This PR addressed a regression where remounting NFS volume hangs for an extended period before succeeding. The regression is a side effect from  https://github.com/longhorn/longhorn-manager/pull/2815, and the way the share manager's Service is cleaned up caused the remounting to hang after the share manager Pod restarts.
This PR proposes moving the responsibility of cleaning up the Service and Endpoint to the setting controller. This is a more logical fit since the setting controller handles the storage network change, which aligns better with the purpose of this cleanup process. This change should eliminate the race condition.
`None`
- https://github.com/longhorn/longhorn/issues/8999#issuecomment-2228183416

Fix(RWX):  long remount time when share manager pod restart

---

controller/kubernetes_pod_controller.go

longhorn/longhorn#9019
This is a "directly created backport' to v1.6.x since the commit we need has unrelated code.

fix: prevent pod reconcile storm when remount requested

---

controller/kubernetes_pod_controller.go

longhorn/longhorn#9019
This is a "directly created backport' to v1.5.x since the commit we need has unrelated code.

[BACKPORT][V1.5.6] fix: prevent pod reconcile storm when remount requested

---

util/util.go

Issue longhorn/longhorn#6868
Propose extending the execution timeout for the `fstrim` command to 1 hour for v1.7.0. In the future release, we can work on enhancements such as running sync or making the timeout configurable.
I've not been able to reproduce the timeout issue as mentioned in the issue. In my environment, the `fstrim` completes quickly, However, my test data size is relatively small (100G). cc @longhorn/qa 
`None`

Fix(trim): extend the timeout

---

csi/deployment.go
csi/deployment_util.go
types/types.go

ref: https://github.com/longhorn/longhorn/issues/7938
enable csi sidecar metrics on port 8000
- csi-attacher
- csi-provisioner
- csi-resizer
- csi-snapshotter
cc @PhanLe1010

feat(csi metrics): enable csi sidecar metrics

---

datastore/longhorn.go
types/types.go

Issue Longhorn/longhorn#9073
Non-existing block device results in longhorn-manager pods to be in Crashloopbackoff state. When longhorn-manager pods are in Crashloopbackoff, users are unable to update the default-data-path setting.

fix(disk): non-existing block device results in longhorn-manager to be in Crashloopbackoff state

---

controller/backup_target_controller.go
controller/backup_volume_controller.go

No particular linked issue. I saw the following logged when I configured a backup target in my cluster and I was quite confused.
```
[longhorn-manager-qwx8h longhorn-manager] time="2024-07-24T14:47:28Z" level=info msg="Found 1 backup volumes in the backup target that do not exist in the backup target and need to be deleted" func="controller.
```
The repeated mention of "backup target" doesn't make sense, and I was worried that backups were being deleted from the target itself, which I would not expect. (That is not the case, so the log can be clarified.)

chore(backup): clarify deletion log message

---

controller/share_manager_controller.go

longhorn/longhorn#9086
My preferred solution. There is no reason to enqueue the share manager in hopes of catching the pod with containers ready. The share manager controller has a pod informer that will enqueue the share manager any time the pod status changes.
Reduced number of reconciles with the following message to 34 on `master-head`. (Even this number is inflated, because it accounts for reconciles from all share manager controllers in the cluster. In the buggy case, the tens of thousands were additional reconciles from only the owner).
```
[longhorn-manager-mckzz longhorn-manager] time="2024-07-25T21:44:39Z" level=warning msg="=====> In syncShareManager with state starting" func="controller.(*ShareManagerController).syncShareManager" file="share_manager_controller.go:333" …
```

fix: rely on pod informer to requeue while share manager is starting

---

controller/share_manager_controller.go
controller/volume_controller.go
datastore/kubernetes.go

If the volume is faulted, we don't need to have RWX fast failover.
If shareManager is delinquent, clear both delinquent and stale state.
If we don't do that, the volume will get stuck in the auto-savage loop.
See https://github.com/longhorn/longhorn/issues/9089
New statemachine

If the volume is faulted, we don't need to have RWX fast failover.

---

controller/share_manager_controller.go

Related to longhorn/longhorn#6205

Performance optimisation: skipping checkLeasesAndEnqueueAnyStale if the setting SettingNameRWXVolumeFastFailover is not enabled

---

controller/node_controller.go
go.mod
go.sum
vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/disk.go
vendor/modules.txt

fix(disk): no need to check disk UUID while deleting a disk 

---

csi/deployment.go

Related to work done for longhorn/longhorn#9223.
I noticed a typo in a comment. It made it more difficult to understand.
Should be backported to `v1.7.x` as well, but should not gate any release activities, etc.

fix(typo): add intended word to make comment less confusing

---

controller/setting_controller.go
controller/share_manager_controller.go
datastore/longhorn.go

Issue https://github.com/longhorn/longhorn/issues/9272
We meet a corner case that the service/endpoint would not be cleanup. That will cause the service keep the ClusterIP `None`. With this config, the endpoint of sharemanager would not be correct, so the CSI driver cannot perform the mountpoint well.
We would like to have a checking mechanism to know if the service/endpoint did not cleanup. Then we will cleanup the service/endpoint to ensure the correct endpoint.

fix(networking): cleanup service/endpoint if needed

---

controller/instance_manager_controller.go

Issue # https://github.com/longhorn/longhorn/issues/9183
btw: https://github.com/longhorn/longhorn/issues/5910
Test log of manual attached volume when drain node
```
time="2024-08-05T18:48:14Z" level=info msg="Node instance-manager-68cd2514dd3f6d59b95cbd865d5b08f7 is marked unschedulable but removing harv2 PDB is blocked: some volumes are still attached " func="controller.(*InstanceManagerController).syncInstanceManagerPDB" file="instance_manager_controller.go:730" controller=longhorn-instance-manager node=harv2
```
This is a manual backport to replace https://github.com/longhorn/longhorn-manager/pull/3098, which has conflicts and I have no rights to push to/on-top-of it.

fix(manager): add detailed message when deleting pdb is not allowed (backport #3045)

---

datastore/longhorn.go

Issue https://github.com/longhorn/longhorn/issues/9319
So we can enable the v2 data engine without needing to allocate hugepages on disabled nodes

fix(datastore): skip disabled nodes in ValidateV2DataEngineEnabled

---

engineapi/instance_manager.go

We forget to set disableRevCounter for the newly live upgraded engine. As a result, the newly live upgraded engine always has disableRevCounter as `false` even if the volume has disableRevCounter as `true`.
This mismatch prevents the volume from successfully rebuilding a new replica.
longhorn/longhorn#9331

fix(live upgrade): newly live upgraded engine doesn't respect the disableRevCounter setting

---

controller/system_backup_controller.go
controller/system_rollout_controller.go

Issue longhorn/longhorn#9330
A DR volume doesn't need to have its volume data backed up and should retain and use the `FromBackup` field in the system backup.
`None`
`None`

fix(system-backup/restore): DR volume

---

types/setting.go
upgrade/v16xto170/upgrade.go

ref: https://github.com/longhorn/longhorn/issues/9352
When upgrading Longhorn to v1.7.x
The BackingImage will have minNumberOfCopies = 0
Need to set the default value in upgrade path.

fix(backingimage): set default min number of copies when upgrading

---

upgrade/upgrade.go
upgrade/v170to171/upgrade.go

ref: https://github.com/longhorn/longhorn/issues/9352
add upgrade path
1.7.0 -> 1.7.1

[BACKPORT v1.7.x] fix(backingimage): set default min number of copies of backing image

---

controller/node_controller.go
controller/node_controller_test.go

longhorn/longhorn#7738
Key change:
- A defer statement and a `nodeReady` conditional variable now ensure we don't record ready (i.e. log and emit an event) during the check for a manager pod just to later record not ready during the Kubernetes node status check.
Additional changes:
- A nil pointer exception used to be possible in this controller, though the severity and potential to hit it was extremely low. (It probably required a longhorn-manager pod running on a node that was actively being removed from the cluster. In this situation, a crash is probably fine.) The exception should no longer be possible.
- The logic for setting `Ready` and `Schedulable` is now broken out into a separate function.

fix: don't log NodeReady is true and false in same reconcile loop

---

controller/backup_target_controller.go
engineapi/backups.go
types/setting.go

Issue # longhorn/longhorn#8954 longhorn/longhorn#8319
Add a default setting `backupExecutionTimeout`

fix(backup): customize the timeout of backup binary execution

---

controller/setting_controller.go
datastore/longhorn.go

Issue # longhorn/longhorn#9391
Delete the old storage class set in reconciling the `default-longhorn-static-storage-class` setting.
Create the storage with a label if the storage class named as the value of `default-longhorn-static-storage-class` setting does not exist.

fix(setting): do not delete the storage class set in the setting `default-longhorn-static-storage-class`

---

csi/crypto/crypto.go
csi/node_server.go

Issue # longhorn/longhorn#9385
In the normal process of attaching a volume via CSI, the encrypted volume should be closed or inactivated before Longhorn attempts to open it.
Full regression test:
~https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7529~
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7538/

fix(encrypt): close encrypted volume if it is opened

---

metrics_collector/backup_collector.go
metrics_collector/types.go

Issue N/A
Monitoring on usage of Backup per recurring job so we can trace the type of backup applied by PVC
Tried to understand documentation here and on longhorn-tests, but I am thoroughly confused on how to test a simple code change without creating a new version.
`make`/`make test` and CI seems to work though.
Our recurring jobs, to trace usage/granularity per PVC, so we can raise alarms on certain pods not being backed up enough etc...
```yaml
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
name: backup-weekly
namespace: longhorn-system
spec:
cron: "@weekly"
task: "backup"
groups:
- backup-weekly
- backup-daily
- backup-hourly
retain: 12
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
name: backup-daily
namespace: longhorn-system
spec:
cron: "@daily" …
```

feat(metrics): Add recurring job label to backup metrics or empty value

---

api/model.go
client/generated_backup_backing_image.go
controller/backup_backing_image_controller.go
engineapi/backing_image_manager.go
engineapi/backup_backing_image.go
go.mod
go.sum
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/backupbackingimage.go
vendor/github.com/longhorn/backing-image-manager/pkg/client/manager_client.go
vendor/modules.txt

ref: https://github.com/longhorn/longhorn/issues/8884
update
- `backupBackingImage` status CRD to add `secret` and `secretNamespace`
- pass the `secret` and `secretNamespace` to `backing-image-manager` through grpc using `parameters`
- update `backupBackingImage` api model to pass the `secret` and `secretNamespace` to UI

feat(backupbackingimage): add parameters to backup backing image create proto

---

controller/engine_controller.go
controller/instance_manager_controller.go
controller/replica_controller.go
engineapi/instance_manager.go

longhorn/longhorn#6552
See https://github.com/longhorn/longhorn/issues/6552#issuecomment-2319177183 for context. It may be possible to delete engine and replica processes from an instance-manager even when the instance-manager's state is unknown. Doing so prevents the processes from becoming orphans if the instance-manager eventually recovers from the unknown state.
This PR is looking good in some local testing, but I want to put it through a few more paces before review.

fix: attempt to delete processes from instance-managers in unknown state

---

controller/engine_image_controller.go
manager/volume.go

https://github.com/longhorn/longhorn/issues/9389
Stopgap to prevent live engine upgrade on attached strict-local volumes.

fix(upgrade): block live upgrade of strict-local

---

k8s/crds.yaml
k8s/patches/crd/webhook/engineimage.yaml

Issue Longhorn/longhorn#9438
longhorn/longhorn crds.yaml is already updated.
Correct the port number to avoid any confusion.

fix(crd): update conversion webhook port to 9501

---

controller/volume_controller.go
datastore/longhorn.go
metrics_collector/volume_collector.go

ref: https://github.com/longhorn/longhorn/issues/8508
Export the metrics in the following form
- metric name: `longhorn_volume_file_system_read_only`
- type: gauge
- if the volume becomes read-only, it has metric value 1 with the corresponding labels
- So you know which volume is in read-only mode now
- You can sum up the metrics to see how many volumes are in read-only mode now 
```
longhorn_volume_file_system_read_only{node="kworker1",pvc="nginx",pvc_namespace="default",volume="pvc-3a7a208b-c8c9-46a9-b2ce-4c5f740c8673"} 1
```
Note:
If Longhorn remounts the mount point to read-write successfully, the metrics will be cleaned up.
The metric is either 1 or no record for each volume

feat(metrics): add volume filesystem read only state metrics

---

controller/setting_controller.go

This will prevent the upgrade responder from having too many tags which can be a performance issue
longhorn/longhorn#9522

fix: aggregate "*-dev-*" versions into single "dev" version

---

k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/backingimage.go

ref: https://github.com/longhorn/longhorn/issues/8757
add unit to the size field description in BackingImage

docs: add unit to the backing image size description

---

controller/volume_controller.go

Issue longhorn/longhorn#9514
Update PV volume-scheduling-error annotation when the replica schedule precheck fails.
`None`
`None`

fix: pv volume-scheduling-error not consistent with volume condition

---

controller/backup_backing_image_controller.go
controller/backup_controller.go
controller/backup_target_controller.go
controller/backup_volume_controller.go
controller/system_backup_controller.go
controller/system_backup_controller_test.go
controller/utils.go
datastore/longhorn.go
types/types.go
webhook/resources/backupvolume/mutator.go

Issue # longhorn/longhorn#9530
Only delete backups' resources (BackupVolume, BackupBackingImage, SystemBackup, and Backup) when synchronization.
Add the label `DeleteCustomResourceOnly`, and delete remote backup data when deleting the corresponding backup resource in the cluster and the label does not exist.

fix(backup): only delete backups' resources when synchronization

---

controller/node_controller.go

Issue Longhorn/longhorn#9616
The wrong logic is introduced in the refactor commit https://github.com/longhorn/longhorn-manager/pull/3138

fix: fix node readiness condition logic

---

controller/backup_controller.go
controller/backup_volume_controller.go
engineapi/backups.go
k8s/pkg/apis/longhorn/v1beta2/backup.go
types/types.go

ref: https://github.com/longhorn/longhorn/issues/8746
follow LEP to implement: https://github.com/longhorn/longhorn/pull/9152
- Make backup deletion asynchronous
- Add Deleting state to Backup
- Add deleting in-memory map to allow go routine to pass the command failure to the controller.
- Add backoff to delay deletion command execution. 
- When the Backup is being deleted it should follow the following diagram
- Disallow backup creation when there is any backup being deleted.
```
Completed => Deleting 
=> finalizer removed (CR isgone)
Completed => Deleting 
=> Error (found the error message in the map) 
=> Deleting (Retry the command) => finalizer removed (CR isgone)
Completed => Deleting 
=> Error (failed to find the record in the map)
=> Deleting (Retry the command) => finalizer …
```

feat(backup): delete backup in the backupstore asynchronously

---

scripts/package

fix: don't build longhorn-manager twice before packaging

---

package/Dockerfile

Issue Longhorn/longhorn#8744
The packages aren't updated frequently, so the content of the image layer usually remains unchanged.
To avoid unnecessary rebuilding of this layer, copy the longhorn-manager binaries after installing the packages.

chore(dockerfile): reduce packaging time

---

controller/node_controller.go

Issue longhorn/longhorn#9558
https://github.com/longhorn/longhorn/issues/9558#issuecomment-2443161797
`None`
https://github.com/longhorn/longhorn/issues/7571

feat(env-check): support Talos Linux 

---

app/daemon.go
util/util.go

Part of https://github.com/longhorn/longhorn/issues/6702
Suppress logging of incoming REST GET queries unless log level is debug or more.  They can overwhelm all other logging.
this should backport to 1.6 and 1.7.

fix(logging): only log GET requests at debug level

---

app/post_upgrade.go
app/pre_upgrade.go

Issue https://github.com/longhorn/longhorn/issues/9569
Add a sleep after Run() before panicking to let the queued event get flushed.  We thought that eventBroadcaster.Shutdown() would take care of that, and it did in some testing, but there is still a race and it does not work reliably.  QA found that while testing the feature and I did reproduce it - see the note in https://github.com/longhorn/longhorn/issues/9569#issuecomment-2425705470
This is the simplest fix.  We could do something more complicated, like calling Watch() on the events and waiting for it to appear, but there is no need to speed up the exit as soon as possible.  The upgrade will not go forward anyway.  The important thing is to guarantee the event can be found so the problem can be corrected.

fix(upgrade): add sleep to allow event to flush before panic

---

controller/system_backup_controller.go
controller/system_backup_controller_test.go

Issue longhorn/longhorn#6027
When the system backup volume backup policy is set to `if-not-present`, check the last backup and create a backup when it's outdated. 
https://github.com/longhorn/longhorn/issues/6027#issuecomment-2445884734
`None`
`None`

feat(system-backup): check outdated backup in if-not-present volume backup policy

---

controller/volume_controller.go
engineapi/instance_manager.go
go.mod
go.sum
manager/volume.go
vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/instance.go
vendor/modules.txt

Issue longhorn/longhorn#8430
Support auto-salvage for v2 volumes.
`None`
`None`

feat(auto-salvage): v2 support

---

app/driver.go
csi/deployment.go

Issue longhorn/longhorn#9580
- Remove the default CSI component images from the command flag.
- Validate the required command flags are not empty.
`None`
`None`

chore: remove default CSI component images

---

controller/node_controller.go

Issue # https://github.com/longhorn/longhorn/discussions/9823 https://github.com/longhorn/longhorn/issues/9829
- Added package validation logic for Red Hat Enterprise Linux (RHEL).

fix: support red hat package validation to resolve unknown os event

---

controller/instance_manager_controller.go
controller/setting_controller.go

Issue https://github.com/longhorn/longhorn/issues/6702
Sync the log level with instance-managers.

fix(logging): make RPC call to instance-manager to set log level

---

datastore/longhorn.go
webhook/resources/volume/mutator.go

feat: allow v2 volume to attach on the an old and running instance-manager pod

---

webhook/resources/persistentvolumeclaim/validator.go
webhook/server/validation.go

Issue longhorn/longhorn#6633
Introduce a PVC admission validator to prevent PVC expansion requests that exceed the storage maximum size.
`None`
`None`

fix(expansion): Prevent oversize PVC expansion requests

---

controller/instance_manager_controller.go

- log the deletion of isntance manager pod
- rename cleanupInstanceManager() to cleanupInstanceManagerPod()
Issue longhorn/longhorn#9886

feat: log the deletion of isntance manager pod

---

controller/volume_controller.go

Issue longhorn/longhorn#9916
When new replicas are created, the following error messages are emitted in the longhorn-manager. Empty timestamp is expected in this case, so the error messages are misleading.

fix: change misleading error message to warning level

---

types/types.go
webhook/resources/volume/validator.go

Issue longhorn/longhorn#6735
When the server node is down, the RWX NFS server is unable to create on another node because of the strict-local volume. Also, strict-local is for distributed application only. Distributed application means it has replication capability, so they will only RWO.

feat(webhook): reject strict-local RWX volume creation

---

datastore/longhorn.go

Issue Longhorn/longhorn#9943
Because there is only one active instance manager image for v2 data engine, find a running instance manager for v2 data engine.

fix: find running instance manager for v2 data engine

---

controller/controller_test.go
controller/node_controller.go
controller/node_controller_test.go
k8s/pkg/apis/longhorn/v1beta2/node.go
vendor/github.com/longhorn/go-common-libs/nfs/nfs.go
vendor/modules.txt

Issue longhorn/longhorn#9830
Though the node supports NFSv4, the NFS client picks the protocol version by `Defaultvers` defined in host's `/etc/nfsmount.conf`. This may cause problem while using backup-related features.

feat(env-check): check NFS default protocal version

---

controller/instance_manager_controller.go
datastore/kubernetes.go

ref: https://github.com/longhorn/longhorn/issues/9851
Extend the liveness probe failure timeout.
Period: every 30 seconds
Timeout: every 29 seconds if command not response
FailureThreshold: 3 times failure in a row.

fix: extend im pod liveness probe failure timeout

---

controller/node_controller.go
controller/volume_controller.go
datastore/kubernetes.go

Issue https://github.com/longhorn/longhorn/issues/9093
Do a fail-safe clearing of RWX fast-failover status still pending on a node that is NotReady.  If it hasn't already happened, it is too late for fast failover, so let the normal IsNodeDownOrDeleted logic take over.

fix: clear fast-failover status when node goes not ready

---

controller/volume_controller.go
k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/replica.go

feat: support v2 volume live migration

---

controller/instance_manager_controller.go

Issue longhorn/longhorn#9959
Introduce pre-stop script to the instance manager pod lifecycle.
`None`
`None`

fix(v2): clean up v2 resources on instancemanager pod pre-stop

---

controller/kubernetes_node_controller.go
types/types.go

Issue # https://github.com/longhorn/longhorn/issues/9871 https://github.com/longhorn/longhorn/discussions/9797
This PR addresses a bug where the Storage Reserved value is incorrectly set to 0 during automatic disk registration when using Engine v2 block type.
To retrieve the total capacity of the block device, the implementation uses unix.Syscall.
If there is a more efficient or reliable approach to gather block device capacity, please provide your suggestions or feedback.

feat: add automatic storage_reserved calculation for block type disks

---

controller/node_controller.go
k8s/pkg/apis/longhorn/v1beta2/node.go

Issue https://github.com/longhorn/longhorn/issues/9983
This PR introduces a checkHugePages function to the Longhorn NodeController. The purpose of this function is to periodically verify the configuration and availability of HugePages (2Mi) on Kubernetes nodes.

feat: add check for hugepages configuration

---

api/backup.go
api/model.go
api/router.go
api/volume.go
controller/backup_controller.go
controller/uninstall_controller.go
csi/controller_server.go
datastore/longhorn.go
manager/engine.go
manager/kubernetes.go
manager/volume.go
webhook/resources/backuptarget/validator.go

fix(backup): modify backup volume/volume APIs and naming

---

api/model.go

Modify the name of the action `updateBackupTargetName` of volume in the api/router.go to `updateBackupTarget` to match the name in api/model.go.

fix(backup): correct mismatch action name of volume API

---

webhook/resources/backupbackingimage/validator.go

ref: https://github.com/longhorn/longhorn/issues/10020

fix: use backup backing image spec backing image name when getting backing image CR

---

controller/backup_backing_image_controller.go
controller/monitor/disk_monitor.go
controller/monitor/environment_check_monitor.go
controller/monitor/monitor.go
controller/monitor/snapshot_monitor.go
controller/node_controller.go
controller/node_controller_test.go
engineapi/backup_backing_image.go
types/condition.go

Issue longhorn/longhorn#9983
- Move environment checks to a dedicated monitor
- Remove hugepage condition after disabling v2 data engine
- Increase the environment check period to 30 minutes

fix: move environment checks to a dedicated monitor

---

upgrade/v17xto180/upgrade.go

fix(upgrade): fix upgrade issues from v1.7.x to v1.8.0

---

webhook/resources/backupbackingimage/validator.go

Issue #ref longhorn/longhorn#10026, longhorn/longhorn#6341
Do not get the backing image custom resource if the backup backing image is synchronized from the remote backup target because the backing image might not exist.

fix(backup): do not get backing image custom resource

---

controller/backing_image_controller.go

ref: 
- https://github.com/longhorn/longhorn/issues/9976
- https://github.com/longhorn/longhorn/issues/9882
We found that the real size may change when syncing with other nodes.
And it may also changes when transferring to different OS.

fix: ignore backing image real size inconsistency between nodes

---

controller/monitor/disk_monitor.go
controller/monitor/environment_check_monitor.go
controller/monitor/fake_disk_monitor.go
controller/monitor/fake_environment_check_monitor.go
controller/node_controller.go
controller/node_controller_test.go

fix(monitor): set monitors to nil after closing them

---

controller/monitor/disk_monitor.go
controller/node_controller.go

Issue Longhorn/longhorn#10035
No need to close the monitors after deleting a node resource. If a node is gone, monitor will return error and won't continue the following tasks.
e2e
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2295/console

fix(monitor): remove the close of monitors

---

api/backupbackingimage.go
api/model.go
client/generated_backing_image_restore_input.go
controller/system_backup_controller.go
manager/backupbackingimage.go
manager/volume.go

ref: 
- https://github.com/longhorn/longhorn/issues/6341
- https://github.com/longhorn/longhorn/issues/10023
Fix:
- generate UUID for backupBackingImage when backing up from UI  (cc @mantissahz )
- To fix: https://github.com/longhorn/longhorn/issues/10023
- add `DataEngine` option in restoring backup backing image
- restore volume will check the existing backing image dataEngine or restore backupBackingImage with correct dataEngine
cc @derekbit @mantissahz @houhoucoop

fix: add data engine option to restore backing image api

---

webhook/resources/backupbackingimage/validator.go

ref: longhorn/longhorn#10023
reject creating the same backing image to the same backup target
- Create a backup backing image to BackupTarget: `nfs`
- Do the same operation again, it should be reject because it already exists.
Since now the BackupBackingImage name has suffix random UUID
So this is not blocked naturally and need to use webhook to do the validation.

fix: reject creating the same backing image to the same backup target

---

controller/monitor/disk_utils.go

feat: change the AIO disk block size to 512 bytes for v2 data engine

---

app/daemon.go

Issue longhorn/longhorn#10054
Introduce leader election to sequentially start webhook servers, one node at a time.
`None`
`None`

fix(webhook): endless secret update retries

---

controller/monitor/environment_check_monitor.go

Issue longhorn/longhorn#10019
Instead of reading the system package database, check the executables needed by the system, to eliminate the system management tool chain issue.

feat(env-check): remove dependency of system package manager from node env checker

---

controller/controller_test.go
controller/system_backup_controller.go
controller/system_backup_controller_test.go
controller/system_restore_controller_test.go
controller/volume_controller.go

Issue # longhorn/longhorn#5411, longhorn/longhorn#10057
In `enqueueVolumesForBackupVolume` of volume controller, it needs to use BackupVolume.Spec.VolumeName` to get volume CR instead of `BackupVolume.Name`.
Run test cases:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7981
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7986 
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7995
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8001
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8012
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8013
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8014
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8015

fix(backup): enqueue volumes with correct names

---

csi/controller_server.go

ref: https://github.com/longhorn/longhorn/issues/10084
backing image should be created with the same data engine as volume in storageclass

fix: backing image should follow the same data engine as volume in strorageclass

---

app/daemon.go
controller/kubernetes_configmap_controller.go
datastore/longhorn.go
types/setting.go
types/types.go
util/util.go

Issue # longhorn/longhorn#5411, longhorn/longhorn#10089
Separate the default backup related settings from default settings into a new yaml file `default-backupstore-setting.yaml`. Check if ConfigMap `longhorn-default-backupstore-settings` changed to update the default backup target.

feat(backup): separate backup settings from default settings

---

controller/node_controller.go

Issue Longhorn/longhorn#10121
Unlink a filesyste-type disk that contains log, etc and other files, there is no need to truncate block-type disk's StorageAvailable value.

feat: no need to truncate block-type disk's StorageAvailable value

---

controller/backup_target_controller.go
controller/system_backup_controller.go
controller/system_backup_controller_test.go
controller/uninstall_controller.go
datastore/longhorn.go
types/types.go
upgrade/util/util.go
upgrade/v17xto180/upgrade.go
webhook/resources/systembackup/mutator.go

Issue # longhorn/longhorn#10104
Deleting failed backups failed when uninstalling because failed backups will not update the backup target name in the `Status`.
Clean up system backups when deleting the default backup target. Add OwnerReferences with default backup target into system backups.

fix(uninstall): deleting failed backups when uninstalling

---

types/setting.go

Issue Longhorn/longhorn#9794
Experimental: An early stage "Preview," these features truly are experiments and might never reach GA.

fix: use `experimental` for alpha features

---

app/recurring_job.go
controller/backup_controller.go

https://github.com/longhorn/longhorn/issues/10090
This PR has 2 commits:
1. fix: recurring job should not fail on pending backup
2. fix: backup with non-existing snapshot should be marked as errored
Right now, backup with non-existing snapshot is stuck in pending forever.
This is not good because it will keep the volume in attached state
forever.
Moreover, snapshot doesn't exist is a non-recoverable error so
the backup should be marked as errored
**Before the fix**
Deploying a backup with non-existing snapshot 
```yaml
apiVersion: longhorn.io/v1beta2
kind: Backup
metadata:
name: test-backup
namespace: longhorn-system
labels:
backup-volume: pvc-34e83a41-bb6a-4406-b9d9-91fe3a8fcfbc
spec:
backupMode: incremental
snapshotName: non-exist-snapshot-name
```
The backup will stuck in pending state …

fix: handle backup with non-existing snapshot and fix recurring job to correctly handle pending backup 

---

controller/backup_controller.go
util/timed_counter.go
util/timed_counter_test.go

Prevent the backup CR from being stuck in the pending state forever. Backup creation will only be retried up until max retry
longhorn/longhorn#10090

fix: add retry max retry mechanism for backup creation

---

controller/share_manager_controller.go
csi/crypto/crypto.go
csi/node_server.go
webhook/resources/volume/validator.go

Issue # longhorn/longhorn#7355

feat(crypto): v2 volume encryption

---

controller/monitor/environment_check_monitor.go

chore: update the comment in environment_check_monitor.go

---

controller/backup_target_controller.go
controller/monitor/disk_monitor.go
controller/monitor/environment_check_monitor.go
controller/monitor/fake_environment_check_monitor.go

Issue Longhorn/longhorn#10190
There are 5 workers in each controller, so the map bsTimerMap should be protected by lock.

fix: backupTargetController.bsTimerMap should be protected by lock

---

k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/backup.go

fix: incorrect field name for backup target in printcolumn

---

controller/system_backup_controller.go
controller/system_backup_controller_test.go

Issue # longhorn/longhorn#10215
The snapshot of the last backup of the volume might be removed. Therefore, volume backup will not be up to date and needs to create a new backup.
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8300/ - passed

fix(system-backup): handle snapshot of last backup removed

---

controller/system_backup_controller.go

Issue # longhorn/longhorn#6027, longhorn/longhorn#9330, longhorn/longhorn#10239

fix(system-backup): skip backup if it is a DR volume

---

types/types.go

fix: fix v2 log flag validation

---

scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go

**Root cause:**
The root cause of the issue longhorn/longhorn#10210 with [the reproducing steps ](https://github.com/longhorn/longhorn/issues/10210#issuecomment-2594392777) is that when `Replica Disk Level Soft Anti-Affinity` is `false`, Longhorn never considers a disk which contains a failed replica as a valid candidate.
**Propose solution:**
We should not exclude the disk which has failed replica in 2 cases:
1. The caller is trying to reuse the failed replica, this disk is a valid candidate
2. The failed replica is no longer reusable, this disk is a valid candidate
**Test plan:** 
https://github.com/longhorn/longhorn/issues/10210#issuecomment-2600594553
longhorn/longhorn#10210

fix: bug cannot use the disk which has failed replica

---

.github/workflows/create-crd-update-pr-in-longhorn-repo.yml

Issue Longhorn/longhorn#10193
- Fix the secrets not found error by `pull_request_target`
- Fix committer for passing DOC check.
- Create PR after opening, editing or synchronizing the longhorn-manager PR.

fix(workflow): fix create-crd-update-pr-in-longhorn-repo.yml

---

controller/kubernetes_pod_controller.go

pv is not always the same as pv.Spec.CSI.VolumeHandle and pv.Spec.CSI.VolumeHandle is always the same as longhorn volume name
longhorn/longhorn#10314
More details is at https://github.com/longhorn/longhorn/issues/10314#issuecomment-2632648534

fix: should find the volume name of a pv from pv.Spec.CSI.VolumeHandle

---

api/model.go

ref: https://github.com/longhorn/longhorn/issues/9938
Currently there is a chance that when the volume is detached and the `len(rs) != numOfReplicas`, the `scheduledCondition` won't be set back to True even all the current replicas are scheduled.
This can happen when 
1. Volume with 2 replica (A & B) has best-effort locality and attached to node-X
2. The new replica-X can't be scheduled to the node-X due to node is cordoned. Volume `scheduledCondition` is False
3. Another replica-A on node-A becomes faulted because the node-A is also cordoned and the instance-manager is deleted somehow.
4. replica-A will be deleted due to stale time.
5. replica-X will be deleted when the volume is detached due to `replica.Spec.RebuildRetryCount = scheduler.FailedReplicaMaxRetryCount`
6. now the volume is …

fix: fix volume not ready for workload condition

---

.github/workflows/create-crd-update-pr-in-longhorn-repo.yml

Issue Longhorn/longhorn#10193
Use head commit's author name and email as committer's information.

fix(workflow): fix DCO check

---

controller/setting_controller.go
datastore/longhorn.go
webhook/resources/systemrestore/validator.go

Issue https://github.com/longhorn/longhorn/issues/10233
Revert to checking volume state rather than engine instances when changing some settings.
Rename the engine instance check to reflect what it actually does.
Regression tests for changing settings passed:  https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8332/

fix: use volume state to check all volumes detached when changing some settings

---

csi/controller_server.go

Reverting the commit
https://github.com/longhorn/longhorn-manager/commit/473b6d4b29c16e42ddb5019769396a33d76d9d2c because I cannot see the reason why we need to refuse the csi detachment when the volume is currently attached for operation such as backup/snapshot
Futher more, reading the design decision at
https://github.com/longhorn/longhorn/issues/8735#issuecomment-2177309258, I think we don't really need that commit
(https://github.com/longhorn/longhorn-manager/commit/473b6d4b29c16e42ddb5019769396a33d76d9d2c)
longhorn/longhorn#10171

fix: workload pod will be able to move to new node when backup operation is taking a long time

---

api/backup.go
csi/controller_server.go
manager/engine.go

1. One Volume can have multiple BackupVolumes, need to check all BackupVolumes when finding backups
2. It is totally valid to look up BackupVolumes of non-existing Volume. A deleted Volume can still have Backups in the cluster. Do not panic
Issue # https://github.com/longhorn/longhorn/issues/10303
Putting this PR as draft. Need @mantissahz to help to review the multiple backup target logic

fix: do not panic when looking up BackupVolume of non-existing Volume

---

k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/backup.go
upgrade/upgrade.go
upgrade/v18xto190/upgrade.go

Issue Longhorn/longhorn#10358
The data type of backup.status.size is string. If backup is failed and the size is not set to "0". The metrics collect will fail to parse it.
- The default value of backup.status.size should be "0"
- Update the existing backups with backup.status.size == "" to "0"

fix: empty string of backup.status.size

---

go.mod
vendor/modules.txt

Issue #
longhorn/cli complains the v1.5.2 is incompatible.
https://github.com/longhorn/cli/pull/168

chore(vendor): update k8s.io/client-go to v0.32.1

---

csi/deployment.go

Issue longhorn/longhorn#10411
https://github.com/longhorn/longhorn/issues/10411#issuecomment-2655252262
`None`
`None`

fix(csi/expansion): disable feature-gate RecoverVolumeExpansionFailure

---

controller/volume_controller.go

Issue longhorn/longhorn#10302
Reduce auto balancing logging noise for detached volumes. This might also be confusing and prompt people to investigate these messages are errors (they are warning) - at least I did

fix(log): reduce auto balancing logging noise for detached volumes

---

csi/crypto/crypto.go
vendor/github.com/longhorn/go-common-libs/ns/crypto.go

longhorn/longhorn#10416
This happens with encrypted volume only
While Longhorn CSI plugin is doing `NodeStageVolume`, if the Longhorn engine crash right before [GetDiskFormat](https://github.com/longhorn/longhorn-manager/blob/5f9ec86d18612afaa9f97c78cee3e34f7b653ad6/csi/node_server.go#L486) and recover quickly after that, the following race condition can happen:
1. When engine is crash, the engine removes the Longhorn device at `/dev/longhorn/volume-name`
2. Because the device path is gone, `getDiskFormat` returns empty value for `diskFormat` and `nil` error. Ref https://github.com/longhorn/longhorn-manager/blob/5f9ec86d18612afaa9f97c78cee3e34f7b653ad6/vendor/k8s.io/mount-utils/mount_linux.go#L687-L693
3. Now engine is recovered, so it recreates the device at `/dev/longhorn/volume-name` …

fix: data lost caused by Longhorn CSI plugin doing a wrong re-encryption of volume in rare race condition

---

.github/workflows/build.yml
.gitignore
Dockerfile.dapper
Makefile
package/Dockerfile
scripts/build
scripts/ci
scripts/package

Supports security build.
* Merge binary building process into container build as a separate building stage.
* Prepare for potential secure release
The secrets provided by EIO MUST NOT present in any visible output.
Guidance on achieving SLSA Level 3

feat: self-contained container image build

---

csi/node_server.go

fix: need to check the device path exist first before checking filesystem type and doing formatting

---

engineapi/backup_monitor.go

Issue Longhorn/longhorn#10301
Use warning-level messages for context cancellation.

fix: fix the false alarm while stopping syncing backup status

---

controller/volume_controller.go

feat(log): don't emit "Failed to auto-balance volume in ..." for detached volumes

---

controller/setting_controller.go
types/setting.go

feat(setting): add upgrade-responder-url setting

---

controller/volume_controller.go
scheduler/replica_scheduler.go
scheduler/replica_scheduler_test.go

Issue longhorn/longhorn#10502
Fix `Panic: runtime error: integer divide by zero` during `IsSchedulableToDiskConsiderDiskPressure()`.
`None`
`None`

fix(scheduler): integer divided by zero panic

---

api/backup.go
api/model.go
api/router.go
client/generated_backup_volume.go
csi/controller_server.go
datastore/longhorn.go
manager/engine.go

Issue # longhorn/longhorn#10501
- check if the backup target is available before starting the backup process.
- refactor the function 'getBackup' to fix that it keeps creating backups if the backup target is unavailable.
- add a new API `backupListByVolume` to list backups with the volume name (and backup target if it has.)
Regression test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/8274/

fix(csi): check if the backup target is available before creating a backup

---

types/setting.go

Issue Longhorn/longhorn#7746
The huge page setting for v2 IM should belong to danger zone settings as CPU requests, as it's related to resource change. It should be eventually applied in the same as other dangerous settings.

feat: move SettingNameV2DataEngineHugepageLimit to danger zone settings

---

controller/backing_image_controller.go
controller/backup_target_controller.go
controller/engine_controller.go
controller/instance_manager_controller.go
controller/volume_controller.go
engineapi/proxy.go
engineapi/proxy_snapshot.go

Issue Longhorn/longhorn#10495
Reject snapshot purge when volume is being live migration. If snapshot purge is executed while live migrating a volume, the disk files will be changed. The new engine and replicas are unable to be aware of the change and cannot list the new disk files, resulting in ERR replicas.

fix: reject snapshot purge when volume is being live migration

---

webhook/resources/node/validator.go

ref: https://github.com/longhorn/longhorn/issues/10522
Backing images can also have disk storage allocated. We should mention it when reject deleting disk.

fix: fix reject message when deleting disk

---

csi/crypto/crypto.go
go.mod
go.sum
vendor/github.com/longhorn/go-common-libs/ns/crypto.go
vendor/modules.txt

Issue longhorn/longhorn#10584
- Update Longhorn to the `-d -` for cryptsetup instead of `-d /dev/stdin` for compatibility with newer Talos versions.
- Add validation after device encryption.
`None`
https://github.com/longhorn/longhorn/issues/10584#issuecomment-2734973730

fix: volume encryption not working in Talos 1.9.x

---

k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta1/backingimage.go
k8s/pkg/apis/longhorn/v1beta1/backingimagedatasource.go
k8s/pkg/apis/longhorn/v1beta1/backingimagemanager.go
k8s/pkg/apis/longhorn/v1beta1/backup.go
k8s/pkg/apis/longhorn/v1beta1/backuptarget.go
k8s/pkg/apis/longhorn/v1beta1/backupvolume.go
k8s/pkg/apis/longhorn/v1beta1/engine.go
k8s/pkg/apis/longhorn/v1beta1/engineimage.go
k8s/pkg/apis/longhorn/v1beta1/instancemanager.go
k8s/pkg/apis/longhorn/v1beta1/node.go
k8s/pkg/apis/longhorn/v1beta1/recurringjob.go
k8s/pkg/apis/longhorn/v1beta1/replica.go
k8s/pkg/apis/longhorn/v1beta1/setting.go
k8s/pkg/apis/longhorn/v1beta1/sharemanager.go
k8s/pkg/apis/longhorn/v1beta1/volume.go
scripts/package
upgrade/upgrade.go
upgrade/util/util.go
upgrade/v18xto190/upgrade.go

Issue longhorn/longhorn#10250
We're going to retire the v1beta1 CRDs (#10249), and the migration in this PR is the prerequisite.
Since we marked v1beta2 as the storage version, and we already have [K8s builtin trivial converter](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/) and our customized conversion webhooks, we migrate the all existed resources to the new version by simply read in v1beta2 then write back WITHOUT modification.
- Mark all v1beta1 CRDs as deprecated
- Implement the migration logic from 1.8.x to 1.9.0
The following CRDs are included in this PR:
- BackingImage
- BackingImageDataSource
- BackingImageManager
- Backup
- BackupTarget
- BackupVolume
- Engine
- EngineImage
- InstanceManager
- Node
- RecurringJob
- …

feat(k8s): deprecates v1beta1

---

upgrade/util/util.go

ref: https://github.com/longhorn/longhorn/issues/10644
The upgrade path will fail if the CRD field is unknown during the upgrade, which can occur when the new CRD is applied after the new Longhorn manager starts.

feat: add strict field validation to the upgrade operaiton in upgrade path

---

controller/backup_controller.go
types/setting.go

Issue # longhorn/longhorn#9213
- Introduce a new boolean field `Spec.CleanupBackupSnasphot` to check if it needs to delete the snapshot after the backup is completed when doing a recurring job.
- Introduce a new field `Spec.CleanupSnapshot` to specify the backup will delete the snapshot after the backup is completed.

feat(backup): delete snapshot immediately  after backup completed

---

controller/monitor/disk_monitor.go
controller/monitor/disk_utils.go
controller/monitor/fake_disk_monitor.go
datastore/longhorn.go

ref: https://github.com/longhorn/longhorn/issues/10616
When generating the disk uuid, we first get all existing disk uuid to check and prevent it from having the same first-4-char prefix.

fix: fix naming collision when creating bim based on the prefix of the disk uuid

---

controller/uninstall_controller.go

Issue longhorn/longhorn#10731
Handle the support bundle finalizer after a timeout, since it will not be removed if the manager is gone.
`None`
https://github.com/longhorn/longhorn/issues/10731#issuecomment-2814455301

fix(uninstall): remove support bundle finalizer after timeout

---

datastore/longhorn.go

ref: https://github.com/longhorn/longhorn/issues/10749
the diskUUID may be empty during creation

fix: fix empty diskUUID crashed

---

controller/kubernetes_pod_controller.go
datastore/kubernetes.go
datastore/uncached.go

Issue longhorn/longhorn#10689
Add logic to determine whether a VolumeAttachment associated with a force-deleted pod should be cleaned up. This ensures that stale attachments can be removed safely.
`None`
https://github.com/longhorn/longhorn/issues/9248#issuecomment-2800206182

fix: safely delete VolumeAttachment for force-deleted pods

---

controller/uninstall_controller.go
datastore/longhorn.go

Issue longhorn/longhorn#10731
~Patch to remove support bundle finalizer, allowing bypassing webhooks, which may be unavailable during uninstallation.~ https://github.com/longhorn/longhorn-manager/pull/3712#issuecomment-2820244244
Delete support bundles before deleting managers.
`None`
`None`

fix(uninstall): remove support-bundle before deleting manager

---

go.mod

Issue #
Listing all modules fails because there is no replace directive for `k8s.io/externaljwt`
``` bash
> go list -m -mod=mod all
go: k8s.io/externaljwt@v0.0.0: invalid version: unknown revision v0.0.0
```
Comments in the `go.mod` file recommends to add replace directives for all k8s.io dependencies of `k8s.io/kubernetes` that `k8s.io/kubernetes` itself replaces in its go.mod file

fix(deps): add replace directive for `k8s.io/externaljwt`

---

controller/volume_controller.go

Volume controller does not handle reattachment now. It is the responsibility of VolumeAttachment controller 
longhorn/longhorn#10800

chore: remove some confusing logs

---

controller/backing_image_controller.go
controller/backup_controller.go
controller/snapshot_controller.go

Issue Longhorn/longhorn#10874
Requeueue the snapshot if there is an attachment ticket for it to ensure the volumeattachment can be cleaned up after the snapshot is created.

fix: enqueue snapshot to ensure volumeattachment ticket can be correctly cleaned up

---

controller/snapshot_controller.go

Issue longhorn/longhorn#10808, longhorn/longhorn#10874
This reverts commit 014fd6ea9167d87bd794ca39c90a418531a02c58 for the cause of https://github.com/longhorn/longhorn/issues/10808#issuecomment-2883235961.
- Backport to v1.9.x, v1.8.x, v1.7.x
`None`

revert: "fix: enqueue snapshot to ensure volumeattachment ticket can be correctly cleaned up"

---

controller/instance_manager_controller.go
controller/node_controller.go
types/setting.go

Issue Longhorn/longhorn#10904
1. switch-case works better for conditions based on a single number or string, whereas if-else is more suitable for decisions involving multiple variables.
2. In the current implementation, with auto orphan deletion enabled, the orphan CR and its associated process are deleted almost immediately after the orphan CR is created. This behavior might be too abrupt. We could introduce a configurable setting, such as a wait interval (deletion grace period), to delay this automatic deletion. For instance, if the interval is set to 60 seconds, the orphan CR and its process would be deleted 60 seconds after the creation timestamp.
Manual deletion of the orphan CR by the user would bypass this delay and proceed immediately.

feat(orphan): introduce orphan-resource-auto-deletion-grace-period setting

---

controller/node_controller.go
controller/node_controller_test.go
scheduler/replica_scheduler.go

Issue [longhorn/longhorn#10436](https://github.com/longhorn/longhorn/issues/10436)
- Refactor IsSchedulableToDisk to return detailed error reason alongside result
- Improve logging in node controller and replica scheduler for unschedulable conditions
- Replace ambiguous messages with actionable suggestions (e.g., tuning reserved space or over-provisioning)
- Update related unit tests to match new error message format
- This is a behavioral/logging improvement only; no core scheduling logic is changed
https://www.suse.com/support/kb/doc/?id=000021268

feat(scheduler): add detailed error messages for disk schedulability checks

---

controller/volume_controller.go

Right now when there are multiple backup volumes of the same volume on the same backup target, we silently ignore the error, return nil, and abort the volume syncing: https://github.com/longhorn/longhorn-manager/blob/7b9d2aa08a572b2b8bce35b3ff0e90dfaa1b0eaf/controller/volume_controller.go#L530-L532
User would have no idea of why the volume is stuck.
longhorn/longhorn#11152

fix: do not silent the error returned by ReconcileBackupVolumeState

---

webhook/resources/backup/validator.go
webhook/resources/backupbackingimage/validator.go
webhook/resources/systembackup/validator.go

Issue longhorn/longhorn#10085
Check if the backup target is available before creating a backup, backup backing image, and system backup

fix: backup target status validation improvement

---

k8s/crds.yaml
k8s/pkg/apis/longhorn/v1beta2/node.go

Issue longhorn/longhorn#11127
I had issues using NVMe drives on a talos cluster with a recent kernel.
After a bit of digging I found out that the driver name for "vfio_pci" is not the same.
Running the "auto-detection" driver commands manually : 
```
nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net env PCI_ALLOWED=0000:02:00.0 bash /usr/src/spdk/scripts/setup.sh
0000:01:00.0 (144d a80a): Skipping denied controller at 0000:01:00.0
0000:01:00.0 (144d a80a): Active devices: mount@nvme0n1:nvme0n1p5, so not binding PCI dev
0000:02:00.0 (144d a80a): nvme -> vfio-pci
INFO: Requested 1024 hugepages but 1024 already allocated 
nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net env PCI_ALLOWED=0000:02:00.0 bash /usr/src/spdk/scripts/setup.sh disk-status …
```

fix: add nvme manual disk driver when auto detection failed to detect the nvme driver

---

controller/volume_controller.go
scheduler/replica_scheduler.go

Issue #
To reduce flooding log messages caused by scheduling failures, record reason for the failure in the volume's Scheduled condition.
Longhorn/longhorn#3708

feat(scheduler): record reason for scheduling failure in the volume's Scheduled condition

---

csi/controller_server.go
csi/controlller_server_test.go
csi/deployment.go
csi/deployment_util.go
csi/identity_server.go
csi/manager.go
csi/node_server.go
csi/util.go

Issue https://github.com/longhorn/longhorn/issues/10685
Enable storage capacity-aware pod scheduling using `CSIStorageCapacity`. 
Changes:
- set `StorageCapacity` field of csi driver to `true`
- added `GET_CAPACITY` capability and implemented `GetCapacity` rpc
- added `VOLUME_ACCESSIBILITY_CONSTRAINTS` plugin capability and slightly changed `NodeGetInfo` rpc implementation to return accessible topologies. This is needed because kubelet uses response from `NodeGetInfo` rpc to populate `topologyKeys` field of the `CSINode` objects, which is then consumed by the external-provisioner to build the `AccessibleTopolgies` field of the `GetCapacityRequest`.
- added flags to the external-provisioner deployment to make it automatically produce `CSIStorageCapacity` objects.
These changes won't affect …

feat(csi): enable storage capacity-aware pod scheduling using `CSIStorageCapacity`

---

webhook/resources/backup/mutator.go
webhook/resources/backup/validator.go

Issue Longhorn/longhorn#11416
Improve backup webhook validation and mutation to handle cases where backup.Spec.SnapshotName might be empty, which can occur during certain backup operations.

fix(webhook): handle backup validation when snapshot name is empty

---

controller/engine_controller.go

Issue Longhorn/longhorn#11420
Fix variable shadowing issue where the parameter 'e' was being reused within the loop, potentially causing confusion and masking the original engine parameter.

fix(controller): avoid variable shadowing in waitForV2EngineRebuild

---

controller/instance_manager_controller.go
datastore/kubernetes.go
types/setting.go

Issue Longhorn/longhorn#10788
Make instance manager pod liveness probe timeout configurable.

feat(setting): add instance-manager-pod-probe-timeout

---

controller/instance_manager_controller.go
types/setting.go

When applying the setting, Longhorn will try to restart all instance-manager pods if all volumes are detached and eventually restart the instance manager pod without instances running on the instance manager.
Issue Longhorn/longhorn#10788
When applying the setting, Longhorn will try to restart all instance-manager pods if all volumes are detached and eventually restart the instance manager pod without instances running on the instance manager.

feat(setting): move instance-manager-pod-liveness-probe-timeout to danger zone settings

---

api/router.go
api/volumeattachment.go

https://github.com/longhorn/longhorn/issues/11400
Support WebSocket streams for `VolumeAttachment` list
new websocket route
- `"/v1/ws/volumeattachments"`
- `"/v1/ws/{period}/volumeattachments"`
```bash
> david@david-suse:~$ wscat -c ws://localhost:8080/v1/ws/volumeattachments | jq
{
"data": [
{
"actions": {},
"attachments": {
"csi-e920bd359d775d2c722e6ae6edc450db919a0c589e3da2b9a99606a9b6b917ea": {
"attachmentID": "csi-e920bd359d775d2c722e6ae6edc450db919a0c589e3da2b9a99606a9b6b917ea",
"attachmentType": "csi-attacher",
"conditions": [
{
"lastProbeTime": "",
"lastTransitionTime": "2025-08-15T06:48:13Z",
"message": "The attachment ticket is satisfied",
"reason": "",
"status": "True",
"type": "Satisfied"
}
],
"nodeID": "vm1-virtualbox",
"parameters": {
"disableFrontend": "false", …
```

feat(api): add WebSocket streams for VolumeAttachment list

---

controller/utils.go
controller/volume_controller.go
controller/volume_rebuilding_controller.go
scheduler/replica_scheduler.go

Issue # longhorn/longhorn#11274
- If a disk candidate exists, degraded volumes will start offline rebuilding which is enabled.
- Detach offline-rebuilding volumes if the volume condition `Scheduled` is false.
Regression test: https://10.115.5.5/job/private/job/longhorn-tests-regression/177/

fix(replica): check if disk candidates exist when rebuilding and detach offline-rebuilding volume if necessary

---

controller/backup_controller.go
controller/backup_volume_controller.go
datastore/longhorn.go

Issue # https://github.com/longhorn/longhorn/issues/11619
When enable v2 data engine, we allow user to disable v2 on the specific nodes. In this case, if the backup is scheduled to the non-v2 engine, it may have error. 
This PR add a checking in `isResponsibleFor()` for making sure the v2 volume will be scheduled to the node supported v2.
1. disable v1 engine & enable v2 engine 
2. add `node.longhorn.io/disable-v2-data-engine="true"` on some nodes
-  `k label nodes vm1-virtualbox  node.longhorn.io/disable-v2-data-engine="true" --overwrite` 
-  `kubectl get nodes -L node.longhorn.io/disable-v2-data-engine`
3. create v2 volume and backup it
- Do multiple backup and wait for complete
4. there should not have the backup on the non-v2 node (check the ownerID)
``` 
kubectl get backup -n …
```

feat(controller, datastore): add volume / node compatible check

---

controller/backup_backing_image_controller.go

Make sure the BIM has a ready backing image replica before creating a backing image backup.
Issue longhorn/longhorn#11675
When Longhorn creates a BackupBackingImage (BBI), it may [select a BackingImageManager (BIM) that doesn’t have a ready BackingImage (BI) replica](https://github.com/longhorn/longhorn-manager/blob/979b8d559b4fe2cb087e39a32d08ce1e329a0cef/controller/backup_backing_image_controller.go#L366-L382). As a result, the BIM pod might try to read a file that isn’t ready during BBI creation.
Reproduction steps:
* Set up a cluster with Longhorn (I used Harvester).
* Run this [[script](https://github.com/WebberHuang1118/misc-tools/blob/main/backingimage/create_bi_bbi_cycle.sh)](https://github.com/WebberHuang1118/misc-tools/blob/main/backingimage/create_bi_bbi_cycle.sh) to repeatedly …

fix: make sure the BIM has a ready backing image replica before creating a backing image backup

---

controller/monitor/snapshot_monitor.go
types/setting.go

fix: Allow applying different values for Snapshot Data Integrity Check CronJob for v1 and v2
ref:#11537
Issue longhorn/longhorn#11537

fix: Allow applying different values for Snapshot Data Integrity Check CronJob for v1 and v2

---

controller/engine_controller.go

https://github.com/longhorn/longhorn/issues/11767
V2 volume require checkSizeBeforeRestoration() for updating the size before restoration

fix(engine_controller): v2 volume also require checkSizeBeforeRestoration

---

controller/backup_controller.go
controller/backup_volume_controller.go
controller/engine_controller.go
controller/replica_controller.go
controller/volume_controller.go
datastore/longhorn.go

Issue # longhorn/longhorn#11774
Some nodes will label a disabled v2 data engine, and then these nodes should not be the owner for the v2 volumes.

fix: get the correct owner for v2 volume

---

csi/controller_server.go
csi/controlller_server_test.go

…ey is missing
Issue #https://github.com/longhorn/longhorn/issues/11906

fix(csi): GetCapacity rpc must default to v1 engine
