- deploy/02-components/01-manager.yaml
- deploy/02-components/03-ui.yaml
- deploy/02-components/04-driver.yaml
- deploy/update_image_manager.sh
Also add script update_image_manager.sh to help.
> Update images for manager and UI

- controller/engine_controller.go
- engineapi/engine.go
- util/util.go
Also fix the timeout bug in the util.
> engineapi: Fix large size of rebuild failed due to timeout

- api/model.go
- api/router.go
- api/volume.go
- controller/engine_controller.go
- controller/instance_handler.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- engineapi/engine.go
- engineapi/enginesim.go
- engineapi/types.go
- manager/setting.go
- manager/volume.go
- types/resource.go
- types/types.go
> Engine Live Upgrade support

- deploy/02-components/01-manager.yaml
- deploy/02-components/04-driver.yaml
Engine image to rancher/longhorn-engine:f065eba
Manager image to rancher/longhorn-manager:fabeb53
> Upgrade images

- manager/engine.go
Fix: https://github.com/rancher/longhorn/issues/88
> Fix backup setting problem for nfs

- controller/volume_controller.go
- manager/volume.go
1. API won't allow upgrade to another image when previous one is in process.
2. If live upgrade failed, user can choose to rollback (call upgrade api to
current image) to the previous image. This process will delete any extra
replicas.
> controller: volume: Add upgrade rollback support

- controller/provisioner.go
- types/types.go
Due to `invalid volume frontend specified`
> controller: provisioner: Fix cannot create volume

- controller/volume_controller.go
- scheduler/replica_scheduler.go
- scheduler/replica_scheduler_test.go
For issue https://github.com/rancher/longhorn/issues/94
> Fix race condition in replica scheduler

- api/model.go
- api/node.go
- api/router.go
- datastore/kubernetes.go
- datastore/longhorn.go
- manager/volume.go
For issue https://github.com/rancher/longhorn/issues/100
1. Add Address to Node for UI
2. Remove host api
3. Update ListNodes and ListManagerPods to return a deep copy list
longhorn-tests also need to be change(https://github.com/rancher/longhorn-tests/pull/52)
> Update Node API

- types/setting.go
> types: Rename SettingDefinition.Nullable to Required

- controller/volume_controller_test.go
> controller:test: Fix assert problem in volume_controller_test

- app/driver.go
- csi/deployment_util.go
~1. use the configz to detect if the user has enabled MountPropagation~
~2. create a pod and get back pod spec and check if all the MountPropagation was set correctly~
~3. add nodes/proxy for accessing node configz~
Sometimes the kubelet configuration on different nodes are different, so we need to create a daemonset and check the pod spec.
https://github.com/rancher/longhorn/issues/108
> Detect if the node's kubelet MountPropagation option is enabled before deploy CSI

- controller/websocket_controller.go
This PR fixes the panic that occurs when the `WebsocketController` begins shutting down its `Watchers` as described in rancher/longhorn#119. The issue was being caused because of how the slice of `Watchers` was being processed. Because of how the for loop was picking up the modifications of the slice, this would occur:
**Two asterisks means being currently processed in the for loop:**
```
// Processing index 0.
**watcher1** | watcher2 | watcher3 | watcher4
watcher2 | watcher3 | watcher4
// Now processing index1.
watcher2 | **watcher3** | watcher4
// watcher2 was skipped, now watcher3 is getting removed
watcher2 | watcher4
```
There's no third index here, but the for loop still had the value of watcher3 stored and attempted to close its channel twice, causing the issue.
There are a few …
> Fix WebsocketController shutdown panic

- api/model.go
For issue(https://github.com/rancher/longhorn/issues/130)
> Move DiskID and DataPath to be replica specific

- api/model.go
- api/router.go
- api/volume.go
- app/volume.go
- controller/engine_controller.go
- controller/node_controller_test.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- datastore/longhorn.go
- engineapi/engine.go
- engineapi/types.go
- manager/engine.go
- manager/volume.go
- types/resource.go
- types/types.go
https://github.com/rancher/longhorn/issues/87
> Migration support

- controller/engine_controller.go
- datastore/longhorn.go
https://github.com/rancher/longhorn/issues/134
> controller: engine: notify engine to stop monitoring when it's not running

- api/stream.go
- vendor.conf
- vendor/github.com/rancher/go-rancher/api/writer.go
https://github.com/rancher/longhorn/issues/121
> api: Update go-rancher to support populate links for websocket

- api/model.go
- app/driver.go
- client/generated_client.go
- client/generated_controller.go
- client/generated_disk_update.go
- client/generated_disk_update_input.go
- client/generated_node.go
- client/generated_node_input.go
- client/generated_replica.go
- client/generated_setting.go
- client/generated_volume.go
- controller/node_controller.go
- controller/node_controller_test.go
- controller/volume_controller_test.go
- csi/deployment_util.go
- deploy/02-components/01-manager.yaml
- types/resource.go
Fixed issue(https://github.com/rancher/longhorn/issues/129)
> Manager to run mount propagation test instead of the driver-deployer

- api/node.go
- manager/node.go
- manager/volume.go
Fixed issue: https://github.com/rancher/longhorn/issues/142
> api: Move the actual node update logic out of node api

- types/resource.go
Serialize `DiskStatus` json key from `State` to `state`
> types: Update State json tag

- controller/controller_test.go
- controller/node_controller.go
- controller/node_controller_test.go
- manager/node.go
- Watch for umounted disks and auto update disk status
- Update node api, UI could delete umounted disks from node
Fixed issue: https://github.com/rancher/longhorn/issues/136
> Delete umounted disks from node

- controller/node_controller.go
Fixed issue: https://github.com/rancher/longhorn/issues/182
> controller: Fix disk status LastTransitionTime keeps changing everytime

- controller/node_controller.go
- scheduler/replica_scheduler.go
Fixed issue: https://github.com/rancher/longhorn/issues/185
> controller: Change to use scheduler calculation to check disk pressure

- api/stream.go
https://github.com/rancher/longhorn/issues/145
> websocket - serverside reconnect logic

- csi/deployment_util.go
This PR adds a check to all of the deletion related functions in `deployment_util.go` that will wait for deletion of a `resource` before continuing. This helps work around two separate issues:
- The `deployer` crashing when it attempts to detect the state of an already deleting `resource`
- The `deployer` crashing when creating a new `resource` even though the old one hasn't been torn down yet.
The `deployer` is currently set to wait 120 seconds on a `Service`, `DaemonSet`, and `StatefulSet` for deletion before it times out and restarts the Pod again.
This PR resolves rancher/longhorn#173.
> Check for deletion when redeploying CSI driver

- controller/engine_image_controller.go
Otherwise it would be always in deploying state.
https://github.com/rancher/longhorn/issues/204
> controller: engine image: don't count unready node in the check

- api/volume.go
Fixed issue: https://github.com/rancher/longhorn/issues/205
> API: Don't allow attach volume to unready node

- api/setting.go
- manager/node.go
- manager/setting.go
Fixed issue: https://github.com/rancher/longhorn/issues/211
> API: Validate user input for disks and settings

- datastore/longhorn.go
Fixed issue: https://github.com/rancher/longhorn/issues/219
> Update default reserved value for root disk

- deploy/scripts/environment_check.sh
https://github.com/rancher/longhorn/issues/216
> Add script to check k8s environment for MountPropagation

- deploy/scripts/environment_check.sh
https://github.com/rancher/longhorn/issues/216
> Detect flexvolume path by inspecting host pid namespace

- scheduler/replica_scheduler.go
https://github.com/rancher/longhorn/issues/243
> controller: Tweak scheduling algorithm

- controller/node_controller.go
https://github.com/rancher/longhorn/issues/254
> controller: Replica scheduled to the node that shouldn't able to scheduled

- deploy/scripts/cleanup.sh
https://github.com/rancher/longhorn/issues/261
> Add script to tear down Longhorn system

- app/driver.go
- csi/deployment.go
https://github.com/rancher/longhorn/issues/272
> Cleanup workloads in parallel

- app/driver.go
- app/driver_flexvolume.go
- csi/deployment.go
- util/util.go
https://github.com/rancher/longhorn/issues/266
WIP needs some more testing
> Detect flexvolume dirpath

- deploy/scripts/environment_check.sh
We have built-in auto detection now.
Signed-off-by: James Oliver <joliver@rancher.com>
> deploy: remove the Flexvolume detection in the environment_check.sh

- csi/util.go
https://github.com/rancher/longhorn/issues/287
> Pass fromBackup parameter in create volume request

- controller/controller_manager.go
- controller/replica_controller.go
- controller/replica_controller_test.go
- controller/volume_controller.go
https://github.com/rancher/longhorn/issues/273
> Refactor delete logic

- controller/controller_manager.go
- controller/replica_controller.go
- controller/replica_controller_test.go
- controller/volume_controller.go
Reverts rancher/longhorn-manager#196
Merged too soon. Commits are not squashed and commit comments are wrong.
> Revert "Refactor delete logic"

- controller/controller_manager.go
- controller/replica_controller.go
- controller/replica_controller_test.go
- controller/volume_controller.go
https://github.com/rancher/longhorn/issues/273
> controller: volume: refactor engines/replicas deletion process

- deploy/01-prerequisite/02-serviceaccount.yaml
https://github.com/rancher/longhorn/issues/318
> Add endpoints permission

- app/driver.go
https://github.com/rancher/longhorn/issues/319
> Fix pv-controller ignoring stop channel

- controller/events.go
- controller/replica_controller.go
- datastore/longhorn.go
https://github.com/rancher/longhorn/issues/306
> Adopt replicas belonging to down or deleted nodes

- app/post_upgrade.go
- main.go
https://github.com/rancher/longhorn/issues/322
> Perform post-upgrade job cleanup when crossing v0.3.2 boundary

- app/driver.go
- app/post_upgrade.go
- controller/uninstall_controller.go
- csi/deployment.go
- datastore/kubernetes.go
- types/deploy.go
Fixes https://github.com/rancher/longhorn/issues/403
> app: Add driver deployer cleanup in `longhorn-manager uninstall`

- engineapi/backups.go
- engineapi/types.go
- vendor.conf
- vendor/github.com/rancher/backupstore/Dockerfile.dapper
- vendor/github.com/rancher/backupstore/LICENSE
- vendor/github.com/rancher/backupstore/Makefile
- vendor/github.com/rancher/backupstore/README.md
- vendor/github.com/rancher/backupstore/backupstore.go
- vendor/github.com/rancher/backupstore/config.go
- vendor/github.com/rancher/backupstore/deltablock.go
- vendor/github.com/rancher/backupstore/driver.go
- vendor/github.com/rancher/backupstore/list.go
- vendor/github.com/rancher/backupstore/logging/logging.go
- vendor/github.com/rancher/backupstore/singlefile.go
- vendor/github.com/rancher/backupstore/trash.yml
- vendor/github.com/rancher/backupstore/types.go
- vendor/github.com/rancher/backupstore/util/util.go
https://github.com/rancher/longhorn/issues/399
> show error info of listing backup volume in logs

- api/volume.go
- manager/volume.go
https://github.com/rancher/longhorn/issues/415
> manager: prohibit user from deleting the last replica contains data

- types/resource.go
https://github.com/rancher/longhorn/issues/472
> manager: kubernetesStatus should be camelCase

- api/model.go
- api/router.go
- api/volume.go
- manager/kubernetes.go
Feature 2: https://github.com/rancher/longhorn/issues/461
> api: create associated pv and pvc for existing volume

- controller/controller_manager.go
- controller/controller_test.go
- controller/kubernetes_controller.go
- controller/kubernetes_controller_test.go
Feature 3: https://github.com/rancher/longhorn/issues/461
> controller: speeded up disaster recovery by deleting VolumeAttachment in time

- app/uninstall.go
- deploy/uninstall/uninstall.yaml
https://github.com/rancher/longhorn/issues/462
> uninstaller: add ability to cleanup leftover resources with finalizers when longhorn uninstall stuck

- controller/node_controller.go
- types/resource.go
https://github.com/rancher/longhorn/issues/454
> controller: added event only when kube node unknown condition became true

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/uninstall/uninstall.yaml
And UI to rancher/longhorn-ui:50946e1
> deploy: Update manager to rancher/longhorn-manager:192b0e7

- controller/controller_manager.go
- controller/engine_controller.go
- controller/instance_handler.go
- controller/replica_controller.go
- manager/setting.go
- types/setting.go
Experimental feature. This may lead to scheduling failure if the resource is tight.
> controller: Add GuaranteedEngineCPU setting

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/uninstall/uninstall.yaml
And UI to rancher/longhorn-ui:241599b
> deploy: update manager image to rancher/longhorn-manager:50c16a3

- app/driver.go
- csi/deployment.go
- deploy/install/02-components/04-driver.yaml
https://github.com/rancher/longhorn/issues/486#issuecomment-484298815
> deployment: replica count of attacher and provisioner configurable

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/uninstall/uninstall.yaml
Manager: rancher/longhorn-manager:043c3af
Engine: rancher/longhorn-engine:3c79348
UI: rancher/longhorn-ui:e077811
> Update deploy files

- manager/misc.go
The support bundle is required to have snapshot info for every volume, if present. It is placed in yamls/volumes/<volume_name>/snapshots.yaml. If there were any errors experienced while fetching the snapshot info, it would be recorded in yamls/volumes/<volume_name>/generationError.log.
Commit ID: 72cb9fceeca240f2b65417a791a9b1e68de47039
> Support Bundle to include Snapshots

- manager/kubernetes.go
https://github.com/rancher/longhorn/issues/514
> manager: added waiting time for PV/PVC creation

- api/misc.go
- api/model.go
- api/router.go
- manager/misc.go
https://github.com/rancher/longhorn/issues/414
> Support bundle API change to use GET

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/uninstall/uninstall.yaml
rancher/longhorn-manager:2253cd0
rancher/longhorn-ui:9f1e1cf
rancher/longhorn-engine:be1c74c
> Update deployment to rancher/longhorn-manager:2253cd0

- controller/setting_controller.go
- types/setting.go
https://github.com/rancher/longhorn/issues/523
> setting: add global setting for backupstore poll interval

- datastore/kubernetes.go
- manager/kubernetes.go
https://github.com/rancher/longhorn/issues/525
> Fix bug for PVC creation with reused PV

- api/model.go
- manager/misc.go
The following code changes indicate the download progress of the support bundle.
Issue: https://github.com/rancher/longhorn/issues/527
> Enhance Support Bundle to show download progress in percentage

- manager/engine.go
> manager: Put API backup call into goroutine

- manager/setting.go
https://github.com/rancher/longhorn/issues/537
> manager: fix error message for bakcup target setting failure

- manager/kubernetes.go
https://github.com/rancher/longhorn/issues/544
> manager: change default delete policy to Retain for PV creation

- controller/engine_controller.go
https://github.com/rancher/longhorn/issues/549
> controller: check if engine is restoring before running incremental restoration

- controller/replica_controller.go
- engineapi/types.go
https://github.com/rancher/longhorn/issues/566
> controller: modify replica ReadinessProbe for gRPC switch

- api/model.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- datastore/longhorn.go
- manager/volume.go
- types/resource.go
Real restoration completed when restored volume first created, workload starting time has been reduced.
> Volume is now usable once restoration is done.

- controller/setting_controller.go
- datastore/longhorn.go
- manager/setting.go
https://github.com/longhorn/longhorn/issues/573
> Backupstore polling is disabled by setting backupolling interval to 0

- controller/volume_controller.go
- controller/volume_controller_test.go
https://github.com/longhorn/longhorn/issues/602
> Automatically attach standby volume after it's created

- manager/setting.go
This PR is for https://github.com/longhorn/longhorn/issues/605
> Required settings are validated in longhorn-manager

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/576
> controller: Reconcile volume to faulted state when all replicas have failed

- controller/engine_controller.go
This PR allows for the `Engine` to be able to automatically mark failed `Replica` rebuilds to allow for new `Replica` creation, albeit with a delay. 
The `EngineController` now comes with a `Backoff` from `client-go` to track the `backoff` period for handling a `Replica` rebuild failure. The `EngineController` responsible for adding a `Replica` and handling the rebuild on an `Engine`, upon detection of a failure, will check to see what the `backoff` period is, and if the `backoff` period has passed, will attempt marking the `Replica` as failed and progress the `backoff` period up to a maximum of five minutes. This allows for rebuilds to be attempted on new, clean `Replicas` automatically without possibly causing excess load due to quick `Replica` recreation.
Once a `Replica` has …
> Mark failed Replica rebuilds using Backoff

- manager/engine.go
https://github.com/longhorn/longhorn/issues/624
> Wait for newest backup finished before update volume's LastBackup

- api/backup.go
- api/model.go
- api/router.go
- engineapi/backups.go
- manager/engine.go
https://github.com/longhorn/longhorn/issues/598
> Provide an option to delete backup volume

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/uninstall/uninstall.yaml
The refactoring is now in.
Manager: longhornio/longhorn-manager:5b29b03
Engine: longhornio/longhorn-engine:0f79e7a
> deploy: Update manager to longhornio/longhorn-manager:5b29b03

- engineapi/backups.go
- manager/engine.go
- util/util.go
https://github.com/longhorn/longhorn/issues/606
> Execute engine binary without timeout for deleting backup

- app/volume.go
- engineapi/engine.go
Missing the engine port number after the refactoring.
> Fix failed recurring job after the refactoring

- api/model.go
This PR adds a `Timestamp` attribute to the various `Resources` that can be updated by `WebSockets` to the `HTTP API` wrapper `structs` in order to represent the time that the response for that `Resource` was generated. This `Timestamp` attribute will appear for both regular `HTTP` requests and `WebSocket` updates, and is intended to be used to reconcile any conflicting states that can appear between the `HTTP` result and the `WebSocket` result due to delays from networking or other causes.
This PR is a fix for the response inconsistencies described in longhorn/longhorn#648.
> Add timestamps to watchable Resources

- engineapi/backups.go
- engineapi/types.go
Reverts longhorn/longhorn-manager#369
Engine part cannot pass the integration test.
> Revert "Asynchronous deleting backup volume"

- api/model.go
https://github.com/longhorn/longhorn/issues/657
> api: Add `managerType` to the instance manager output

- api/model.go
- csi/util.go
- types/types.go
Issue #658
https://github.com/longhorn/longhorn/issues/658
> Update default stale replica timeout to 48h

- app/daemon.go
- datastore/longhorn.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- deploy/install/02-components/01-manager.yaml
- manager/setting.go
- manager/volume.go
- types/setting.go
- types/types.go
https://github.com/longhorn/longhorn/issues/623
Design doc: https://docs.google.com/document/d/1eBd5_W-rOrlh66GcIJd5Dl0H0kxSsxG9hhHKJB-jhgc/edit?usp=sharing
> Customized default setting

- controller/controller_test.go
- controller/engine_controller.go
- controller/instance_handler.go
- controller/instance_handler_test.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- controller/replica_controller.go
- engineapi/instance_manager.go
- types/resource.go
https://github.com/longhorn/longhorn/issues/674
https://github.com/longhorn/longhorn/issues/659
Start monitor for running instance manager. 
And use actively polled results only to update the instance map of instance manager.
> Refactor instance manager controller

- longhorn-engine-exec
https://github.com/longhorn/longhorn/issues/655
> Add script to simplify running longhorn command

- controller/instance_manager_controller.go
Previously the thread won't be stopped and returned after instance manager
streaming connection is closed. And longhorn manager log will be flooded
by the related error messages. e.g.:
time="2019-08-16T23:55:46Z" level=error msg="error receiving next item in engine watch: rpc error: code = Canceled desc = context canceled"
time="2019-08-16T23:55:46Z" level=error msg="error receiving next item in engine watch: rpc error: code = Canceled desc = grpc: the client connection is closing"
> controller: Stop the thread which receives instance manager streaming msg

- app/driver.go
- app/uninstall.go
- controller/controller_manager.go
- controller/engine_image_controller.go
- controller/instance_handler_test.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- controller/kubernetes_controller_test.go
- controller/node_controller_test.go
- controller/setting_controller.go
- controller/volume_controller_test.go
- csi/deployment.go
- csi/deployment_util.go
- datastore/datastore.go
- datastore/kubernetes.go
- datastore/longhorn.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- scheduler/replica_scheduler_test.go
- types/setting.go
- util/util.go
Issue:
https://github.com/longhorn/longhorn/issues/584
Design doc:
https://docs.google.com/document/d/1Sv8WqLvrBN3eRvt3GO7HmBeW9YiA0j0Z_ArWzTZwR3g/edit?usp=sharing
> Add support for Toleration setting

- api/model.go
https://github.com/longhorn/longhorn/issues/683
> Expose instance manager name for engine and replicas in API response

- controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/687
> Fix the issue causing rebuilt repeatedly fail

- engineapi/backups.go
- manager/engine.go
https://github.com/longhorn/longhorn/issues/700
> app: DeleteBackup() should be sync in backup recurring job

- app/volume.go
- engineapi/backups.go
- engineapi/enginesim.go
- engineapi/types.go
- manager/engine.go
https://github.com/longhorn/longhorn/issues/700
> Backup recurring job should wait for backup creation complete

- api/model.go
- app/driver.go
- app/get_proc_arg.go
- app/volume.go
- client/generated_backup_status.go
- client/generated_client.go
- client/generated_controller.go
- client/generated_engine_image.go
- client/generated_node.go
- client/generated_purge_status.go
- client/generated_replica.go
- client/generated_restore_status.go
- client/generated_setting.go
- client/generated_volume.go
- controller/controller_manager.go
- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/instance_handler.go
- controller/instance_handler_test.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- controller/replica_controller.go
- deploy/install/02-components/03-ui.yaml
- deploy/scripts/longhorn-engine-exec
- engineapi/backups.go
- engineapi/enginesim.go
- engineapi/types.go
- manager/engine.go
Included PRs:
https://github.com/longhorn/longhorn-manager/pull/393
https://github.com/longhorn/longhorn-manager/pull/394
https://github.com/longhorn/longhorn-manager/pull/397
https://github.com/longhorn/longhorn-manager/pull/395
https://github.com/longhorn/longhorn-manager/pull/396
https://github.com/longhorn/longhorn-manager/pull/400
https://github.com/longhorn/longhorn-manager/pull/401
https://github.com/longhorn/longhorn-manager/pull/402
> Merge multiple PRs from `staging` to `master`

- app/driver.go
- app/uninstall.go
- controller/controller_manager.go
- controller/engine_image_controller.go
- controller/instance_handler_test.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- controller/kubernetes_controller_test.go
- controller/node_controller_test.go
- controller/setting_controller.go
- controller/volume_controller_test.go
- csi/deployment.go
- csi/deployment_util.go
- datastore/datastore.go
- datastore/kubernetes.go
- datastore/longhorn.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- scheduler/replica_scheduler_test.go
- types/setting.go
- util/util.go
Included PR:
https://github.com/longhorn/longhorn-manager/pull/385
> Merge PR from `staging` to `master` with modifications for Toleration Setting

- controller/engine_controller.go
- controller/instance_handler.go
- controller/replica_controller.go
https://github.com/longhorn/longhorn/issues/684
> Handle instance delete for node down case 

- controller/engine_controller.go
- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/687
> Fix repeatedly rebuild failure

- app/volume.go
- engineapi/backups.go
- engineapi/types.go
https://github.com/longhorn/longhorn/issues/716
> Fix the failure of backup recurring job.

- controller/engine_controller.go
- controller/instance_manager_controller.go
https://github.com/longhorn/longhorn/issues/160
https://github.com/longhorn/longhorn/issues/720
> Speed up attaching process

- types/setting.go
https://github.com/longhorn/longhorn/issues/721
> datastore: document that setting BackupstorePollInterval to 0 disables the polling

- controller/engine_controller.go
- controller/instance_handler.go
- controller/instance_manager_controller_test.go
- controller/replica_controller.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- datastore/longhorn.go
https://github.com/longhorn/longhorn/issues/622
> Upgrade support from v0.5.0 to v0.6.0 

- controller/controller_manager.go
- controller/controller_test.go
- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- controller/node_controller.go
- controller/node_controller_test.go
- controller/replica_controller.go
- controller/setting_controller.go
- controller/uninstall_controller.go
- datastore/kubernetes.go
- datastore/longhorn.go
- types/resource.go
- types/types.go
https://github.com/longhorn/longhorn/issues/718
> Use engine image controller to manage the creation and deletion of instance manager

- controller/engine_image_controller.go
https://github.com/longhorn/longhorn/issues/712
> Count reference for the engine image even if the volume is live upgraded to other engine image

- controller/volume_controller.go
- datastore/longhorn.go
https://github.com/longhorn/longhorn/issues/727
> Find node for restoration volume only if the volume NodeID is empty

- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- controller/replica_controller.go
- datastore/kubernetes.go
- datastore/longhorn.go
- types/types.go
https://github.com/longhorn/longhorn/issues/724
> Fix slow engine detach due to cannot enqueue the instance manager immediately

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/735
> controller: volume: Ignore unscheduled replicas during attaching check

- controller/controller_manager.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
https://github.com/longhorn/longhorn/issues/734
> Add instance manager informer for engine image controller

- app/driver.go
- app/uninstall.go
- controller/controller_manager.go
- controller/engine_image_controller.go
- controller/instance_handler_test.go
- controller/instance_manager_controller_test.go
- controller/kubernetes_controller_test.go
- controller/node_controller_test.go
- controller/uninstall_controller.go
- controller/volume_controller_test.go
- datastore/datastore.go
- datastore/kubernetes.go
- datastore/uncached.go
- deploy/install/01-prerequisite/02-serviceaccount.yaml
- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/uninstall/uninstall.yaml
- examples/statefulset.yaml
- scheduler/replica_scheduler_test.go
https://github.com/longhorn/longhorn/issues/742
> Update AppsV1beta2 to AppsV1 for statefulset/deployment/daemonset

- controller/engine_image_controller.go
- datastore/longhorn.go
- types/types.go
https://github.com/longhorn/longhorn/issues/741
https://github.com/longhorn/longhorn/issues/743
> Wait for instance manager cleanup before deleting engine image

- controller/engine_image_controller.go
https://github.com/longhorn/longhorn/issues/745
> controller: Skip checking instance manager when counting old engine image refCount

- controller/kubernetes_controller.go
- controller/kubernetes_controller_test.go
https://github.com/longhorn/longhorn/issues/754
> controller: Kubernetes: Fix NPE caused by CSI driver checking

- deploy/uninstall/uninstall.yaml
https://github.com/longhorn/longhorn/issues/758
> deploy: The uninstall role gets access to the resource node

- controller/node_controller.go
- controller/node_controller_test.go
- util/util.go
https://github.com/longhorn/longhorn/issues/776
> Create disk path replica subdirectory if it doesn't exist

- controller/engine_image_controller.go
https://github.com/longhorn/longhorn/issues/769
> Check and delete engine image DaemonSet with mismatching labels

- controller/instance_handler.go
https://github.com/longhorn/longhorn/issues/789
> controller: Make sure instance manager name is set as long as the related instance process exists

- datastore/uncached.go
- manager/misc.go
https://github.com/longhorn/longhorn/issues/792
> support bundle: Add instance managers and config maps

- controller/controller_manager.go
- controller/kubernetes_controller.go
- controller/kubernetes_controller_test.go
https://github.com/longhorn/longhorn/issues/793
> Add ownerID check and equal check for the volume in kubernetes controller

- controller/kubernetes_controller.go
https://github.com/longhorn/longhorn/issues/793
> Check ownerID before updating volume's kubernetes status for PV deletion in kubernetes controller

- app/volume.go
- controller/controller_test.go
- controller/engine_image_controller.go
- controller/engine_image_controller_test.go
- controller/instance_handler_test.go
- controller/instance_manager_controller_test.go
- controller/volume_controller_test.go
- datastore/longhorn.go
- types/types.go
https://github.com/longhorn/longhorn/issues/725
> Add unit test for engine image controller

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/uninstall/uninstall.yaml
> deploy: Change back deployment tags to master

- Dockerfile.dapper
- api/model.go
- util/util_test.go
> build: Upgrade golang to v1.13.2

- controller/engine_image_controller.go
- controller/engine_image_controller_test.go
- controller/instance_manager_controller.go
- controller/uninstall_controller.go
- controller/volume_controller.go
- datastore/longhorn.go
- types/types.go
https://github.com/longhorn/longhorn/issues/822
> Correct OwnerReference containing wrong Longhorn resource kind

- controller/controller_manager.go
- controller/engine_controller.go
- controller/instance_manager_controller.go
- controller/replica_controller.go
- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/847
> controller: Refactoring `isResponsibleFor` to determine ownerID

- controller/instance_manager_controller.go
https://github.com/longhorn/longhorn/issues/833
> controller: instance manager: Add mount propagation explicitly to the pod

- controller/volume_controller.go
- controller/volume_controller_test.go
https://github.com/longhorn/longhorn/issues/728
> Get rid of replicaUpdated and engineUpdated

- app/get_proc_arg.go
Cause:
https://github.com/rancher/k3s/releases/tag/v0.10.0
Issue:
https://github.com/longhorn/longhorn/issues/835
> app: Use default root dir for k3s v0.10.0+

- controller/events.go
- controller/volume_controller.go
- csi/node_server.go
- types/resource.go
- util/util.go
https://github.com/longhorn/longhorn/issues/851
> Remount reattached volumes

- csi/controller_server.go
- csi/manager.go
- csi/node_server.go
- examples/block_volume.yaml
https://github.com/longhorn/longhorn/issues/678
> Support block volume

- deploy/install/02-components/05-storageclass.yaml
https://github.com/longhorn/longhorn/issues/772
> Add StorageClass for Longhorn deployment

- deploy/install/02-components/01-manager.yaml
https://github.com/longhorn/longhorn/issues/868
> Change the default-setting directory

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/882
> controller: volume: Don't update engine/replica immediately for logRequested

- app/upgrader.go
https://github.com/longhorn/longhorn/issues/905
> csi: Fix the NPE issue of the CSI upgrader

- controller/volume_controller.go
Put all the UpdateEngine() and UpdateReplica() call in one place, to
avoid trigger other controllers in the process of updating.
https://github.com/longhorn/longhorn/issues/882
> controller: volume: cleanup UpdateEngine() and UpdateReplica()

- app/upgrader.go
https://github.com/longhorn/longhorn/issues/957
> app: Skip the non-existing PVC

- util/util.go
https://github.com/longhorn/longhorn/issues/950
> util: Fix OutOfIndex issue in remount function

- controller/controller_test.go
- controller/instance_manager_controller.go
- controller/volume_controller.go
- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/uninstall/uninstall.yaml
- scheduler/replica_scheduler_test.go
- types/setting.go
- types/types.go
https://github.com/longhorn/longhorn/issues/846
> Update default path

- go.mod
- go.sum
- vendor/github.com/longhorn/backupstore/deltablock.go
- vendor/github.com/longhorn/backupstore/util/util.go
- vendor/modules.txt
> Update backupstore to 3524b8ae9518014b544ffaaf9c3ece22a87836f9

- api/model.go
- controller/engine_controller.go
- datastore/longhorn.go
- engineapi/engine.go
- engineapi/enginesim.go
- engineapi/types.go
- types/deepcopy.go
- types/resource.go
https://github.com/longhorn/longhorn/issues/46
> Replica rebuild progress report

- util/util.go
https://github.com/longhorn/longhorn/issues/950
https://github.com/longhorn/longhorn/issues/982
> Modify remount for all kinds of filesystem

- app/driver.go
- csi/deployment.go
- csi/deployment_util.go
https://github.com/longhorn/longhorn/issues/899
https://github.com/longhorn/longhorn/issues/985
> Fix CSI plugin mount issues

- manager/volume.go
https://github.com/longhorn/longhorn/issues/983
> manager: Unset the field DisableFrontend after detachment

- deploy/install/02-components/01-manager.yaml
longhorn/longhorn#909
longhorn/longhorn#635
> Add readiness probe to longhorn manager

- csi/deployment.go
- csi/deployment_util.go
Fix for longhorn/longhorn#1019
> csi: mount csi plugin directory to longhorn-csi-plugin

- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- deploy/install/02-components/01-manager.yaml
- types/types.go
- upgrade/upgrade.go
https://github.com/longhorn/longhorn/issues/984
> Store the image name rather than the object name in im.spec.EngineImage

- api/snapshot.go
- api/volume.go
- controller/volume_controller.go
- manager/backup.go
- manager/volume.go
- types/resource.go
A new field volume.Status.IsStandby is introduced for this feature.
Longhorn #1006
> Don't reject the activate command if the restoration is in progress

- api/model.go
- app/driver.go
- controller/node_controller.go
- controller/node_controller_test.go
- scheduler/replica_scheduler.go
- types/resource.go
- types/types.go
- util/util.go
https://github.com/longhorn/longhorn/issues/929
> Check k8s zone and region during replica scheduling

- types/types.go
- upgrade/upgrade.go
- util/util.go
https://github.com/longhorn/longhorn/issues/868
> Migrate engine binary files for the existing engine images

- controller/events.go
- controller/volume_controller.go
- types/setting.go
- util/util.go
https://github.com/longhorn/longhorn/issues/1046
> Auto-salvage feature

- deploy/install/02-components/03-ui.yaml
> change frontend service to type NodePort

- deploy/install/02-components/03-ui.yaml
> change frontend service to type ClusterIP

- controller/engine_controller.go
https://github.com/longhorn/longhorn/issues/1058
> controller: engine: don't update engine status unnecessarily

- examples/storageclass.yaml
> example: Explain the magic number of staleReplicaTimeout

- api/model.go
- controller/engine_controller.go
- controller/volume_controller.go
- csi/controller_server.go
- csi/identity_server.go
- csi/node_server.go
- engineapi/engine.go
- engineapi/enginesim.go
- engineapi/instance_manager.go
- engineapi/types.go
- manager/volume.go
- types/resource.go
- util/util.go
https://github.com/longhorn/longhorn/issues/1040
> Fix volume expansion

- app/driver.go
- app/get_proc_arg.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- csi/deployment.go
- csi/deployment_util.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- types/setting.go
> Longhorn Airgap - add registry-secret setting to deploy from private registry

- controller/node_controller.go
- datastore/longhorn.go
- types/types.go
longhorn/longhorn#991
longhorn/longhorn#1053
> Enable setting default disk and node tags

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/uninstall/uninstall.yaml
We will not change the tag later.
We might need to change the tag for instance manager image from time to
time still.
> deploy: Update tags to master

- types/setting.go
> types: Accept the boolean value with upper cases for default settings

- api/model.go
- api/volume.go
- manager/kubernetes.go
- package/Dockerfile
> add fstype to pv create request

- manager/volume.go
> set max number recurring job retain to 50

- types/condition.go
> types: Fix excessive condition change logs

- api/model.go
- api/router.go
- controller/kubernetes_node_controller.go
- controller/node_controller.go
- controller/node_controller_test.go
- go.mod
- go.sum
- manager/node.go
- types/resource.go
- types/types.go
- util/util.go
- vendor/github.com/longhorn/go-iscsi-helper/iscsi/initiator.go
- vendor/github.com/longhorn/go-iscsi-helper/util/util.go
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/972
The test case in https://github.com/longhorn/longhorn/issues/1147 will be removed.
> Disk status refactor

- manager/kubernetes.go
> manager: Remove unecessary wait during the PV or PVC creation

- api/model.go
- app/volume.go
- controller/engine_controller.go
- controller/node_controller.go
- controller/volume_controller.go
- engineapi/enginesim.go
- engineapi/snapshot.go
- engineapi/types.go
- manager/engine.go
- scheduler/replica_scheduler.go
- scheduler/replica_scheduler_test.go
- types/deepcopy.go
- types/resource.go
https://github.com/longhorn/longhorn/issues/673
https://github.com/longhorn/longhorn/issues/1119
> Add volume actual size to the scheduling calculation

- api/model.go
- controller/controller_test.go
- controller/engine_image_controller.go
- controller/engine_image_controller_test.go
- controller/node_controller.go
- controller/node_controller_test.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- datastore/longhorn.go
- k8s/pkg/apis/longhorn/v1beta1/zz_generated.deepcopy.go
- scheduler/replica_scheduler.go
- scheduler/replica_scheduler_test.go
- types/condition.go
- types/deepcopy.go
- types/resource.go
https://github.com/longhorn/longhorn/issues/961
> Add conditions for EngineImage

- api/model.go
> api: Fix NPE caused by changing DiskStatus to pointer

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/1156
> controller: volume: Don't block volume reconciliation if remount failed

- util/util.go
- util/util_test.go
https://github.com/longhorn/longhorn/issues/1162
Otherwise we will have backup issues.
> util: Make sure the size is aligned to 2MiB

- .drone.yml
> Add slack notification for build failure

- app/migrate.go
- datastore/kubernetes.go
- deploy/scripts/migrate-for-pre-070-volumes.sh
- main.go
- manager/kubernetes.go
> Migrate PVs and PVCs for pre v0.7.0 volumes

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/1099
> controller: volume: Don't auto attach incompatible engines

- api/model.go
- types/resource.go
https://github.com/longhorn/longhorn/issues/1166
So we can know which replica is responible for creating the backup
> controller: engine: Add ReplicaAddress to the BackupStatus

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/1101
https://github.com/longhorn/longhorn/issues/1143
> controller: volume: Don't enable frontend if volume is in standby

- manager/volume.go
https://github.com/longhorn/longhorn/issues/1193
> manager: Fix error message of create volume to UI

- api/model.go
- api/router.go
- api/volume.go
- controller/engine_controller.go
- controller/events.go
- controller/volume_controller.go
- engineapi/types.go
- manager/volume.go
- types/resource.go
> Expansion canceling

- api/model.go
- types/resource.go
https://github.com/longhorn/longhorn/issues/1167
> Add FromReplica for RebuildStatus

- types/types.go
https://github.com/longhorn/longhorn/issues/1219
> controller: kubernetes_node: don't allow duplicate disk name from annotation

- api/model.go
https://github.com/longhorn/longhorn/issues/1167
https://github.com/longhorn/longhorn/issues/1220
> api: Use IP and Port to find the correct replica

- deploy/scripts/lhexec
> fix lhexec script

- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/1270
> Disable rebuild for restoring volume or DR volume

- controller/instance_handler.go
- controller/instance_handler_test.go
> Clean up status.InstanceManagerName only if the instance is stopped

- types/types.go
This fix is to avoid multiple disk paths are in the same filesystem.
To avoid disk usage calculation issue.
https://github.com/longhorn/longhorn/issues/1285
> types: Fix filesystem ID checking for disk path

- api/model.go
- controller/engine_controller.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- datastore/longhorn.go
- manager/volume.go
- types/resource.go
> Restore failure handling

- api/model.go
- client/generated_backup.go
- client/generated_backup_status.go
- client/generated_client.go
- client/generated_controller.go
- client/generated_disk_info.go
- client/generated_engine_image.go
- client/generated_node.go
- client/generated_pvcreate_input.go
- client/generated_rebuild_status.go
- client/generated_volume.go
- csi/controller_server.go
- csi/node_server.go
> Update go client and check v.ready in the CSI plugin

- types/setting.go
Signed-off-by: Catherine Luse <catherine.luse@gmail.com>
> Edit descriptions of Longhorn settings

- deploy/install/02-components/01-manager.yaml
https://github.com/longhorn/longhorn/issues/1113
> deploy: Update instance manager to v1_20200514

- controller/node_controller.go
- util/util.go
This fix moves the multiple disks checking in the same filesystem ID after UUID checking.
If the UUID is not avaiable, we do not need to check the filesystem ID.
https://github.com/longhorn/longhorn/issues/1291
> controller: Fix adding default disk back after extra mount disk unmounted

- controller/volume_controller.go
- controller/volume_controller_test.go
> Allow restore/DR volume retry restoring after engine crashes

- controller/volume_controller.go
- types/setting.go
Back to the whiteboard.
longhorn/longhorn#307
> setting: Remove ReplicaRebuildConcurrentLimit setting

- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
> deploy: Update to security context for ui and driver

- api/model.go
> api: Check condition `scheduled` for `v.Ready`

- controller/volume_controller.go
> controller: Make sure DR volumes can be activated after deleting the last backup

- controller/volume_controller.go
- manager/volume.go
longhorn/longhorn#1361
longhorn/longhorn#1373
> Disable expansion and restore if the volume scheduling fails

- api/stream.go
- controller/instance_manager_controller.go
- csi/controller_server.go
> Fix ticker leakage

- go.mod
- go.sum
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/1408
> Update go-iscsi-helper to v0.0.0-20200601183015-ca8b762c2f38

- controller/engine_controller.go
- controller/events.go
- controller/instance_handler.go
- controller/instance_handler_test.go
- controller/replica_controller.go
- controller/volume_controller.go
- types/resource.go
https://github.com/longhorn/longhorn/issues/1451
> Mark the volume as Unknown for node down cases

- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
> Refactor IM monitor starting and stopping workflow

- app/volume.go
This PR modifies the cleanup code for the `Job` so that it also prevents the `Job` from reporting an error in any part of the `Job` after the actual `Snapshot` or `Backup` that would've caused the `Job` to fail (this includes listing `Backups` and `Snapshots` for deletion or deleting `Snapshots` before purging them). This addresses more cases that could trigger the condition described in longhorn/longhorn#1424.
> Warn on all cleanup tasks during Recurring Job

- controller/engine_controller.go
> controller: Eliminate redundant engine upgrade retries

- util/util.go
Return error from RemountVoume() when:
1. Fail to detect the filesystem
2. The filesystem is XFS  (we do not support remount volume with XFS)
3. There is not any available mount point for volume
longhorn/longhorn#1362
> util: When fail to remount a volume, return an error instead of nil

- controller/engine_controller.go
- controller/events.go
- controller/volume_controller.go
- engineapi/backups.go
- engineapi/types.go
- util/util.go
> Capture and handle the restore cmd error

- main.go
This belongs to https://github.com/longhorn/longhorn/issues/1494
> proposed solution to logging in json format

- controller/engine_controller.go
Fix the 2nd scenario in longhorn/longhorn#1545
Check the issue for more details
> controller: Fix the deadlock during the engine monitor stopping

- examples/rwx/01-security.yaml
- examples/rwx/02-longhorn-nfs-provisioner.yaml
- examples/rwx/03-rwx-test.yaml
Moved RWX examples into longhorn-manager
> Add rwx example to longhorn-manager

- datastore/longhorn.go
- types/types.go
- util/util.go
> types: Add a new field VIRTUAL_HOSTED_STYLE in backup target credential

- manager/engine.go
> Change Backup volume deletion to be async

- deploy/longhorn-images.txt
- deploy/release-images.txt
> deploy: Add image list

- controller/engine_controller.go
> Fix the race condition leading to live upgrade error

- deploy/longhorn-images.txt
- deploy/release-images.txt
They will be updated during the release process.
> Update image tags to master

- deploy/install/02-components/01-manager.yaml
> deploy: Update instance manager image

- upgrade/upgrade.go
- upgrade/v100to101/upgrade.go
1. To reduce the number of conflicts when doing CRDs upgrade, we do not update IM's label (IM objects and IM pods) if it is up to date. This fix alone solves the issue.
1. Add retry logic when doing CRDs update: if the current leading manager get an error while upgrading, it will release the lock, and crash. This fix alone also solves the issue. See the below picture for more detail.
We combine both of the above fixes to achieve fast (reduce the number of conflicts) and safe (adding retry logic). 
longhorn/longhorn#1646
> upgrade, upgrade/v100to101: do not update IM label if it is up to date, add retry logic when doing CRDs update

- .drone.yml
> Update Drone slack notifications instance URL

- .drone.yml
- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
- deploy/uninstall/uninstall.yaml
- patch/vendor-add-duration-seconds-to-election-record.patch
- patch/vendor-fix-nil-pointer-for-Leader-Election-Record.patch
- upgrade/upgrade.go
- upgrade/v100to101/upgrade.go
- vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
- vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
https://github.com/longhorn/longhorn/issues/1655
https://github.com/longhorn/longhorn/issues/1647
> Backport from v1.0.x

- deploy/install/01-prerequisite/05-podsecuritypolicy.yaml
Signed-off-by: Michael William Le Nguyen <michael@mail.ttp.codes>
https://github.com/longhorn/longhorn/issues/1671
> deploy: add podsecuritypolicy to deploy

- controller/engine_image_controller.go
- controller/engine_image_controller_test.go
- manager/engine.go
https://github.com/longhorn/longhorn/issues/1665
> Backport:  Fix the issue that engine image may be wrongly marked as incompatible

- deploy/install/02-components/01-manager.yaml
Related to: https://github.com/longhorn/longhorn/pull/1585
Fix containerd issue: https://github.com/containerd/containerd/issues/3667
> /var/run/ - mountPropagation: Bidirectional

- controller/volume_controller.go
The error message should address the port.
> Fix error message

- api/model.go
- client/generated_volume.go
- controller/controller_test.go
- controller/engine_controller.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- csi/controller_server.go
- datastore/longhorn.go
- engineapi/backups.go
- engineapi/engine.go
- engineapi/enginesim.go
- engineapi/enginesim_test.go
- engineapi/types.go
- manager/backup.go
- manager/volume.go
- types/resource.go
- upgrade/v1alpha1/upgrade.go
> Add rebuild for restore/DR volumes and refactor the auto attach/detach logic

- datastore/datastore.go
- datastore/kubernetes.go
- datastore/longhorn.go
- datastore/uncached.go
Added comments to exported functions and methods for datastore:
* datastore.go
* kubernetes.go
* longhorn.go
* uncached.go
> Add func/method comments to datastore

- types/setting.go
> types: fix a typo in Default Data Locality Setting

- controller/engine_controller.go
By switching to structured logging and removing the common element
information from the individual log messages it becomes much simpler to
correlate a log statement with some code flow. The structured log fields
also allow us to easily filter logs based on specific element keys.
depends on longhorn/longhorn-manager#661
longhorn/longhorn#1724
longhorn/longhorn#1725
> Refactor engine controller to use structured logging

- api/model.go
To help UI implement Longhorn #1716
https://github.com/longhorn/longhorn/issues/1716
> api: Add actualSize field to the volume controller object

- controller/volume_controller.go
This will clean up the extra failed to scheduled replica when there is
no eviction requested and the healthy replicas count is not less then
the volume spec replica numbers.
https://github.com/longhorn/longhorn/issues/1679
> controller: Clean up extra failed to scheduled replica when no eviction requested

- controller/websocket_controller.go
Refactor websocket controller to address structured logging implementation.
Ref: 
* https://github.com/longhorn/longhorn/issues/1735
* https://github.com/longhorn/longhorn-manager/pull/661
> Refactor websocket controller for structured log

- controller/volume_controller.go
1. Revert back the replica clean up for corrupted or staled case.
2. Refactor replica clean up for failed to scheduled case.
3. Add replica clean up support for data-locality enabled and eviction requested case.
https://github.com/longhorn/longhorn/issues/1679
> Refact replica clean up with supporting data-locality and eviction requested

- controller/volume_controller.go
This change adds auto attach for eviction requested volume and auto
detach it once the eviction is done.
https://github.com/longhorn/longhorn/issues/1704
> controller: Add eviction support for detached volume

- controller/volume_controller.go
Refactor volume controller to address structured logging implementation.
Ref:
* https://github.com/longhorn/longhorn/issues/1734
* https://github.com/longhorn/longhorn-manager/pull/661
> Refactor volume controller for structured log

- manager/misc.go
Snapshot list are now in the engine status.
> support bundle: Remove volume snapshot list

- monitoring/node_collector.go
- monitoring/volume_collector.go
Added the following metrics:
1. `longhorn_node_count_total` : We use this one to detect and alert when a node is down. e.g when the number of ready nodes < total number of nodes. This metric is necessary because when a node goes down, Longhorn manager on the node stops reporting so we cannot get the NotReady status directly from that Longhorn manager.
2. `longhorn_volume_state`: To display and alert about state of volume
3. `longhorn_volume_robustness`:  To display and alert about robustness of volume. e.g: send an alert when volume becomes fault.
With the 3 newly added metrics we are able to draw this dashboard: https://grafana.com/grafana/dashboards/13032.
longhorn/longhorn#1180
> Prometheus support, part 3

- controller/engine_controller.go
> controller: Fix the unexpected auto detachment during the restoring

- controller/uninstall_controller.go
> Fix bug that the uninstaller may get stuck there

- examples/block_volume.yaml
- examples/csi/example_pv.yaml
- examples/deployment.yaml
- examples/pod_with_pvc.yaml
- examples/rwx/03-rwx-test.yaml
- examples/simple_pvc.yaml
- examples/snapshot/restore_existing_backup.yaml
- examples/snapshot/restore_pvc_snapshot.yaml
- examples/statefulset.yaml
https://github.com/longhorn/longhorn/issues/1830
Signed-off-by: khushboo-rancher <khushboo@rancher.com>
> Add namespace in example pvc/pod

- manager/engine.go
This enables us to return errors for a requested backup creation. For
example when a lock cannot be acquired because of a running delete operation.
For the moment we are just returning the raw errors as received.
longhorn/longhorn#1845
> Change backup initiation to be blocking

- app/volume.go
We do recurring backup jobs when:
1. `volume-head` has new data
2. `volume-head` doesn't new data but:
1. last snapshot != last backup's snapshot
We do recurring snapshot jobs when:
1. `volume-head` has new data
1.  recurring snapshot is triggered by recurring backup jobs
longhorn/longhorn#1858
> app: modify the recurring job so that it only happens when volume has new data since the last backup/snapshot

- types/setting.go
https://github.com/longhorn/longhorn/issues/508
> types: Fix disable revision counter setting typo

- controller/setting_controller.go
Refactor setting controller to address structured logging implementation.
Ref:
* https://github.com/longhorn/longhorn/issues/1732
* https://github.com/longhorn/longhorn-manager/pull/661
> Refactor setting controller for structured log

- .drone.yml
- Dockerfile.dapper
https://github.com/longhorn/longhorn/issues/6
Longhorn manager arm support PR.
> Arm64 support

- .drone.yml
> Fix drone build for ARM64 support

- .drone.yml
> add drone slack notifications 

- .drone.yml
https://github.com/longhorn/longhorn/issues/6
> Update drone base docker image to ubuntu18.04

- csi/deployment.go
https://github.com/longhorn/longhorn/issues/6
> Upgrade default csi images

- controller/engine_controller.go
- controller/engine_image_controller_test.go
- controller/instance_handler.go
- controller/instance_handler_test.go
- controller/kubernetes_node_controller.go
- controller/node_controller.go
- controller/replica_controller.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- manager/volume.go
> controller: Clean up the Longhorn node when the kube node is gone

- deploy/install/01-prerequisite/04-default-setting.yaml
https://github.com/longhorn/longhorn/issues/307
> Add 'Disable Replica Rebuild' Setting to default-setting.yaml

- deploy/install/01-prerequisite/04-default-setting.yaml
https://github.com/longhorn/longhorn/issues/508
> Add 'Disable Revision Counter' to default-setting.yaml

- app/driver.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- csi/deployment.go
- csi/deployment_util.go
- datastore/longhorn.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- types/setting.go
It's `IfNotPresent` by default. Can be also set to `Never` or `Always`.
https://github.com/longhorn/longhorn/issues/1891
> setting: Add SystemManagedPodsImagePullPolicy

- controller/engine_controller.go
- controller/events.go
https://github.com/longhorn/longhorn/issues/1669
> Add snapshot purge after rebuild to cleanup system generated snapshot

- controller/engine_controller.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- types/setting.go
https://github.com/longhorn/longhorn/issues/1669
> Add global setting for auto cleanup systen generated snapshot

- controller/kubernetes_pod_controller.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- types/setting.go
> Add a global setting for user to choose whether they want Longhorn todelete workload pod automatically when the volume is detached unexpectly

- deploy/install/02-components/01-manager.yaml
- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/util/util.go
- vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
- vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
- vendor/modules.txt
https://github.com/longhorn/longhorn/issues/1854
> build: update instance manager to v1_20201021

- types/setting.go
https://github.com/longhorn/longhorn/issues/1891
> setting: Fix a typo regarding system managed pods

- update-longhorn-deps.sh
- update-vendor.sh
- vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
- vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
https://github.com/longhorn/longhorn/issues/1779
> Vendor update

- deploy/install/02-components/04-driver.yaml
> fix CSI components images tags

- controller/volume_controller.go
- controller/volume_controller_test.go
- scheduler/replica_scheduler.go
- types/resource.go
- types/setting.go
> Try to reuse failed replica during rebuilding

- csi/controller_server.go
- csi/node_server.go
Fix inconsistent attachment condition checking.
Split device frontend checking with attachment checking.
https://github.com/longhorn/longhorn/issues/1712
> Fix csi 'ControllerPublishVolume' checking attachment condition

- controller/volume_controller.go
- controller/volume_controller_test.go
- types/resource.go
https://github.com/longhorn/longhorn/issues/496
> Add 'TooManySnapshots' condition to volume

- app/driver.go
https://github.com/longhorn/longhorn/issues/1390
> Remove cleanup code for compatible csi attacher

- controller/engine_controller.go
- controller/volume_controller.go
> controller: Handle the case that engine crashes during live upgrade

- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/node_controller.go
- controller/replica_controller.go
- controller/uninstall_controller.go
Refactor setting controller to address structured logging implementation.
https://github.com/longhorn/longhorn/issues/1733
https://github.com/longhorn/longhorn-manager/pull/661
> Refactor uninstall controller for structured log

- csi/controller_server.go
https://github.com/longhorn/longhorn/issues/1712
> Fix csi controller attachment issue

- deploy/uninstall/uninstall.yaml
> Add ConfigMap resource to longhorn-uninstall-role

- controller/controller_test.go
- controller/instance_manager_controller_test.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- scheduler/replica_scheduler.go
https://github.com/longhorn/longhorn/issues/1304
> Fix the issue that causes the reboot test failure for failed replica reuse feature

- app/volume.go
Problem: In the old implementation, the recurring job is stuck in running state and never finishes if the volume is detached unexpectedly in the middle of a backup. This prevents the cronjob from creating any new job in the future. Effectively, it suspends the recurring cronjob forever.
Recurring cronjob now detects when a volume is detached unexpectedly, and cancels the current running job. This makes sure that it doesn't block other running in the future.
longhorn/longhorn#1882
> Recurring job is stuck in running state and never finishes if the volume is detached unexpectedly

- deploy/install/01-prerequisite/04-default-setting.yaml
> deploy: Add setting replica-replenishment-wait-interval

- controller/instance_manager_controller_test.go
> controller: Add an unit test for the IM IP sync issue

- app/volume.go
In the recurring backup job, we check whether the engine process is running. If it is not running, the volume is detached in the middle of the backup process. Therefore, we return error.
longhorn/longhorn#1882
> Return error in the backup recurring job when volume is detached unexpectedly

- controller/volume_controller.go
- upgrade/upgrade.go
- upgrade/v102to110/upgrade.go
> Fix failed replica reuse issues

- api/model.go
- controller/controller_test.go
- controller/node_controller.go
- controller/node_controller_test.go
- controller/replica_controller.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- datastore/longhorn.go
- scheduler/replica_scheduler.go
- scheduler/replica_scheduler_test.go
- types/resource.go
- types/types.go
- upgrade/upgrade.go
- upgrade/v102to110/upgrade.go
> Disk and replica migration

- controller/volume_controller.go
I have posted the analyst at https://github.com/longhorn/longhorn/issues/1942#issuecomment-722698783
longhorn/longhorn#1942
> Add logic to handle the case RemountRequestedAt sometimes is not set when all replicas fail

- deploy/install/02-components/04-driver.yaml
> deploy: Update default csi-snapshotter image tag

- controller/instance_manager_controller.go
- datastore/kubernetes.go
> Clean up poddisruptionbudget of non-existing instance manager pods

- csi/deployment_util.go
When users specify new images for CSI components by changing LonghornDriverDeployer environment variables, we update the corresponding CSI component to use the new images.
longhorn/longhorn#1642
> Update the CSI components when their images change

- controller/volume_controller.go
- manager/volume.go
> Fix the replica disk check during the salvage

- controller/volume_controller.go
If Longhorn fails to start a replica during attaching,
`r.Spec.FailedAt` won't be set since the engine is not running and
replica mode is always empty. Longhorn should be able to handle
replicas failing at the attaching stage.
longhorn/longhorn#1999
> controller: Handle replicas failing at attaching stage

- upgrade/v102to110/upgrade.go
The bug was that we didn't get a new list of IM Pods after `upgradeInstanceMangerPodOwnerRef()`
This PR fixes the bug by getting a new list of IM Pods before `updateIMPodLastAppliedTolerationsAnnotation()`
longhorn/longhorn#2017
> Resolve conflicts when updating Intance Manager Pod's toleration annotation during Longhorn upgrade

- controller/volume_controller.go
> Fix nil pointer issue

- deploy/iscsi/longhorn-iscsi-installation.yaml
Move the original from `longhorn/longhorn` to `longhorn/longhorn-manager`.
> deploy: add iscsi deploy helper

- types/setting.go
> types: Update description for setting 'Guaranteed Engine CPU'

- controller/volume_controller.go
When a volume is created with number of replicas more than available nodes and `AllowVolumeCreationWithDegradedAvailability` is enabled, volume controller constantly updates the volume's `ScheduledCondition`. This prevents other components to update the volume's spec since there will be a lot of conflicts. As a result, volume sometimes takes a long time to attach.
This PR makes sure volume controller only update volume's condition if the condition's status has changed
Longhorn/longhorn#2073
> Fix: volume controller constantly update the ScheduledCondition

- controller/share_manager_controller.go
- datastore/kubernetes.go
- types/types.go
This also includes 2 minor fixes in separate commits.
https://github.com/longhorn/longhorn/issues/2048
> create pv/pvc based on the volumes access mode

- deploy/uninstall/uninstall.yaml
Added services, endpoints, secrets and sharemanagers
> Add missing access rights to the uninstall service account

- csi/controller_server.go
- csi/manager.go
> csi: Add more debug logs for CSI components

- controller/share_manager_controller.go
https://github.com/longhorn/longhorn/issues/2049
> Marshal empty tolerations for share manager annotation

- controller/share_manager_controller.go
- types/types.go
https://github.com/longhorn/longhorn/issues/2086
> Add prefix to share manager pods

- manager/misc.go
https://github.com/longhorn/longhorn/issues/2069
> add share manager yaml into the support bundle

- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/node_controller.go
- controller/replica_controller.go
- controller/share_manager_controller.go
- controller/uninstall_controller.go
- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/2089
> fix log spam

- controller/share_manager_controller.go
We only transfer ownership if the node is unschedulable and the share
manageris in error state, since one shouldn't create new pods on an
unschedulable node. The reason we don't transfer ownership while the pod
is running, is that unschedulable only means that no new pods should be
created on this node.
longhorn/longhorn#2072
> Transfer share manager ownership when a node is being drained

- controller/uninstall_controller.go
- datastore/kubernetes.go
> uninstaller: remove services when uninstalling

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
> Update instance manager image to v1_20201216

- controller/kubernetes_node_controller.go
> controller: KubeNodeController stop filtering keys in the enqueue function

- csi/controller_server.go
This fixes an issue for RWX volume creation as well as volume creation
based on a snapshot where the storage class has no params defined.
longhorn/longhorn#2154
> Fix csi plugin nil pointer for storage classes with no defined params

- go.mod
- go.sum
- vendor/modules.txt
Bump longhorn/backupstore version to support s3 pagination.
https://github.com/longhorn/longhorn/issues/1904
> Support s3 pagination

- controller/instance_manager_controller.go
- controller/volume_controller.go
Find that some logs need to be fixed when I check longhorn/longhorn#2015
> controller: Fix some controller logs

- api/model.go
- api/node.go
- controller/controller_manager.go
- controller/instance_manager_controller.go
- controller/setting_controller.go
- datastore/longhorn.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- manager/node.go
- types/resource.go
- types/setting.go
- types/types.go
- upgrade/upgrade.go
- upgrade/v110to111/upgrade.go
> Enhanced instance manager CPU reservation

- controller/instance_manager_controller.go
- controller/replica_controller.go
Refactor replica controller to address structured logging implementation.
https://github.com/longhorn/longhorn/issues/1731
https://github.com/longhorn/longhorn-manager/pull/661
> Refactor replica controller for structured log

- csi/controller_server.go
- datastore/longhorn.go
- manager/volume.go
- util/util.go
Part of and relate to https://github.com/longhorn/longhorn-manager/pull/825#issuecomment-783294412.
- Add volume name autocorrection.
- Correct misuse of the error codes.
Fix https://github.com/longhorn/longhorn/issues/2270
> Fix CSI sanity check - Create Volume

- types/deepcopy.go
> Update the deep copy function for engine image status to copy the the NodeDeploymentMap

- controller/controller_manager.go
- types/setting.go
> Fix one typo for the CPU reservation

- controller/engine_controller.go
> Fix log entry using INFO while passing fmt strings

- manager/volume.go
Small PR for typo fix.
Signed-off-by: khushboo-rancher <fnu.khushboo@suse.com>
> Fix a typo

- client/generated_backing_image.go
- client/generated_backup_volume.go
- client/generated_engine_image.go
- client/generated_node.go
- client/generated_setting.go
- client/generated_volume.go
https://github.com/longhorn/longhorn/issues/2372
> Remove Timestamp from api-client

- deploy/longhorn-images.txt
- deploy/release-images.txt
ref https://github.com/longhorn/longhorn/issues/2295
> Add backing image in images.txt

- controller/volume_controller.go
The temporary solution is: don't attempt to start replica if the corresponding default IM is `error`, `unknown`, or `stopped`
I think in the long run, we should consider refactor the replica's reconciliation logic in replica controller so that it correctly set the state of the replica
longhorn/longhorn#2475
> Fix volume cannot be attached when one of the replicas has error IM and the node of IM is still running

- api/model.go
> api: Expose backing image size

- controller/backing_image_manager_controller.go
- deploy/install/02-components/01-manager.yaml
- go.mod
- go.sum
- vendor/github.com/longhorn/backing-image-manager/pkg/types/types.go
- vendor/modules.txt
> Update backing image manager and bug fix

- deploy/longhorn-images.txt
- deploy/release-images.txt
ref: https://github.com/longhorn/longhorn/issues/2416
> Upate backing image to v1_20210416 in images.txt

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
> Update share manager to v1_20210416

- controller/volume_controller.go
> Add PriorityClass setting to recurring jobs

- manager/backingimage.go
> Cherry-pick: Auto correct backing image name during creation

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
Master tag is changed to master-head
Signed-off-by: Khushboo <fnu.khushboo@suse.com>
> Change master tag to master-head

- controller/kubernetes_secret_controller.go
- datastore/kubernetes.go
- datastore/longhorn.go
Fix aws Iam role processing modifying pods from lister directly
longhorn/longhorn#2633
> Fix aws Iam role sync modifying pods from lister directly

- controller/kubernetes_pv_controller.go
- controller/kubernetes_secret_controller.go
- datastore/kubernetes.go
- datastore/longhorn.go
- types/deepcopy.go
Backport of the following prs.
https://github.com/longhorn/longhorn-manager/pull/901
https://github.com/longhorn/longhorn-manager/pull/902
https://github.com/longhorn/longhorn-manager/pull/903
For the following issues:
https://github.com/longhorn/longhorn/issues/2631
https://github.com/longhorn/longhorn/issues/2632
https://github.com/longhorn/longhorn/issues/2633
> Backport of deepcopy, ws order, AWS IAm fixes

- app/volume.go
Retain only last copy of backup snapshot to resolve issue '[FEATURE] automatic successful backups should only retain the last snapshot'
Test case update in https://github.com/longhorn/longhorn-tests/pull/615
Refs: https://github.com/longhorn/longhorn/issues/2231
None
> Retain only last copy of backup snapshot

- controller/controller_manager.go
- controller/kubernetes_pv_controller.go
- controller/kubernetes_pv_controller_test.go
- csi/node_server.go
- csi/util.go
Backports the following PR's
https://github.com/longhorn/longhorn-manager/pull/910
https://github.com/longhorn/longhorn-manager/pull/911
For the following issues:
longhorn/longhorn#2629
longhorn/longhorn#2060
> BACKPORT: VA removal and mount cleanup

- csi/controller_server.go
By rounding up the requested volume size before checking the size of
existing volume, we ensure that the CSI volume creation operation is
retried with idempotency in the case where the requested size is not
multiple of 2*1024*1024
longhorn/longhorn#2624
> Roundup requested volume size at the beginning of the CSI CreateVolume() call

- csi/controller_server.go
By rounding up the requested volume size before checking the size of
existing volume, we ensure that the CSI volume creation operation is
retried with idempotency in the case where the requested size is not
multiple of 2*1024*1024
longhorn/longhorn#2624
> Cherry-pick: Roundup requested volume size at the beginning of the CSI CreateVolume() call

- controller/volume_controller.go
When volume is not attached and the setting `Allow Recurring Job While Volume Is Detached` is disable, we delete the CronJob instead of suspending it. When volume is attached, we recreate the CronJob. This is to prevent Kubernetes from permanantly stopping the CronJob if the volume is detached for a long time.
longhorn/longhorn#2513
> Delete CronJob instead of suspending

- controller/volume_controller.go
When volume is not attached and the setting `Allow Recurring Job While Volume Is Detached` is disable, we delete the CronJob instead of suspending it. When volume is attached, we recreate the CronJob. This is to prevent Kubernetes from permanently stopping the CronJob if the volume is detached for a long time
longhorn/longhorn#2513
> Cherry-pick: Delete CronJob instead of suspending

- api/backingimage.go
- api/model.go
- api/stream.go
- manager/backingimage.go
https://github.com/longhorn/longhorn-manager/pull/918
https://github.com/longhorn/longhorn/issues/2672
> [Backport][v1.1.2] ws data cleanup

- controller/node_controller.go
This one is a bit of a behavior change, I picked 100MB arbitrarily could have used 10MB instead but it means it will report sooner / more often.
Since this is retrieved as part of the node_controller on block precision,
the node controller will be constantly updating the diskStatus since there
will always be something using disk space on the default disk (logs, etc)
Even for external disks, that don't have another consumer except longhorn
There is no need for block precision on StorageAvailable since it should
be a problem to minimally under report the available storage.
This also addresses another cause of excessive websocket traffic https://github.com/longhorn/longhorn/issues/2672
issue ref: https://github.com/longhorn/longhorn/issues/2680
> Fix infinite Node Status updates by truncating disk StorageAvailable to the next available 100MB

- controller/engine_image_controller.go
- controller/node_controller.go
- controller/replica_controller.go
- datastore/longhorn.go
- manager/node.go
Backport of read only lister usage #920
longhorn/longhorn#2681
> Backport of PR 920 - read only lister usage

- controller/node_controller.go
Backport of #921
longhorn/longhorn/issues/2680
> Backport of PR 921 - Node Status available storage truncation

- controller/volume_controller.go
- manager/volume.go
Backport of PR 925
longhorn/longhorn#2686
longhorn/longhorn-manager#925
> Backport PR 925

- controller/instance_manager_controller.go
longhorn/longhorn#2561
This is a surgery fix. IIRC, we need to refactor the monitor implementation in all controllers. @joshimoo Do you remember the issue number?
> controller: Stop monitoring if the streaming does not work

- controller/instance_manager_controller.go
> BACKPORT: controller: Stop monitoring if the streaming does not work

- api/model.go
- api/router.go
- app/daemon.go
- deploy/install/02-components/01-manager.yaml
Backport https://github.com/longhorn/longhorn-manager/pull/931
https://github.com/longhorn/longhorn/issues/2696
> [Backport][v1.1.2] Add pprof and disable-profiler cmd flag

- api/model.go
- api/router.go
- app/daemon.go
- deploy/install/02-components/01-manager.yaml
This reverts commit 32905ff62ec0aeab9a4a115f42ad4018ffe5d4c1.
https://github.com/longhorn/longhorn-manager/pull/938
https://github.com/longhorn/longhorn/issues/2696#issuecomment-863995649
> Revert "Enable pprof by default and allow user to disable"

- app/daemon.go
To fix https://github.com/longhorn/longhorn/issues/2715
Please revert the following PR's
- https://github.com/longhorn/longhorn-manager/pull/931
- https://github.com/longhorn/longhorn-manager/pull/937
deployment reverts:
- https://github.com/longhorn/longhorn/pull/2700
- https://github.com/longhorn/longhorn/pull/2709
website reverts:
- https://github.com/longhorn/website/pull/324
- https://github.com/longhorn/website/pull/325
Afterwards this PR can be merged.
It's based on the latest commit before the above commits
https://github.com/longhorn/longhorn-manager/commit/d32898046ab984db6c88b5980bcef2f181c77a1e
See comment here: https://github.com/longhorn/longhorn/issues/2696#issuecomment-863995649
Signed-off-by: Joshua Moody <joshua.moody@suse.com>
> Add pprof http endpoint

- csi/controller_server.go
- csi/deployment.go
- csi/deployment_util.go
- csi/nfs/nsenter_mount.go
- csi/node_server.go
- csi/server.go
- csi/util.go
These where the fixes that where merged into v1.1.2 longhorn/longhorn-manager#927
This is just to have the same fixes in master that are currently in v1.1.2
Additional CSI fixes/work for master will be done in longhorn/longhorn-manager/pull/922
> UI path fixes for master

- app/daemon.go
Backport of longhorn/longhorn-manager#938 default pprof enabled on localhost:6060
longhorn/longhorn#2715
> Backport of pprof for v1.1.2

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
Issue longhorn/longhorn#2697
PR https://github.com/longhorn/longhorn-instance-manager/pull/89
> Update instance-manager@v1_20210621 to fix deadlocks

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
Issue longhorn/longhorn#2697 
PR longhorn/longhorn-instance-manager#89
> Backport: Update instance-manager@v1_20210621 to fix deadlocks

- controller/instance_manager_controller.go
Fix drain stuck forever for unreplicated volume to resolve issue '[BUG] kubectl drain node gets stuck forever'
Refs: # https://github.com/longhorn/longhorn/issues/2673
None
> Fix drain stuck forever for unreplicated volume

- manager/volume.go
Fix regression v1.1.2 expand with static storage class to resolve issue 'Application couldn't mount the volume after expanded the volume'
Get static class name from setting `default-longhorn-static-storage-class`.  If class name exist, continue with PVC expansion.  If not exist, continue with LHV expansion.
enhancement
* Case 1: From UI, PVC expand Volume with `default-longhorn-static-storage-class` set as `longhorn-<CUSTOMIZED-NON-EXISTED-CLASS-NAME>`
Expand will success.
Refs: Longhorn: #2692
- Issue discussion: https://rancher.slack.com/archives/C01G91NUHFY/p1624409225268200?thread_ts=1624316294.238500&cid=C01G91NUHFY
> Fix regression v1.1.2 expand with static storage class

- types/setting.go
ref: https://github.com/longhorn/longhorn/issues/2060
> Deprecate VA policy from UI

- package/Dockerfile
ref: https://github.com/longhorn/longhorn/issues/2763
cc @meldafrawi
> Frequently update packages when building image

- deploy/install/01-prerequisite/04-default-setting.yaml
1. volume-attachment-recovery-policy
2. guaranteed-engine-cpu
> deploy: Remove deprecated values from the default setting yaml file

- client/common.go
> [cherry-pick-v1.1.3] Increase rancher HTTP client default timeout to 1 min

- controller/instance_handler.go
- controller/volume_controller.go
> Back-port v1.1.3: Fix auto salvage logic and log stream socket connection leaking

- Dockerfile.dapper
- package/Dockerfile
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
> update Dockerfile and Dockerfile.dapper

- controller/engine_controller.go
- engineapi/engine.go
- engineapi/enginesim.go
- engineapi/types.go
> Backport 2818 - further optimize sockets

- datastore/longhorn.go
> Backport 2827 - fix ds get engine call returning raw cached object

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/process_manager.go
- vendor/modules.txt
> Update IM version for grpc connection leak

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
- go.mod
- go.sum
- vendor/github.com/longhorn/longhorn-instance-manager/pkg/client/process_manager.go
- vendor/modules.txt
> Backport 2824 - update im version to v1_20210731 to fix connection leak

- client/generated_backup.go
- client/generated_client.go
Package client out-of-date.
https://github.com/longhorn/longhorn/issues/2530
> Update package client

- api/model.go
- controller/backing_image_controller.go
- controller/backing_image_data_source_controller.go
- controller/node_controller.go
- controller/replica_controller.go
- csi/controller_server.go
- deploy/install/01-prerequisite/06-storageclass.yaml
- examples/storageclass.yaml
- manager/backingimage.go
- upgrade/v111to120/upgrade.go
longhorn/longhorn#2899
longhorn/longhorn#2900
> Backing image fix

- api/backup.go
- api/model.go
- api/router.go
- client/generated_backup_target.go
- client/generated_client.go
- controller/backup_target_controller.go
- engineapi/types.go
- manager/engine.go
- types/deepcopy.go
- types/resource.go
https://github.com/longhorn/longhorn/issues/2887
> Add BackupTarget unavailable reason and HTTP endpoint

- datastore/longhorn.go
https://github.com/longhorn/longhorn/issues/467
> Validate recurring job group name

- controller/backing_image_controller.go
- controller/backing_image_data_source_controller.go
- controller/controller_manager.go
- controller/node_controller.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- datastore/longhorn.go
- manager/backingimage.go
- types/resource.go
- types/types.go
> Support exporting backing image from volume

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
> Update backing image manager to v2_20210820

- deploy/uninstall/uninstall.yaml
> Add missing recurringjob resource in cluster role in uninstall

- types/setting.go
https://cloud-native.slack.com/archives/CNVPEL9U3/p1629250829158500
> types: Explicit explain how Longhorn identifies a node zone in the setting description

- controller/volume_controller.go
> controller: Fix a informer typo for volume controller

- controller/instance_manager_controller.go
- controller/uninstall_controller.go
- datastore/longhorn.go
> Fix the bug that lead to the uninstaller loop in instance manager deletion and recreation

- upgrade/v110to120/upgrade.go
> upgrade: Remove finalizers and update OwnershipReference for Instance Managers

- controller/instance_manager_controller.go
- controller/uninstall_controller.go
- datastore/longhorn.go
- upgrade/upgrade.go
- upgrade/v112to113/upgrade.go
> [Backport][v1.1.3]Fix the bug that lead to the uninstaller loop in instance manager deletion and recreation

- deploy/longhorn-images.txt
- deploy/uninstall/uninstall.yaml
Keep the images in `/deploy/longhorn-images.txt` to be up to date
> Update the Longhorn images to latest version

- controller/backup_volume_controller.go
https://github.com/longhorn/longhorn/issues/2897
> Delete old engine image backup with state Completed

- upgrade/v110to120/upgrade.go
> Fixed in upgrade path: sometime we forget to remove the finalizer from all instance managers

- api/model.go
https://github.com/longhorn/longhorn/issues/2740
> Create the data struct for backupvolume/backup in HTTP response

- controller/volume_controller.go
Fix E2E test `test_kubernetes.py::test_backup_kubernetes_status`
> Fix LastPVCRefAt/LastPodRefAt did not update

- client/generated_backup_volume.go
> Update the client after updating backup volume endpoint

- controller/engine_controller.go
> controller: Wait for BackupVolume updating the status size before restore

- controller/volume_controller.go
> Fix restore volumes not working issue after unexpected engine crash or node down

- controller/volume_controller.go
Don't attempt to find the IM on a down or deleted node before starting a replica
longhorn/longhorn#2848
> Backport to v1.1.3: Fixed bug volume cannot attach after Kubernetes node is deleted

- upgrade/v110to120/upgrade.go
https://github.com/longhorn/longhorn/issues/2961
> Fix volume update for recurringJob during upgrade

- upgrade/v110to120/upgrade.go
https://github.com/longhorn/longhorn/issues/2961
https://github.com/longhorn/longhorn-manager/pull/1024
> [Backport][v1.2.x] Fix volume update for recurringJob during upgrade

- examples/storageclass.yaml
https://github.com/longhorn/longhorn/issues/2964
> Add fstype in the example sc

- controller/backing_image_controller.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- types/resource.go
- types/setting.go
> Fix bug: Longhorn wrongly restart downloading for the ready backing image 

- controller/backing_image_controller.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- types/resource.go
- types/setting.go
> [Backport][v1.2.x]Fix bug: Longhorn wrongly restart downloading for the ready backing image

- csi/controller_server.go
backport https://github.com/longhorn/longhorn-manager/pull/1032
https://github.com/longhorn/longhorn/issues/2271
> [Backport][v1.2.x] Fix sanity test - volume source volume not found

- types/resource.go
- upgrade/v110to120/upgrade.go
Backport https://github.com/longhorn/longhorn-manager/pull/1027
https://github.com/longhorn/longhorn/issues/2961#issuecomment-909810861
> [Backport][v1.2.x] Fix recurringJob CRs not created during upgrade

- controller/volume_controller.go
- manager/volume.go
> Allow migration for degraded volumes

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
> Backport SM image update for v1.2.1 to v1_20210914

- controller/controller_manager.go
- controller/replica_controller.go
- controller/volume_controller.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- types/setting.go
> Introduce a new setting to limit per node concurrent rebuilding count

- controller/volume_controller.go
- controller/volume_controller_test.go
Longhorn/longhorn#2805
Longhorn/longhorn#2460
> Fix regressions introduced by migration & rebuilding changes

- controller/controller_manager.go
- controller/replica_controller.go
- controller/volume_controller.go
- controller/volume_controller_test.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- manager/volume.go
- types/setting.go
longhorn/longhorn#2805
longhorn/longhorn#2460
> [Backport][v1.2.x] Migration fix and concurrent rebuilding feature introducing

- controller/volume_controller.go
- csi/controller_server.go
- manager/volume.go
- scheduler/replica_scheduler.go
longhorn/longhorn#2962
longhorn/longhorn#2952
> Enforce overprovisioning limit when expanding volume size and fix the rounding issue with Storage Over Provisioning Percentage

- controller/replica_controller.go
> controller: Fix the replica eviction not working issue

- controller/replica_controller.go
> [Backport][v1.2.x]controller: Fix the replica eviction not working issue

- controller/replica_controller.go
> [Backport][v1.1.3]controller: Fix the replica eviction not working issue

- controller/setting_controller.go
- types/setting.go
> Notify users about latest stable version of every minor release line

- controller/setting_controller.go
- types/setting.go
> [Backport v1.1.3] Publish Longhorn stable releases

- controller/setting_controller.go
- types/setting.go
> [Backport v1.2.1] Publish Longhorn stable releases

- upgrade/v102to110/upgrade.go
> [Backport][v1.2.x] upgrade: Avoid CR update if there is nothing change

- upgrade/v102to110/upgrade.go
> [Backport][v1.1.3] upgrade: Avoid CR update if there is nothing change

- controller/replica_controller.go
- controller/volume_controller.go
- types/setting.go
- upgrade/upgrade.go
- upgrade/v120to121/upgrade.go
> Deprecate setting 'disable-replica-rebuild' and merge it into the new setting

- controller/replica_controller.go
- controller/volume_controller.go
- types/setting.go
- upgrade/upgrade.go
- upgrade/v120to121/upgrade.go
> [Backport][v1.2.x] Deprecate setting 'disable-replica-rebuild' and merge it into the new setting

- controller/volume_controller.go
> controller: live upgrade should not continue checking the old replica count while the new replicas are activated

- controller/volume_controller.go
> [Backport][v1.2.x]controller: live upgrade should not continue checking the old replica count while the new replicas are activated

- controller/volume_controller.go
> [Backport][v1.1.3]controller: live upgrade should not continue checking the old replica count while the new replicas are activated

- controller/replica_controller.go
- types/setting.go
> Fix the concurrent rebuild limit not working issue

- upgrade/v111to120/upgrade.go
> upgrade: Check if the label already exists before setting it for a volume

- upgrade/v111to120/upgrade.go
> [Backport][v1.2.x]upgrade: Check if the label already exists before setting it for a volume

- app/csi.go
- csi/manager.go
> [Back-port: v1.2.1] Fixed the log about Longhorn CSI plugin version

- app/csi.go
- csi/manager.go
> Fixed the log about Longhorn CSI plugin version

- csi/manager.go
> Fix a confusing log

- csi/manager.go
> [Backport v1.2.1] Fix a confusing log

- app/csi.go
- csi/manager.go
> [Backport: v1.1.3] Fixed the log about Longhorn CSI plugin version

- csi/node_server.go
Fixes issues when im crashes for replica sets.
This does not fix encrypted RWO volumes for replicasets in the case where the im crashes.
For details check main pull request longhorn/longhorn-manager#1079
longhorn/longhorn#3070
> BACKPORT HOTFIX Replicaset IM crashes

- manager/misc.go
https://github.com/longhorn/longhorn/issues/3142
> [v1.2.x] Add missing Longhorn CRs in support bundle

- app/daemon.go
- app/driver.go
- app/recurring_job.go
- client/common.go
- controller/backing_image_data_source_controller.go
- controller/backing_image_manager_controller.go
- controller/backup_target_controller.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/kubernetes_node_controller.go
- controller/uninstall_controller.go
- csi/deployment_util.go
- csi/server.go
- datastore/longhorn.go
- engineapi/backups.go
- engineapi/engine.go
- engineapi/enginesim.go
- engineapi/instance_manager.go
- engineapi/types.go
- main.go
- manager/node.go
- manager/volume.go
- util/time.go
- util/util.go
Signed-off-by: slayer321 <sachin.maurya7666@gmail.com>
related to bugbash
https://lift.sonatype.com/result/longhorn/longhorn-manager/01FHW2JKTWJ3Z4RA5MMT2A53WS?t=CustomTool%20%22Staticcheck%22%7CST1005
> error strings should not be capitalized

- controller/recurring_job_controller.go
https://github.com/longhorn/longhorn/issues/2432
> Recurring snapshot/backup job supports imagePullSecrets

- controller/backing_image_data_source_controller.go
- controller/backing_image_manager_controller.go
- controller/engine_controller.go
- controller/instance_manager_controller.go
- controller/kubernetes_pv_controller.go
- controller/node_controller.go
- controller/replica_controller.go
- controller/share_manager_controller.go
- csi/server.go
- monitoring/monitoring.go
- types/deepcopy.go
Signed-off-by: slayer321 <sachin.maurya7666@gmail.com>
related to bugbash
https://lift.sonatype.com/result/longhorn/longhorn-manager/01FHW2JKTWJ3Z4RA5MMT2A53WS?t=CustomTool%20%22Staticcheck%22%7CS1023
> removing redudant statement

- api/node.go
- controller/node_controller.go
- controller/replica_controller.go
- controller/setting_controller.go
- controller/volume_controller.go
- datastore/longhorn.go
- types/setting.go
- upgrade/v102to110/upgrade.go
- upgrade/v110to111/upgrade.go
- upgrade/v1alpha1/types/setting.go
Signed-off-by: Shatakshi <shatakshi.gupta85@gmail.com>
Related to Bugbash.
> Fix S1002 errors

- api/stream.go
- client/common.go
- controller/kubernetes_pv_controller_test.go
- controller/node_controller_test.go
- controller/recurring_job_controller.go
- controller/volume_controller_test.go
- csi/server.go
- csi/util.go
- manager/misc.go
- scheduler/replica_scheduler_test.go
- upgrade/v1alpha1/upgrade.go
no issue related to bugbash
https://lift.sonatype.com/result/longhorn/longhorn-manager/01FHW2JKTWJ3Z4RA5MMT2A53WS?t=CustomTool%20%22GoSec%22%7CG104&t=CustomTool%20%22golangci-lint%22%7Cerrcheck
> handle the  unhandled errors.

- app/recurring_job.go
No matter the volume head is empty or not, always take backup/snapshot
in recurring backup job to avoid confusion.
Longhorn#3128
> recurring jobs: always take backup/snapshot

- go.mod
- go.sum
- util/util.go
- vendor/github.com/google/uuid/README.md
- vendor/github.com/google/uuid/hash.go
- vendor/github.com/google/uuid/marshal.go
- vendor/github.com/google/uuid/null.go
- vendor/github.com/google/uuid/sql.go
- vendor/github.com/google/uuid/uuid.go
- vendor/github.com/google/uuid/version1.go
- vendor/github.com/google/uuid/version4.go
- vendor/modules.txt
Replace package from satori/go.uuid to google/uuid
> Fix CVE-2021-3538

- examples/network-policy/backing-image-data-source-network-policy.yaml
- examples/network-policy/backing-image-manager-network-policy.yaml
- examples/network-policy/instance-manager-networking.yaml
- examples/network-policy/manager-network-policy.yaml
- examples/network-policy/ui-network-policy.yaml
> Add network policy examples

- controller/volume_controller.go
> Ask the new engine to restore data only when it is required

- controller/volume_controller.go
> [Backport][v1.2.x]Ask the new engine to restore data only when it is required 

- .github/workflows/stale.yml
- .gitignore
> Add stale github action workflow

- scheduler/replica_scheduler.go
* Refactor the replica scheduler for readability
* Allow disk eviction to move replicas from old disk to new disk on the same node even if the Node Level Soft Anti-Affinity is disable
longhorn/longhorn#3076
> Refactor the replica scheduler

- datastore/longhorn.go
Issue: https://github.com/longhorn/longhorn/issues/811
> Add validation for credential secret

- csi/deployment.go
- deploy/longhorn-images.txt
> Change the CSI sidecar images from upstream repo to Longhorn repo

- csi/deployment.go
- deploy/longhorn-images.txt
> [Backport v1.2.3] Change the CSI sidecar images from upstream repo to Longhorn repo

- scheduler/replica_scheduler.go
* Refactor the replica scheduler for readability
* Allow disk eviction to move replicas from old disk to new disk on the same node even if the Node Level Soft Anti-Affinity is disable
longhorn/longhorn#3076
longhorn/longhorn#3257
> [Back-port v1.2.3] Refactor the replica scheduler

- api/setting.go
- datastore/longhorn.go
https://github.com/longhorn/longhorn/issues/3267
> Validate S3 input to make sure they don't contain trailing newline or space

- controller/share_manager_controller.go
This fix is included in the below backports for v1.1.3 and v1.2.3
https://github.com/longhorn/longhorn-manager/pull/1137
https://github.com/longhorn/longhorn-manager/pull/1138
> fix for a potential nil pointer issue

- deploy/longhorn-images.txt
- deploy/release-images.txt
> Update patched csi sidecar images in image.txt

- deploy/install/02-components/04-driver.yaml
> Update patched csi sidecar images comment in driver.yaml

- controller/engine_controller.go
- controller/replica_controller.go
https://github.com/longhorn/longhorn/issues/3255
> controller: Try best to clean up instance processes

- controller/kubernetes_node_controller.go
This is a straightforward fix without a Github ticket. It's found in PR https://github.com/longhorn/longhorn-manager/pull/1092#discussion_r729693344
> controller: Update node when there is a modification

- controller/engine_controller.go
- controller/replica_controller.go
Longhorn/longhorn#3255
Longhorn/longhorn#3288
> [BACKPORT][v1.1.3]controller: Try best to clean up instance processes

- controller/kubernetes_node_controller.go
https://github.com/longhorn/longhorn-manager/pull/1148
> [Backport][v1.2.x]controller: Update node when there is a modification

- controller/engine_controller.go
- controller/replica_controller.go
Longhorn/longhorn#3255
Longhorn/longhorn#3287
> [BACKPORT][v1.2.x]controller: Try best to clean up instance processes

- controller/kubernetes_node_controller.go
https://github.com/longhorn/longhorn-manager/pull/1148
> [Backport][v1.1.3]controller: Update node when there is a modification

- go.mod
- go.sum
- vendor/github.com/gogo/protobuf/proto/text_parser.go
- vendor/modules.txt
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
> bump github.com/gogo/protobuf to v1.3.2

- vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
- vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
> Applying leader election patches

- controller/volume_controller.go
- controller/volume_controller_test.go
- datastore/longhorn.go
- k8s/pkg/apis/longhorn/v1beta1/engine.go
- manager/volume.go
- upgrade/v122to123/upgrade.go
longhorn/longhorn#3206
https://github.com/longhorn/longhorn/issues/3315
> [Backport][v1.2.x] Migrating volume auto recovery

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>
> patch longhorn backing image and share manager images

- csi/deployment.go
https://github.com/longhorn/longhorn/issues/3303
https://github.com/longhorn/longhorn/issues/3339
> [Backport][v1.2.x]csi: Add a flag for the resizer so that it would handle completed job pods

- csi/deployment.go
> csi: Add a flag for the resizer so that it would handle completed job pods

- deploy/install/02-components/02-backend.yaml
Signed-off-by: Keith Lucas <keith.lucas@suse.com>
> Add a service definition for instance manager

- controller/replica_controller.go
Longhorn/longhorn#3242
Signed-off-by: Shuo Wu <shuo.wu@suse.com>
> controller: ReplicaController does not enqueue irrelavent replicas for backing image changes

- controller/replica_controller.go
longhorn/longhorn#3242
longhorn/longhorn#3363
> [BACKPORT][v1.1.3]controller: ReplicaController does not enqueue irrelavent replicas for backing image changes 

- controller/replica_controller.go
Longhorn/longhorn#3242
https://github.com/longhorn/longhorn/issues/3362
> [BACKPORT][v1.2.x]controller: ReplicaController does not enqueue irrelavent replicas for backing image changes

- api/model.go
- controller/backing_image_controller.go
- controller/node_controller.go
- controller/replica_controller.go
- manager/backingimage.go
> Make sure backing images can be handled even if spec.disks is not initialized

- app/daemon.go
- deploy/install/01-prerequisite/04-default-setting.yaml
- deploy/install/02-components/01-manager.yaml
- types/setting.go
Create a new overlay folder to customize the default setting after longhorn manager DaemonSet.
Also, the customize default setting is changed from ConfigMap to Setting CRs.
https://github.com/longhorn/longhorn/issues/2570
> Change default setting from ConfigMap to Setting CR

- api/model.go
- csi/controller_server.go
- csi/deployment.go
> [Backport v1.2.3] Fix potential bugs inside Longhorn CSI related to the CSI snapshot flow

- controller/instance_manager_controller.go
Signed-off-by: Keith Lucas <keith.lucas@suse.com>
> Pass the DNS suffix to the replica instance manager

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
- deploy/release-images.txt
> Update im to v1_20211210

- deploy/install/01-prerequisite/04-default-setting.yaml
> Fix indent in default setting YAML

- api/model.go
- client/generated_backup_status.go
https://github.com/longhorn/longhorn/issues/3228
> feat: response backup size to the volume API endpoint

- controller/backup_controller.go
> controller: Fix NPE issue when trying to get the client for a nil engine

- deploy/install/01-prerequisite/03-crd.yaml
- k8s/pkg/apis/longhorn/v1beta1/recurringjob.go
- k8s/pkg/apis/longhorn/v1beta2/recurringjob.go
https://github.com/longhorn/longhorn/issues/3493
> crd: add recurring job retain count max check

- controller/backup_controller.go
Longhorn/longhorn#3484
https://github.com/longhorn/longhorn/issues/3496
> [BACKPORT][v1.2.4]controller: Fix NPE issue when trying to get the client for a nil engine

- csi/deployment.go
- deploy/install/01-prerequisite/03-crd.yaml
- k8s/generate_code.sh
- k8s/pkg/apis/longhorn/v1beta1/volume.go
- k8s/pkg/apis/longhorn/v1beta2/volume.go
- types/data_source.go
The field DataSource should be a string with full information about the source of volume. For example, `snap://vol-name/snapshot-name`
longhorn/longhorn#3508
> Fix bug volume cloning feature is broken

- controller/controller_test.go
- controller/instance_handler.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- datastore/kubernetes.go
https://github.com/longhorn/longhorn/issues/2650
https://github.com/longhorn/longhorn/issues/3459
> Change the lifecycle management of the instance manager pods

- controller/controller_test.go
- controller/instance_handler.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- datastore/kubernetes.go
longhorn/longhorn#2650
longhorn/longhorn#3459
https://github.com/longhorn/longhorn/issues/3541
https://github.com/longhorn/longhorn/issues/3542
> [BACKPORT][v1.2.4] Change the lifecycle management of the instance manager pods

- controller/controller_test.go
- controller/instance_handler.go
- controller/instance_manager_controller.go
- controller/instance_manager_controller_test.go
- datastore/kubernetes.go
longhorn/longhorn#2650
longhorn/longhorn#3459
longhorn/longhorn#3543
longhorn/longhorn#3544
> [BACKPORT][v1.1.4] Change the lifecycle management of the instance manager pods

- csi/controller_server.go
> Extend CSI Snapshot support to Longhorn snapshot

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
Update the images tag with v1.1.x-head
Signed-off-by: Khushboo <fnu.khushboo@suse.com>
> Update the image tags on v1.1.x branch

- deploy/install/02-components/01-manager.yaml
- deploy/install/02-components/03-ui.yaml
- deploy/install/02-components/04-driver.yaml
Update the image tags in the 1.2.x branch
Signed-off-by: Khushboo <fnu.khushboo@suse.com>
> Update the tags in specific branch

- deploy/scripts/environment_check.sh
> environment_check: check per node packages

- api/router.go
- controller/backing_image_controller.go
- controller/backing_image_data_source_controller.go
- controller/backing_image_manager_controller.go
- controller/backup_controller.go
- controller/backup_target_controller.go
- controller/backup_volume_controller.go
- controller/controller_manager.go
- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/kubernetes_configmap_controller.go
- controller/kubernetes_node_controller.go
- controller/node_controller.go
- controller/recurring_job_controller.go
- controller/replica_controller.go
- controller/setting_controller.go
- controller/share_manager_controller.go
- controller/uninstall_controller.go
- controller/volume_controller.go
- monitoring/monitoring.go
- monitoring/registry/registry.go
- monitoring/workqueue/metrics.go
https://github.com/longhorn/longhorn/issues/3083
https://github.com/longhorn/longhorn/issues/3609
> [Backport 1.2.4] Fix scalability issue and expose controller workqueue prometheus metrics

- api/router.go
- controller/backing_image_controller.go
- controller/backing_image_manager_controller.go
- controller/controller_manager.go
- controller/engine_controller.go
- controller/engine_image_controller.go
- controller/instance_manager_controller.go
- controller/kubernetes_configmap_controller.go
- controller/kubernetes_node_controller.go
- controller/node_controller.go
- controller/replica_controller.go
- controller/setting_controller.go
- controller/share_manager_controller.go
- controller/uninstall_controller.go
- controller/volume_controller.go
- monitoring/monitoring.go
- monitoring/registry/registry.go
- monitoring/workqueue/metrics.go
https://github.com/longhorn/longhorn/issues/3083
https://github.com/longhorn/longhorn/issues/3610
> [Backport 1.1.4] Fix scalability issue and expose controller workqueue prometheus metrics

- controller/kubernetes_pod_controller.go
- controller/kubernetes_pv_controller.go
- controller/kubernetes_secret_controller.go
- controller/node_controller.go
> Fix forget to change AddRateLimited() to Add() in some controllers

- controller/kubernetes_pod_controller.go
- controller/kubernetes_pv_controller.go
- controller/kubernetes_secret_controller.go
- controller/node_controller.go
longhorn/longhorn#3083
https://github.com/longhorn/longhorn/issues/3610
> [Backport v1.1.4] Fix forget to change AddRateLimited() to Add() in some controllers

- controller/engine_image_controller.go
Hi,
I refactored the logging in the engine image controller similar as it was done in https://github.com/longhorn/longhorn-manager/pull/662 for the engine controller.
This would resolve issue https://github.com/longhorn/longhorn/issues/1726.
Looking forward to get some feedback on this.
Thanks and kind Regards
> Refactor engine image controller to use structured logging

- client/schemas.go
- controller/volume_controller.go
https://github.com/longhorn/longhorn/issues/3649
> Enqueue volume for replica-auto-balance on node change

- controller/backup_controller.go
This prevents the `longhorn-csi-plugin` from printing out many error messages. This also prevents `csi-snapshoter` from setting a meanless error in the VolumeSnapshot
longhorn/longhorn#3392
> Update backup status with snapshot creation time and volume size at the beginning

- controller/setting_controller.go
This helps users quickly identify why the pods are deleted
https://github.com/longhorn/longhorn/issues/3672
longhorn/longhorn#2820
> [backport][v1.1.4] Add logs before deleting managed components' pods

- controller/backup_controller.go
https://github.com/longhorn/longhorn/issues/3669
longhorn/longhorn#3392
> [Backport][v1.2.4] Update backup status with snapshot creation time and volume size at the beginning

- deploy/uninstall/uninstall.yaml
Image update in the uninstall manifest in the v1.1.x  branch.
Signed-off-by: Khushboo <fnu.khushboo@suse.com>
> Update the image in uninstall manifest

- csi/controller_server.go
The values will be either `snap`, `bak`,or `""` after this change.
The benefit of this approach is that both `type` parameter in `VolumeSnapshotClass` and the snapshot ID in `VolumeSnapshotContent` will have the same value (one of the 3 possible values: `snap`, `bak`,or `""`)
longhorn/longhorn#2534
> Using user-friendly name for the csiSnapshotType

- app/recurring_job.go
- controller/recurring_job_controller.go
- datastore/longhorn.go
- manager/volume.go
Fix unable to parse engine image with array type condition issue. Use longhorn client instead - partial [Longhorn-3470](https://github.com/longhorn/longhorn/issues/3470).
Implement volume clean-up when the recurring job/job-group is deleted - https://github.com/longhorn/longhorn/issues/3517.
> Fix  condition unmarshal failure & implement volume recurring job label clean up

- app/recurring_job.go
- controller/recurring_job_controller.go
- datastore/longhorn.go
- manager/volume.go
backport https://github.com/longhorn/longhorn-manager/pull/1223
https://github.com/longhorn/longhorn/issues/3470
https://github.com/longhorn/longhorn/issues/3517
> [BACKPORT][v1.2.x] Fix condition unmarshal failure & implement volume recurring job label clean up

- deploy/install/02-components/01-manager.yaml
- deploy/longhorn-images.txt
Use an instance manager version with the tgt 100% CPU usage fix.
https://github.com/longhorn/longhorn/issues/3636
Signed-off-by: Keith Lucas <keith.lucas@suse.com>
> Update instance manager

- controller/kubernetes_node_controller.go
> Fix bug: in kubernetes_node_controller, enable the resync for kubeNodeInformer and disable resync for nodeInformer event handler
